### PR TITLE
Console support for rivers

### LINKED ISSUE #11433: River cannot be added on consol?
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.3

### Describe the bug

I couldn't add river on world screen using `tile addfeature river` consol command.
In fact it did but the river is applied **ON** tiles, not between of them.

### Steps to Reproduce

1. Start or load a game to see world screen.
2. Select any tile and check its info.
3. Open consol and enter `tile addfeature river`.
4. Check again its info. The tile now would have "river" and might have "fresh water" but there's no new sprite of river around it. Especially if it was a hill, its color would look different from any normal hills.
5. Apply the consol command on any adjacent tile of it.
6. Check there's no river sprite even between of "river tiles".

### Link to save file

[Siam_-_0_turns.zip](https://github.com/yairm210/Unciv/files/14925193/Siam_-_0_turns.zip)

### Operating System

Android

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Closes #11433 - see gif over there and commit messages.

Note - that last commit came about because I puzzled "why does `tile addr<tab>`work but `tile remover<tab>` seems dead?" - now you'd know.

### CODE REVIEW

File: core/src/com/unciv/ui/screens/devconsole/ConsoleTileCommands.kt [hunk 1]
```diff
@@ -84,10 +93,47 @@ class ConsoleTileCommands: ConsoleCommandNode {
...
+        "addriver" to ConsoleRiverAction("tile addriver <direction>", true),
+        "removeriver" to ConsoleRiverAction("tile removeriver <direction>", false),
     )
 
     private fun getTerrainFeature(console: DevConsolePopup, param: String) =
         console.gameInfo.ruleset.terrains.values.asSequence()
         .filter { it.type == TerrainType.TerrainFeature }.findCliInput(param)
         ?: throw ConsoleErrorException("Unknown feature")
+
+    private enum class RiverDirections(val clockPosition: Int) {
```
Comment (yairm210) [inline core/src/com/unciv/ui/screens/devconsole/ConsoleTileCommands.kt:105]: This is a good idea, we should move this to where the other river logic is because it will make things more readable

File: core/src/com/unciv/ui/screens/devconsole/DevConsoleCommand.kt [hunk 2]
```diff
@@ -16,12 +17,23 @@ internal fun <T: IRulesetObject> Iterable<T>.findCliInput(param: String): T? {
...
 /** Returns the string to *add* to the existing command */
-internal fun getAutocompleteString(lastWord: String, allOptions: Iterable<String>): String? {
+internal fun getAutocompleteString(lastWord: String, allOptions: Iterable<String>, console: DevConsolePopup): String? {
+    console.showResponse(null, Color.WHITE)
+
     val matchingOptions = allOptions.map { it.toCliInput() }.filter { it.startsWith(lastWord.toCliInput()) }
     if (matchingOptions.isEmpty()) return null
     if (matchingOptions.size == 1) return matchingOptions.first().drop(lastWord.length) + " "
 
+    console.showResponse("Matching completions: " + matchingOptions.joinToString(), Color.FOREST)
```
Comment (yairm210) [inline core/src/com/unciv/ui/screens/devconsole/DevConsoleCommand.kt:35]: Pics?

File: core/src/com/unciv/ui/screens/devconsole/ConsoleTileCommands.kt [hunk 3]
```diff
@@ -84,10 +93,47 @@ class ConsoleTileCommands: ConsoleCommandNode {
...
+        action = { console, params -> action(console, params, newValue) }
+    ) {
+        override fun autocomplete(console: DevConsolePopup, params: List<String>): String? {
+            if (params.isEmpty()) return null
+            // Note this could filter which directions are allowed on the selected tile... too lazy
+            val options = RiverDirections.values().map { it.name }
+            return getAutocompleteString(params.last(), options, console)
+        }
+
+        companion object {
```
Comment (yairm210) [inline core/src/com/unciv/ui/screens/devconsole/ConsoleTileCommands.kt:125]: Why as a static function?

File: core/src/com/unciv/ui/screens/devconsole/ConsoleTileCommands.kt [hunk 4]
```diff
@@ -84,10 +93,47 @@ class ConsoleTileCommands: ConsoleCommandNode {
...
+        South(6),
+        SouthWest(8),
+        NorthWest(10)
+    }
+
+    private class ConsoleRiverAction(format: String, newValue: Boolean) : ConsoleAction(
+        format,
+        action = { console, params -> action(console, params, newValue) }
+    ) {
+        override fun autocomplete(console: DevConsolePopup, params: List<String>): String? {
```
Comment (yairm210) [inline core/src/com/unciv/ui/screens/devconsole/ConsoleTileCommands.kt:118]: Why is this separate? Why can't the regular autocomplete do this?
