### PR TITLE
No ruins undo

### LINKED ISSUE #10373: Ruin reward rollback
**Platform**
Windows, Android

**Version**
4.8.13 (Build 923)

**Describe the bug**
You can change the reward you receive from a ruin by Ctrl-Z unit's move.

**To Reproduce**
1. Find ruin
2. Get the opportunity to roll back the movement. (I don't know, it works weird, sometimes it appears, sometimes it doesn't)
3. Roll back move Unit on ruin.

I'm showing how it works in a multiplayer game. But this can be reproduced in single player as well.
Unciv_AjHEZCWTfU

UPD. Attached save
Save game 
[Bug_ruin.txt](https://github.com/yairm210/Unciv/files/13196795/Bug_ruin.txt)

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Closes #10373

But first I encapsulated the entire Undo thing, consistent interface (not a literal one though, just the fourth variant of kludge for the lack of partial classes in kotlin), we could plug in a N-level stack without any outside change.

### CODE REVIEW

**Review by yairm210 — APPROVED** [review]

File: core/src/com/unciv/logic/map/mapunit/MapUnit.kt [hunk 1]
```diff
@@ -750,6 +751,7 @@ class MapUnit : IsPartOfGameInfoSerialization {
     private fun getAncientRuinBonus(tile: Tile) {
         tile.removeImprovement()
         civ.ruinsManager.selectNextRuinsReward(this)
+        GUI.clearUndoCheckpoints()
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/mapunit/MapUnit.kt:754]: Do we need this anymore with the other changes in place? I think we don't

**Comment by yairm210** [comment]
I'm in favor of the UndoHander, I would rather forgo the blocking of the undo because it's unclear to the player why ("every unit move I can undo except for this one, BUG!") and the problem it solves is... not really solved, just made harder to do
