### PR TITLE
Fix ruleset error crash

### LINKED ISSUE #9653: Immediate crash upon start new game
Load up unciv, first I can't continue my old game, will post image. So I hit start new game, immediate crash as stated below. 

**Platform:** Android
**Version:** 4.7.3 (Build 882)
**Rulesets:** [RekMOD, Ruins Extended, The Demon World, Thin Bubbly Borders, Nextgen Maps, NextgenMaps Labs, tGUR 1.9 experiment, Antiyoy maps, Better ruins Lite, LesserSpaceNations, Civ V - Vanilla, No Fog Of War, Resource Recyclers, Civ V Leader portraits, Alpha Frontier, Raze anything, All units can be automated, Civ V - Gods & Kings, Yet Another Resource Mod, The Great Unciv Rework, tGUR 2.0 experiment, Closer Cities Distance of 1, DeCiv in Alpha Frontier, Better Workers, Better ruins, Mapping Tools for Unciv]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

Device Model: SM-G973U1
API Level: 31

--------------------------------

**Message:**
```
com.unciv.logic.UncivShowableException: Building 'Revealer' is buildable and therefore must either have an explicit cost or reference an existing tech.
	at com.unciv.models.ruleset.Ruleset.updateBuildingCosts(Ruleset.kt:461)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:630)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:610)
	at com.unciv.models.ruleset.RulesetCache.getComplexRuleset(Ruleset.kt:592)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:54)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:49)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:154)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:153)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:103)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:101)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:55)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:40)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:209)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

```

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Complements #9664 
Together, should close #9653 and... #9656

Meaningful commits

Snuck in sneakily: Crass mishandling of map file SelectBox changes fixed - never thought to really switch on brain for that, it's a well-known caveat for such usecases even on other forms frameworks...

### CODE REVIEW

**Comment by SeventhM** [comment]
I believe your documentation links the wrong PR. You want #9664

File: core/src/com/unciv/ui/screens/newgamescreen/NewGameScreen.kt [hunk 1]
```diff
@@ -354,11 +358,37 @@ class NewGameScreen(
...
 
-    fun updateRuleset() {
+    /** Updates our local [ruleset] from [gameSetupInfo], guarding against exceptions.
+     *
+     *  Note: The options reset on failure is not propagated automatically to the Widgets -
+     *  the caller must ensure that.
+     *
+     *  @return Success - failure means gameSetupInfo was reset to defaults and the Ruleset was reverted to G&K
+     */
+    fun updateRuleset(): Boolean {
```
Comment (yairm210) [inline core/src/com/unciv/ui/screens/newgamescreen/NewGameScreen.kt:368]: tryUpdateRuleet, since it can fail and returns a boolean to indicate this

File: core/src/com/unciv/ui/screens/newgamescreen/NewGameScreen.kt [hunk 2]
```diff
@@ -354,11 +358,37 @@ class NewGameScreen(
...
+        var success = true
+        fun handleFailure(message: String): Ruleset {
+            success = false
+            gameSetupInfo = GameSetupInfo()
+            ToastPopup(message, this, 5000)
+            return RulesetCache[BaseRuleset.Civ_V_GnK.fullName]!!
```
Comment (yairm210) [inline core/src/com/unciv/ui/screens/newgamescreen/NewGameScreen.kt:374]: Why are we resetting to GnK? I would expect us to go back to the previously selected ruleset, not to default

**Comment by yairm210** [comment]
Neither of these is a blocker for me, so I'll merge this and fix the first issue manually
