### PR TITLE
Fix number popup with commas in the number

### LINKED ISSUE #13491: Gold Trading Numbers buggy
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Game Version

4.16.18

### Describe the bug

When trading more than 1000 gold, trying to change the gold amount of that gold will cause the game to automatically place a comma separating the digits (so 1000 becomes 1,000). The game does not accept this new value as a valid amount.

### Steps to Reproduce

1. Go to the trading menu
2. Select the gold trade
3. Enter an amount that's larger than 1000
4. Press ok
5. Reselect the gold trade
6. Press ok again
7. See bug

### Screenshots

https://github.com/user-attachments/assets/db485bcb-9e0e-4131-a69e-d15df3919682

### Link to save file

_No response_

### Operating System

Windows

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by RobLoach**
When you have a trade window with commas in the number, the window reports that it's an invalid number. This is because `.toInt()` doesn't handle commas, unfortunately.

This change adds a `.replace()` to where that's used to fix #13491.

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Sounds to me like a localization problem. These commata shouldn't be output in the first place. Seems to work fine on my copy, which is set to English. So, if it's localization dependent, then the parser should be localization dependent too - thousands separators aren't equal across the world. Or fix the "renderer" to omit them.

Edit: Oh I see you have to re-open that dialog. OK, I repro.

*  [`offer.amount.tr()` is the culprit.](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/screens/diplomacyscreen/OfferColumnsTable.kt#L123)
* `UncivGame.Current.settings.getCurrentNumberFormat().parse(stuff)` would be the correct counterpart
* That means this thing would be broken in Bangla in a way this `replace(',','')` approach doesn't fix - anybody understand enough Bangla to test? (hurr hurr - the guy who broke this probably, as that `Number.tr()` was made for Bangla, wazznt it)

**Comment by SomeTroglodyte** [comment]
So, I'd propose you appropriate this as your own because you're the one testing it:??

```patch
Subject: [PATCH] Fix number popup with commas in the number
---
Index: core/src/com/unciv/ui/popups/AskNumberPopup.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/ui/popups/AskNumberPopup.kt b/core/src/com/unciv/ui/popups/AskNumberPopup.kt
--- a/core/src/com/unciv/ui/popups/AskNumberPopup.kt	(revision 50ee33cf1eb0b0161f2c14aa5b145cbbd632044b)
+++ b/core/src/com/unciv/ui/popups/AskNumberPopup.kt	(date 1734797190238)
@@ -4,6 +4,7 @@
 import com.badlogic.gdx.scenes.scene2d.ui.Button
 import com.badlogic.gdx.scenes.scene2d.ui.Table
 import com.badlogic.gdx.scenes.scene2d.ui.TextField
+import com.unciv.models.translations.parseTranslatedNumber
 import com.unciv.models.translations.tr
 import com.unciv.ui.components.widgets.UncivTextField
 import com.unciv.ui.components.input.onChange
@@ -66,13 +67,12 @@
         val nameField = UncivTextField(label, defaultValue)
         nameField.textFieldFilter = TextField.TextFieldFilter { _, char -> char.isDigit() || char == '-' }
 
-        fun isValidInt(input: String): Boolean {
-            return input.toIntOrNull() != null
-        }
+        fun isValidInt(input: String) = input.parseTranslatedNumber() != null
+        fun getInt(input: String): Int? = input.parseTranslatedNumber()?.toInt()
 
 
         fun clampInBounds(input: String): String {
-            val int = input.toIntOrNull() ?: return input
+            val int = getInt(input) ?: return input
 
             if (bounds.first > int) {
                 return bounds.first.tr()
@@ -97,7 +97,7 @@
                 ).apply {
                     onClick {
                         if (isValidInt(nameField.text))
-                            nameField.text = clampInBounds((nameField.text.toInt() + value).tr())
+                            nameField.text = clampInBounds((getInt(nameField.text)!! + value).tr())
                     }
                 }
             ).pad(5f)
@@ -121,12 +121,12 @@
         addCloseButton()
         addOKButton(
             validate = {
-                val errorFound = !isValidInt(nameField.text) || !validate(nameField.text.toInt())
+                val errorFound = getInt(nameField.text)?.let { validate(it) } != true
                 if (errorFound) add(errorLabel).colspan(2).center()
                 !errorFound
             }
         ) {
-            actionOnOk(nameField.text.toInt())
+            actionOnOk(getInt(nameField.text)!!)
         }
         equalizeLastTwoButtonWidths()
 
Index: core/src/com/unciv/models/translations/Translations.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/models/translations/Translations.kt b/core/src/com/unciv/models/translations/Translations.kt
--- a/core/src/com/unciv/models/translations/Translations.kt	(revision 50ee33cf1eb0b0161f2c14aa5b145cbbd632044b)
+++ b/core/src/com/unciv/models/translations/Translations.kt	(date 1750610237346)
@@ -12,6 +12,7 @@
 import com.unciv.ui.components.fonts.FontRulesetIcons
 import com.unciv.utils.Log
 import com.unciv.utils.debug
+import java.text.ParseException
 import java.util.Locale
 import org.jetbrains.annotations.VisibleForTesting
 
@@ -548,7 +549,23 @@
     return UncivGame.Current.settings.getCurrentNumberFormat().format(this)
 }
 
+fun String.parseTranslatedNumber(): Number? {
+    return try {
+        UncivGame.Current.settings.getCurrentNumberFormat().parse(this)
+    } catch (_: ParseException) {
+        null
+    }
+}
+
 // formats number according to given language
 fun Number.tr(language: String): String {
     return LocaleCode.getNumberFormatFromLanguage(language).format(this)
 }
+
+fun String.parseTranslatedNumber(language: String): Number? {
+    return try {
+        LocaleCode.getNumberFormatFromLanguage(language).parse(this)
+    } catch (_: ParseException) {
+        null
+    }
+}
```

Edit: had to fix mistake already - see? Testing is all the work.

**Comment by RobLoach** [comment]
Force pushed your change. Would you also be able to make it so that entering an empty string removes it? The change I had prior allowed pressing "OK" an empty to remove the gold... Essentially empty strings are considered 0.

Screenshot from 2025-06-22 12-56-29

**Comment by SomeTroglodyte** [comment]
> Force pushed your change

I repeat - I never do.

> allowed

Dunno. The `actionOnOk` in `openGoldSelectionPopup` is what supports removal upon value 0, so: `fun getInt(input: String): Int? = if (input.isEmpty()) 0 else input.parseTranslatedNumber()?.toInt()` ??? Probably needs empty treatment in `isValidInt` as well? But why? `"".toIntOrNull() == null`, so how did it work before?

**Comment by RobLoach** [comment]
In isValidInt() I added an empty check to return true. In a custom toInt() handler I returned 0 when it was empty.

**Comment by SomeTroglodyte** [comment]
Ah I get it. The current master _doesn't_ allow removing a trade offer by clearing the amount, only by actually setting it to 0. Your original PR added that. Can't re-read that version, the commit link says: "Sometimes commits can disappear after a force-push"... Edit: Comment overlap. There you have it.

**Comment by RobLoach** [comment]
Haha. I guess all we need is a check for isEmpty() in there.

**Comment by SomeTroglodyte** [comment]
> a check

Two.

But there's something fishy still. AskNumberPopup is older than Number.tr() and not at all adapted. That TextFieldFilter - will it allow Bangla numerals entered? I wouldn't know how to operate a Bangla IME... Using only the buttons and/or latin digits it seems to work OK - you can even mix Bangla numerals and Latin - at least the number changes... But typing input???

Edit:
image

... probably means it's OK.

@touhidurrr - your opinion?

**Comment by touhidurrr** [comment]
1. Number formatting does not favor any special language. It's true I added tests in Bangla to see if it works but that's it.
2. Bangla numerals are nothing special. There is no complex rendering system for them. They work the same as Arabic numerals do and just have different glyphs.
3. Your `it.isDigit()` method is working properly.
4. It is true that Number input is something that I did not think of. But if we can convert numbers into other locales there should be some way to turn them back.

Why is someone noticing an issue after this long time by the way. This looks like something that was supposed to be spotted much earlier. It's surprising that something like this was not spotted till now.

**Comment by touhidurrr** [comment]
> So, if it's localization dependent, then the parser should be localization dependent too 

I disagree with this slightly. We should try to parse numbers in English then fall back to localized version. Or, fallback to English when Locale has failed. Because most of the time while playing games you don't have a localized keyboard setup enabled by default. It interferes with games and most games cannot handle Bangla typing well. But either ways, it is common for polyglots to mix multiple keyboards.

File: core/src/com/unciv/ui/popups/AskNumberPopup.kt [hunk 1]
```diff
@@ -66,13 +67,12 @@ class AskNumberPopup(
         val nameField = UncivTextField(label, defaultValue)
         nameField.textFieldFilter = TextField.TextFieldFilter { _, char -> char.isDigit() || char == '-' }
 
-        fun isValidInt(input: String): Boolean {
-            return input.toIntOrNull() != null
-        }
+        fun isValidInt(input: String) = input.parseTranslatedNumber() != null
+        fun getInt(input: String): Int? = input.parseTranslatedNumber()?.toInt()
```
Comment (touhidurrr) [inline core/src/com/unciv/ui/popups/AskNumberPopup.kt]: using `toLong()` should be safer?

File: core/src/com/unciv/models/translations/Translations.kt [hunk 2]
```diff
@@ -548,7 +549,23 @@ fun Number.tr(): String {
...
+}
+
 // formats number according to given language
 fun Number.tr(language: String): String {
     return LocaleCode.getNumberFormatFromLanguage(language).format(this)
 }
+
+fun String.parseTranslatedNumber(language: String): Number? {
+    return try {
+        LocaleCode.getNumberFormatFromLanguage(language).parse(this)
```
Comment (touhidurrr) [inline core/src/com/unciv/models/translations/Translations.kt]: Can you fallback to `String.toLong()` if this fails?

File: core/src/com/unciv/models/translations/Translations.kt [hunk 3]
```diff
@@ -548,7 +549,23 @@ fun Number.tr(): String {
     return UncivGame.Current.settings.getCurrentNumberFormat().format(this)
 }
 
+fun String.parseTranslatedNumber(): Number? {
+    return try {
+        UncivGame.Current.settings.getCurrentNumberFormat().parse(this)
```
Comment (touhidurrr) [inline core/src/com/unciv/models/translations/Translations.kt]: Kindly fallback to `String.toLong()`

**Review by touhidurrr — CHANGES_REQUESTED** [review]

**Comment by touhidurrr** [comment]
> Force pushed

I don't think there is any need for force pushing since this pr will most likely be squash merged anyways. So, I suggest that you leave commit for future reference.

**Comment by RobLoach** [comment]
I was lazy when applying the patch. There were conflicts against it and liked the translation solution more.

**Comment by SomeTroglodyte** [comment]
> I disagree with this slightly. We should try to parse numbers in English then fall back to localized version

I think you misunderstand slightly: `AskNumberPopup` will display numbers - whether typed or incremented by the buttons - using your translation function. I say "Display" but the way that works means the translated string is physically present in the TextField Widget and its backing StringBuilder. Thus, the need to parse them back appropriately.

That gives me a new idea - create a new Widget that does not _hold_ the translated number internally, that truly only displays. But: a) more work and b) how would you expect that to react if you sent Bangla digits from your keyboard/IME... Nah, this is fine. I tested as far as not being able to actually read those numbers can carry me.

> toLong()

Stats.gold isn't a long either. And as far as I can tell, no fallback is needed as it's the same Java "service" used to render, and it can always parse back what it produced itself. IMHO.

Also: Remember that number localization isn't constricted to being based on a decimal system. If Java had the formatter, a Maya vingesimal notation would work. Both ways. Even with keyboard input if you could find an IME to produce the (existing!) Unicode points.

**Comment by SomeTroglodyte** [comment]
Now back to playing OpenMW. I'm addicted, after all. Or else I'm going to _implement_ that Maya formatter and force it upon players playing the Maya as soon as the long count kicks in...

**Comment by touhidurrr** [comment]
Anyways, if a fallback is not necessary then I think we can go through with the existing code. But does that mean I need to keep a Bangla keyboard layout enabled while playing Unciv. hmm. Maybe its not a bad idea after all. But then again, this looks problematic in Android. And would be cool if it could be fixed.
`toLong()` I like it because I think we should use the maximum range available to us in case some modders decide to mess with really long numbers.
But the pr looks ok as is if it works.

**Review by touhidurrr — APPROVED** [review]

**Comment by RobLoach** [comment]
Regarding the type, we return a null or Number, but we are focused on Ints for the pop-up. Perhaps we have to get specific in our intended usage? While I don't think we need to parse a float anytime soon, it could benefit from the specificity. Particularly if we are adding it as a function to the String type itself.

**Comment by SomeTroglodyte** [comment]
> Regarding the type

I chose the extension functions to mirror the existing `Number.tr()` functions closely. The client then coerces the type to what it needs. That was the idea anyway.

**Comment by RobLoach** [comment]
Made it a bit more verbose. Empty strings also now result in 0, which means you can clear out the number in the textbox and press OK to set the value to 0.

**Review by yairm210 — APPROVED** [review]

**Comment by SomeTroglodyte** [comment]
We'll need to revisit the general underlying problem.

Example: The current map seed field in map - Advanced Parameters was broken by Number.tr() too. Currently, I think not touching it will be OK and still give random maps, but once you touch it, you'll always get seed 0L.

Theoretically also affects custom map size (though - are we even allowing dimensions >= 1000?), and any other UncivTextField used for numbers - but I think Debug-simulateuntilturn is the last one.

I think:
a. The solution should move into a `UncivNumberField : UncivTextField`?
b. Map seeds could be displayed as base64 instead. I think that would be nicer for community exchange. No reason not to allow parsing longs as well... Shattered does something similar: They look like "JBM-BWR-SSS"... Looks even better than base64, but can carry only 42 bits, hello Douglas. Would need 14 letters to cover >= 64 bits.
