### PR TITLE
Resolved #7316 - unified unit capture unique mechanics for no double-capture

### LINKED ISSUE #7316: Ottomans privateer has a chance to duplicate barbarian water unit
**Platform**
Operating system type, major version, architecture (64/32 bit).
Android 10
**Version**
Where you got the game and the exact version number.
4.1.13-patch2
**Describe the bug**
Ottomans privateer has a chance to duplicate barbarian water unit
**To Reproduce**
Screenshot_20220626-230315
Screenshot_20220626-230350

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by yairm210**
Disregarding #7376 for a moment, there are currently 3 unit capture uniques for Germany, Ottomans and Prize Ships.
This PR unifies the functionality to ensue no double-capture occurs and consequentially also unifies capture notifications.

Old uniques were fully deprecated.

### CODE REVIEW

File: core/src/com/unciv/logic/battle/Battle.kt [hunk 1]
```diff
@@ -226,21 +222,76 @@ object Battle {
...
+                    unitCaptured = true
+                }
+            }
+            return unitCaptured
+        }
 
-        if (attacker.unit.getMatchingUniques(UniqueType.KillUnitCapture)
-            .none { defender.matchesCategory(it.params[0]) }
-        ) return false
+        val wasUnitCaptured = unitCapturedPrizeShipsUnique() || unitCapturedGermanyUnique() || unitCapturedOttomanUnique()
```
Comment (OptimizedForDensity) [inline core/src/com/unciv/logic/battle/Battle.kt:271]: The prize ships unique merely captures the unit but the German and Ottoman uniques capture the unit and give gold, so an Ottoman privateer will first try to capture using the privateer unique before trying with the Ottoman unique. This could deprive the player of some gold if the privateer unique capture chance has a successful roll since the Ottoman unique won't have a chance to roll, but this is a gameplay choice and not strictly a code issue.

File: core/src/com/unciv/logic/battle/Battle.kt [hunk 2]
```diff
@@ -226,21 +222,76 @@ object Battle {
...
+        fun unitCapturedPrizeShipsUnique():Boolean {
+            if (attacker.unit.getMatchingUniques(UniqueType.KillUnitCapture)
+                        .none { defender.matchesCategory(it.params[0]) }
+            ) return false
+
+            val captureChance = min(0.8f, 0.1f + attacker.getAttackingStrength().toFloat() / defender.getDefendingStrength().toFloat() * 0.4f)
+            return Random().nextFloat() <= captureChance
+        }
+
+        fun unitCapturedGermanyUnique():Boolean{
```
Comment (OptimizedForDensity) [inline core/src/com/unciv/logic/battle/Battle.kt:243]: I feel that `unitCapturedGermanyUnique()` should be renamed to something `unitGainFromEncampment` and `unitCapturedOttomanUnique()` renamed to something like `unitGainFromDefeatingUnit` since those are a touch more descriptive.

File: core/src/com/unciv/logic/battle/Battle.kt [hunk 3]
```diff
@@ -226,21 +222,76 @@ object Battle {
...
-        return spawnCapturedUnit(defender.getName(), attacker, defender.getTile(), "Your [${attacker.getName()}] captured an enemy [${defender.getName()}]!")
+        return spawnCapturedUnit(defender.getName(), attacker, defender.getTile())
+    }
+
+    /** Places a [unitName] unit near [tile] after being attacked by [attacker].
+     * Adds a notification to [attacker]'s civInfo and returns whether the captured unit could be placed */
+    private fun spawnCapturedUnit(unitName: String, attacker: ICombatant, tile: TileInfo): Boolean {
+        val addedUnit = attacker.getCivInfo().placeUnitNearTile(tile.position, unitName) ?: return false
+        addedUnit.currentMovement = 0f
+        addedUnit.health = 50
```
Comment (OptimizedForDensity) [inline core/src/com/unciv/logic/battle/Battle.kt:286]: `addedUnit.health` as a function argument could solve #7376 in the same PR :)

**Comment by OptimizedForDensity** [comment]
Looks pretty good so far! Also reminds me that "When conquering an encampment..." and "When defeating a [combatantFilter] unit..." could possibly be conditionals but that's for another day.

**Comment by xlenstra** [comment]
> Also reminds me that "When conquering an encampment..." and "When defeating a [combatantFilter] unit..." could possibly be conditionals but that's for another day.

Thought about that before, but the problem is that those aren't restrictions on a unique but triggers for when a triggerable unique should be executed, which is different

File: core/src/com/unciv/logic/battle/Battle.kt (hunk 1 above)
Comment (yairm210) [reply core/src/com/unciv/logic/battle/Battle.kt:271]: Oh, because of the way that or operators resolve... good catch!
I could separate this into 3 lines but that's not as nice, wonder if there's a better way

File: android/assets/jsons/translations/template.properties [hunk 4]
```diff
@@ -790,8 +790,11 @@ The City-State of [name] has been destroyed! =
 Your [ourUnit] captured an enemy [theirUnit]! = 
 Your [ourUnit] plundered [amount] [Stat] from [theirUnit] = 
 We have captured a barbarian encampment and recovered [goldAmount] gold! = 
-A barbarian [unitType] has joined us! = 
-We have captured an enemy [unitType]! = 
+An enemy [unitType] has joined us! = 
+
+# This might be needed for a rewrite of Germany's unique - see #7376
+# A barbarian [unitType] has joined us! =
```
[the remark this answers is not in the document]
Comment (yairm210) [reply android/assets/jsons/translations/template.properties:796]: Indeed, I means to add the comment and not comment out the line

File: core/src/com/unciv/logic/battle/Battle.kt (hunk 3 above)
Comment (yairm210) [reply core/src/com/unciv/logic/battle/Battle.kt:297]: That needs to be dealt with separately anyway, since apparently it doesn't actually capture a unit but instead activates when capturing an encampment even if there's no unit... so that'll need to be another PR anyway

**Review by OptimizedForDensity — APPROVED** [review]
