### PR TITLE
Fix Spacebar key binding in LWJGL3; Switch to integer/named key.

### LINKED ISSUE #5632: Spacebar broken for Next Turn.
**Platform**
Linux

**Version**
Git Master

**Describe the bug**
Spacebar binding for "Next Turn"'s broken in `WorldScreen`.

**Additional context**
Presumably due to #5614.

PR incoming, probably.

### PR DESCRIPTION
**Pull request by will-ca**
Fix #5632.

### CODE REVIEW

File: core/src/com/unciv/ui/worldscreen/WorldScreen.kt [hunk 1]
```diff
@@ -565,7 +565,7 @@ class WorldScreen(val gameInfo: GameInfo, val viewingCiv:CivilizationInfo) : Cam
         nextTurnButton.labelCell.pad(10f)
         val nextTurnActionWrapped = { nextTurnAction() }
         nextTurnButton.onClick(nextTurnActionWrapped)
-        keyPressDispatcher[' '] = nextTurnActionWrapped
+        keyPressDispatcher[Input.Keys.SPACE] = nextTurnActionWrapped
```
Comment (SomeTroglodyte) [inline core/src/com/unciv/ui/worldscreen/WorldScreen.kt:568]: KeyCharAndCode has a prefab for that, also often saves an import

**Comment by SomeTroglodyte** [comment]
OK, now I've seen the code live I suspect this regresses #4542, which was made for issue #4430 involving cyrillic keyboards. Anyone (@sockybob?) can confirm this is still OK in the situations described in #4430?
