### PR TITLE
close app completely when clicked 'Exit' button

### LINKED ISSUE #7515: Apps cannot be started in some case
**Platform**
Android 10

**Version**
Github release 4.1.20 (build 739)

**Describe the bug**
You can't start a game

**To Reproduce**
1. Launch a app
2. Create new game
3. Press back button twice and tap Exit button
4. Try to relaunch app
5. You will see initial screen forever

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```

```
</details>

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/97716654/180582636-4fbcf3ea-919b-4c03-9d40-8dd1edec48d8.mp4

I'd attach video that reproduce this bug

**Additional context**

### PR DESCRIPTION
**Pull request by CrispyXYZ**
Fixes #7515 . I tested it on my Android phone and the bug recurred. This bug seems to be caused by that the 'Exit' button can not close Unciv completely on Android. call `this.finishAndRemoveTask()` method in overridden `onDetroy()` can fix this problem.

*See also [finishAndRemoveTask()](https://developer.android.com/reference/android/app/Activity.html#finishAndRemoveTask()), [onDestroy()](https://developer.android.com/reference/android/app/Activity#onDestroy())*

### CODE REVIEW

**Comment by CrispyXYZ** [comment]
Also fixes #7178

**Comment by CrispyXYZ** [comment]
It was too strange that the bug recurred when i called `super.onDestroy()`.

**Review by OptimizedForDensity — APPROVED** [review]
My brain shut off for a second there with the label. This seems to work but I keep getting a "App keeps crashing" pop up but I can't tell if that's from me constantly trying to close something out or if there's a different bug happening.

**Comment by CrispyXYZ** [comment]
Get it! This problem is similar to https://stackoverflow.com/questions/34368616/how-to-exit-a-lib-gdx-application-safely

**Comment by CrispyXYZ** [comment]
I know what i did before. I made Unciv crash when exiting so it could exit completely. Now uses `System.exit(0)` and it'll exit in the right way.

**Comment by xlenstra** [comment]
I don't know enough about the gdx app life cycle to either approve or disapprove this, but have you tested that this doesn't also stop the multiplayer turn checker thread? Even if we completely close the game, that should still always keep running

**Comment by OptimizedForDensity** [comment]
I looked a little more into it and I think what's happening is that the "LoadJSON" job in UncivGame.kt is getting cancelled immediately when the player reloads the app without fully shutting down, and since the main menu is called from within this job, the screen never changes. I don't know what's causing the cancellation but I think fixing this would be a better approach.

File: core/src/com/unciv/UncivGame.kt [hunk 1]
```diff
@@ -294,7 +294,7 @@ class UncivGame(parameters: UncivGameParameters) : Game() {
                 restoreDefault = { musicController.resume() },
                 action = {
                     Gdx.app.exit()
-
+                    System.exit(0)
```
Comment (JackRainy) [inline core/src/com/unciv/UncivGame.kt:297]: Android Studio suggests to replace this line with `exitProcess(0)`.
P.S> I remember I have spent a good potion of time to overcome this bug, but not remember why I've given up.

Comment (CrispyXYZ) [reply core/src/com/unciv/UncivGame.kt:297]: I have a new plan. call `System.exit(0)` at the end of `dispose()`.
