### PR TITLE
Sea Unit can't capture Land Civilian (and vice versa)

### LINKED ISSUE #6111: Barb camp - capture missionary in camp bug
**Platform**
Windows
**Version**
3.19.5 - playing Gods&Kings

**Describe the bug**
Barb camp with a swordsman & a missionary - attack to kill swordsman, attack (with boat) to capture missionary. Barb camp at that point still exists with my missionary in it. Next turn: barb unit spawned, so is on the same tile as my missionary... Looks really weird. Either a) the capture of the unit captures the camp or b) the captured unit is kicked out to another tile?
image

### PR DESCRIPTION
**Pull request by itanasi**
Fix #6111 without changing all the combat rules.
Add in a check to prevent capturing Civilians you can't reach
Note if they were defended, still won't capture since won't move on to tile

### CODE REVIEW

**Comment by yairm210** [comment]
This is a good compromise :)
The poll got a lot more attention than I expected

**Review by yairm210 — APPROVED** [review]

File: core/src/com/unciv/logic/automation/BattleHelper.kt [hunk 1]
```diff
@@ -47,6 +47,8 @@ object BattleHelper {
                         // DO NOT use "!unit.movement.canPassThrough(it)" since then we won't be able to
                         // capture enemy units since we can't move through them!
                         && !it.canCivPassThrough(unit.civInfo)
+                        // Land Unit can't capture Naval and vice versa
+                        && !(unit.type.isLandUnit() && it.isWater || unit.type.isWaterUnit() && it.isLand)
```
Comment (xlenstra) [inline core/src/com/unciv/logic/automation/BattleHelper.kt:51]: I may be mistaken, but isn't this line in the function for getting the attackable enemies? And so doens't this also stop melee attacks into/from the water?

Comment (yairm210) [reply core/src/com/unciv/logic/automation/BattleHelper.kt:51]: No, since this is in the "mapCombatant.isCivilian" filterNot check

Comment (xlenstra) [reply core/src/com/unciv/logic/automation/BattleHelper.kt:51]: Ah, my bad

**Comment by itanasi** [comment]
Ooh, just realized maybe could add an exception if the unit has Amphibious?

**Comment by yairm210** [comment]
No I think this is fine
