### PR TITLE
Mods can use the Hills and mountains distribution uniques on Land or Feature terrains

### LINKED ISSUE #10976: Hills not acting as base terrain, even when mod says they should
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.0

### Describe the bug

In the original DeCiv, hills were a base terrain type instead of a terrain feature, similar to how Mountains are a base terrain and not a feature on top of the terrain. I've attempted to recreate that in a mod that I'm calling DeCiv 1. I changed Hill's type from TerrainFeature to Land. In spite of this, whenever you start a game, Hills always appear on top of existing terrain, such as Tundra or Wasteland.

### Steps to Reproduce

Start a game with this mod and you'll see Hills on top of every land terrain except mountains.
[DeCiv1Hills.zip](https://github.com/yairm210/Unciv/files/13998607/DeCiv1Hills.zip)

### Screenshots

Screenshot (163)

### Link to save file

_No response_

### Operating System

Windows

### Additional Information

Here's the code for Hill terrain:
`{
		"name": "Hill",
		"type": "Land",
		"production": 1,
		"movementCost": 2,
		"defenceBonus": 0.1,
		"RGB": [105, 125, 72],
		"uniques": [
			"Rough terrain",
			"[+5] Strength for cities built on this terrain",
			"Has an elevation of [2] for visibility calculations",
			"Occurs in groups around high elevations",
			"[+1] to Fertility for Map Generation",
			"A Region is formed with at least [40]% [Hill] tiles, with priority [5]",
			"Considered [Desirable] when determining start locations",
			"Considered [Production] when determining start locations",
			"Every [22] tiles with this terrain will receive a major deposit of a strategic resource."
		]
	}`

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Closes #10976 - though still untested with that mod. Maybe later.

While testing with huge maps to better measure timings, I couldn't leave some other generator steps alone, those with the worst times. Shaved off a minute out of a minute-and-a-half.

 The replaced raiseMountainsAndHills function got faster despite more complexity, the ruins step was way off due to avoidable looping in chooseSpreadOutLocations, and Pangaea was off due to excessive retries for that single continent[^1] - I tweaked that from 80 iterations down to 10, less with same size but other seeds. 

Testing with seed:1706296205814, 256x512 rect no-wrap.

<details><summary>Timings this PR:</summary>

```
MapGenerator run with parameters ({Rectangular} 256x512) {Resource Setting}: {Abundant}
2024-01-26T20:35:38.223225024Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.MapLandmassGenerator took 5580.17ms
2024-01-26T20:35:38.722291561Z [threadpool-nondaemon-0 @NewGame#52] [MapElevationGenerator] Mountain-like generation for Mountain
2024-01-26T20:35:39.289181839Z [threadpool-nondaemon-0 @NewGame#52] [MapElevationGenerator] Hill-like generation for Hill
2024-01-26T20:35:40.693543666Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.raiseMountainsAndHills took 2469.80ms
2024-01-26T20:35:41.266749080Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.applyHumidityAndTemperature took 572.41ms
2024-01-26T20:35:51.398482558Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.spawnLakesAndCoasts took 10130.94ms
2024-01-26T20:35:51.548373735Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.spawnVegetation took 149.38ms
2024-01-26T20:35:51.607592139Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.spawnRareFeatures took 58.51ms
2024-01-26T20:35:52.169253912Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.spawnIce took 560.82ms
2024-01-26T20:35:52.353382557Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.assignContinents took 183.53ms
2024-01-26T20:35:52.585841159Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerationRandomness] chooseSpreadOutLocations: distance 1 < initial 6
2024-01-26T20:35:54.996833063Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.RiverGenerator took 2642.91ms
2024-01-26T20:35:57.267476515Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.generateRegions took 2138.94ms
2024-01-26T20:35:59.249735269Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.assignRegions took 1981.3ms
2024-01-26T20:36:01.193228216Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.NaturalWonderGenerator took 1943.2ms
2024-01-26T20:36:11.393841295Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.placeResourcesAndMinorCivs took 10199.95ms
2024-01-26T20:36:13.074896098Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerationRandomness] chooseSpreadOutLocations: distance 5 < initial 8
2024-01-26T20:36:13.077993400Z [threadpool-nondaemon-0 @NewGame#52] [MapGenerator] MapGenerator.spreadAncientRuins took 1683.53ms
```
</details>

<details><summary>Timings master:</summary>

```
MapGenerator run with parameters ({Rectangular} 256x512) {Resource Setting}: {Abundant}
2024-01-26T19:26:09.956191836Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.MapLandmassGenerator took 18272.19ms
2024-01-26T19:26:09.956844047Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] Mountain-like generation for Mountain
2024-01-26T19:26:09.957112708Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] Hill-like generation for Mountain
2024-01-26T19:26:15.238749400Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.raiseMountainsAndHills took 5281.15ms
2024-01-26T19:26:15.801358210Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.applyHumidityAndTemperature took 561.17ms
2024-01-26T19:26:26.203815261Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.spawnLakesAndCoasts took 10401.70ms
2024-01-26T19:26:26.359668851Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.spawnVegetation took 155.17ms
2024-01-26T19:26:26.422933147Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.spawnRareFeatures took 62.54ms
2024-01-26T19:26:26.981175596Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.spawnIce took 557.63ms
2024-01-26T19:26:27.268614268Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.assignContinents took 286.50ms
2024-01-26T19:26:28.067753801Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerationRandomness] chooseSpreadOutLocations: distance 1 < initial 6
2024-01-26T19:26:30.700862484Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.RiverGenerator took 3431.42ms
2024-01-26T19:26:33.066102732Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.generateRegions took 2297.49ms
2024-01-26T19:26:34.888247278Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.assignRegions took 1816.44ms
2024-01-26T19:26:36.457171912Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.NaturalWonderGenerator took 1567.44ms
2024-01-26T19:26:48.152900454Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.placeResourcesAndMinorCivs took 11694.51ms
2024-01-26T19:27:37.744595910Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerationRandomness] chooseSpreadOutLocations: distance 5 < initial 8
2024-01-26T19:27:37.747932616Z [threadpool-nondaemon-0 @NewGame#25] [MapGenerator] MapGenerator.spreadAncientRuins took 49594.74ms
```
</details>

Edit: The changed Pangaea loop _can_ lead to maps generated with a specific seed before this not being identical to maps generated with the same seed after this.

[^1]: when I patched that for tiny maps I was very wrong with the comment that retries are only relevant when the times are not - and I overlooked two other types had a similar potentially too long loop (though not endless as water threshold < -1 should not generate any water at all).

### CODE REVIEW

File: core/src/com/unciv/logic/map/mapgenerator/MapElevationGenerator.kt [hunk 1]
```diff
@@ -0,0 +1,212 @@
...
+    private class TileDummyMutator : ITileMutator {
+        override val name get() = ""
+        override fun lower(tile: Tile) {}
+        override fun raise(tile: Tile) {}
+        override fun isElevated(tile: Tile) = false
+    }
+
+    private class TileBaseMutator(
+        private val flat: String,
+        private val elevated: String
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/mapgenerator/MapElevationGenerator.kt:188]: Should be called flatTerrainName and elevatedTerrainName

**Comment by yairm210** [comment]
Definitely good enough to merge,if there are further errors we'll discover them only with mods
