### PR TITLE
Resolved #14295

### LINKED ISSUE #14295: 4.18.18:  crash when attacking/liberating - SOLVED 4.18.18-patch1
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Game Version

4.18.18 + mods

### Describe the bug

Tank attacks barbarian camp from the see and frees a captured settler

**Platform:** Android
**Version:** 4.18.18 (Build 1182)
**Rulesets:** [The Undead, Anime Multiverse, Civ V - Vanilla, Deciv 2, Brave New World, Resource Recyclers, Medieval Civilizations, UnTile Civ6 Tileset, Civ6 mod, Ningen no Sato Touhou, World Of Gensokyo Touhou Mod, Civ IV, Latin American_Civs, Smoky Skies Redux, Ancient Civilizations, Civ V - Gods & Kings, Maid Empire, My Uncivilized Ponies]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

Device Model: EB2103
API Level: 33
System Memory: 7394 MB
    Available (used by Kernel): 2056 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 18 MB

--------------------------------

**Message:**
```
com.badlogic.gdx.utils.GdxRuntimeException: Malformed Vector2: HexCoord(x=-24, y=-22)
	at com.badlogic.gdx.math.Vector2.fromString(Vector2.java:298)
	at com.unciv.ui.screens.worldscreen.AlertPopup.addRecapturedCivilian(AlertPopup.kt:342)
	at com.unciv.ui.screens.worldscreen.AlertPopup.<init>(AlertPopup.kt:118)
	at com.unciv.ui.screens.worldscreen.WorldScreen.update(WorldScreen.kt:440)
	at com.unciv.ui.screens.worldscreen.WorldScreen.render(WorldScreen.kt:758)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.unciv.UncivGame.wrappedCrashHandlingRender$lambda$0(UncivGame.kt:79)
	at com.unciv.UncivGame.$r8$lambda$xG_ssdkEWQ3c5KZMkOMhnHtsiCQ(Unknown Source:0)
	at com.unciv.UncivGame$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt.wrapCrashHandling$lambda$0(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt.$r8$lambda$ZmD3ejHdHQgJjNvghy9393ssfKE(Unknown Source:0)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt.wrapCrashHandlingUnit$lambda$0(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt.$r8$lambda$4MlUfb0a_98IfrUPubAef8aLYuM(Unknown Source:0)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
	at com.unciv.UncivGame.render(UncivGame.kt:415)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:503)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1605)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1284)

```
**Save Mods:**
```
[Civ V - Gods & Kings, Ancient Civilizations]
```
**Permanent audiovisual Mods**:
```
[My Uncivilized Ponies, Maid Empire]
```

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

_No response_

### Link to save file

Prohibited by GitHub, too long

Time to make crash reporter prepare zipped text files as reports, if you decided to switch the reporter from mail to GH forms

### Operating System

Android

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by yairm210**

### CODE REVIEW

**Comment by yairm210** [comment]
release patch

File: core/src/com/unciv/logic/map/TileMap.kt [hunk 1]
```diff
@@ -534,6 +533,10 @@ class TileMap(initialCapacity: Int = 10) : IsPartOfGameInfoSerialization {
             tileInfo.setTerrainTransients()
             tileInfo.setUnitTransients(setUnitCivTransients)
         }
+        
+        val minColumn = tileList.asSequence().map { HexMath.getColumn(it.position) }.min()
+        val maxColumn = tileList.asSequence().map { HexMath.getColumn(it.position) }.min()
+        width = maxColumn - minColumn + 1
```
Comment (SomeTroglodyte) [inline core/src/com/unciv/logic/map/TileMap.kt:539]: Will always be 1 as both lines above do the same - `min`

File: core/src/com/unciv/logic/battle/BattleUnitCapture.kt [hunk 2]
```diff
@@ -169,7 +169,9 @@ object BattleUnitCapture {
                 attacker.getCivInfo().popupAlerts.add(
                     PopupAlert(
                         AlertType.RecapturedCivilian,
-                        capturedUnit.currentTile.position.toString()
+                        // Currently these are in (1.0,1.0) format
+                        // TODO: Migrate to e.g. 1,1 format, avoid the vector2 nonsense
+                        capturedUnit.currentTile.position.toVector2().toString()
```
Comment (SomeTroglodyte) [inline core/src/com/unciv/logic/battle/BattleUnitCapture.kt:174]: Could also have removed the "HexCoord" part of HexCoord's toString - Vector2.fromString comes down to hard checking for `(,)` then Float.parseFloat so missing fractional digits won't hurt. Later add the parser for (x,y) to HexCoord too... Might cover more cases than this.

File: core/src/com/unciv/logic/map/TileMap.kt (hunk 1 above)
Comment (yairm210) [reply core/src/com/unciv/logic/map/TileMap.kt:539]: 🤦🏿
