### PR TITLE
AI doesn't counter offer and request a defesive pact, open borders or research pact at the same time

### LINKED ISSUE #10822: Double trade offer when countering an offer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.12

### Describe the bug

When offering a trade request to an AI, the AI might give a counteroffer as well as a trade request in the same turn. This may result in some weird behavior where an AI might counteroffer the defensive pact trade and offer their own defensive pact.

### Steps to Reproduce

1. Get high relations with the AI
2. Create an offer with a defensive pact and a city
3. The AI may counteroffer the defensive pact trade and offer their own defensive pact

### Screenshots

DefensivePactDoubleTrade

### Link to save file

_No response_

### Operating System

Windows

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tuvus**
This PR fixes  #10822 by having the AI search through the pending trades for defensive pact, open borders or research pact when determining if they are eligible to offer it to the player.

### CODE REVIEW

File: core/src/com/unciv/logic/automation/civilization/DiplomacyAutomation.kt [hunk 1]
```diff
@@ -97,7 +97,13 @@ object DiplomacyAutomation {
             .filter { it.isMajorCiv() && !civInfo.isAtWarWith(it)
                 && it.hasUnique(UniqueType.EnablesOpenBorders)
                 && !civInfo.getDiplomacyManager(it).hasOpenBorders
-                && !civInfo.getDiplomacyManager(it).hasFlag(DiplomacyFlags.DeclinedOpenBorders) }
+                && !civInfo.getDiplomacyManager(it).hasFlag(DiplomacyFlags.DeclinedOpenBorders)
+                && !civInfo.tradeRequests.filter { request -> request.requestingCiv == it.civName }
+                    .any { trade -> trade.trade.ourOffers.any { offer -> offer.name == Constants.openBorders }}
+                && !civInfo.tradeRequests.filter { request -> request.requestingCiv == it.civName }
```
Comment (yairm210) [inline core/src/com/unciv/logic/automation/civilization/DiplomacyAutomation.kt:103]: Make this a function, hasOffered(), since you use it several times

**Review by yairm210 — APPROVED** [review]
