### PR TITLE
Snow, Ice, Atoll & Map Generation

### LINKED ISSUE #1806: Rectangular maps and map generation algorithms
Hi, I created this issue to notify you I started working on implenting rectangular maps and improving map gen algorithms (with help by CPT. Klutz).
The rectangular map (although it is ready) cannot be deployed yet because the mapgen algorithms don't work well in such a shape.
The following is a sketched to do list; if you have requests/suggestions post them below!

- [x] rectangular maps
- [x] archipelago map type
- [x] mapgen advanced settings (height, temperature, moisture etc.)

### LINKED ISSUE #1886: Continents maps don't really have continents (commit ddf86ecf2f)
Hex continents now have very few land tiles, and each continent is likely to be broken.

Screenshot_20200209_195126_com unciv app

Screenshot_20200209_195407_com unciv app

### LINKED ISSUE #1938: map advance options "map height" can't set too large.
1. "map height" should replace with "average altitude" or "mountain percent".
2. map advance options "map height" can't set too large. the reason is that when all the tile of the land is mountain, there will be not enough tile to place civilizations. the game will catch this bug. the solution is giving enough tiles to location civilization at the time of creating map.

### PR DESCRIPTION
**Pull request by r3versi**
Changes in this PR:

**General**
- Added Snow, Ice and Atoll
- Fixed White Hexagon (the image was irregular on the borders and felt "weird" when rendered)
- Utility functions for `latitude` and `longitude` in `TileMap` and `TileInfo`
- One can generate a new map from the map editor menu

**Map generation related**
- **New map type by [@Eddh](https://github.com/Eddh): archipelago** 
- Biomes are selected according to combination of 2 perlin noise channels: `temperature` and `humidity`
- Vegetation is spawned according to 2 perlin noise channels: one regulating `density`, the other regulating the `type` (forest vs jungle)
- Hills and Mountains are spawned according to a perlin noise channel: `elevation`
- Strategic, Luxury and Bonus resourced are spawned using the same logic
- Reproducible maps: two equal sets of parameters (with the same seed) produce the same map.

Fix #1806, Fix #1938 and Fix #1886

### CODE REVIEW

File: core/src/com/unciv/logic/map/Perlin.kt [hunk 1]
```diff
@@ -54,6 +55,29 @@ object Perlin {
         return total/max
     }
 
+    fun ridgedNoise3d(x: Double, y: Double, z: Double,
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/Perlin.kt]: Please add a comment explaining what this is for, and what the parameters mean (or alternatively, link to an explanation)

File: core/src/com/unciv/logic/map/TileMap.kt [hunk 2]
```diff
@@ -6,32 +6,29 @@ import com.unciv.logic.GameInfo
...
 import com.unciv.models.ruleset.Ruleset
+import kotlin.math.abs
 
 class TileMap {
 
     @Transient lateinit var gameInfo: GameInfo
     @Transient var tileMatrix = ArrayList<ArrayList<TileInfo?>>() // this works several times faster than a hashmap, the performance difference is really astounding
     @Transient var leftX = 0
     @Transient var bottomY = 0
+    @delegate:Transient val maxLatitude: Float by lazy { values.map { abs(it.latitude) }.max() ?: 0f }
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/TileMap.kt]: Instead of using ?: 0f, you could "if values.isEmpty 0f else ..."
It's clearer what the alternative is if it's spelled out =)

**Comment by yairm210** [comment]
Also, you have some conflicts =)

File: core/src/com/unciv/logic/map/TileMap.kt (hunk 2 above)
Comment (r3versi) [reply core/src/com/unciv/logic/map/TileMap.kt]: I'm applying the change, but here I think it really makes it less readable.

File: core/src/com/unciv/logic/map/MapGenerator.kt [hunk 3]
```diff
@@ -659,6 +667,9 @@ class MapGenerator(val ruleset: Ruleset) {
             return Perlin.noise3d(worldCoords.x.toDouble(), worldCoords.y.toDouble(), seed, nOctaves, persistence, lacunarity, scale)
         }
 
+        /**
+         * Generates ridged perlin noise. As for parameters see [getPerlinNoise]
```
Comment (Eddh) [inline core/src/com/unciv/logic/map/MapGenerator.kt]: A link explaining the basic principle behind ridged perlin noise https://stackoverflow.com/questions/36796829/procedural-terrain-with-ridged-fractal-noise

**Comment by yairm210** [comment]
Alright let's merge this bad boy!
Merge master into it and it's ready to go!
