### PR TITLE
Resolves #11772 - Allow hidden conditionals

### LINKED ISSUE #11772: "Suppress warning" modifier showing up on uniques in Civilopedia
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.0

### Describe the bug

When a unique is modified with a suppressed warning, it shows up in the Civilopedia and the nation picker screen.

### Steps to Reproduce

Screenshot (204)

### Screenshots

Screenshot (203)

### Link to save file

_No response_

### Operating System

Windows

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by yairm210**
Currently, we can hide an entire unique - but not specific conditionals within that unique
No longer

### CODE REVIEW

File: core/src/com/unciv/models/ruleset/unique/Unique.kt [hunk 1]
```diff
@@ -177,6 +178,8 @@ class Unique(val text: String, val sourceObjectType: UniqueTarget? = null, val s
 
 
     override fun toString() = if (type == null) "\"$text\"" else "$type (\"$text\")"
+    fun getDisplayText(): String = if (conditionals.none { it.isHiddenToUsers() }) text
+        else text.removeConditionals() + " " + conditionals.filter { !it.isHiddenToUsers() }.joinToString(" ") { "<$it>" }
```
Comment (yairm210) [inline core/src/com/unciv/models/ruleset/unique/Unique.kt:182]: ${it.text} obviously
Damn
