### PR TITLE
Avoid Civilopedia stumbling over missing Grassland

### LINKED ISSUE #10948: Adding River to Terrains causing Civilopedia to crash
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.19

### Describe the bug

**Platform:** Desktop
**Version:** 4.9.19 (Build 957)
**Rulesets:** [Future-Expansion-2022-09-18, The Undead, RekMOD, Wakanda for Unciv, Upside Down, DeCiv Redux, Thin Bubbly Borders, NukeTest, The North Pole, Outlaws of the Wastes, The Star Wars Special Edition, Warfare Expanded Lite, PoliciesforDeciv, Plants vs UnZombies, Plants vs UnZombies Working folder, FreePromotionTest, DeCiv 1, The Star Wars Special Edition working folder, Civ V - Vanilla, Resource Recyclers, Lolcat Kingdom Of cats, Dreams of Steam, Alpha Frontier, Gray Goo, Smoky Skies Redux, Alpha Frontier altered, Civ V - Gods & Kings, BarbarianBreakage]
**Last Screen:** `com.unciv.ui.screens.worldscreen.WorldScreen`

--------------------------------

OS: Windows 10
	Windows 10 Pro Version 22H2 (Build 19045)
Java: Eclipse Adoptium Temurin-11.0.20+8
	Max Memory: 1024 MB
System default encoding: windows-1252

--------------------------------

**Message:**
```
java.lang.Exception: Terrain Grassland does not exist in ruleset!
	at com.unciv.logic.map.tile.Tile.setTerrainTransients(Tile.kt:726)
	at com.unciv.ui.screens.civilopediascreen.CivilopediaImageGetters.terrainImage(CivilopediaImageGetters.kt:40)
	at com.unciv.ui.screens.civilopediascreen.CivilopediaImageGetters.access$terrainImage(CivilopediaImageGetters.kt:20)
	at com.unciv.ui.screens.civilopediascreen.CivilopediaImageGetters$terrain$1.invoke(CivilopediaImageGetters.kt:89)
	at com.unciv.ui.screens.civilopediascreen.CivilopediaImageGetters$terrain$1.invoke(CivilopediaImageGetters.kt:86)
	at com.unciv.ui.screens.civilopediascreen.CivilopediaScreen.<init>(CivilopediaScreen.kt:223)
	at com.unciv.ui.screens.worldscreen.topbar.WorldScreenTopBar$SelectedCivilizationTable$onNationClick$1.invoke(WorldScreenTopBar.kt:220)
	at com.unciv.ui.screens.worldscreen.topbar.WorldScreenTopBar$SelectedCivilizationTable$onNationClick$1.invoke(WorldScreenTopBar.kt:219)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:70)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.unciv.app.desktop.HardenGdxAudio.<init>(HardenGdxAudio.kt:46)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:76)

```
**Save Mods:**
```
[DeCiv 1]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAAAO1dXXPbxpL9K1y+3N0qMSXwm36T5ST2rThJWb7rh6wfIBKSsAEJLQgq1nXlv++ABEhKRAPdpxuQH1yVcmySwHT3zPT09DnT87X7ECTrMF51X33trjbL6yDpvhqcdedJ4KfB4lOY3mXfpMGXtPuqO/xh9oM3657tfzkbTf7+2/06fAij8N9+6l607r7642v3PvIfg+Tj433gHnu7Wfqr7vZnv/rL7JOLNPLX7pM0mOfvn9+tPwTrwE/md8HCvaJ76V6VJpt59k73y493QefTXRBE7u+fkjANV7fubz9GwTxN4lU4z9723p/fhasgeex+dkLdx1E4DwMnz9ediMdvzD/9v02wTt/7K/820yb7JAmi8Nb94MmHt3G0CFYXt8XLbjPr/B7E91GQSX8fh6t0/VOc/OrM9HP23c+BE8OPLuPNKt2+pLv9uJN/nn0wdxZwr+v+r//g/xD5q9sf3rnfZk2edR/8aOPe3D8//zszb7C+dxI5cZ4I9RDO0zh5fCr9Jlytn3yS+k7fuR9dvNv9O/hyH8VJsPgQ3Oa9nsb3vwQ3afbXL91X3uis++j+d+5+ex2nabz8EN7e7b89332bifX1qD9fR/78z7/8xFnpe69+C736rH8uN1HaiW86725XYc28O+6S76bXm/43NymSzPb/DJLYfcI2fvl8+N4R/I7IbJM+XqVuJfvdrXKuocj920n2Lkm2a5WT92lnuT4K53cxt5O+d0aTnfEmcFHFP9adS3/1GNesK+UT50N4E2V/+95PBv30Nl6nodPwaSddREvfff19wrTfEUc/+NcqdCZzf2ZR+ttgNb/LIu5nPZUk8eN319b4gv/zneufzvtMcD9ku63v9jZeSj67/YufuP9Cv7DdIry5CecuFM5+e+WvFtfxl6x/3GR6799nKi79+9/9xPWjs8E6/+Aq/PfWZom/CDfrTMez7l/hItsYD4dn3btgtz/qz9y2eDcC3gful0s3/bLHXYfHm2SedUT3KnXyOTXmnde+M+B8O4cPO+3/Lrbi+Ua785+vN2G06Lhd9n+5X66DbNB4k/PRYOKNzifj4ezvnfS/hOt0u+2+9tfBx8BZIcze8slfp4FrZ9HNRslOjK14qZ+tk3fuKdcduUXjlVs0g5V7z3k2nu/jdZjmO0S38et5241fz8u2hU014uWby6om2O8rl/a1v8hetH4q7MfNddbfsrdXy5nuPv3Jde4myTr/j+7bMHLz/EnDv7sple62uSJDMfUCX8/v5Z8T5y8Wf/np1gmI2ujvBlS/ShWeES+izTJcuQl3+PRimfmxbSZLItROplORmB2LTKjTxt64FSJJy1v652Z16zy4sC2PUOtojTp6XdlEkvaSW1ncMiWSs1TC6lau7pNtdI9Yo0HfcOhd2EUUa97rx+zTZxGFUN9Kq2qXhVbmSp8wZs0Y9KMo3sgG4ZFjkjZX4pggiw52zQ9sVsEvWx/ofnj6viN1EPtUvrDSJRxZ6GqeuMALGQ3V9uH1z6fAv88C69N1o48580qbaH2KR+jN9+I2Y6BuMCncmkFkhEUVh3VVOTh71Fp71L6pc8ecFRZH9ChHbLSqHXd//Nc2pFQGdOhs+VI7W/z16xwde8g2rm6XHiBuubLjwuV9Ej8Ey+07uleb5CF8iJPO3F+Kh+WAGifH9jjo5Ha0lGKkKtw449OdGxqg/OhuQdTWcNfWEBrmZ0js61rdNSpus3RVfeOnPmjgUwEYBj4rFwN04QOGJZCApVI1k5gENF7p4vNutQ7mKbjvEHfjx/hLOO9sLWy5Dp+KwQ9WjAYA2i2y5ao6kixfK4pPM/IFvIqQgSeRsNHsZisXRIGx/pX4q9AuXVOzBwVcRfULTYbFEPGJNXk57vIAuhYqYKkR4eDdLOPeas+CT7jSeKB6fJnM42F9NIjEMM3Ee0NRvPc2TtYBqoDd3B5iaQNwpzS0zuL0dry83qjBKHvXxGkLxFqCogtDShNefG0YLg0Jhe03Lqdt7NP88nXg9GX8XW2fMYzka3Dl6xpMlnrgUAJzwx5jgogASrtXiU3AX5ePOunH1Tx5vE+DRSffYyoTp+R2pYHwtXIbILBBDdxYsag2uA8gk/Ls8bQMozD1k8cdiehrN/5rlYlySmeJk/A2XPnRb9QPchbE1TybYa6hTZK4Zt7vM1lO1vskXsYFq+XJv/7oXv0ZJstwfece/XkTJM5T+G5nmtz4SdB59670U/fhh8AptPLD9TrjVbiPMkLNMm/zfbB0Ugf50YRSjzj4++/sid1JBn9lZoXL/IWdy3j1ED+W2WPwzB6Q4NSXLeWhyfxcM464R6Ucm3B6mtiircw8tX9g26OJXWt1nILuPuxil1H9pqssQDFx2EU8D+/QTPe4I2w6YanuQnXF7FWma0f1ztFc22ZTdCMtfICoxM2oYxmA8a6RcXuZnl2Lpw1q9+yICozpaijokBK0ioyGgGtDhuRaCH6AKIPNhIF1R/Qp2RtJU/UZ4je/exe3j/WVRyjbBJNRrlOJTW1wEqSDD0pb7hFYyRpgAFW/UBDoX/ppuj1Xo2d3kJiz0jOYJDFQMo15TptBTRR0HxQ4kTiDDnnBCdOWM47cYxgmuKlNFDoopA76aOV7mdRbja/XAyZjiP68j87UvqyIxMXDqEGjjxkb1iZSGoUtWuG9j1uFLMfCfaqZTcfEyrYP17Uuamy9GI+JuMNaYi4yicEik10jE2zTJ3a2AtF2kp0KBgcaY5Wq4pFRLblRU0V24bSxJyiEa8OPPsWrxRam+HUzjwI/2VH9OleuMf82gHJNhr0zrO0deURnKN6gVryjqfhbGCk3bPtI21CFPqUCuBHMawl8bhQc7mNzyZLz5oF2K6eQllrtyo+kI9zTORlN2kZlDUkrL6LdIUlRuQtRp7apVBQ6v0lSj9JhyHk17G2sxG+8HK2CPBXROu/Wir0C7kHt+YwUHxNT6zL2DdZdFjAJxGhm2SXOTtwqvKTSDpawJebln5yxeqGkT7Xk9SNTGAtNZJ2BUnMnnHMGTdp1wsjrIBq1cXBwwkjXILI3yxyYMJgDWkR2wuALyGWuyL9Y+cAJIw9jloGbEFGhWVZpwohtgWDGxqFOd8JNRZ36UxTHi8595D5e160GAmF2spyKwqfZTxBt7ApETRgKKBJ4FSk2TGN5DHTajmX9DykqMKpVXh6GyixpeYh4WKsNnw4v3mNYdKym8A5qdkaqB+uOAWEW/Gz5RZKGNz5DEupMwL6U6HMW/P4LuzMAWmK/69BKZj9bl8aZ/IWk5Ld8msth+MnTSNBIM5h/HkdNINcqz/6hCz8kfukMZaXEBNlURShDpsBRggyVvTZMsJIsSkPeC4c72ShISp4sbZwDQZ1C5W6KailOhkfq+WcLIafFKdsDZCDNz41zK9PZZKvaJMn0KCoQWvEGr2lLZs9QV8nJ+on2tS+W1xNFL09vq/nMTfSrPeqUMDe0iSsSGhWvYyQ0agzzQtnvaf2U0zrWqTUUM7XOzk45rrrRLM8UO/QFedmpNYdu2lYOd4rlcLHi0lMiKuRnDqey2BWZXFMiAhcLWRnEV9vUZlWZ7eSYoVOgpsJmk+H7TvRTyYVpnacLRHF/VYO7yaPulwp/dNhfnRWbEubjnfHjWK0E4dChCgUoUCG0PNoUWqAyvDiyg9XRiFqNG10gx3UmMoDMRxoVLXJWozolkdx/tUc1J94MBR2lKcMlXihEBFhNfp9tcHSc9jkWYChplkbqM/R+Ks/xLbNPhdLUhQJNIk8rw1EK1wpGUFzt0q5Kz7ZhCKPq8SQi0UgJHwp7UJKCzU8RcDP3JccAG0uCG1ZgoEo6lBX/t8hPG5K2qXKWymR0u1Vl2Pl6VUxodBfKIcblJtgrfDRECcWT7NoMnTVVk8yXyvWxQTF6VD64fWShesV8KQ60WTRdlfAv3Yab6zKrS/1bZSNnnFHOt45ZND4jZnNTBpDU2K8yABT5zwiXbbbdnIHYAHuCyLWtOF+PqNYK6jBrCyOYUbFY2YhAVsuZGheYUZEu1I2z+lC+wdBhxoAPzJfzmQ2PElFU2mj1XYk2i7d3nq9E5+AgMLrAZieGWIqXzuXPONYzamyGmUgGErUTZ+1ZEafKNFZNYYqZ7wBWNo2STDhjSRmSTBhG4AwTVS3XkuYbK5tUNcIQgIc5YpH1cMToG21EOqzXomGcaljbLVbR3KBeVwbQYVjJBRz3Z+QqR6e+kbsf+9rZybCmUUq+T9nzKJCuNBVedt5Txkt2QFJNR3GHik3uQDdyGkGvrAYybTqzKwxJCLLNMzdG3AHWOSXAMeH4W4lfbAGMYpeGUFQ3Z4NwVvlBskJ8zcx6lg0HYhY7bI+8Qs/yRAjnEj0ArxLn2ypngTx2bwkEJEte6I5Q2NG+SV668J7sZ9FAGvnivG6PouHbAqYsxALInUhxNSV4JMpJMZM69ukRyQa9SnH2JXX2N1KfMw4tSRdB6iD6UxOcnuF+/v23cCx9n3itPpcOqtbgKfVngtNfK5A9YKQprpGCEuYvilzmQmCHjs5QZk6henWzfNXttk/npthmoWfF+9ibR4uhjSGf6k3hORUn84sGnBOhe1XKtOYwDqICcKEVUTMFiJxzITTnrAo9UKAWELdyt63NQhf6aOpRnGNkaqXXP21P0ItF6vB0afy4WS0SX7CDO0GBmwjh8jQjWmaUdzzECIjdhx0YcZBbSxSIgCHzmZ/t69vR/UhDw7wpKq4vdD0New/ffAOx/Kzo6MpIXqBMc9H7U1GpLyXuqTzsOUbHEV6AWfGMKWMSciYYUJ9/D+g3Xa93YqSjWTy+B/ptbqIGgq4x5nt1F+HWqAtwAVqp8D20nnNDSnhR1M0+7sYtY0jxAzC6NwPsRrZdg1rbsXFdvJyZZixQa/mxoKdL4NNvv4E1vc9a0wGlmlvb+1Vrex+ek3VT0eBmQXpj1OAVwLBz5U5AcY0qfXyO+jPa715ESz99FFm43LbgkQfavDwyb5P7YxZfyoabwWYFagplyg9yHSq5AKtMJdulDYaGuEgrGB4ySjeX9qDl+WLze/rMKsGOOJQSGzqGHYeEvJnTkuND3S+KCs25f0O/G+1xrhIBuBaCO6L2PArlBt66WCB56FGkid02nTrt+RLHE2ncWGQcu3sIeiwKAx/txI991+zGXujYd02MhyDgprAFtNNpaCR51NhuqQis3Hxt3JS1t0vFeXP+MDI5qJFLZFgfttCx4pg5TibQrW+5aADNgUDH7VamwmqNUDCaIEbnArdwSL0wTUVTgOCaM+keeVsuH85nXAfBGYyQJVu5p92jCnsJGcOQhpVEi+eXw18ky8fOm+A+BocSVtdN3YtwOTnbsKOVs62HiAJvzop4UUAGp4s4BzYuWcGM4pg8442JZWYdr946Jos4oieLZGJdZwLsD4B4I2sJriSBcGdauRJlVmsGjqYmYfWe19HGtmJK6Y3AO+VGMdwbTjSWQQODic5E2mzsWDsNlAKMKfWV1yvV9KISnB9RUldtMegyhLpbQcVjBxuow1qdq7FphA8iMzAWtQ6QvuTB8Qjdw0KOA1KsxxDI2E3MgrFZvugojiolUmYMmwwVx3eZAOzWt0+WmY+s11HKOyhjGigMoQeSaeKKIHtCsVGUFb9b2omSpVhq4Fv2nTs6jF99sw6whNSU6ZWD92KiAnZrVY+6ets+Rh+1mHnLgzO4rePlzKZ80ZhDebDSfsygPrAX+d/cOpFkyXS3L4qXJzeKm22LJlSOGyqyVIIT/+Qm+AakNlQzMgRrb7U1zbAJ8tI+EbJuc8VPj3NbIcCpULJDsHqGVAFpoKwrWqJCfhi9TH3w4hzOyXsgl6nlgGBnUinagCGjqy7jYMCkbo7Mox+sfRtiBkaj7VNDyxZQrooQmuQi94mpCFZA6HP8Cm4wQLUK/gSkmoyPgcwS6/s2c8krKBFqH9ivZV3oczt5I20wJfq1TAnrxHreZOW9UfwsLZyu6usJGYxbvoTsICzkLnRptJyih5WYLI3kUNp0oWgb22+Pc+uiPj5Ez5WokjCeNCNlts86BBlY6q20CIVFWGCYXDzoiFYx4fCVlVyDAsk5XeNflpKSoz6nYrm99Tqt9ckH26sVsyu91dfq5JE6SdmDoFk4gL9R4u9Ag6kQVbnVKegvzRnDzmHOrCeqnB5jbCaIFSPNIFWXhJJTZazr7NZoBDBVsEqHrASm9DrIMUdF5U5srNQa4q5wFQID3FGbOg3BmVUybIxrp+MGsGe6VORAGHQGO7SHjIvEdA9DYh4daxlxY36OfXEOlYy2RBkNoMQCwpapjOgAuseB/YL1iYysYmpjsIzGt7Ps0QyoRo43gCSn08RBgzl3eiPc0tXbrM29dj8oHCf0pVvtUIvNbtp6oWPVQ13KDDwnNsQObmGtjTikJvu4fVSf4m0i6hu3yXQa65hOEnYKEr1MNLwnxrUpJg6NKmD33Byn9d5Of/ENFLLLt+Tj6kJ2CuUavGriiejUl3zmS8mABmhUzXHSrJKM0zZZatgegbw+Xkb0MU5Ecisj4dlzyrnstDuddcXn34AjOdz+UelJmJo05zWeyUl+K5wdZIFE6M4u1gUuCHXOjP9VNt+sGS09TrGZJuY7zQYrUKsSS11tVn8Gq86HTV6PhwfWVXIZdQiGAnSrHngGJJ8BoTxbQISu97xiUqOMu0Ed405Ij0GTbQMNVY8OqnWcvUEdZ69d40AwgMA2ZhMGq3cE2eTlb7caEHFqozV/BjAnEFNPvNk1PB6w15Z3AxeCVHrURcRCR3/6gob6Q3yWzoyBTlYdFmdGdT7G7njiXifpKcvSMQ4RN+3yvRDDDD5jaxdiNX27zEHZCsZfWTc2H3yVAETS+FJZNsmKsVjwFU4XZZ5C+QtKni/rIpDOOyCFNGuk6FheE28CcS3dA4eyoolm522fUvFim6BpgqV5YFmetipmWVYYDuNCqntCQ5PEGodYjrxBXV4lRIh2zSTTyKTFPZmxMolqZNIppZ44lDIDvvfUxzb0nzD0h0iN3Ay4gtTYhn32nMbm99MjTCsVUF/TT2rq0YGsCHUWcosbuMGlQxIIlCuj6ZktwmRoU7YXryAyogB2rl0JNFN88Q2gTL1DeFYNM3GVaRCefiYq/bUlgRRgi2ICWOwcG7GAPWJOBrZNVyZ4yfFRrjFzu0kyfJVMHmiY90hWME8bugpiwzBkweBE0xh0YsYuauuRaSaejEXEgmboLOGgoSZZCMWFNUROIKbFy9zLSYttHEXPtx5aNihWX8yiJhwEBkwaJmoCvLbGWJlAFkFaP+MFqGunAGLhD+vNQCeJ7C77K7Jr9BKPyZm/166AG31BUo2gx3PQT1wLnfI4tSIfSrf5ZCt26wf1IRFZMomvBq+lHlnsiRm8kdya3+aBz6lYqyP3lESd3Ia18Ainu+VjaUjZUyQcjmUNQQaQYWiVy8CaT5x0c5WeaJifP0+PoRITSTl/QwavmRdW2J1kzYWiFyw7vVFuvBbLGRJRg3AGVYYdgEA4K4a8tbmBWlBU1WehrC/Ia+EcX6vfQkgBH488q9cSkExuZw0xf3r7LlTSZt9W6IwTiwuFZOWrjO+KI681kWoho69gZeELael1124B0VcCgnPVBWRIr5M14UWOBKLPH2xw+gYj8kvRk7iIg3oRrZalQZ2s8MYJFV8bpfS11vdI8cUkHpkFzApOHUg/6i5ADsycI8qXJ93eBA9h9I9159JfPcYNlqGZveSQndXaS2AUOzbblLRJOe4BVfefUro3epvthKOaLYuIt9xAs31MatMYaPEijqVHBw9N3Z2D6KmsDwL0Yz3Qe2R46+OlZLQDVFe8SNLwxlcwlPR+hGFBLHlHRlp4rW87WiUdshlxSGw2pmRsZ39+D3Q1P/lRlPG6KqwCcGagYFbRocqdXrnIPPiBwWZCWCsoGkLXJ2wApK+t8qwAUOijOA0oojw4RGeP2r4XQZkIKwIWiwNspgW6SiSCN/xjKkFrSI8a61g5TeyPJlRCnplnmNQAAup035RCN5gCTjH2TOmp09qgEzp5UwIlMXWbKQkwDcbTRe5GTH2xAH/Pa0BMfRtFeo1ekEHGjFeDO/OIJRp+jCw/etoSM0AiS5GY0Cyogisi9F/BeqE4JEzjoGFnWaTMbVIl8QES0bXPGg7cEToSDDEmcWukGvR7kWBaykjlHvbtN8hryZtgOV/5vB7VrSos4U5XTGH/oSu2R10vLWy/2QvOqOq3QiGx6inExgflPVBEeMvRqCZ1IPBU7Q6I67DRNxQSsIiScChXSAkTJkfUJl66sMHBBHmZiVQC5apRwYi1mAUw4bbnFdAP7FZzOEft13EJRloJhloJhloJBloJBpQE0ivrTt+AE3vC5X2yP73rYpnkIXyIk87cX4IXf4LSydK9Xm1f6AM1D1aHRpoqQX3DyzPPtWP1XNOXAp2vwuhBXnho1nz3z9ruffOCwFMrb4GwXaat+YJJvZq6UHLSmir0Ot98wEyGCGVWtKMf0YGFqqqsIaJPRi7m3U+HOMjhI+tkPBk/CTsKYnwoKr82TfWAwzk6mrPUzSyoIKM7bvSqDUkU7RMNV5EkPsZfwnln2xP60aLZeNAclV/8P58zMSu4EWjmmy6908StS2SZHZ6w9G2c5TC15l40NGFBnzdp7vZWOL9D55faLzlCJtR4qhTRlSEpIo/YeK+UZo4mVPZURD1AH58qiQ/TGuIDZ/dVksdnJmtmBI4g2v3ixIP8BfBS51EwDjdX5REgE3PJ6deh97xMFfo8fdWELFcHg+9kFQBZthJ9XgsW95RotSJJCkc5YyW+PtaZLH8e7/FxHZjOah8f8WMlcj5Wzdh9+zAzZ6zyWPv2G8HV85crZgW1nogGJw6LkxenijoHR7zJGmii9k9DGWH7aCzkScI8LvtGFI6CI1Zxtr8QT+lQFefyCwmULlUBLBcSKJ2qokgTXUsc52iRZ/ukHYM76yJnj3q0/AXw8wcdYAnGWglGpAQySB2XYFgrgXxwDSmhpFURYLMM6iSwoN30GzBdnxLcGHK1OaR3wODhnvLqekpUJYC36p5LOq521aXKwz8T9bSy+skPvoFy8QXmP6muFg/r1vg1xYXk5LdNTCyIt4BOmRmsCQ2V6kgJ6M02MhVKj+SYIVtTzfg4ZlUZ3TlPR0fw4kLGS9h1U3T0xBvHZPDUAjOlRwdejV3oRIZqzKioPlLjQE54+9qgTBKTMVfy+giMA2saxQEU1g2HRorQ3tR1aDYYNOBfhbuXAoaGzEgdC5iuoNHaXaU9sjyGDCJvB88nL2qSYeVN1kskSzLKEHI40aU8gUEn6pjtk6lCXvtFtAKftJnUJVdZQDXrCBNzbZmq0s0zKtktwq7Rx4sdLp4WOq/BzuWZDU8HfxSpBhg+6Wvh9L4OTh9o4fSBDk4ni73LMoUwnE4eNJblSmE4XYkNF9liGArB56I2Qa7O0Ovax3t8ohsy+fP4iJ/opkz+PD7jJzqXkT+vRmhglzdRIuYTJWJOXQolbF85/3DEvLbukHwVpviAQpHQF3hknCf1SegbCgn0XhE+bT3RxfoHCZSOUQGKFxIoXaMCFKdvB5dJoMevle5RwbOjT71x31Bk4uGNRp42V/s4XIKJVoKxVoKxVoKRVoKRVoIhKYFhObAhJaWUFgDbaaCVoK+VoF8ngQBqrATkYQk9rYQKQF6Z76gQmpEhVFp+VjuFWLCuid1RSgu9HEjScPj8ohcD3gvItUCUBcXbJ1cCURaY6YZ5k0u7NNSvDCzUEW5f6/NJl89sX+vxSYfPXZq1rlHRPt6wRmUtbtrTAKdH8J7yTDccldMXHIiAenhfUsx4uFTVULe301by6ilriWkp5z2S9C7D0k7zC0eXUq2yOMaPPsWrxZZv924dR35G0Xq3Pr0yugJwQ9MgRaQAA35TXSJopstD5dEanMY6V8J7+QuUQboC3/NUqdFiH4QnHvo6MG+gBfMGOjCPvJZYtuGGk1dkiVxZygFO35EHHWVJF2UCUwHm6aAxRTinzbSpU3269vEenyrBvKkSzJsqwbypEsybKsG8qRLMmyrBvKkSzJsqwTzqjgph+/CSR9WyELavnP84ckdSpGT+B0fu6JBRJoHeBSp9oAK5KyRQekEFcldIoPSDCuSukEDpCRXIHX3dqUwCPe6m9IYKUhF9Bof7hiLhDXuUPOOtdmm4BFOtBBOtBBOtBGOtBGOtBCOtBCOtBEOtBENKAsN7dhTiDbQG6msl6NcZSABOyQ3oacX3tOJzAUxlQqnieSN0Eq1+ovXVWlet9dRaR036aQsPQftwO/aF1s3TXt7AAtoVQLsAkP5fCFKiL9A6eK1/J927EKSE3Z+ifbxhjcpaWLanwWWPQEoYJCWPvspASngLRBbOloGU8CaQvMteBlI2c10QeReRDMGEswTKolk0P1l2GhDNktB5Hhk4ieaJimALzpXNdLm2IhzF/fm5Dh71tPCop4NH+1p4tK+DRwdaeHSgg0eHWnh0qINHyRs0ZTkFOENI1kGVZVWUpxsU8Kju5JwW6ysya3CeHHc82mSiOpupax/v8ZkSHp0p4dGZEh6dKeHRmRIenSnh0ZkSHqWumRe2D7t8qti9sH14ydMVLNi3Dy/5OkLXvn2t/8HhUW3QWEigd4FKH6iARwsJlF5QAY8WEij9oAIeLSRQekIFPFpIoPSFCniUvtpRJoEe3FT6Q0V+iD5PxE0K5rvAPupR8hfAzx+CGqVPU0gw1Uow1Uow0Uow0Uow1kow1kow0kow0kow1Eow1Eow0Eow0ErQ10rQ10rgaSXwtBJofaKn9Ylal6j1iFqHqPWHWneo9YZaZ6j1hVpXqPWEWkeo9YNaN6j1glonqPaBWgekaB9vWKOyFhzuadDhI6hUeQRYeQJZwbQkCyfLoFJ4O0Ze+iyDSuEN6Ui3oaWvz5Ghoejz2lpJPWW1Ji3nvKdkvWvTSj1lYmtPztNGjXhqztPisZ4Oj+1r8di+Do8daPHYgQ6PHWrx2KEOjx1p8diRDo8l72WUpRCUtdYUeKyukqf27GGRRlKmpRV4rA7dVETLytwhrHGRvMRV1uGx++Sprn14xBftoy/In4dnfNE++oL8edjjFe2jL+hTl28L24fviKAKqAvbh4vY6ApM7NuH+ak6Btm+fXjTpwzZDg5I6wH1LlDpA/HAfy+B0gviW5+9BEo/iG/+9hIoPSG+/d1LoPSFeAJgL4HSG+IpkL0ESn+oR1Nxxn7tES+uBLw3fD7rrlM/ScPV7S/x3M/elJW9/OwevvWXwe9+4v5Mg2R7keQivLkJ55sodc92r/zV4jr+4t53H/mP21/88bU7v4vXweoyfHC/uEgjf73//uPjfcZyf7tZOiGc5Nl/rvVV/NpPrv0k9LOG02QTnHUfwnkmYPbEtgbnm3gZrraydY/k/THxu9kFUbvbJ/8dLDrB9ka2TOkPmyhYB+n2eydMx3Of+/N5kN1P+D5eXN4F8z9/TJI4k7r7yU9W7n2vOm/dvwMnXidcd9abe2da99I07vibNF669ud+FD12Nve3ib8IOn7aSYP5XedDeBO5x886ziCd9C5Igps4CTofgkW8DDIq/1byjvuwE6br/eNvN+u1n3SW/mNnFaedxyDtXAedxIntJ/O7YPEf/7PaC1bc2RkkrYj2JvFvY/c5S7YPm+vrKOi8z+43DX2ZfJfx8jpcuV9eJMv1cymLgxAn4v36+jK7GHQ9T8L7lCfk2zCV92vgBq6bMpl2bh6kJwJebu8knT+eCHjhena9DpkGfO3eGqYy2X5c3Tq7BUlZ5+76/ESoqzhahAFzwL1zmt1uIl843vD+fO8nf66zLqLFc06juAb2961HOXIxma96t3AfLPrj6fXNjdcbDa+93nDqe73r0fl57zroB2NvNJ8PF9ODC7zKXMnHTbLKriT7fyBF0ZOO9QEA
```
</details>

[DeCiv1.zip](https://github.com/yairm210/Unciv/files/13944599/DeCiv1.zip)

### Steps to Reproduce

Adding the River as a terrain feature to a mod that doesn't Grassland causes the game to crash when you open Civilopedia. I think that the entry for "River" in the TileSets JSON file is causing trouble.

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Windows

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
... and minor things I stumbled upon while looking at - fixes #10948. See commit titles.

### CODE REVIEW

File: core/src/com/unciv/ui/screens/civilopediascreen/CivilopediaImageGetters.kt [hunk 1]
```diff
@@ -26,17 +26,18 @@ internal object CivilopediaImageGetters {
     private fun terrainImage(terrain: Terrain, ruleset: Ruleset, imageSize: Float): Actor {
         val tile = Tile()
         tile.ruleset = ruleset
+        val baseTerrainFromOccursOn = Constants.grassland.takeIf { it in terrain.occursOn && it in ruleset.terrains }
```
Comment (yairm210) [inline core/src/com/unciv/ui/screens/civilopediascreen/CivilopediaImageGetters.kt:29]: We can avoid referencing grassland by name entirely, sounds cleaner

Comment (SeventhM) [reply core/src/com/unciv/ui/screens/civilopediascreen/CivilopediaImageGetters.kt:29]: Out of scope question: but wouldn't a better idea be to define the default here, but add something to `civilopeidaText` to define which image the entry is using? There's plenty of other use cases for it anyways (such as defining a building's image to be an alias of another building or unit directly in the buildings json instead of in the atlas

**Review by yairm210 — APPROVED** [review]

File: core/src/com/unciv/ui/screens/civilopediascreen/CivilopediaImageGetters.kt (hunk 1 above)
Comment (SeventhM) [reply core/src/com/unciv/ui/screens/civilopediascreen/CivilopediaImageGetters.kt]: (I know I'm going pretty off topic for this. You can stop me when you want)
> IMO automatic atlas aliasing is perfectly fine.

Counterargument: Rekmod has numerous "Great Work of Whatever" that would all love to share the same icon. Via Atlas aliasing, I kinda only have 1 of 2 options
1. Copy the image over and over and over. That's 33 extra images all matches one of the images already in the mod, which can take up quite a lot of space. And that's the easy example where all I have to do is copy-paste 3 images a bunch of times and just rename stuff. That's not even looking at the many one off cases of a building or promotion explicitly wanting to copy some other image
2. Cheat, and start manually editing the atlas. I don't think anyone really wants to edit the atlas, and this solution has to be reapplied every time you update images
The worst case scenario is [the leader mission mod](https://github.com/Jiangeshi/Leader-Mission-2-Rising-Power) which not only have to deal with the many issues in trying to run a custom atlas, but also runs 80 copies of the same image for all of the leaders

The other side of this is if the was a way to define images or icons or whatever easily in the json, we wouldn't need to define it in code here. It could just be that river's icon is just whatever you want or some combination similar to what's in the tileset jsons or whatever

Comment (SeventhM) [reply core/src/com/unciv/ui/screens/civilopediascreen/CivilopediaImageGetters.kt]: (Funny, you commented just before I was going to add in this)
> And if your third-party tool is more pain than joy

Actually, that's not the only issue. On android, custom atlases are fine enough, but on desktop (especially when I'm testing in Studio), that mod I link actually tends to redo the atlas, which, because the images don't actually match their building/unit/terrain/etc names most of the time, it actually ends up breaking the majority of the images. So the downside of custom atlases isn't just setting it up, but rather making sure it works on all platforms
