### PR TITLE
Fix OneTimeRemovePolicy triggered Unique

### LINKED ISSUE #14133: Using the unique "Remove [all] and refund [120]% of its cost <upon entering a new era>" crashes the game
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Game Version

4.18.9

### Describe the bug

Once the said unique is activated, the game will crash once you reach the Medieval era or any other era after that if you happen to start later.
It produces something like this:

Image

Image

Image

Image

I've only tried it a few times but the results are very consistent.

### Steps to Reproduce

1. Get a civ that has the unique "Remove [all] and refund [120]% of its cost <upon entering a new era>"
2. Play a game, then reach the Medieval era or any era beyond (if you start at a later era)
3. The game crashes

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Android

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Fix #14133

Questionable choices:
- Needs more documentation, too lazy to think of simple words to do so
- The refunding version will always "refund" the free policies it removes (it can't know which were picked as free, so that counts when more policies are removed than _bought_), no matter the percentage of culture specified. One could do that only if > 50? The plain `OneTimeRemovePolicy` will not of course.
- Removal of "branch complete" policies is silent
- Does not really prevent illegal states - such as removing Liberty while one still has some policies in that branch. The sorting helps though, and "all" are removed in a consistent and logical order.

Tested by console - add "Remove [all] and refund [100]% of its cost" to China, then starting as China and giving me 2000 culture and the Oracle, buying a branch +2 policies in another, then triggering. The refund allowed an exact re-gain f all policies I had before, including the Oracle-free one. No crash anymore from attempts to remove "Liberty complete" by name or from going below 0.

### CODE REVIEW

**Comment by RobLoach** [comment]
Oh, this is nice. Thanks!

File: core/src/com/unciv/logic/civilization/managers/PolicyManager.kt [hunk 1]
```diff
@@ -141,17 +141,24 @@ class PolicyManager : IsPartOfGameInfoSerialization {
...
         var policyCostInput = numberOfAdoptedPolicies
 
         val policyMap = mutableMapOf<Policy, Int>()
 
         for (policy in policiesToRemove) {
+            if (policy.policyBranchType == PolicyBranchType.BranchComplete)
+                continue
             policyCostInput--
-            policyMap[policy] = (getPolicyCultureCost(policyCostInput) * refundPercentage/100f).roundToInt()
+            policyMap[policy] = if (policyCostInput < 0) -1 // This is a marker to refund a free policy
```
Comment (yairm210) [inline core/src/com/unciv/logic/civilization/managers/PolicyManager.kt]: Instead of using -1 directly please use a const FREE_POLICY_MARKER = -1 in all places (I see 2 places) so that we can ctrl-click and find them

Comment (yairm210) [reply core/src/com/unciv/logic/civilization/managers/PolicyManager.kt]: Reminder :)

Comment (SomeTroglodyte) [reply core/src/com/unciv/logic/civilization/managers/PolicyManager.kt]: ⏰ oops

**Review by yairm210 — APPROVED** [review]
