### PR TITLE
Fix Resource Production Modifier Calculations

### LINKED ISSUE #14456: Stockpiled Resources with City Resource Modifiers
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Game Version

4.19.5

### Describe the bug

When you have a Civ-wide Stockpiled resource, its generated isn't affected by local resource modifiers.

### Example

In BNW, the [Broadcast Tower](https://civilization.fandom.com/wiki/Broadcast_Tower_(Civ5)) provides...
```
[+34]% [Tourism] resource production <in this city> <after adopting [Media Culture]>
```

If you have 3 Great Works, the base should be +6 Tourism. With [Media Culture](https://civilization.fandom.com/wiki/Media_Culture_(Civ5)), you should result with +8 Tourism total. But it's only resulting in +6 Culture.

Originally reported by @kittridgecoffey-a11y over at https://github.com/RobLoach/Civ-V-Brave-New-World/issues/209 .

### Steps to Reproduce

1. Use [BNW](https://github.com/RobLoach/Civ-V-Brave-New-World)
2. Make a city
3. Add 3 buildings that give Tourism
4. Expect to have +6 Tourism, or whatever
5. Get Media Culture `civ addpolicy japan media-culture`
6. Add a Broadcast Tower city addbuilding broadcast-tower`

### Screenshots

Image

### Link to save file
```
H4sIAAAAAAAA/+1d63OcOpb/V9j+sjO15g5vmnxzfPPaTexe23dSW6l8UIPaZtINPUA715Py/75HEtC8BBLQjqcqlam5bjhIR0LnnN95SPxYPOAkDeNo8erHIjrs1jhZvLLOFn6CUYaDz2F2T+5k+M9s8Wph/aZ7v9mLs5JS1z3j6QnIw4dwG/4LZdBSunj15Qe5col2GB56jZI1SkIENyjhh9+bFzPs57349+k1TjFK/HscQDuLC2gvSw4+aRgof0/QDikoCpRVjLPkES5doC2OApTAn1f7LPRJg59Qdo93qPyVxhGlfR8nKV4j/5tyHQZhdEduhhH74010F0YYJ+zXbYL2e/bn6ySO/oWVz3HyjV24QTBWRnUP1+8x3sLf54RnxtEhSXDkkz9XcZaxi+dRuENb5f0hXQP79NLnJMxYO+d3SegfttkhwfDrA3RY6W51H27jNN7fPy6+wlTv423ohxhm+Qeb+OoU5Vf/ecBp9glF6I68JHIlwdvwDghqF+/ibYCj8zva2CLN4gQH7+m4cQqXdEMjRGQlrHC832JCtY/DKEvfxsklLIl35N47HOEEbS/iQ5TRlhf0spJfX7wyNI2sEZzugQHovcbDQ+hDv491Zg9hlNau4D/3W8LdNb5jaxUaBF626BEnt497sszeH3aILBEyKODd0s4qa/C/0Z7eLJZf8btYeSnMaOTjq81HlGbL20NCV/HybHlmwz8H/rlny69nv1bo4ArN5+g2LmaJzhFRD8oNTuBtk+ffHcJtQAeOM+jyAia9ZDfexneUx/vwAW0pG5+Qfw8jp3+v7h9TNmlvgoOP8lm/ydgQVzA5pClllZAlDFODopzJcz8+pPl8vztE+/h7gMkreePHUbxj18kMhcB/PkzK3faQUH4+RAE8Dyqr0HOkW7JssnAT+grhnDJ4HW7yuQem0A6WwXfWzxbahUkMM0L1FsTxPiPkGFaxj9F6i5UVSrK0JI0jxtRr4CEsOL9GbCFdx/63fHndgKIGigykuJj9D9Eqie/oFMDirs/+K0d/qquRXPIv8tf7yjTPFiiI96D/VyXVl8UlgvehwLILwnz4nxBZHzusfIg2CWJSwGYOaMM7OkvKjX8fx+TdvKEyXEzdJwxzjaJMAVL6jnEQIqXg4WthYq42501ObBBjRtYQV90604nAumce/acbX7s15GIN6y/7kOFdSgzch4hYuxRe2kWcZkyBgfKByX2lEzkLE0yUCPxNlrzyOkZZyn6iJAnjhP0NUwGW9D8Vurbh0pOgHs5n/y2iptYwjjQ3GbxZUFYrmCZYXdFCQGXblojKXgGncVTR2Ix7eF7T6Nr4GTo+CGF97BBoJWj+Ktkd6BBjGHpyUSpydr0kBqkgs0RIFyuMqHI53voUByCbMFbS0P+BNkqvNozqlfmbTfiFVQW6rqOf/Mb0jvTfYL3e3CN4T292a5SmdA2bpPOPSPk7qA/U0X15a4aRkq7+TohQpFwQ7dPurnZ7epcam9w32X0Y78Ou8ZW3xnT2R4R8H+8zojN/ByMagSl5pS5/M2Cm64xY/Mn/FJMLXbwVd3pYowo0if8Md/l8vsbbO1CM5PHLOCK8g9ASIMAmfHEB9pFczZd1SZQvv8VbqtTrb6l86LhOFpcYzMYaMMKiOr21y+XAKleB3QgGAJL6OY4COo1fFm+JMKMwUuKN8n/xAbQP0boxNWdVIA9K6I6YNmAItD1mgJ26A1/+5zHO4q/KPUoVQGgwFBwoYZYq0Cnp5T+ANPRZQwsyhR/Ij79VlDzyjx19jFm35wxKwaxu8yvk7z+p4gcuVHA4CPgbJHeA7iuhFBzBXRJ/jzgsr+L9Ycsal+W6i43fS1V35KT68r8qYaogsKlhQN7OY3xIlB1AugyMkrIngKLGZ0N8r8h6ZnwfO5JlWzXYbC/ZbJcNHR/o0yHtIQMgCUqQXIy5bjTZa1hjHCnUQCuwNvMXxHkr1TZfkybAhrNbDXM85qWd5cgp3hNoUiENo2/APJOkZkdi7zqX0XzdhQ8w4kOqfPkvU1PexWQi4PJ3rIDeUmCSlU2YpJmyQ/+IEwXgjJLFyg7jjNzbdc8MaUV60CZ747bYgv2MgfsHrIAfwVAByH45sNryPCrUWVZmvjCZXDVV1sf4jrYCCiaiGuMlKzRrgia7zkFihfnCIDD+N/BWCPv7HD0qX97iJCNK5BF8S/AWvnJGw5BoYyxFd0ceC5Sai3+jcWENUCLqadJfQeYNzj+h/R9RmPVMLrQONtjwBkWetPO3Sk/5GBsCEYSpHz8weWjZWN6kHzG81CIq7OHXnBO66p0Jq/4ZjWCLjasUfUPPjCZsURGk1FbHMLqXNfMMJ67p3L2UXNA5TNLzdW1qgus6762xmFzZxVR5i6daTNx3IWqmGO6uy2Lp8c1ipI6rSwQPFAhfEvdVvMR5MJ9eQ9jDmK9koK4Jf4CqY7MOHkymfNG/Kl9YvIAqTxjZeZJ9ffqhPP0IDpjAGb+M0ER3ypcvJGr5MT48JLjzSUX/+lSdhxbFQkhIBbqZEZEO93YKlFrwINJ9Q/KXLxw80bWqy0Ko51qixvMsUeNZl6jxc5eoIaBnPuIHvFUMhcaLH2tvkMa06durBZvrL6r+/KImEd6ARAy79S/K36u6+PIRCjIUtE3j6ngshToPnJWXOxYjbXat92cLf7g5uP5KwvIp2GMf32Sx/20fblkInuRDsHIN2B5TD/rc9w87gmyA5zKj4mlni1t4OEx3LMTfWGUMrflMoRL+OD7KQnc3yyBYLlXNtT3V8jYbde0YhmrjteFtDNcwN+6CBPuoeaZqAH5SV5CkN8KHSu5zf0RgNElw/GWRR+LghmYXCNKivD12p1EK8c1d/eiwA0QAzX9ZIZLY6pTkPDHJZJ3QDhsnEsdNQho1fZ3EKPARiMhtnltjXS1aWZizMpMj0AdVbj7NjGbVoX5I/0hxcoNhZcIlDDSVm/97wAfM0sCgg9ID9d/2pYq9Aj9ws42/s1dIrWJRbJHnsIpJNirJoap7nZ5nN/EOr0hKJk+Fke7eoCS7Vz5RPMa6BN8RmmNrEkZaPE+GB78/4jscBYZLMzVn9cdfOY3kDcvHZGyJf6lgbrJM6U83/28Zkj0r1mnDBWHUuak+qzRV/LJrV4uGrOK/OS2M8Du8Kxzc9jDV3XCliTC9SmBSIrS9QHsA1dvijW626C6lya0APBYyhde5sLP8AjzvPdEXH2Ef3sBtnDdQ5AVIM6Q/jqeSS69nok2g2Ui1kKap1tK01aVn+aqDTbTGS990df8ovdSR4kovsUjn/j8PIVs9feJs1MXZGyXOufSRWSyTy60WSAL7HkekU5Ms6NHSdGzo64Dc6M8mOHpbcMxhwSkcweoSNWtyYdXuWTURqlPWW7FrlBZHRtyOVint8Jr3nggds0oXrB6MLqZWMc4ii/cf8SbLV72uMZEDBhfrOMvi3TUtdsgtq5tLLS0c24IavwHw+mEHSvMB08UGdH8BV1Q1/sq8jEfFxzTtfLb4i3FmdlwFa60uO647Z1rHVfdMJ1dX4O9nRTkCXLTIxbdhek8gIgvw0SasZhPANoCfN6Dar75HOODolCyGHzkCeBsnIAMZTknhwNLLb1I8VLtlGrTpTzATwfkhI7lHHJDoTFq0mgLH6fuQJP5p4lEH3m50Q7vUL8yV+053bt23uue+183Phn5uwQiMQQqTUtjOpXFhr3T9neXc6jajMQoai9AYmn5pXixXupHTGJrxXtcLGpvRmAWNY9/qDtDYFRqH0uj6pZXTWLe6y2jKvlxG417aF17RDtBYxnujpFkymmVJ497qywaNd6TRtZVuvnMNSqQ5OZEDRLpGqQzn0smpQM5vdQ/IvPeGzsioD8MKyxyvWldWyWMXpWWVS/3VZaSqzMr/2WfOr+qyearLhGqgLHegBkrX7M4iqPOEyJ6fMH/lCkwF4eKRzVheGNVXvGTyipdIraFT/iO1hul9fNgGV3scMS9hFfrfiNFhWGNC5We94sjUplUcmd5LKRKtFRAxnNQOWRb4qafspG0ZYX1igvouYzBWWbbFl7D4/oBnPPNJsCampxSlVirSrkSq3J2pGuj0VU/mC6h6Gq7RyddIrXymXrdTvcOr3anSNCp4WFkPp37nWKjDCn2eJoUY7GVvBMEo4CTzRDDWPQ2spaqtXV+1Al1XPdN0Vawh39OCYOla1tETOQ+CMFXO12jd9kcq5k7YA9GX4i5I6fWXPv5NhrdDjkhZwGlpTxwXoyAZcjA8Of+imQeXdzGaLYh4GUbNezZrvoNec4uNjnv156iv0HrCqj1h1p4waq62yfFE6lwZR0+EGbprTNTEXVRJDOaY99nddjYOtxAWx7UCX9fWKtgAEBYDaerS0nTVxTpyfG9t2ht8FJb3KKFSzxWTuufuNuWmKijOCDmREg9vqnToP106msChQzrY+6wHp9zamnVr67lOuaxRLmuU9eeWvStf0Os2NFG3e6If6jhcP9Qy254m9ZOW1qV2oa004kZq1EXUiIekEUeK+Zkm9TOtd4Z2uwSC5XvdJhTm0RMtKUxK4VUomCdq2AWFc+s1KKw6hWXdeswLLSlsRuHmFA74fBqQWBUS6oTqpgkOr0VIbEYCPqhVkLgNkmWbhLqgumODu+uCY+14dU/WLDxQ3XErJMsaScWx1DWn6lmWUKzwK8sLw16lffz3y6sc61Xme5S63cn85itbG/Ajl91u5FVyh6LwXwDgKnV8+Z+HVLmNt+AVRRTurEKcPY7zKe0zu7EW5H3Kwb0ytT0x4za9kA1HU1xQzXmRLujR4Wh5OuWt6Z6Ole9kmceJbNsn5vAGrNqj8HsNQ8LvJexNcMeFujF+rrtpnXbHi6BzLe7xMsdU2NdtuLVVyrGbUwgH0zxeqz9nrh6zgwzGB8jZeMYaqe4SrVXLWW5UtHaR6uvLYO25yFp7+hHGf4YZR99bOL60wuLOrjYl31b6vYKAfjkZ0GtyiL5gmRSpkNqVd3EwBtZ3NiPi+aoFWC/zSsVvu+b3qo1kcUFulOTFH1bnc0a9WZWXk24+bhWPT8s/G/oYR7ZgtsxAW0jzbJAC1fLWnmpt3I263jgY/gqstW062FqbRxm4SJAf98jAQA76mZLONQBi89Z/dYPAvBGfk0qAgHdbvGSzsWKt1hI8ay6KGn1DAI7t2d33eRnnmoQIhGiey9+1evxdbay/qzvgZ+or+52uLW9dmjTUtbrDWyHxWiR57tUAP9NcOZSE5lW9927d5aUkFiVZtkjsJonbImE+r22VJA5LznoVd9U9JoJLGrdBk3u9JBFs82g8Po3b8nsJ+Pc7Nt8Wfu/xSr/ja53V/v1yfJ8xnWoaQ+lUe8lzUs2z2r/nS3wuBTxLy3yRnuWpT0eY6rQ9PfeJA/Y86T7mFklt0pfzhcpMH0FK+/MtJge+0P2q7BCjt6Tym9gl5BP884C2h+OEd9tTKkdggLeEIRo9ocfHMFdkmodl9HtY5X7hIk9iI3fjOxvVXxu+apmOq3oawMyNubZ83dMcHaMjuDzq9Tq6rOh7iRLH5/SxWGnjJCfLakBMqfLdIUBoFhukq3mLEr6Z9Z9GJ7FVJ7bqxI2meAm/7rbME6f8DG3YU2rjTX1+vGlYXLy5rIT9a1H/SlywPCnveOnXOXlzApsBxGJaJ0QiAtDj5Ry+V4Me42qHkpicqhYnnRHma0wKa7ePqy0O7nCQE1MZpMG7aANWkCRDqGf+PAHdDkBRwoeuA35aRUHdgVN2tYoT2JVquJRdqRzjQy48yZp+U9D0P3UrPr9o8Y8ohAVNapCBlVuc+GG8qDhvelV7NUBdocEal3+5cS8nf2kN5S91x3pxjhsNUQ/mBF+m+nzpnluXmrmke15xcE4PJsgRlsxBcJPOWjuFB1icrCbj/ck5eqwtzllscprcmejEuf1psnITcO7FaVqwdOzAUHXL11TLMTeqZ7mW6nvLtemYmrMMlkcvrqHb665c4yY/O6BLFLpN998sS9Z/q3trQ/H4cutwHi83yxmuxc+94rfRuG827uuN9ozu+8vGfVCTvSkqaGBiTsp4IZ4W2cLA8bR0rYJl2LGnaJuLewL4I9g+VuCMUYtFV+BkAWUql/phDCm4+QVjZoAx9ROiu9FMneaVNRiN/jcFNYbmvkhQ8zyFThRKnBo/nR496a4oepqwV6fX325xZJxJ+uDj65zGBgKsOhPOS9jdc/LDeOVwontanFieDZbjRNff4M3aN9TA9mzAichU1xsrUH3T9l13bfmGWcGJFcNZx4iVG8IlVc8a7Z+KFueN7VdeQw3smfmmHVrf1ACG5T2jcUNvNGI0EGhXYL/VxEQMaf07YMhKuN6tFenXymrLSv3a1aFw1y+c+LNwojm4CdzRXxxO9P59Y1+/oAxlwq4zYY+IW829FVm0WlsOkOgTAYnVD0jK/aQMjxhLFzlY91RNW1qqRc5VWjuBper6xnaxqVuasT7ikbqObtS31vV3rQpBl4Ap5rMWJbiTixLckwKXyubiYwzKrCMOs363AXKsOnHjrln/afCCXw0+KtQn3mf8PEUHLhfGeDKRsHpZQuFdFwin+P2rIGFOzPLCCxLMl4kqTr2zzHq+XWT283+q6Wfm5352QcVJojCioKez7oLYiPXxy6jwEKgjtNsTaMAs2D5OwyoIssryvYV/ZBGMWrpHxH7kh8dp5IDf40YW8nT9JMMfBTCqXSZ4Zrslh6wCJg3xJu06QbECnmqi98Tb0/LjWALacbuzT94em3bf+YJ56jgpouy3eaezy46jKtq9lcvsiaqlzYZaA7Iy2bZZMoUEBn1Ce9L/Du1XCCwhznIZSe8RrfsFdyFD0R0gSfIEkN2E/8IVjm/DiEg7OWLskGe1vocB/WAg4Jl7zM5XZLufjl/u/XvxaV/24V5L3aPMv9eVv1Dsqei6p/8VWk0xg3+OCw6vq2uG5+bo7WNI9nh3LLsi+kMicSBV+BYn4ICRnq58TN99/RlKrAsSl6fMqDQpIvjIMSsq+sQxLyv6hFVmYkWfsI/yKfjEcTeW6BPucZOf4BPLMjAo+oR3jP6KvkLtuP9W9BEZWqPYZyn8ROk2iD5RZtJlnimWrihnsutc563zixiA5OJoVl4/Liof3/rKF5m2AMg3ZfIkQ74piycyA00d7e6CnePaI4886ZLh0+GJHeOTL6htseseGTOjXV0v+6VRvCGvX0bFG+KuYIkmdGmJNkZLtOiIa3izi2t1yFTJtdhnwrqn8qx3kepyIl449q2mhYTLkFMC3M74+kVUKRRNV/mPUUBCKknNrbk/bvg1qgJ/trgEPvjaqa1AhrXTPAzY/WpnhAabro9cnj4aqdja0inbkJwMdWu0XnUkrddkoNPxtE5RvWbOrtcMrl7rfhf1Ftv6oi4AjTBGRQq8jk+6cERBlcRChaJptM4VkSmaU7SPo45uq83fcQpOqIyS9uMoCyN6iL7GV9BtLSrfU+X1nkOf/zwQT/kGPOXFOE03yLvJU7yrLfw3Hcn7Z5ZrCaufH2h8L4CMpox5XcOPESO8FhmhxdPs7xKUpnmKVAT8XiASezjVi7B5VqN8ERm79BaTABvOI2vwR0b4HMAwg907Y2zN2THHXIZsegyZnP0RbZwXaJjWqscxU7IWM7d3030KXR9tvcbZmh7rNZdlEDVemrzxmtvAzMFq8c1Rtu3vxyLOWyv6jvOs5FXjeh6tvNljlOzoFZKaB72Gio+ZFAlMULe7uMxiV399WVzjfxwecMSS6kQh7XLV/AnvoGfcHQnXC9vWM9cO/dBdy8aPtrz8d9BUYj7ZexyiqDmjRYvNGS2uFzNaRpPzTyp9Kq2Vnn++2hKYJ+4E8eenevO58MksNv6EGKRtoftM3/twu20bvudm3eJZbT64kH9/Ns82VzsRniK+HeROV/FI058orgtNlcMDAcNT1WGya8jsdZjScogBnjVpnkVjLv2MSnLFdeD5aKTj5Z9nsdzb56Og6QGIHAXxwIs0CpJIyhS53BlRkPnyURA3B3F7iIIETYFBR7G7yeLJbp7ccIUcPnWq53+qF9XP+QAYGG0CxdFUN0Bpw4ZPeT3HnNEaYzQGOON6wWKxChBa0khx5XxHRkd9VjHY0m/7hV8bR8TuMd6LhBzs8eClrd65L1gIO/ARTL/tnwHBjLC2w7hFVI30sjVFRw4NQ0gruhwIwfEBRKHXTbj91jIBtW+Azv5CliNAiRzgmZ66yQEPD6eIN1Q51mBqvuAiQWth62tKgA1uxc9NRM+5ngFqXIVdOto8rUWunzrBA1ISYdmBob8+1ihyIRcTt1OPejg28cxwpBuI9HFzhdIwlcIEYnCoLdLCcEgA/7Q1zyytm6MtfSvlz8cR0tb9vw/RHfuomoTtEQ0BCgZVyb6C7gigwSKAZkeYVSRyandWGXRGAtsLe3pIpJ2BK3Yu/egz1hmtwY5r3w2nu3jmh1WnwSOf72GBnQJ1uBzUwXGoRfnlGjYhEDQdqHgcnDIS8IhWAPYAHns2wMMrqCowlWiOiG+m+8JDbcgwBg5VOxNGK227LeJn8R3pynEz0yHMHwmKwsOuY9UbwsBEDgqIAZPKjiMJUNJfVjAzMx2BATHQIldVIMmicAJq5gQGY2i4d5MHTyaElprwqA+hNNHS6az9gNGzpI2ezTHSYyIgQnigvUSm4gGhmTFGwoG5as4l7a+QlfNmNsii1nLIPHJ3+3CQVMX41I1htVZue9iFUadRGYZSKrcKeoyP32Ere016ZRS/Y+aJiBn5kel8ARTB9XQF8yeilmHAMs1mfnSe+ekzADzndLoZlPR5Giu9WRU6ZPzmdsplLN2QizeiopGj5nPRGVDz7kgDOA64DKMHafM4Ltckx4goVD+RSZUzhVzW82B3PdRBTGUY3eUfLJQfAtd+y1nZErXwHXLeztYRDRYfIpzLftty25E45ruvHrLmRDbjd7WbeRDvPYxdPf8T94TxDJgFlB8mQMQhCzfFMUQp+xnmn0MSKossd1P2IJzusj+VuxFTFv/U13Z5TzkebiAAJobr/yVsRAf2KfF5xaMdFdMQRiM9wQoJW61yPedp3VZVTmVKmqHJyi2xyhFhx6mPudrRHVROmgd3nGYAR4w2U4VATzhFwuZKO6MDMWmhOMWY+kieDeyubBn2iKxxvrjE1NoT4Iwsiul3DmeHMQ4HxgwkCjjMk8OvuvHXzBUltYFKVJSIbtmdUrTTCcR46KHsoIkcyhvt/RQ81KAvxfDAMgdtXIDYjQWWHKwnNIN9WG8GcMaBfaLMVlou510wMiQc2BjqQxj99GALYSV0SuzTA0Km8FfDJSJm40S2X+UGaOSxVtecz1WHJzbkYd0pn40QLSjiDPpUmE0WIIyEYaNx0aQCkkppa9OSVG6JlpF4YoakOEyJCw+NTkPCO4Npembp5nBHD08TLPCszExzdVVuSVQnj9lZNTQmeuxp2o2qhgdjjRmMzQGFp6iQ6i8XnBHjtg31xGIYPtg9UbBxJPQa2pFO2+YdZ9dsuwrneLqoYvBa8bDjLfFdrZpgmMvtC3O5BdbsDHO5I5FoH6w9JfjkHmE2HJbjgM/+9ET5UHMZlzfEsBP3eAsJ0MzFp6dgmLttZhKmFRhL/66ablzkjcKz3HqXE7kVp4N4KjcuN1N8mI/b66/sNYrgXzNpM2WkMwaeeLD7yP47vBPj3RwfPB1fSzvMf1dZbTc8Wo6BR7wTB2fAr/ke1ROBVJMDUkfsTBAOkM2OsWfddCn6YkYHp+0h7DnTPkJ5f6EDmNojofVpgKnLAabdbQ9NC7e82p2K1vowoGi8uaPVMXjm2SLNjiAkLw+q7AGxVjck555xyVez3bN46vTE8KsROwiAezrLGGx8Wjg8JvbZyaMgNhUGC1P7a3fE3XNW6UoMonQEVkdUeQ/bhWF81OVRdNtpY4yd5p11eoLt80J50yV/pCh9HWdZvLsmH0+4Dh+K7+iMACs8vSsVmRXRvbqY7i3Oj+UCWLNT7/KOne3DiG+3cRwoe7Z0x4f/OoO3crp48rsVUtXmEBAdfdTCW3j7cw9JAlvLFVbNhK2nbLGyOfhzBjU6qj6j5w0JIekJaJeLoEWPHBVrU13y8HJ3q/2hUpcHkwcaEwLfosW5Q7BxBTp52wyIiANyDrCVyRXN5B6IpxOFnYXBVKJuyxWpdmYTKzd7ilRlIjJD77w4pE9gS3qus4U2o3e9J3s8Dp+Ai0XA91wJQPEuebHBEWc8deHtWQ6P+lpT81UbXFz9iDdV3c+FyDNXFErF4ji8TkcSBgccnR5ADoV9pV7aXNFWiQPpRJdcC/t1DIwL8dp2m8vPqPUkP7lux+Ryod60cOCgvyvIi3NCYCXx0TeV+9W33kkRDIyO+jKMaHBXFTomeL4N2yr32J9JWc5JLI0450Do1AsJCy9QrCY8LavaJ9Nlbf5M4SIeE5KHUXQaZ76irHUqJwi8I4LnRwJCdlu4nHlKV+aQ1z6DHZK1OD8xoCdY32TlBpBr2rtrmyyO3czP9xGXrLkPChWzwEIBOZtjj38eNhD99pigtfTkscGShw0G4cSJLD73oz1TdtgPvssuj1sb4XFzDwWeeOTLhwfCVEuS0K6ZoJlrINKm5hNK0vvxXln3mXHDB1arIjsM5XHSWJQiX/QjAkU66n3qjzVLuet3ZarihPPKAnwX0bEBCCWTux+DI3QOZOEkowcrZ8IgwJEie2iJMVsOonPmRyCrExn7cSZSMPX0Moy3fULjLWOJuR9nn8USj/pU67CmF86TtM3WsxUuuYLZiPL7Pz1IRu/ORnA/HTQ9PTy9MKk+9WKFScIK9tlBGe/MJlGjLLqyuz7ZNG9JlfDxBVzrLAIh9LEQglcV8qKY5IVSZJgUt7ZSyGOyYdc5IGN8hx0wVAjozPNxATkG+SUiliAkmgYvej9L0Q04PDHAYXEAx5Syj/wc1PYnxPh4Iz8QWwqjeDyMMrxzkAN3TvOVFHW+D/p2wx3xY9vEwVALVMzC/Cys8I7Z/VlG1xkNHGbx5k9q0ng7diT5nBFTSgxRDF3y6gXGbNmb0ao8B1SZEz9ImvOZwYQQehHO3Q/1x8Umc1l5Xk7cPEF4wBpvrWU+r+7xTOxoa922AHN8yr5jD/4szfK+4HLqj9KqvEN551v7Ku/wkfGOz0BV1akMnVTAWGoUF4gcM3HyYfCS6CfTrOr8juGA2TilFtfltPhoO8H3t8TVgFh/prR2z+0BT7t2rgHu8a+F6uwY1gefU5NfWBeeqeixLqImode6zNAG7/Oh/WVxfLMhajVFLIFoTL++ukUMgHAZIKfldqCDr6lFNzbLjIKXSJve8hD+lJB6wV5HqzEB/SiKPwUUoYxiMscrJr78jFFMMhzw5oqPa2Va531mb4x24H0zoXvR1Ns6ealafhSXLnrifDEYvhrs3fU/qyYb+LCe6N4zGX3DK3Cc3jIvBj+Xjpxbac2lrnRpdWVIq6tcwcngHp17eNYoBcc9v2qcupQGcDK6j/dh8yFtKZovENGWol8sF8FlonpABInxJJ+vK3hRD74O4OFkvmyL2kJJQdOlBc0YL2hy6EM+piaFLaQlgPcd3CGZkUnL8U475T/B20TPf4JXUz60ymXWLM9TH1rlwktXctHq0os2X+bc103wzx1grxVK4P9BtafkwSDcbEL/sAXDWj0ddb9Fj5QC0JZ/H6c4uggfFsdjvNj928c9rWQ87BhL5H/Eh0n3wBa6w28itN4ePw3+EPok5EWeorbkNtzRrEoKYDILo7s3CYLWPuEgxA9oq2Ca5d/FASWG/tW/q68T9IDVS/xd/RwnW+pFs63QbGNDjiRXlLsKu/n1W6C8IZ3Rnl/pruOahqZrjunZbHI+ALMLd21qvr501cDd6Krl+r6KjI2tGqbprw1rs0GuD41uAakQCEyeMc0yosc6gJ4Wr4CjAxBcQsPpLfqGIxrQje8j5ff48I2e2Phh+4iUa7yn+3yu8W6doCjIlAcUKdfhP8jF2/t4h1LlHQmuruMkPtzdw7D/H9GBlnpGHwEA
```

### Operating System

Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by RobLoach**
This does two things to fix up how resource modifiers are applied. Fixes #14456, particularly with this [BNW](https://github.com/RobLoach/Civ-V-Brave-New-World/) example:

```
"[+34]% [Tourism] resource production <in this city>"
```

### 1. Resource Modifier Calculation

When applying resource modifiers, it would apply the modifier amount to each gained resource. This would cause issues as if you have a `[+34]%` resource modifier, as it would mess up due to integer precision. 33% of 2, when converted to an int, is 2. This applies the modifiers to the supply total, instead of each individual entry.

#### Before

Take the example of having 3 33% resource modifiers. The modifier would be applied to each entry, while converting each to an integer. It ends up looking like:

```
2 * 1.34 + 2 * 1.34 + 2 * 1.34
= 6
```

Effectively the 3 resource modifiers do nothing. You start with 6, and end up with 6.

#### After

The amount is modified after the total is calculated, so the integer precision doesn't have a negative impact on the calculation:

```
(2 + 2 + 2) * 1.34
= 8
```

The resource modifier is now applied after the total is calculated, meaning you start with 6, and once 33% is applied, you now have 8. This effectively mimics the effect of the original Civ5.

### 2. City-Level Resource Modifiers

When applying the resource modifiers, it would only take the Civ-wide resource modifiers. This means that if you had a building that would modify the resource production `<in this city>`, it would get lost.

#### Before
The below would not work at all, since it would only use **civ-wide** resource modifiers. The `<in this city>` was skipped.
```
"[+34]% [Tourism] resource production <in this city>"
```

#### After
The `<in this city>` modifier now works, as resource modifiers are retrieved at the city-level.
```
"[+34]% [Tourism] resource production <in this city>"
```

### References

- https://github.com/yairm210/Unciv/issues/14456

### CODE REVIEW

File: core/src/com/unciv/models/ruleset/tile/ResourceSupplyList.kt [hunk 1]
```diff
@@ -93,6 +93,22 @@ class ResourceSupplyList(
...
 
+    /**
+     * Applies the given modifiers list to the resource supplies.
+     *
+     * @param resourceModifier The list of modifiers to apply to each resource.
+     */
+    fun applyModifiers(resourceModifer: Map<String, Float>) {
+        for ((resourceName, modifier) in resourceModifer) {
+            if (modifier == 1f) continue
+            for (resourceSupply in this) {
```
Comment (SomeTroglodyte) [inline core/src/com/unciv/models/ruleset/tile/ResourceSupplyList.kt:104]: Two loops or one loop and a Map lookup?

Comment (RobLoach) [reply core/src/com/unciv/models/ruleset/tile/ResourceSupplyList.kt:104]: I'm unsure what you're proposing, but I think it would do well as a Dr. Seuss book.

File: core/src/com/unciv/logic/city/CityResources.kt [hunk 2]
```diff
@@ -74,33 +74,47 @@ object CityResources {
...
         return resourceSupplyList
     }
 
     @Readonly
     private fun getResourceFromUniqueImprovedTiles(city: City, resourceModifer: Map<String, Float>): ResourceSupplyList {
         val resourceSupplyList = ResourceSupplyList()
-        for (tileInfo in city.getTiles().filter { it.getUnpillagedImprovement() != null }) {
-            val gameContext = GameContext(city.civ, city, tile = tileInfo)
+        val applicableTiles = city.getTiles().filter { it.getUnpillagedImprovement() != null }
+        val gameContext = GameContext(city.civ)
```
Comment (SeventhM) [inline core/src/com/unciv/logic/city/CityResources.kt]:
```suggestion
        val gameContext = city.civ.state
```

That said, why move the context outside of the for loop? I'm pretty sure tile information matters here

File: core/src/com/unciv/models/ruleset/tile/ResourceSupplyList.kt (hunk 1 above)
Comment (SeventhM) [reply core/src/com/unciv/models/ruleset/tile/ResourceSupplyList.kt:104]:
```kotlin
   for (supply in this) {
        val modifier = resourceModifer.firstOrNull { it.key == supply.resource.name  } ?: continue
        if (modifier.value == 1f) continue  // Oh hey, you misspelled modifier above
        // mutiply here
    }
```

1 loop, and the second loop is moved to the lookup function (firstOrNull)

File: core/src/com/unciv/logic/city/CityResources.kt (hunk 2 above)
Comment (RobLoach) [reply core/src/com/unciv/logic/city/CityResources.kt]: Maybe even `city.state?`
``` suggestion
        val gameContext = city.state
```

Comment (RobLoach) [reply core/src/com/unciv/logic/city/CityResources.kt]: Good catch, moved it back in.

File: core/src/com/unciv/models/ruleset/tile/ResourceSupplyList.kt (hunk 1 above)
Comment (RobLoach) [reply core/src/com/unciv/models/ruleset/tile/ResourceSupplyList.kt:104]: Most cases the modifiers are `1f`, so likely better to `continue` the loop early rather than iterate through each checking against 1f over and over.

If you really want to actually improve performance here, it may be better to have `getResourceModifiers()` return only the modifiers that not `1f`. But that is something I'd rather not take on in this diff.

I'd be happy to look at micro-performance tweaks in a follow up PR.

Comment (SomeTroglodyte) [reply core/src/com/unciv/models/ruleset/tile/ResourceSupplyList.kt:104]: :+1:  As long as some thought was applied

Comment (SomeTroglodyte) [reply core/src/com/unciv/models/ruleset/tile/ResourceSupplyList.kt:104]: "second loop is moved to the lookup function" - `firstOrNull` is still a loop. Or it would be (`resourceModifier.values.firstOrNull`) - it's not defined on a Map. Oh and `resourceModifer` is a typo not repeated in the Kdoc - doesn't your IDE tell you that that `@param` points to nothing? Reminds me of a certain [witchfinder](https://en.wikipedia.org/wiki/Good_Omens#Humans)...

So what I meant was -
```kotlin
    fun applyModifiers(resourceModifier: Map<String, Float>) {
        for (resourceSupply in this) {
            val modifier = resourceModifier[resourceSupply.resource.name] ?: continue
            if (modifier == 1f) continue
            resourceSupply.amount = (modifier * resourceSupply.amount).toInt()
        }
    }
```
... but you're right the actual impact might be irrelevant.

Comment (RobLoach) [reply core/src/com/unciv/models/ruleset/tile/ResourceSupplyList.kt:104]: Fixed the speling, thanks.

Comment (SeventhM) [reply core/src/com/unciv/models/ruleset/tile/ResourceSupplyList.kt:104]: > second loop is moved to the lookup function

That's why I said "moved to", not "replaced by"

But you're right, I kinda just somehow missed that ``get`` was far more applicable here. Same idea, though
