### PR TITLE
Fix: Potential crash on new game after deleting a base ruleset mod

### LINKED ISSUE #11506: Game crash on starting new game after deleting mod
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.5

### Describe the bug

I deleted ancient total war mod, which I didnt use at all. When I go to create new game I get a crash report. The last selected play option was a mod Fantasia that worked fine.
Crash report:
**Platform:** Android
**Version:** 4.11.5 (Build 988)
**Rulesets:** [Civ V - Vanilla, RekMOD, Civ V - Gods & Kings, DeCiv Redux, Epic of Fantasy, Barbarian xp farm, Civ6 Tileset, Fantasia]
**Last Screen:** `com.unciv.ui.screens.mainmenuscreen.MainMenuScreen`

--------------------------------

Device Model: M2101K6G
API Level: 33
System Memory: 5570 MB
    Available (used by Kernel): 1995 MB
    System Low Memory state: false
    Java heap limit: 512 MB
    Java heap free: 19 MB

--------------------------------

**Message:**
```
kotlin.UninitializedPropertyAccessException: lateinit property baseRuleset has not been initialized
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.deselectIncompatibleMods(ModCheckboxTable.kt:199)
	at com.unciv.ui.screens.newgamescreen.ModCheckboxTable.updateSelection(ModCheckboxTable.kt:79)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable.update(GameOptionsTable.kt:77)
	at com.unciv.ui.screens.newgamescreen.GameOptionsTable.<init>(GameOptionsTable.kt:70)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:77)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.<init>(NewGameScreen.kt:50)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:150)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$newGameButton$1.invoke(MainMenuScreen.kt:149)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:103)
	at com.unciv.ui.screens.mainmenuscreen.MainMenuScreen$getMenuButton$1.invoke(MainMenuScreen.kt:101)
	at com.unciv.ui.components.input.ActivationActionMap.activate(ActivationActionMap.kt:56)
	at com.unciv.ui.components.input.ActorAttachments.activate(ActorAttachments.kt:42)
	at com.unciv.ui.components.input.ActivationExtensionsKt.activate(ActivationExtensions.kt:17)
	at com.unciv.ui.components.input.ActivationListener.tap(ActivationListener.kt:15)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(ActorGestureListener.java:52)
	at com.badlogic.gdx.input.GestureDetector.touchUp(GestureDetector.java:206)
	at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(ActorGestureListener.java:125)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:354)
	at com.unciv.ui.screens.basescreen.UncivStage.access$touchUp$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$touchUp$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.touchUp(UncivStage.kt:87)
	at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:423)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:503)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1590)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

```
Able to provide any additional info needed. 

### Steps to Reproduce

1. Install ancient total war mod.
2. Don't use it.
3. Also have fantasia installed.
4. Make new game of Fantasia mod.
5. Delete ancient total war.
6. Go to new game
7. Crash

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Android

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Fixes #11506

### CODE REVIEW

File: core/src/com/unciv/ui/screens/newgamescreen/ModCheckboxTable.kt [hunk 1]
```diff
@@ -84,7 +85,9 @@ class ModCheckboxTable(
         savedModcheckResult = null
         clear()
         mods.clear()  // We'll regenerate this from checked widgets
-        baseRuleset = RulesetCache[newBaseRuleset] ?: return
+        baseRuleset = RulesetCache[newBaseRuleset]
+            // We're calling this from init, baseRuleset is lateinit, and the mod may have been deleted: Must make sure baseRuleset is initialized
+            ?: return setBaseRuleset(BaseRuleset.Civ_V_GnK.fullName)
```
Comment (yairm210) [inline core/src/com/unciv/ui/screens/newgamescreen/ModCheckboxTable.kt:90]: Not good, we've already changed baseRulesetName! This check should be the first thing in the function

**Comment by yairm210** [comment]
We should disallow players to delete the base rulesets - I'm surprised we haven't already

**Review by yairm210 — APPROVED** [review]
