### PR TITLE
Notification log fix

### LINKED ISSUE #8501: String is not translated and Notification bubble problem
Platform
Windows and Android

Version
GitHub, 4.4.7, jar(Windows)
Play Store, 4.4.5(Android)

This string is not translated by the game (with any language selected):
The city will not produce anything. 

Notification bubble is not displayed correctly for this string (with any language selected):
An ancient tribe trained us in their ways of combat!

### PR DESCRIPTION
**Pull request by OptimizedForDensity**
Closes #8501 by translating the "This city will produce nothing" text as well as fixing the bugged notification bubble. I also found a separate bug where ruin rewards had a faulty check for "Only available <conditional>" uniques that caused the conditional to never be considered properly. This is fixed as well.

### CODE REVIEW

File: core/src/com/unciv/ui/overviewscreen/NotificationsOverviewTable.kt [hunk 1]
```diff
@@ -88,7 +88,7 @@ class NotificationsOverviewTable(
             for (notification in categoryNotifications) {
                 val notificationTable = Table(BaseScreen.skin)
 
-                val labelWidth = maxEntryWidth * notification.icons.size - 10f
+                val labelWidth = maxEntryWidth - iconSize * notification.icons.size - 10f
```
Comment (yairm210) [inline core/src/com/unciv/ui/overviewscreen/NotificationsOverviewTable.kt:91]: Are you sure you're not missing () here?

Comment (OptimizedForDensity) [reply core/src/com/unciv/ui/overviewscreen/NotificationsOverviewTable.kt:91]: Do you mean parentheses as in for order of operations?
