### PR TITLE
Fix Civilopedia when opened for a religion-free ruleset without a loaded game

### LINKED ISSUE #13228: Easter Egg breaks Civilopedia from title screen
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Game Version

4.16.4

### Describe the bug

When "Enable Easter Eggs" is enabled in Advanced options, the Civilopedia from the title screen is broken (Civilopedia in-game is OK).

If "Enable Easter Eggs" is not enabled, the title screen Civilopedia is fine.

### Steps to Reproduce

1. Enable "Enable Easter Eggs" in Advanced options (I don't remember if it's enabled by default)
2. Restart Unciv
3. On the title screen, click on the Civilopedia icon

Edit: if the civilopedia is displayed at least one time in-game, going back to the title screen (with Easter Eggs enabled) and clicking on the civilopedia icon does not produce the bug anymore.

### Screenshots

Image

Image

### Operating System

Windows

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Fixes #13228, including "search scope includes hidden objects".

### CODE REVIEW

File: core/src/com/unciv/models/ruleset/unique/IHasUniques.kt [hunk 1]
```diff
@@ -153,9 +153,28 @@ interface IHasUniques : INamed {
...
+                    UniqueType.ConditionalEspionageEnabled,
+                    UniqueType.ConditionalEspionageDisabled
+                )) return true
+        }
         return false
     }
     /** Overload of [isHiddenFromCivilopedia] for use in actually game-agnostic parts of Civilopedia */
     fun isHiddenFromCivilopedia(ruleset: Ruleset) = isHiddenFromCivilopedia(UncivGame.getGameInfoOrNull(), ruleset)
+
+    private fun gameAgnosticVisibleForReligionOrEspionage(hasFeature: Boolean, enabler: UniqueType, disabler: UniqueType): Boolean {
```
Comment (yairm210) [inline core/src/com/unciv/models/ruleset/unique/IHasUniques.kt:173]: I have no idea what this is meant to do

Comment (yairm210) [reply core/src/com/unciv/models/ruleset/unique/IHasUniques.kt]: Coming back to this, I still can't read this.
What does this function mean? What is 'agnostic visible'? What is the bad case and what is the fix?

Comment (SomeTroglodyte) [reply core/src/com/unciv/models/ruleset/unique/IHasUniques.kt]: Means - determine whether religion- or espionage-related stuff (`this` IHasUniques) should be visible in Civilopedia when there is no game loaded (if there is a game loaded, I can ask the GameParameters. If not, I need to guess by looking at the ruleset and by looking for enabling/disabling Uniques on this object. Read <code> &#96;game-agnostic      visible-for-religion-or-espionage&#96; </code>.

The caller provides the guess whether the ruleset has feature-related stuff (true for G&K, false for Vanilla - Vanilla defines no Belief's and no spy names) and enabling/disabling UniqueTypes to look for. Those are different for religion/espionage but the logic how to deal with them is the same.

 Choose any name you like.

Comment (yairm210) [reply core/src/com/unciv/models/ruleset/unique/IHasUniques.kt]: So like... shouldBeVisibleIfNoGameLoaded?

Comment (yairm210) [reply core/src/com/unciv/models/ruleset/unique/IHasUniques.kt]: If there's something that's disabled only if yes/no espionage/religion is enabled/disabled, and there's currently no game loaded, I think we should display it. So for me this entire thing is just 'if no game and yes ruleset, return false' - i.e. should be displayed

Comment (SomeTroglodyte) [reply core/src/com/unciv/models/ruleset/unique/IHasUniques.kt]: Ooooh.... Failed to have that idea so far. Alright. Brainstorm.
- Primary goal: Prevent ~crash~ an empty Pedia when user enters Civilopedia right away from main menu
- Required situation: (lastGameSetup or easter egg ruleset) lets Pedia run with a Religion-free ruleset but gameInfo null. That may be Vanilla, or even a mixed one with extension mods on top of Vanilla (which the easter egg rulesets are).
- Exact cause of ~the crash: Forgot, will look up then edit post, 99% there are still conditionals to evaluate from the ConditionalReligionEnabled, ConditionalReligionDisabled, ConditionalEspionageEnabled, ConditionalEspionageDisabled set~ wrong. All IHasUniques are hidden because of the `if (gameInfo == null && ruleset!!.beliefs.isEmpty()) return true` line - no conditional checking, and that's a bit the point - see the TODO in that function's doc that this PR removes. So at this point it's _not_ a simple "is this religion-specific". So returning `false` = don't hide should be best.  ...???... Nope! We might still be running a ruleset ***with*** Religion so we still need a test whether to show or not. We can assume that if the ruleset has no Religion, there won't be any non-Religion objects -> show is OK. If the ruleset has Religion, we can assume the new-game choice would be "yes", so show all Religion-specific objects. But we don't know how mods might try to do stuff - wild guess - switch between two versions of the same object one for with one for without? That's an argument for spending the effort to do a best guess. Drop complexity because Border case and some imperfection might be acceptable? - counter-argument: it's easy enough.
- ~Could be it's actually a mod checker- findable issue, need to investigate. A ruleset without religion _testing_ for religion? Merits a warning??~ Nope, not the point here, though such a check would make sense.
- ~If so... Yes, definitely, a simple true or false guess might be best~ see above
- ~But if so... Then the Vanilla ruleset would fail the new modchecker test??~ n/a

Comment (SomeTroglodyte) [reply core/src/com/unciv/models/ruleset/unique/IHasUniques.kt]: Alright, renamed, inverted bool to save some negations, and commented a bit much - but if the author meself keeps forgetting the key points and needs to look closely to explain every time we revisit this PR, maybe some verbosity is in order.

**Review by yairm210 — APPROVED** [review]
