### PR TITLE
fixed crash in NextTurnAutomation

### LINKED ISSUE #7226: Exception during next turn
**Platform:** Desktop
**Version:** 4.1.12

**Message:**
```
java.lang.NullPointerException
	at com.unciv.logic.automation.NextTurnAutomation.getClosestCities(NextTurnAutomation.kt:1305)
	at com.unciv.logic.automation.NextTurnAutomation.getMinDistanceBetweenCities(NextTurnAutomation.kt:972)
	at com.unciv.logic.automation.NextTurnAutomation.valueCityStateAlliance(NextTurnAutomation.kt:315)
	at com.unciv.logic.automation.NextTurnAutomation.useGold(NextTurnAutomation.kt:282)
	at com.unciv.logic.automation.NextTurnAutomation.automateCivMoves(NextTurnAutomation.kt:57)
	at com.unciv.logic.GameInfo.nextTurn(GameInfo.kt:247)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invokeSuspend(WorldScreen.kt:653)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.ui.worldscreen.WorldScreen$nextTurn$1.invoke(WorldScreen.kt)
	at com.unciv.utils.concurrency.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:164)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.concurrency.CrashHandlingDispatcher.dispatch$lambda-0(Concurrency.kt:164)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
**Save Mods:**
```
[Civ V - Gods & Kings, philosophy mod]
```

**Save Data:**
<details><summary>Show Saved Game</summary>

```
H4sIAAAAAAAA/+1d3ZbTuJZ+lZpzMxcTM/G/nTugD013w4FpoFkzLC4cW6lyk8R1nAS6Dou3mSeZJxvZkqUtWbJlOwlVRa3uVTiyvCXL0t6ftj5tfU3zz/k6/1eyz4vtbvHhK/79j2SDFk+ScpmUebLdzfYovVp8/Ta7LtZ5mqNddY2zPcUP7MtDSp7Eaf88oN3+ZbJNLlFZ/S7ROr/EN0HSZbHO0PbxZSVkty9KlD1Prq/zLdrtFraD75co2b9GxfUaVdk/5ynOdANlHvLtDvy+SnZ//4zKV1+2KHtV4uK2yfppcp3vk/Vilax36Nvs6/U6uUHl25trtHh+2CTbuha4OH/WvOzPJUIpoi+6w++4TdGr1Ytkt4/eHsqqXbzZHP73sc67+x3tUFKmVyhbfHh8WebpYb0/lIjefVs09xcfXhf7PSpv6J1ftq/LAr8rfuuv9M7C+wZbmDTOUyJvYZ+mwd0RDZ7l1+tik6Q3i69P0PqyTDL8YLG/QuXTpufQ5CbrPk/f7JP9Ybd4jZIUJr8ssnyVoxLX7b9xO+1ereoci/kjHzcG/ozo4m3xZSvJZ+lTC3i83X9B5bUknqZqhH+bvSulB96VEyuCv3tZ/JVv8j1s1H8UWzT7I9mmxQF3cPLzTb69TK7xV1z8A+WXV8ui3M3+64CWKL14Wj1dZ+LtVv98tsb5cX8mv/CXzNfJ4llSzn47JOvk4sVhc32g4l/g0ZSQy9+S5WHdFJoVVNbjMlnmyeLputjhcq7wYCOSkv0VHlfZgeai7crr+DPaFlTwc7Te5dtPOfn1P8n2XznWM+TXk/Kw2+H75NevCP9M1mhTl/FHsl6j/Z5K+T0vLjJ08WuyRXlZNO99VXxitXuebAtayOM1/gY3TRH4c+zWyWcq6GVxmWT57upAH/sDbfOmrd7elE2r4Tbbgvd5+e9PcMUT67die1mA9Kdovd/V1X3XfLGbbItI2d9m22KPe0HKdO0e/bVf/O0Dba+PF7j5Ly7zz2h7cdhdfPgPd37xf//7+PBpV3y8wHe+oIukRBe4612s8nK3v9gkfxblBVYMF/viYoPQvrq3+dssT2vxVVf8pbr8z5+xEvg4S2rFsfiarhM8+NNi8+iwxQ8/WheXefoI2oFHLwpSycf1I7N1wev81yKaVcrqI+629AXeI1zzz+gCVX11i5UZyi7YS/0bq08zsF5Vg4dU7KdGmRy3dm5Vu49YZe4rXfrha5Njge8H32Z5tkg8J4rsKLPsdIkszwtsK878wEoiL1u6S3tpe+lsW6sDXFtsA1f4zTI8+vCgb6xFo22Jabw+rGkZq6LI3tSqduFUent/Iynu5SFf75/gP5VAXL/XeBym2GjkzCpID7wvyk9YBfhYGriBB/4BLT6Qmx+/zdBf19hak0YkdoPWAluPfb5GpH3w++O/Pm4ly64vQ3xJrgKeGLDEkOTHzfmlKih7yyRVaflONrq4dmi2WieX+CVwZ8hq/Y3tYHEoU/QTqtTEwon553laGaCqklX9K1UFSoikupC6e1U1HVWNaarHs/F7/AG3voqY1IjdjYS7Hmspm7aB1HI+LzIE7Sm1qs/Eh8KVx65IkTF7Imb5YuEuHnQzPDr2bxDa/rLBNuMz2qDtvj1m/tzhUfI82V29TK7/QJVFd2Y4Y1mPhqYTkIf+xJrwEVZul4/e4Pvby9nnZI17VWVNLlJUDWZc6AfQIuaPfexGZ3VH2Rf4kqKcZ0WJ+/0eQ5pd3RAEpUUuQ2nE+vxwKM2ehtIgPhCBC7ijRTvcCIvPsnTtk8xgiw82ydrniOEWH6rTtE9QTCM+QhK1zwjgR3wS3tI9/x0gG398BHAjJksAbuRaA90qCDMRtPH6mkO3qtjBwA0UdATwxn8rIVxl6K8fr1G5rwFcNad8VoGxSnNhCEP1IPxCFUzSZKtfteN+03AdWUBX6shFulBHBvbZsLbf4n5eJuv3xTarJiwf3q0P5UGDpiy3MnxujamyeZJmYZRYoeNmlue6yIrSZWCFq+U89qMI+RHFVC9RmiYCpKKq3QBSuceBVG/wGN1XBk2BqOp7xoCKNUF1XYMOYtkth8MDkscD1w7IA591FUCrkaSDW0ZYSqimy+GKUE0HpNsgvy2nO92v4oDX9TTN4GmarUZVPrgmgMoKQP4A5K+vCTK0QvBsJJflgzpA+S64hnUIgHwfyPfAdYDb/gggx7YZyKm10Ckxzst8i8eIAuKQGydBOETKsyTfX1UyOuHOfBrcqfW+aNCrpKm+ImJhRbl12lTBwK5JbjR2QwtimCEWn2ySjwleKsv83WBLVTh1PQFzXaMYIP5kSIZ6hm4DiiFVERGM1t1khlWqIjqQQf2NOu43TdiRhb+0zilj0Tk+RhEYLCTRHLlWhgGD5TlpZCV+EFhJtvTRyvcj240Iivg7tvXLQ3l5JSAJoj/P7psJjuGbsbiro7F63HsA7ZHDb9rcGtkq7BBMhA0RMP3A3QItq80vxapG4DEHWGWHPwAMut16P+6tsbi7xgIeGGjH7VaDhcBQg2ayQOu5sPXYpTPJqpM7tbFTWnvH5i6NWomd0to/3uabZH3x/LBbYt2odG3IWb6Hj2Oi0edmS3Y20HStCSWmQXyqTpu8uES0vrS2VCfqXR+NcZK8HzT5+0EN4yKIGZf8KVWa3nnDLKDkv2nSj4liiPkchWOou+QYGKbT80JunnXBjEOPM/teqmoe0evStFQHFKnb1QyqdLllaPfqyFP3hY77pHm7XDZNG+swUzUPJ4tZ3jJNQwySrDjKlpaXOEtracee5WDwlMbuyvZWGYFMT1D+Z+WtFwBTbYLuJmCibfD1hi7OVH4HYvWrOz67CtldkjtoIaWbjuUsI6DUCP9rUTkYoroY4D1x+CVI9fhlwD0nNq1j9ddjNY+Y8IC9F7+K2BXwMoFL4PgB/hrgqQKpLivTF9qy+W3xxnWFxg2FBm9+W0TSMRwlADgR3fUAnaZCJ2ZCZEhAkqcCAsnuiIWIN78D4jqrJ2Qk50ZYuqEIojacZv6PM5Nwzki74ehhogeE2mKNnQ2JdsV2drlMsaVdZpbjuyvLm0e2FTsrZHmxt/KSwE+9ZE7sbKOdBDtL0wwsrX1USxsew9KGzMYETNFXc/KYsRg47yFmd/kTkcI3QZ6aZHUDZgR5FXyhgrAKDZGCV7rSnsKbBOwq5rd9VkogvCgvOWL5IiaQ14GKCQXZ0VSLmKrWq4k9HLckcDsZvucjnHIdL8pn6VMLmELFMDeDxERIZpCsr34nRu4Q0uy3RoNL36BONLLj1GDK7AtgUOpLkQUA2K0yj6G272SWWl8SuyvYWGE2DRc/pNnyAKPUdOqOKeK7rgkoabCODOyjYT2k8PvazVIn/4fMS2r3KVs2ddg0wAKXNpsS0FSwOAx4eXAtmd7kMwZh7dllsuGqtcfmG1SgLZUIUt0eddtsFkhbrsNRKvVxlQvPGW6/Tj0t/icjTnLtVWmTdVE9DCU9VLsyJrswGxwtuzFp+tQC2ORAlN8kH59QN8qrPMaXO0Jz05mObHBx2jE3VdwPk8B6YIdWb3rRFMtg4Eftc28y5prKtnDPE/dXcccU91ZxXxd3ZvFFRr566Al3OcGdE7aJO4rYL24eqt+sGg674u4vnkYNiWTyuJkL2BWvEveQceek6FCDMwuPzRhcOi3qtVb1JLEaG+g1HgQFvl119mdljrbZ+qbxmfFdbpyze8/oRaf1kE0jUA+H48Mp0Ld4o9mJ6T8du89GE39OTPTpd3hVYrtJykTGBJeXGW2YNLqWtNOwM/NskSbhyp5nqZW4bmR5URJakRNkVhLFSzcLVrYXUtcYV0LQOcZTz7cQdUQKcIunSpkv9VyHruz4IB3ySz352VBJ4yFPT+PyQGptIFch4CtEAp0WEJG0rwiJPjFI11FuA+F1W83ggutQbrYIpMcgPZ5G2jGypXz9ifuEfrTtSP6t9uGdxcUmKmdpcgvvaS38eE/atI1Lxq84xGFHbZk0La0TzwZYvgunh5tlDTzpZPocbWXuju60mrhq1+n9FEo2dIJqWTZ0f5MXuuly5bmWHcxjy4ttx1q6qW858XK5XCXzNFkhgnG4cYAYh6eekWyTlGVeaLeOk7uD6Da1K5b5XoGLlzmM225Yt/EYt4ENfWoCrlF5nmWnMaxMyyENXMlgj5SpV1l6dcFvLjQVuUN4NBb3A1jTmDHduIXfbXbgL14X+O86ybfA181cj/d69XAsSXgAv3aMK/2UPvJTR9A5ua/8HB7l++gq5naty4fb7042obrWzTLF39wMkC4Z1fdTOpO5H5a7kLnvVnT2NuuL3DBwby2/4u5lW3Ivq+KIBDNFpBCWj+8x8WftkB8kDMhoT+/zYlfZZqDI341crWwmmrdeh9PRKe3XIPF4pmrvO04uufVTyjNNE++HAjegfxgGmejmebTCJg2hcgDkDFgdYMM/2OMPtviDbYQgIIAryZUDUQVAdYNYAL5C97bjMwEPpC/VCaQa6WKgbikQud8q9+SweSj8PQPsPDlwHscBMVe1o6gi5rD/PAbjgRpibC5McDrB0JOoI4NNTt+sQWWSRDYGI2kAUC8wRPiVTMwQIXyzA0tC/HzDlaUgeTDDyCggkk3klkYN/Y8I7pkfYRwhUd7N9GB4TuZ3uaUUQnMK+ajAyGfc6tVoT9k6kx02D9bhNMRBWkWl0vZmav4enwdwlM+vAkkZc9YeZ/KpXC2BcDdizhSfXfHNN5wPyLcHeUpd3ZQrE/c84Vlers+u+JYg7uKRNwdFs/5dsEb2QGL18UAJD3thJzL9hnLKTw60TxZ17MeLNGIs+IxB1W4Bt1LYVjw4uNpRgpUMDa82KL7/GKICjZJ71sAkRoFHDGKt1R9Oy9ikk508W7grx1vN3cya+2lqeU5mW8vMTyx3vsL91l4Fy5VPg7Uy+wLJDDz1fDFbGzKDmrI5lMxg8VUhuNWsiYNB/5kJoTua7DNNsDWb3phC0mxmraRgHrmjVQtYWzG1iapK/wG8CBjgFcQCkTbWtWKBiAFjwXTYsk/LumxADmG/32t6wgn37Y4N4v4DT5kY9V0TDVsxcCGjGjKtYXBjyLSGQYwh0zqS5UAmNGRvRyA/va4CCzSs6Ahcx0AOZGabBD0O5DpAdjisA8wDy+2LdDBgMxM4DIJ6I0456aF7eBVzHXLnDtKvhy+gj+c1TXcI3aGjsXSUYB6qR0kGviuB/m5BmB7xzTqxdC+fiHwtHU6mZ91gmIz8eO7ZS8+KgyysQushK/KcpRVlUbwMwzSI45ieE0X1kXCqAU07Y8gfCpE10fUGQmR+CpJ4TJHPHFr8tCSf3eVPeJqgP+40iMw9fd2ErO6Dnbhv0J4L9edOREd691B42OcPe/wyYHJcqUXiGQk8eGy4TD2Dhlxf5uJ5WEX6XvSFWxe6YnxsiZN54caGBX4gFxx/LtRHHDAhHxgcZWSySqVnDahIAWIMB75jRV6KAk4VhftD6Y5pnC9CDNdWZFddYIl2XNWBwYkIa/J+RyY6OWN26jbO27Up9cTnEt8PVQbjHvSGPQPbt7jXwwYeEIdfq3eDgcyACutKl4BBCyi2PKSMZp8a8Es3rhqnuZa3mLFLEJK5uWbpLMnhD1Hi7BFpTOR0hR8EfZ4M6k04NuoeDmvhhCHNmorLrDULtg4Co/MgTnLkdDnausXJLGbh3EEJXCto4qlrYqezSzBkQawM4GieMFQNN41KfljRUP5o3tiJhJNbHXH2dgR2OJpf9+TBHk4Ri+o7BHkwi091FI+uiMbUlIUGneTZwl45oZNFc8vzq6jrWepYy6UXWqGbOShyImeZLSlnQVBKAm9BuHNXAzFYLSwXtUFqJAHWFvprn4FiTQrHzst0QJkACXtSjWBNRcQLoksAfA1DVEXSyzfpMUiPQRnwWoeQhcBTxhDZblrz9FEc3m1zbLHw3/3iNe7GtcdFpoOSc88fuKC38xzZMeEgh7JAz8phHHOk2klCQf5g59m3g0QenbZoQDfsOx22J4Jkc0Z3dbhKuozdKPKsJFtllods34qceG7Z89jJUDSPvVVj3ImGE6w6STr38fFqYz4wdiQ8pzwGtijknh+SB55rDs4tFZ5Vrbg2uabRElvsI3BGq+pYdnjQayS/CszTAIE5KKDVDk67TUJZkA8FefBHAKS6Qmvx68knuafymtn99s6PP3L1hETH8QugJ94QcfLlzJMtxA6PwPSwBHt8B6fBDoJjrNLyJVilGxVEAbHYvmwLLkZIIUOA6xNEzYMHu/DVUbicwfOqtmbP5CD+Ymh/VhcuUMeYH+QrBZOvJ7jnoer8NKD369nB/db5pN9LqxlV2mT1SAaIpBsJqDvzFrqxk6cfWDmRSYBSY0R8NAvUchtca4AkzQIJ5j1wEnLabXDdgEeAG+1+bGkDcAivHS2YPPXKSyr3xPutbU7kgfkRlNitwaX3UNvVJaq1XWsuLG4vhJvoFHvzPKgM2/pRpwF7tJ4vqbUO1TdIfzEN9Sv6gtYl3Kwnbe243+HR7ur5eWNivDzEZzmNStGzWsWAKDJvVTz9mG+JiNgT/Pg0HraEBz/hYUvk85L55oh41g5+ogqS4gu1kkOjeLMhQVKaq5DVgNfFaDMhUEbECXKvdw7fui0O5nriVPS4E8dluevewgfP21EjK5KgG8N3LcDI5Y23SqG6VfGy5I0LquiInHHI2Y3dexOE7Q/QpcZdcYRAqQiYMVOEoDA5BnP0rPmXsqzX95LqINKaBeFxFkStnR5IEBNJECcGtyc3XHc9EOMZQyqe65ToEy48ncmu3ckwBINDex3tdLKzhSjo5c1owhJMPkzV/EBtDQ+GGvSK4uou48z1bWvlzR3Li1crK8K90PKSJPFWAXKclJ6jSiycQIKpU+4iB0ac26pCgcpwwp+Js+E266XZDDGB86LaSCpuM9VHN+XYS3ViOX85MZKpfIq5bqItHykjxyU9PhdVAFspc+g04fDv90rEw6kz3wsA3brTTm8Bb+YeTrINzxUwOBSn81RQ1kA9J4nBo2bAqgwgusDjbpi+bx1Zw1V/IBiB1pk6YGVIdZ4ND1LdG2/RdL7MDxVg20XvtY/0ZJ7Gky0nE9gt2Zx67/Qt9y7eQ/1Ut7t6zRf67pR+NBBbFewRlmKrOnwJGERnBXnBejHI6/JLsLcKrAiDqCYgFdTsCPuFoTZpYMsDHrytgO30Z8LeVch2p/SWAr4QUMHgBkQqrXP31Gf0yWf/qWOUtA5CUp+P7QEoBaKjqE8SlI8a9CQs1D7Rj/JajoCGlAzf39DuKv8krCM3LuP7rdtu6SnZ33+t+m4f2XfiFeuHXSK3AaYaBNkDrmjZhDBFLO/f4Iu/cJtF+5w8YFu4uZDP1RYXtOUjo9p7O9oL1eNoiioiNaHQ/iChqB7o1Ofj1zxsIRmouaqe2KG1SAHDSNeQTg1p1uLhKHDzSZvJAgOOCGe/yLP1ASRsMC0/Jh+719NHFlHvORv7dG6+B0azduIpLFfyID5y4DzOOOYc5XowzNnDEYMDERMTsUdili9m+fgVXyflEXrEOLuQhuzxgnlcPR5WzxcKphn9urypoTCV0823qEzzAoxWgnAfppq3cy5413lld3uyeYsoZ/dSxZtBNnZgcHc0dr4owpGTeESwTJMRiTV8/siPYRdjsetmilV+xaRSZk4rznuXWDdH3NcLVP7z5NOn5Bpr3JzM2BvNDwNz3m+wdn8CvN/hs/vOtV5zpliy90O3sgp0BKkHs9UmUj0MoQKDrMhxN/kTQmx7KSBLO5w9mUdH4FoRkdOV08EqthC1E6bD/PDYRDmuffMWQgRPkhXEw+4I4Tl9tfvjbJmU+P88IUoU98xVrY1vFm8weMKftma2vkyuF183yfXrpMQ9fV/3XfzzTf4vPAhK3CcO1faM2Zc8218tHHd2VbGX9wubnrr7Nt/eYKVN2Knv8/3VH1hCxaP1Hs0f2f4FVvLJvriYB5Ydz3aoYrAGvh8EoeMGgRMRdu2LfLfHPWaZ7BCeYJRJvl38XCa7HR4HGbYbdcozVB1wWfWsXw/byzU2KGXjMsVjBP+3q/i9e6zxt/tFNQ+6Lna5GJ0XW1BYxOvKyyo/hc1PvsZNVpu+rwVu/BKg5YJ+h1dSet0UTaviUb4pmO3aFJ/RBkt/iTb46XpkwJoRECFVlxj9b7VllFNn6lbSvXv7tYe07NMiWbNfjzfFAcsPDVqMAXSxwVjy+PbCbyO9n9xQrUai37n1ts/z9Xr2DKus3R688k8IV0nfk8wbs5Hc1SuNhVV1rVXCEwyais3v1Rj8Pa+mpDVJGtxgaR3lNmvbxx1w6o7QTJHlntCkTxs6vjx0CGTHym9T7Pa/YxOLH8di3lYGrKrYW7RG2NRiZSUOLoq91S3CXvxNvv7c2T2YyTPpgK2+9+Yao4wuPWa3a6nUYsL4H/qAYe2F4dNd5QEdfeh4tDq1IldkSdXBBo4T8xHSqrWJ4hSHpLLRtQO+f+QRx5w46kja+BFHZstyKymNlTPks/SpKhPDLTzVsILgUz/hiWe5n+Ub/MrkLRfV3PWiUhGdXYx6ARQ1YO/x/gp3hd7XUAvp70xvy8Nqte5UDI62jn26yjVDFKouxvxkYi9jyVOsvKqn0UQFLDJ8CUEtDmuu3i7wS1ls5RHv9OlF9ag371Z6e6BBENzUXCF0bYJ94dRagr/w1thvXTeCojNbapWityQ9g0+tQnTKgOndF2ilV7uCkhgE5Qzspn5gqoyYWYWVdoK4jSVDQRLHD2Bbhcvan9TtshKaLtyn9kf0EHcwrGoK00KEjgcbpit88GWlL/AFbnL8ssn6fbHN8Hd4tz6Uhw5Z1N2sMHOaxhtu/ZhvZIqicrX1HGhC1UJMpvDVsos8fa/Sxisupd7ylGpL3XxjdHTbgHvDu6CtrVKHvRxcTquMMRMqFUbpUd49DTYUJnVPlns6rPkUok+5jdVtlkLHjpjSqQYV34ohDiyePt6AEM6SrO5ag0vbw/rG1s9o06ndtYLHW9/26x3RleQN6B6qb8lW7MVPyZLHf8lABeXJKmrra44YMcPbnjHuxrq/et00XteUZLLW9xQqUbamqtlI0CXUp6sVg1QjDQ8xyax7Ywr2tAW3WvdVsst3/ahxaA1c8xr0wlZHUQG5Hd/sq1W6biulFtGHH/xx+EHdYH2dW+UXc038yGQBVnIik8Rp/izLkxcUcIvIKwrDG0nXQMYDoxvbdfaLDW6+fVLeCLa6JpdKdrpOq5uPHuw4cJI3qyiTqk7VNtSWAnNOQEOT/Gl9LmW9M22q7h49Z1TMUBWd4XlR7tBOHl+ewfh6Jzt33k1ZmaEWSqG0FW6dIcilZTkGANuu7jRxrOrVQ6smL5NydwV6zLsy2eaHTfubDVrrGw6C/FEAtM8lrepaZPOS2LtI2gT/sNdSO766d7GtDkdSPH57IHbbfUk3HOfrsU0bg+y939ZrMsx4lQ9btvIH6GFDx6c/1KfVqX1VtpAS3sQuSRPHW8Nm0UnZRAqD6Ov9aka9UrkiU8UilJdj6rQJYy0kjCT5vQLCh2q9F00/1oCjgeegtLeHbVYmvd1SW4f+dpRClooNKt0c37KhCj+REHlyq/rtVpjiKPcU7WM06QqONjDbQ0ctuxtMmbyD6gND8rL4deGdiQuYCivlaAaNM6YBHG0DHMezPLQ+9tAOMtSDO7hOA9unZzbWgxLHo28SLkvshyRtQg90VPQoGndJOTsbNKPvmZoNW13gsaOmLjJNoTOAEHPipwA3JnwPJdPTavhq0vdQcE6meRCVL9xEwZJet0meRs2TmZosmI9yAtjDhDAbWy0bd7zlF9U0or9XD5tldRBShxHX1ErPTNsqnUd1nATJeVSnTYDLgWqFRwkoJzYgftfy0PWZgvZX6rZbJ56bs/AAJjV6ti6K7OK6/sQfzZVlMHQe298DVSqGRZIQOw9LnqBP6RRY2XZtJcMiJxzDYx9oJ9J9H/XoNKFgsFvVhHsUdDqfR09PWews2b7S5PG9wddNpbwRXPCgDYamLc4Gnessw6dvdEaumhQPFkZPVTMXZT6JCPTVHOtwCkbX9vH6sMm3bU9r1OtHCHUfTl4QHk5I8duv0zDBlFP2nsbsWyT02sVNptsZtI6iVirtQAO/SG45kjhtLSJSsRFDJRtxaPOYjwZH0VpGU/ywGxq/TMplN4fe1pcsfaThPdhuV/Bpkez28rxdlafdpo/3BW5U6dle8XR6HvTnsxQuCjMCmG8gXLEGf8Rl8db8ytw+t/f19UFiS8HYPN5YUDFY+idTClaNRlmqVkeGr+m1EbKmOBVcN1rBVEw8ehv5eJR15ZBk7fMs3121cEf/IAi7XmncHKKO/idahTpp6pJGe+4QatYQQ8UHNnR9/1yss4tXpQlFgwbmltyAJHH8PDtUTbNpovSeYbvHj3UCsjBxp1Eg4UkJdqFCPWmGfnhKNUkq0s8B6t1FF7YNkw41G8xmQoU97Gge9eLdyB4VGBVLzp2P+rUVPUi617KHhvLCtrzu9x3BYQ90denU3UG7ZrrG8w1f1h/6sgMgq2dYB29YHQZv92cRQ7qmXT0y3HYdR6tVx7BdHMOObY/qTHZb+qsUJWJPagtW5enNQsF92J/PMpqLUDwfGMhTrK+q5Kn4wwZgSsEg7n9KtXdM+WEVO8N0Y1g2dUp5Cu6QKp/Ky6qUp/A/6xSqjLy0GlqVr7M1DTpffx8mVsSkjpHhy0RaHNbJ7+/abUzKNmjwqAtZ9ck/DWk2andlpQYeYUsjxXAytGEM2A8vNjKHYwN3LUXm0CwaCs06+17n3pJIoXBH+phtxVsYqHxSBZOMcZUx7h/zVT6DbKRgg4xRW54eiRrICw3lBYbyAo28bhvnG0r3DWvrKeRJ1VAsKHgKI2pSmqsrTQEATOQ5hq3hGPYt21CebSLPRJRRtVSQUlt9g3wqv7kWrhnkU3ENlfIU/EJVPtUGNqU8xaY13ViQbZJSnoIorRu5smVWylOsaus0i4wklPIU7iSd5pNRkVaVGuQzGTmGCt6kVrFh9WMzwEvkGTRbbAbIiTyDjLHZhIHIM8gYa6Y3Snnj0NCYJd1YM6frtmOx4fpSbAhHYkM4EpupSCLPSOfO6+46N1DjVU6TjHQEGOSMTSVGphIjU4mhqcTQVGJgKjEwleibSvRNJXqmEj1Tia6pRNdUomMq0TGVaBt3cSOJRsLMqmYK2CwjxEahkcmwV7gDtdDIBGopmBJaaGQCtRRbS7TQyARqKQITaKGRCdRSsOy00MgEainWr7TQyARqKTxGOgVsBLUMwY/ZcDQ2Nub2y1CiSdMRiQY564wmH5dINMhZZzTpfkSiQc46o8kAIRKV7ucW6lKQcmhJJkOblGSAneqMRm7+uaGaqjOaoyKTpYi56dR8rlX1H2e7fVJieHr5okjr489wG+PmvUw2CAZhV8Rrv14nN9W9D1/Tq2KHtk/zzw1BgNyqqa3PD5u6QjwP2dsqJNX0fTGligaBa4cB9RKVr1ZPm+jyu4Vr49R0jZLyPUqucYX/vk2Wa5TROPTNcRxNas3roCdsVDXCFf6pwEi9ftnZ23yDKkpuhpOvr/J1sSuur24ucAJuBNzlcHPYs/RQlhi+S2eW09S3ONObqg0rUSyevB+5c69uxV+yhWfHWRB6gZUtnZXlecHSiueBZyXRfOmtXOS4WfLt/wGdV227VDwBAA==
```
</details>

### PR DESCRIPTION
**Pull request by alexban011**
fixes 1 crash and multiple waiting-to-happen crashes

resolves #7226

### CODE REVIEW

File: core/src/com/unciv/logic/automation/NextTurnAutomation.kt [hunk 1]
```diff
@@ -975,7 +975,10 @@ object NextTurnAutomation {
     data class CityDistance(val city1: CityInfo, val city2: CityInfo, val aerialDistance: Int)
 
     fun getClosestCities(civ1: CivilizationInfo, civ2: CivilizationInfo): CityDistance {
+        val city1 = CityInfo()
+        val city2 = CityInfo()
         val cityDistances = arrayListOf<CityDistance>()
+        cityDistances.add(CityDistance(city1, city2, Int.MAX_VALUE))
```
Comment (OptimizedForDensity) [inline core/src/com/unciv/logic/automation/NextTurnAutomation.kt:981]: You could just do `cityDistances += CityDistance(CityInfo(), CityInfo(), Int.MAX_VALUE)`.

I just checked through the code and all the places where the `city1` and `city2` fields are used check that both civs have > 0 cities so it _should_ be safe to use blank ones. Alternatively, just amending the if statement in the function that's causing the crash to check that both civs have at least 1 city could work too.

**Comment by yairm210** [comment]
We *should* check if both chica have cities in this specific case.
I'm on the fence whether the "less crashes if we got something wrong" is a good of bad thing, I'm actually against because I feel that it will make us miss mistakes in other places...

**Review by yairm210 — APPROVED** [review]
Replacing failable functions with nullable ones means that we need to handle failures so it'll compile, which is perfect :)
