### PR TITLE
Fix doc writer escaping

### LINKED ISSUE #13543: Modding unique page showing wrong characters
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Game Version

4.17.0

### Describe the bug

After the last change to how the uniques page displays certain uniques, the `< >` characters aren't displaying properly in the example text.

### Steps to Reproduce

1. Open the Uniques page for modders
2. Expand an example of a unique conditional
3. Characters will not appear properly

### Screenshots

Image

### Link to save file

_No response_

### Operating System

Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Fixes #13543
Also fixes how NaturalWonderConvertNeighbors was rendered - docDescriptions backtick blocks get an exception, and explicit newlines now render.

### Question
I was testing with a script-based run configuration plus support by DesktopLauncher to allow running the doc writers standalone. I'll show as patch from my Shelf:

<details>

```patch
Subject: [PATCH] Script and launcher support for integrated local Wiki testing
---
Index: test-wiki.sh
===================================================================
diff --git a/test-wiki.sh b/test-wiki.sh
new file mode 100644
--- /dev/null	(date 1751233724900)
+++ b/test-wiki.sh	(date 1751233724900)
@@ -0,0 +1,7 @@
+#!/bin/sh
+
+./gradlew desktop:dist
+java -jar desktop/build/libs/Unciv.jar --docs-writer=./docs
+(mkdocs serve --dirtyreload &)
+xdg-open http://127.0.0.1:8000/
+echo "End of test-wiki.sh"
Index: desktop/src/com/unciv/app/desktop/UiElementDocsWriter.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/desktop/src/com/unciv/app/desktop/UiElementDocsWriter.kt b/desktop/src/com/unciv/app/desktop/UiElementDocsWriter.kt
--- a/desktop/src/com/unciv/app/desktop/UiElementDocsWriter.kt	(revision 54908517c426c8f2fed8ee8e9b57905af46ce175)
+++ b/desktop/src/com/unciv/app/desktop/UiElementDocsWriter.kt	(date 1751230041756)
@@ -2,19 +2,28 @@
 
 import java.io.File
 
-class UiElementDocsWriter {
+class UiElementDocsWriter(docsFolder: String = "../../docs") {
+    private val docPath = File(docsFolder).resolve(relativeDocPath).path
+    private val srcPath = File(docsFolder).resolve(relativeSrcPath).path
+
+    @Suppress("ConstPropertyName")
     companion object {
-        private const val docPath = "../../docs/Modders/Creating-a-UI-skin.md"
+        private const val relativeDocPath = "Modders/Creating-a-UI-skin.md"
         private const val startMarker = "<!--- DO NOT REMOVE OR MODIFY THIS LINE UI_ELEMENT_TABLE_REGION -->"
         private const val endMarker = "<!--- DO NOT REMOVE OR MODIFY THIS LINE UI_ELEMENT_TABLE_REGION_END -->"
-        private const val srcPath = "../../core/src/com/unciv/"
+        private const val relativeSrcPath = "../core/src/com/unciv/"
     }
 
     @Suppress("RegExpRepeatedSpace")  // IDE doesn't know about commented RegExes
-    fun write() {
+    fun write(verbose: Boolean) {
         val docFile = File(docPath)
         val srcFile = File(srcPath)
-        if (!srcFile.exists() || !docFile.parentFile.exists()) return
+        if (!srcFile.exists() || !docFile.parentFile.exists()) {
+            if (!verbose) return
+            if (!srcFile.exists()) println("UiElement documentation skipped: ${srcFile.canonicalPath} not found.")
+            if (!docFile.parentFile.exists()) println("UiElement documentation skipped: ${docFile.parentFile.canonicalPath} not found.")
+            return
+        }
 
         val originalLines = if (docFile.exists()) docFile.readLines() else emptyList()
         val endIndex = originalLines.indexOf(endMarker).takeIf { it != -1 } ?: (originalLines.size - 1)
@@ -100,5 +109,7 @@
         }
 
         docFile.writeText(newLines.joinToString("\n"))
+        if (verbose)
+            println("UiElement documentation successfully written to $docPath: ${elements.size} elements.")
     }
 }
Index: .run/Test Wiki.run.xml
===================================================================
diff --git a/.run/Test Wiki.run.xml b/.run/Test Wiki.run.xml
new file mode 100644
--- /dev/null	(date 1751234947740)
+++ b/.run/Test Wiki.run.xml	(date 1751234947740)
@@ -0,0 +1,16 @@
+<component name="ProjectRunConfigurationManager">
+  <configuration default="false" name="Test Wiki" type="ShConfigurationType">
+    <option name="INDEPENDENT_SCRIPT_PATH" value="true" />
+    <option name="SCRIPT_PATH" value="$PROJECT_DIR$/test-wiki.sh" />
+    <option name="SCRIPT_OPTIONS" value="" />
+    <option name="INDEPENDENT_SCRIPT_WORKING_DIRECTORY" value="true" />
+    <option name="SCRIPT_WORKING_DIRECTORY" value="$PROJECT_DIR$" />
+    <option name="INDEPENDENT_INTERPRETER_PATH" value="true" />
+    <option name="INTERPRETER_PATH" value="/bin/bash" />
+    <option name="INTERPRETER_OPTIONS" value="" />
+    <option name="EXECUTE_IN_TERMINAL" value="true" />
+    <option name="EXECUTE_SCRIPT_FILE" value="true" />
+    <envs />
+    <method v="2" />
+  </configuration>
+</component>
Index: desktop/src/com/unciv/app/desktop/UniqueDocsWriter.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/desktop/src/com/unciv/app/desktop/UniqueDocsWriter.kt b/desktop/src/com/unciv/app/desktop/UniqueDocsWriter.kt
--- a/desktop/src/com/unciv/app/desktop/UniqueDocsWriter.kt	(revision 54908517c426c8f2fed8ee8e9b57905af46ce175)
+++ b/desktop/src/com/unciv/app/desktop/UniqueDocsWriter.kt	(date 1751233261196)
@@ -10,15 +10,20 @@
 import com.unciv.utils.Log
 import java.io.File
 
-class UniqueDocsWriter {
+class UniqueDocsWriter(docsFolder: String = "../../docs") {
+    private val uniqueTypesFileName = File(docsFolder).resolve(relativeUniqueTypesFileName).path
+    private val countablesFileName = File(docsFolder).resolve(relativeCountablesFileName).path
+
+    @Suppress("ConstPropertyName")
     companion object {
-        /** Where the UniqueType file is to be overwritten,
-         *  relative to the current (assets) directory (not incluenced by `--data-dir=`). */
-        private const val uniqueTypesFileName = "../../docs/Modders/uniques.md"
+        /** Where the UniqueType file is to be overwritten, relative to the `docsFolder` parameter,
+         *  which is relative to the current (assets) directory (not influenced by `--data-dir=`). */
+        private const val relativeUniqueTypesFileName = "Modders/uniques.md"
 
-        /** Where the Countables documentation is to inserted,
-         *  relative to the current (assets) directory (not incluenced by `--data-dir=`). */
-        private const val countablesFileName = "../../docs/Modders/Unique-parameters.md"
+        /** Where the Countables documentation is to inserted, relative to the `docsFolder` parameter,
+         *  which is relative to the current (assets) directory (not influenced by `--data-dir=`). */
+        private const val relativeCountablesFileName = "Modders/Unique-parameters.md"
+
         /** Where in the documentation file the Countables are to be inserted, start marker. */
         private const val countablesBeginMarker = "[//]: # (Countables automatically generated BEGIN)"
         /** Where in the documentation file the Countables are to be inserted, end marker. An empty line will always be inserted above it. */
@@ -72,12 +77,17 @@
         }
     }
 
-    fun write() {
-        writeUniqueTypes()
-        writeCountables()
+    fun write(verbose: Boolean) {
+        if (!File(uniqueTypesFileName).parentFile.exists()) {
+            if (!verbose) return
+            println("Documentation skipped: ${File(uniqueTypesFileName).parentFile.canonicalPath} not found.")
+            return
+        }
+        writeUniqueTypes(verbose)
+        writeCountables(verbose)
     }
 
-    private fun writeUniqueTypes() {
+    private fun writeUniqueTypes(verbose: Boolean) {
         // This will output each unique only once, even if it has several targets.
         // Each is grouped under the UniqueTarget is is allowed for with the lowest enum ordinal.
         // UniqueTarget.inheritsFrom is _not_ resolved for this.
@@ -152,9 +162,11 @@
         }
 
         File(uniqueTypesFileName).writeText(lines.joinToString("\n"))
+        if (verbose)
+            println("UniqueTypes documentation successfully written to $uniqueTypesFileName: ${lines.size} lines.")
     }
 
-    private fun writeCountables() {
+    private fun writeCountables(verbose: Boolean) {
         val file = File(countablesFileName)
         val oldContent = try {
             file.readText(Charsets.UTF_8)
@@ -192,6 +204,8 @@
         newContent.append(oldContent, truncateEnd, oldContent.length)
         try {
             file.writeText(newContent.toString(), Charsets.UTF_8)
+            if (verbose)
+                println("Countables documentation successfully written to $countablesFileName: ${Countables.entries.size} entries.")
         } catch (ex: Throwable) {
             Log.error("Can't write $countablesFileName", ex)
             return
Index: desktop/src/com/unciv/app/desktop/DesktopLauncher.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/desktop/src/com/unciv/app/desktop/DesktopLauncher.kt b/desktop/src/com/unciv/app/desktop/DesktopLauncher.kt
--- a/desktop/src/com/unciv/app/desktop/DesktopLauncher.kt	(revision 54908517c426c8f2fed8ee8e9b57905af46ce175)
+++ b/desktop/src/com/unciv/app/desktop/DesktopLauncher.kt	(date 1751233724913)
@@ -66,7 +66,7 @@
             GraphicsEnvironment.getLocalGraphicsEnvironment()
         }
 
-        val customDataDirPrefix="--data-dir="
+        val customDataDirPrefix = "--data-dir="
         val customDataDir = arg.find { it.startsWith(customDataDirPrefix) }?.removePrefix(customDataDirPrefix)
 
         // Setup Desktop logging
@@ -91,6 +91,18 @@
         val isRunFromJAR = DesktopLauncher.javaClass.`package`.specificationVersion != null
         ImagePacker.packImages(isRunFromJAR, dataDirectory)
 
+        val docsWriterPrefix = "--docs-writer="
+        val docsWriterParam = arg.find { it.startsWith(docsWriterPrefix) }?.removePrefix(docsWriterPrefix)
+        val docsOnly = docsWriterParam != null
+        if (!isRunFromJAR || docsOnly) {
+            val docsWriterDir = docsWriterParam ?: "../../docs"
+            // A jar can still write the enum-based documentation
+            UniqueDocsWriter(docsWriterDir).write(verbose = docsOnly)
+            // It's unlikely the jar has access to the sources, but UiElementDocsWriter checks folders anyway
+            UiElementDocsWriter(docsWriterDir).write(verbose = docsOnly)
+            if (docsOnly) exitProcess(0)
+        }
+
         val config = Lwjgl3ApplicationConfiguration()
         config.setWindowIcon("ExtraImages/Icons/Unciv32.png", "ExtraImages/Icons/Unciv128.png")
         if (SharedLibraryLoader.os == Os.MacOsX) updateDockIconForMacOs("ExtraImages/Icons/Unciv128.png")
@@ -118,13 +130,6 @@
 
         config.setInitialBackgroundColor(BaseScreen.clearColor)
 
-        if (!isRunFromJAR) {
-            UniqueDocsWriter().write()
-            UiElementDocsWriter().write()
-        }
-
-
-
         // HardenGdxAudio extends Lwjgl3Application, and the Lwjgl3Application constructor runs as long as the game runs
         HardenGdxAudio(DesktopGame(config, customDataDir), config)
         exitProcess(0)
```
</details>

... Think we should make that official? The script and thus the run config would only work on gnome-including Linux distros, so probably not in this form. Couldn't the docs become a Gradle project, so that a `./gradlew docs:run` could do all that the script does in a more cross-platform way? Doing fresh Gradle configs is way over my head. And yes, I had a jar running UiElementDocsWriter - no problem if I tell it where the sources are. If it doesn't see them, bummer, one console log line, nothing else.

### CODE REVIEW

**Comment by SomeTroglodyte** [comment]
Oh, the deleted file: https://github.com/yairm210/Unciv/commit/96addf305b5a8aaf40b884fc409c45709d5ea51f seems to have misplaced it, it's not referenced in the wiki.

File: desktop/src/com/unciv/app/desktop/UniqueDocsWriter.kt [hunk 1]
```diff
@@ -52,15 +52,21 @@ class UniqueDocsWriter {
     }
 
     // Thanks https://github.com/ktorio/ktor/blob/d89d41ef6dc91479e6c13c25eb306abc15040b8e/ktor-utils/common/src/io/ktor/util/Text.kt#L7-L28
+    /** An escaping routine specifically for mkdocs input: `<>` are escaped **unless** within backticks, and newlines are doubled */
     private fun String.escapeHtml(indent: Int = 0) = buildString(capacity = length + indent + 6) {
+        var inCodeBlock = false
```
Comment (yairm210) [inline desktop/src/com/unciv/app/desktop/UniqueDocsWriter.kt:57]: I see we're going parser-mode 😆

**Comment by yairm210** [comment]
I do not see a reason for a standalone doc parser, I always add the docs directly after a desktop run

**Comment by SomeTroglodyte** [comment]
> I do not see a reason for a standalone doc parser

As I said, similar to having a local "run unit tests" Android Studio _run configuration_, I made that to have **one** green triangle click **compile** the doc writer if necessary, then **run** it, then run mkdocs **serve** and open a browser to it (**view**).
