### PR TITLE
MapGenerator optimization

### LINKED ISSUE #4786: rare bug with hills spawning in water
z
Sometimes Hills can spawn on water tiles. This is extremely rare and i can't find a reliable way to reproduce it apart from generating lots of maps - happens in maybe one out of 25 maps.

`H4sIAAAAAAAAANS9X5PktrHg+1Xm7su+NM9tgPV33mTZss/aOtZaPqHYcOihNFPS1Lqna7a6W7aOwt/9VpEE8cuqBJggWt5rKWKaRQAJEMhMJPIffn53+PHwcPiv3fPh+Pj09i8/n3//x+7j/u2vdqfvdqfD7vHp7nn/7sPbn/9x9+n4cHh32D9dnv/Py/7p+cvd4+6H/eny+7R/OPxwBoFXPxwf3u8fP/uhb/DDab97/mp//PSwf/vz8OP0dHz86nh4fL7U+Mfdj4d3z8fTTwDxYff0mx/3pz/+7XH//o+ncwePu4fPd58Oz7uHt9/vHp72/7j7+dPD7qf96c8/fdq//d3Lx91j1+/b5f39XfiUrz/t3z3vzqCHL7n8+/Sn/dN+d3r3Yf/+7V++OI/9w/Pdbx7O9U7Hx8O7p7s/fnq+/Pn6eb/7+Oar49/2p7vP3h1fnrq3nx8/fnd5PD7e/cfLu4cznDdfvDxdfn55/O7wsH/z5927ruKfjt8du4cvD4+Hxx/u/rQ7PJyOu/dnwOeny5vfvH9518393R92T+cJufvsMqbTT3efv5xO+8d3P939avfwcOj7/eLl+eV0hn4e/91vXx4/Hf/2/jyuL/an58sSnh+/3J9n5s3nu3P1C+x3x8fjx37Aj0/Pp5d3XUeXHg7nObjAuvvs+VLjzZ8/7M8zf+7r8a+Xln/en6fi+PHjy3kuesy4fPOn3dP5k/bnCX+33313/syvdqfnp7vfHU9P++927/765k+H95fWl+k5nFfszWenj+eGH/Yfz+M/Q//3x/fnWTvjVMC38yw8789f97x/uvvVeeL/a//mm+OpG8Fl4h+eP9x9fUa4x+fD93GMX304PByfjp8+nB/P/R/eXQby4aenYWE+vTxfpvHXp93H3Zvd4/vz4u0vnX95nqLn3emnNx3Ed/u7r05nxDt39ear0/78XV/uns8D3XXz/NuXw8N5jX51OD4cf/jpvIrv/trD2J1n7vGyOr95POPifn+6DPUyn7t9X7VHoTOVPP909+ufHncfz992XvX3u9PdV8fn50vTz344l788dLP/7+ePHj/5T4fvO5S4fGcH7D92Px5+2Ek0Ozx1ePbbh+N3cRo/3z3sHy99nHs6HC/r3rX/cnemr3OP57ncP9yFOfrzaffpUzfu9z/uzhPx/g0w7PMPhx93D+c250G8+ebDpd1nj4ePZ6T63cvTd+fpPBd9czp06PX5hXO8+Xp/OtPtvke9h5fTZb72359pdX/qB/fVw66H/dnThbiOHy8f9ni8EOFjP86vPuxOH8849XKudibqb/9vcJrzgC5INrLB5/3fn9/+t2/2bz7sfty/eX94enc8M6LzZP3l8/3pdHzz/ox0x+fj0+Hb/+e/3R3edY2+PjOZf788/r+/66b4jFbf3u06onv787vzNDy9PRPVv708nhnTv52//PDu38h9/+0Px77/z3o6fTjG4fz97frup7fe/ePb8+gzg/vi+PL4vDs8vjl+/+Z/HV+eP/yzhtcszuNr3HZqgL8/7f56ZsW7f9q42mU3sPXUwH7z8ObXx9Pu/fGfNrKNNqTT/t3+8ONlQOcd7Ns3vz1j9pvvj6dxqBeGhbEqQ700+Tb7qV9ekOS8Y/3vfxrytu68CO6eHxz23wum/mXgjd+ex/r05tzNmXSf9++1wY3ce2hRMsTLvjkM78J9OtlggJMY1zXvKxjgTdPakV4DTA25lx9KRjq0qB5gDycxrl4CKhjW0KB2VD2YxKAGKaxgVKFF7bAGOIlxhQ29YGBjk9qRBUCJoQ27f8HIQovagQ1wEuMKYk3BwMYmtSMLgFJDC7JUydjGNtWDC5BShNlLiSWUObSoJs0eTmJc8kBQMLyrhrWjlOASg+2PiwWDHBrUDq4HEwd1lvn6/f58aOo2+/Oh5sxOLsAvsvWbs1Cu7vnDsKLc8JevDvvnM1J0kvhPb747nY8KH968PD5czkLql33en2kIYncR+M8S9psqOGKirw+bBVN+07R28q8BJglsPFkWEVlsVU9oI6zUhgMFQcmmw2bVGw+ApeTE8exfIirGRtXS4ggqMcBrtUPBMG+a1g72GmBq6QdFU8myhybVSz4ASgwNWpaC0bFV7QABKzFGqnAKBima1Y6SwNIySKdsKRNB+iavIIF0gKa2qS/37w/7H4t2qc+PHz/uT+dXr7bBCK1WCU2IdtWEQWiJJe21lAVDHBrUjq0Hk9rsqIEu2e5Eu+oNj9CSW16n0C7a7foW9RtdByfF9IJFoITljW2qGV6AlJq1QUFcMm2hSfW8DYCSctagnS+SskKbehlrgJQUXTr1e5Hc0reoF1o6OCkVyHPZwbSvX63+eE4fSEc7QYkOa2xTrcUKkKZ2qz/tH3eHp6eLCaVgw/pT1/Pu4fD0se5w9cVpv39/rAMipz2YN0umfWxTPe0BUkob0FsmS9QAQ4vq838PJ0XWwopYQt2yYTWRC3BJiWGwGRcJDaFNvdwwQEqMLpo7C4aHRrXji6AyqvVgOC/Ur4/NXkPJHoClBIhg9i8RIMY21QJEgJQTEDs7cal02Dd6FdGwA5WUcAZ/hSIRJ7Spl3EGSBkc3BUf5djqNTBwZzvQRYePgh3ys5fn47vT7l2l8vGPp47PvdbueOOHUiIy3bStFp+uIaaUE9ceNyUaipu21WqKa4iJUQ+OMAVjDS1qRzjASZowpQtRkTHzqmm9WVMCTAw5+oYVDBaNaocZQaXkukMpLwstquW6wxUPk5todOQq2UbRqnojjbDSR7fgnFh2gBtbvcIxLsBKKcQHJ7gSRXhoUq0AHwCl2Azd1EqYjWhXzXIIbVJDejxvao/2zVR+78U5sOQ7u/rV33eBklyBK1/SolW4blu/ElcQUzy18xYu4ad9g2pe2oFJTWXwLC5a4NCmfpEHSKlT8uADWnI+Dk2qT8YDoCyj75y+ixl93+p1GH0HK6n8CA66RfqPsVG9CiSASuvSB4f4MnV6aPQKGvUBVFL7Kl2MS7SwsmW9NlbAm+L4g3/+PI4vnPtLjouiXfWBkdCS7KvM262v/wp7U9LP7XMGMRRidWz3Gog9QkvrewpF6NDiFXQ9GRH6KmahRKl31bJasyfhpXBwCPMoQcPQpBoTB0AZW2UX11JorezbvIa9soOU8i24iRYq8TK4bVztb3ADclpR9f3x9LGrO5PVysCvEs2AbFitFxDgUkrE28ifkt1BaV29R9zCTLpsh5CxIq/tsVG943YAlWQjfcxfERsZmtSzkR5QYmh9iGHBwIYGtcPqwaSMUgxlKzFMiXbVxilCSwmRV+GGJVLkddNqMfIK4NQe/DJ3C3553R34JbMBy7DAIiOgaFhvCCS4jPLt4flDoeLt0uI1lG5nOCntRIwRLlFRoFW1niLCmtp3h6qTW+63d4+7c83dwzfHx/dnVvL2Ogrz7ibw8S5EGt6N0XJ3CHy72//908PxPJA/n7fLISDP3V9CBdfnMf/9bfeMx+F1g/eLy6Pf9O+7H83wqy/ZipJtLGnvWTL86kucKHHof4P+N/E9XzfovfUCkkdJK0palCxEyQIlS1GyjP1v2f8W42UBv30lIK1QshYlmONWzHHLrxRz3IrBYJDDc1+A98PrdovW3Y8WI/ZitcKvvs3iPrZZYB29WMfhV18i1sVjXbxYl+FXN8wVP2uFz2IBZtKLdfRYRy/WcfjVl4h18YQm1sVjXZzoZ/jVzUWgin6Whl99yVaUYJ6dGNvwq18NMect5jzQy1ACellgahaYMr5vMDNOfP/wq+/Diz48SlpRAkpyYs6GX32bhWiDOWslNmJtnMB/h9kM1DS04ajXooSrJmjGEevFqoVfBC363KBW94OU6QTVhF8cjBjlhhS4iRTY44xYfy9gbSKsDWEFytxEymxI5tvrPgQmhV8k8msad4LGh189LIExHhjjBcaEXz0yguAbFuA9MUzwEcc+BIZ5UqXAMFK/E7xn+NW3ERjmgWFeYFj4xWpoz9cN3nfr4wUWkMMIMgIVOfGN4RcHghHejG947vsWWOOJ8z7iFh5FHQ/sHznbBpytH62Y9/CLDBCcka8bvO+p4p59tAKv74lMfkCaiDtetBS4C7IFOY3w0D0FEh87byOFyHEALZ1AJLfi0F3s1aE3OWSPPkCeokUrWgCNnUBWR2QF4MDcN2TUGzDqBUSeBcUc7gDYGnpISwEJG5sTDNcJhruIsBaAJZmvmMVlbLFEC8liSURiKx5/rVGv4cAw4pvxhk1pHXvsOnSCKOTWA/6zFH0TFjY7J7YBsaW4SDt4HPvD+55UBRmNv9bYH/rexZyELWV9vaX4iP54FBuVBxWNW03fOzYOJzYhx03IRxrBo9ioPCjBC9rxnpAivuNR1PGgAy9oymMLEhITNgYntj8n+o4UgsdxI8T7vm9Bg16w+UgfeBR1POjGCxr0pEGxJbuWfUSKwmN43eB934egTW52ASz6u+ktbLpdnp9Asx3eedCsYGOkMzFTQRTvYG0ELPIYFycOj2I7FZAENXBbcmJ2g+i+xi4y0Bb3BmK342EN6M29knUc4KC+A0sRZxN8xXhk6EcE6hPMGBu7E+sajgbrO+xQPaxITWJ7cxCBWCAgtQISaMAJ/h2OEus77FBrbBjd6AVj5w7lokSER7Efih4kXwauOyE2Ce6/Em2GX/5qgjio/tnH+bx6G9o1qNIEIKEYi7FCx90POSSH/lqOrh3A9X/l4W6J0aDRWKnvc40+MY08Yy174Is4hgXHsBjGsEB/qDAued+fXIR79E70vY99LdnXcuhrGBI/EfVaULPcKcdf/WC26F7gXNwS8Sj27/DssXI+LFx4Na5j18VCdL64x+CBchL91hHwegDc/+ViecEfhl9s34wARsCbCHgzAO7/inUQ274j4A0Ag5S8YC/es0sgcSCD/i/Ot0KAkMdVbkKoFZ791aR2j+GVPAZz2xJMzEP8FrI/Tn5OiCnhFNvBEsxNbP0OfBYMg4KGgCSYGDdsJ0QbsQELjuF79POkVB8p1A9Ei1cN6wY5ZEXAqxHwAISk6QfSHP56kCbrhW/pAK8FYLFpQE4gVxIzDAGAov9AJzzFo3iNcYHS+Cy+cZhHkPEonfTD3rBhhO7DMPq/nv2CED347yis9IAh1DuBDy7OreydmnxSjh+GssEYRv0cxtIzgKAg6Lii5JeBhiKVCKUG8GvLcYkD1cBtfE/6HnsmG3myZicGgSMDGI+TGyYYcmTgFCQ5cdQFYI5azA31FoFf9oyl5R4m93OPErnrgm6dEJwdGD4ZW/cj/m3JilEvTE7Xpdx4cbIQ68GJXooW2EWdkMgdJw9T7Ya9b/iLklGI9FyqJboZOg1i2TIOpysYB9C3WaHW0Bl3N8yilEUHJoXyhg0dqNEJahx/9f2DPS0xFLIqIXeMv/rm/MgBm4QmJZ7ccIYDR+UCsCEZsouY7Po+nGRc9xiE/DqghBcDX6ANOQcFVDfs7cNflIyT6OP09p0IAg86gW4WhWTjeuT37NnHHd8POz5eNazrQaleUCr13dJAwp4izUl1yID1fhgdSNODND1I0wtuQPUBzldOiFJCJxG3ttA3hAoc10CAFMWEWDb8GN/fzA1FASFOtLHhcA4Z/qJk1JP4+Nk9KEH2nrxGiGSOS+DiWN2wqQ1/UTJOlY+T2FO0mPUgO11w2QuO5MFdRqmkLwGBC7YtmE/8ejfMy/AXJeK7HObFCa4ddBndUAQL9OAhXpCvMFByXHF7doP4N/xFyahJ8XEs/bgkm5aGT3ASyeiCpBBoKpKZtDdFAhBKIXz9KAT0gMEjxNYEZkj5O0qKcnohI3IOwEddv2U47kWUFSGMubC7cEvwYtgeJa0oIQoIuTjsSV2bhWgDFZHQc0WWy416eKZlYjRZjHLZgFWL2Fk3igB+gX6H8YG/b0ago/6DRhEMiMYOYQXpO1hiFJhMKQQ4AWsRYS0ErBVgrdhiGVuwD0FLTn74GrDACoR0vmQfkQEPuyLl4v7VFjAhfKLiNg5UHMVGoaIfHMR2h31a7uDhFy0rwuTSw+KgtmwRl3jU5HQtgmRw+UEpwQuyDb9oOofl3MehD8Q17OjQBzWsMJRTjeSELOHY4TCuzfUQBYnSjiBNc2ghSNdDmBeHEAjGsBaCK4mtbRDwh78O0oIT+zH1BwDGrQVc34E3e8E9PLeWpSihGBk/YhA1VpHIA0DaPViA94DVRGCgzXEICwyhp0gx2+EXjSKwlvB1g/d9HyvRB7mBj5/l+YWo4zlaQS48xAveDdbtxOQ7MVuRDD04jBcE5sFcQ+90RPCxPzx2r3sNBCELruZJ4OhmUAc0a3QMlgttAj9TYBI9oqSdML5vWOBi72JU5EeS691jdGgymnoiNQfrf2/4Cs+xXJofI00LnRNMeP3TQIFcde6hTgwWRC28NsgV4wdRLRH3a+FCwV0WLE2esJ3Y9uIUh+F0A/VioOwOLFS0kFs22KMTMrM4mEdmMEig/R+xYztgqgPy8TOoWoDASqpykYyD1arlsFsMO/xaoB7YoxAJiJcYnhgp6FN8jaDo8Vff9xJ9L0UJR4+PovjjwB1Y4ICL4cTdwRH8i2dxIebLcZDMhVAx/urrbdCPGGTc8PE4ylh433MpQehe9sFv2bIk7OyXH7AGcEsbxPT+D7cHQawevIhCE7UL3GfIiCCicCMTspAQTdiZAyDU8aA9L6jVg1lJm2x837CgRQ/gIHwOBXjf9yyongd6IZriBO2EeOVEH3EgnmPCFh966PoWbAKCRbCCYo0Bjl1STUCbaAcgthGjDCqEC0Z5QRGULZyYmHCi79qsRBsyY4cuOWJMgIC0FpBAj4LjkuNIzgr+5gX34cbuFhiJ4KixQEAS9Met2gmZLggDXfuhoIcb3zcscKBxSf3BqyngdMRzaX4E/rOACBEVrMLyGPFaHHbFdEA3C5oV/h9xwqA/aAiSW44THwnJXZx7ydKFQCu2OS9gQcd3furJZXjX/RhmyrOlR8sGdAPZAFgDTQOJJ+5LwlIlumjRObDdCWwff/VtFmiziBMiBFvsEXKvHX/1sJaAxdN73KOwW2Gz2gooK0DBQjhBHWF/W97FnXaJnWSAtQYsUHnDJuQ9Yqccf/WwNoCFnVnup1622aINd2rsg3wOBXzfQwq7cSecYWf2AtW5tTmxCTvwAC9QWmxWDoRGUsT2yQO1tMWBMFlAviukRA9RV8jZOB86sUGLHWQhYA242/3rqKZrwcBGmsLLJr5tHDRrALVB6QDWRX3S8H6LrlnA92FNHRQ0fG5ENQe9QyhxhMYiUbJCwSq+5+sG79d8vwYcFvB5gToLTLMbJzc+jTvR+BYgGsJwkC8dxEI+N7eVuOYtCvA+vHZ3cdNz45rHekSD4EZ/adNiQRpW8gKwQwsnSghLtmlRIoe5QMlClCxRshQlK5SsRMkaJWtRskHJRpRsUbJlycCBuh989uLbPL66EUVX9TAHfI4xMigJbTA7fB5VaSwJbTBvfB7VXCwJbTCjfB7FT5aENphrPo/qJpaENlgFPo8CJUtCG6wPn0f9jSjxkRZ7hiH4CjkJIDlOhvgxuu0qJZgnPo+KB5aENpgnPo/iCktCG8wTn0exhCWhDeaJz+PhmSVhnonh95zne87zvWiDWeTzeBK9KXGCYzixCiy6qgca4/N4WGNJaAMa4/N4XGJJaAMa4/N4sGHJ0AZLwtXheuC9mHKuDAu4emK+HddFFLFEoBwxkwV4L9CNWMkCUQlTw1nivIg5AhGRI5GeGL88ct77yHkDt0ZzLh03GEIKXAaB7KKgYUlos0WbLdts2SasEkiAFICqraAgAIwFgqo4mBZTIQPgGKo2bsSMhXeMkneMhXeMkneMhXeMknc3sfCtWKawETPq3TG23THq3TG23THq3TG23THq3TEi3SFWXRQ0LAltMDt8jqzptoRTJX6Mm7xSghnlswx9lXGwHnPN57itM8bdMZLdIcZdFDQsCW2wPnyO2zrj4h2j3x3i4kVBc1PixDgdv0cUCeaK5nJXJYMjJH6Y3K9F7+L7Hb6Zz3GLZly8YyS7Q4y7KGhYEtoAp/kct2jGuDtGpTvEq4uChiWhDXCfz3ErQEmIC4IjO9mqk/Mm5ppFsoSoL36MW7RSAqrgc9yIWUIFhaOCQvxoWM9REeCoCBA/GtZzPHY7HrvFj4b1HBW3jopb8aNhve55zSZrtGAB3m9Yf4P6LMD7LetvUZ8FeL9k/SXqs4DvV3i/iu/5usH7URDo3Dvie74e69Bo5WC0CiVrlKxFyQYlG1GyRcmWJYECYO7pRiMWlWvKgpaQPEbM58hbqcx3VME7KOdFQcOS0AZf6cVXenylF1/Z4ivD8zj38eME9hP5WeAFYAfATpR4lMg2LUrEFAaRA/bTULJEyZIlDtPB58hqqb911KI66FdFQcOSMLmYQj5HkYNaUUe9pIPGUhQ0LAltMG98jsIIdZmOGkUHXaMoaFgS2mCu+RxFDmobHe1VDpYsUdCwJMw1xsPnyBxREtpgPHyO4gNKAuMFRxawME5HFib2APbB4Tv5LSBrPkfxASWhDciaz1F8oK2iLwJKEjuJj8EqAFIDpfF1I8w5IEDQH183pEuSJaiSrxtSK4kVtMrXDd733y5oxpG2RNFoGcD+gO2BrxtuG9w1sGnwdcPNhHsJtxLuJNhI+rFJnBP4xKLROnEX9x5uPV0dQduOPEAUOa6pjwuDx5GYScukWNCrIOQbCid+AosF2nL+fFwUPI57Id4P9eOi4DEG9cX3Q/24PngcD/F4P9SP64bHGFoW3/ffwv0Cu4rYRgRexLXE43iex/uhfrQU4HF0lsL7hhwG/EUwHvIdchfwFsF0rt47forYRYEbrCT2U+CJYJdLAo2TjsfoHx3fD+sVJxGP0c4Y3w/14yTicdxor95zYxXcWqAkKY+1iM80pgl6jIwVj+OGjPcNKRt0LQj+ht5dBIrHcVO9eQ/ad5E/8HUjf8SFl3sgtmPuzNyYwX8ccIDPI33RScDBfSAS2zWpyZa0drWiBMa1UZakvd7BXn+BS+wDhuK1sHuGAwrs9aEEpsTxgEJbuoMtPZTAWoEtxgH1uf2JrVAaUcNOAov5IEJjhaTUTVgwZdKWSWMmRX40jVQB+gA9iTnyWB0+R+kTJaEN1o3PUfpESWiDVeJzPJShJLTB+vE5HspQgk1Q7JN9A6w3dyk0EPCJEuJHQ2uWPNoFJoWVFgeF8BzLSWwCda5+wWgmtqJI3lw4xznkFgWugvqienP1C5PC5ygyoyS0wVTzOR4DURLaYFL5HI+BKGmutkOBgJw4blfgeBItQaSi8Xhk7Ero2zCeElES2tCU79lG2OyllR+Mk8/xyIiSa1LnoYHTxh64WwnGTMcD0WJE0q5EACYAJ6ERpwQ+kneIc2MDBiatwVhTHhsbIcGzDy5qSMQUvxf6IqqRVmKuGKAT24rXooVjJKpjJKr40bCeY2CoY2Co+NGwnmPQpmPQpoMDpoPTJZ8bVBKNG8J1CI9wCI/gc4NKUD9BLTXUi1UazNQoaCBmIoLhW1Z3iFl0iFLkc4NKDkFzYbLu+fEsYsl4OGS0mfjRsJ6Di7aDWzafG1RycKbuAa3ie75u8H7N92vAYcHwPrxax2F4Ds9jeCzw42I5rCc/nygJjBRIjCUHGEAR6LsEdBbwPYlH0BjmE1Pu+K1YooYFYokD3oV3/U9EPnfVwlQxCJrtG6WWAygnSjxKZJsWJa0oWaBkIUqWKFmKEn7MSpSsUbIWJRuUbETJFiVblgSplkkkHGMvHaIyRUHDktAGc8DnuBEyYtMx9NEhKFIUNCwJbTBvfI7SKwMpHRMJOKYYcEwk4JhiwDGu3zHi3zGu3yHiv+ctrOQwtCvuT96EJpKx48Oc+BaiOp+j7MfAM8fQL4egMFHQsCS0wffzOQqCjAR3jNJ2iN8WBQ1LwmwCC/kchUEGTzuGLzsENouC5qbEycUR0ysWgW0EfjvSgShiiRP47UgHooglTuC3Ix2IIpaIaefqsADvxZRzZVjA1RPz7bguooglAuWImSzAe4FuxEoW4L2YJs4SC0Ql0CA5BelJWGxpuJQckWvHRSXjJ6TAPRg/7Bjl6xj/26PrAIroHIqB7rH1eMxkAG4jWzLc1TEQ1jG+1DHy1DGO1DHCdCiBoXPc0voSmIVaMbFhS+tKhHE7bGldiTDnt5jCVkxhiykctzQGJzqELYqChiWhDWaHz5GZMCbRMdLPIQZQFDQsCW0wo3yOGyTj+hxj6xyi7kRBw5LQBqvA57hBoiS0wfrwOap3UBLaYOW8WDmawvncCEujqCVGc7XhgSuRDZELsQ+CuoKLL+Nz3DpREtrgK/kct06UhDbAXD7HrRMloQ1wms9x60SJp3eYp0OY+NGwnqd/l6dPl4c7t4c7N58bVBKNG8L18E/1cFzlc8NKYN+ReXv6jnm6lZHbX9VvRIMQlk6PMk9nM/GjYT1PjzJPZzPxo2E9T48yT2czDw9cD9dcPjeoJBo3hOvpgebpnCZ+NKKe25KTbslJt+SkW3LSPgvTfSxZoJ8xpwkd2sSPhvU8/IY9fIv53KASNlLsr9yCYw1PjzhPXznxo2E9D4+40KZlGxaxRCDRmjMV+OA28kFRi82HFlgPL9bDYz1CRs4wq5hQzwn1mFAWeAJusZytRI4eLtGPGL6JC+DjAoRHTgpIgfjmRgBo38jBedSXJS1KsBqC1EAfDQsEPgeppYO0ECVLlCxFyQolK1GCNW/F2jqsIClXTBUnmwUYSeT7gBSwBIvJ5yjloCS0cWjj2MaxjRNtsC4e9INpGcWVvoEgLPDghsxZzKTHunixLh6z4cW6eA4Az060dwvOJotY4gRk7mMj3d3FHRHPDSqJxg3h9l/P7Zg7X6SN+BTAx7dsRngOFwGE8a84HhaxxEmMXbMNi1jiBJ9yG7Zh0fiDhB3pmq8bvB8U4IHimGPNkRFEPsDXDd4HSGtAWhMSJ0+QiCMpiaJQEnkHQTV4H3rfoHcxI8sIaQlIS0BaCkhbQNoS0ipCWgESZm18ZtY1h7RrA6R1hLQGJMwa+Z0TPMIJCmDR+IMTEueDrxt3M0/bWH+L+piBVmwC2By4n5MhAVfGyYhz4ZD7PXyb57exiCVOsEDXsg2LHPv3EY3wGI915IZMgOaQAM0h4bpjenVH9hm5J183fC/aEiiTnDkmOXMcEkaE1w3eB0igCs/V9hHt8NiwNy/HBKoYlShMyuXj+npK7xQJPUcwyjzoEojKobcQh4X0GVkc5TjBOMk3WSBmAwjvgfBXHwpjYStIDcwqPkb9UHwfIHlAkuy4RQnRtwXV41MbkirG1AqWQY4muSY3aTAAYSMNbHNDVnmHve8ubnZ43eB9sLZiTfkcN7TrEkcG7CKm4jHuoHfYaJlfyyFBeD8hJEMyf7floCgCiu+OaIrHhhux+KBRfES2LFHQsGToI64GHhvOhxPY6YGdfI7iJkoGtAfJCvz0wE8PMULQqvgOIjGFWCErUbwIQ8RoxWA5VqbGckiNJaGyO37E9TeACYlhjzvEhlsBu0bPeN3gfYAEivECc0SHLgJzGKHDCB1WwmEG4kaHkqEPQEULJwjfYQtka9kHmzjMDkVtIhSgSu0YgQp6EyotDAnTfzVwqU8jekHM5EGELI6r6uIejcc4Przf3HKyFT+JRSy54kZrtmHR8AM2gUvvYCfgMty3wCgDL+DtYo73jtH6MAyIzG47jmCsJEwU6IPWCmGs4L1jDjeSsUHDFrRuCOMGbyNzuKeMDZrFzdfBj2kpIMHJo10D0hKQIg5wzxEbwj2artBUrD8kAAASvHoMawUkACKc8AUbfMGGrYE6a9FiixZi5TaxxYYtgljOGzNp/RHGH2aZcjfftIgzxYOPEztcnCiHvcQJZiF8siACiRMAdwMWCK4Yhyp7IIILLgzGxhZXLFz6DEUc4k4E2Qivgd0eeDjeAH837kLC/kTzE41MwsQUL8IKPYB+2JsXR9+ISzz8NGRVoB4PEhiPHbwDEw0cL8q8aT3eIo1KjjdgOtyNyQYNWjjeeuniuB0/IQ7oLh66eENmQ2Py4rpXuuFRpTw8BtwjcvJE6wEK3Xk2EF6CkfC8ZPAg1TbSmjxlkGUAgQXNj1dLEyoTHKKJMHqzO5q8hcWbF206XMG5uO76qgX81LDPOGKMEwhHLz5spg2b8IgCOYAiQRRf6M3piCeOOIyuRKXxhIALpIQJk7ZNca8UWzTCtNktCvZWIf1jn2VjAbXh4UaQfWzNcUc8Zne0kC44DF4y6XD9pDCp0tYqbqVkC3cnj1tL1iei+IhyI6CFhNMAkGSO8Hn0JAIMmzAbdCYGMZ4zcAckGzRoIRo0bNHQlwGeDI6XM3arJcRQyXVBNmzRsAlb+BajxTjkmGIlLwQ9DxoRGxWEO/ZAV3E+hwK879UZceWEImSsQW9WMTKHkkYUOQqeDqyF40QdQnJCOHWCQ7DIcXN2cWLw2LAOITmBo+H4gRS9Djl3+dygkmjcEO6glgY6iLMVTnjiG8AfyGggRtAr/oozrzgmFo0/RpDU/sUVH1AidgwGJxzgw0bD6wjZAIAj3NCWXtJYdMHdyLhYINztw9mL9xA63iroeN/gIsJajJDwslncwIe/+3jw6Evg8c4TjzxJOLDoRhTJKIBw4uigyXmGB644WeB8xKMSTwayj3Di6NzjMS4nGKwTaC380yNWOPJwIeFTUUIyp989NbukCJK/kPQd2bMoEqwtSt2QvyGTiPXzwBw+RxsFL6JzvD3O8V65oQR4wpOAkFMogrBABFJ44JUQ4SFo4bVsCyyCJC3rAJ+kxn08agn0A9JQYg2aMiy90ErGTxVSESUeFsg+4UIOQZdcUqiWRibDA3KsAGYmgpmIDhRdZfwTFla0GKVg3KQmChqWhDZYID7LSadcKLYo6WdP13wySzZhzIojZxMSZtxnsOOAZ0pUZ/yJCDkhtxE/RvmvK2GAwCjcoSS0wQbD5yjRsWR9J6WtRhI7NhwKbkKkW7EPBvUMPxhuhBAjz7OPx9kHddBUVG9Y3/Nk43mC8TxeeB48PE8FntK/h/e3h1s4nxtUQhgUIp8YBBVreMrrnoK8p8TuKZl7yrqeUrCntOsp1Xq43Xu42vO5QSWGZsUIrPjkKQ17ISejqSxgGw8pNbQXbVjEEidxRWACi1gy6t4p/3kE4niE2PC5QSXRuCFcj2gCD8dTPjeo5KMECHRtiJSbcbo5qT4uDV6Hxx4U05h4keBE9tIXeTTyoqRFCaZf0McWo2fBVkBaANJClCxRshQl/JiVKFmjhCQtSMiBhBpRNP7ooW0ATc7MFiXie4KLaxddj36cmGYnkIZFoQT+qx5eq3xuRCVmM/HIZuIhkHkIanxuRKUeEtbFi3XxWBcv1sVjXTx6EZx2LVpgvTzWq2ET2QJr4sWaeKxJeB65b5w8z0n1mFQWSGTHkgbdYCR8+RQ4AzkG5SgPuYcFeN/148RiOExsI4pY4sREuTXbsIglTkyhw+Q6gdYOxCzYJfaphgVEEkFUHrPpBScK+xdT93gm9ekAi02BewILQAZOQHKes8IiljhBVK5lGxaxxAkicQu2YRFLnCAf7hdhYuDIyecGlUTjhnADDSOxyLDrY6rGZ85reMksJKjtkfbHMx2QZ6ISj0QlshabM9+QR76hUNKiBNMtsBOU37BgKyBxNhaiBOEr407DnEKeOYU8cwp55BTyTATkmQlI/GhkPeYh8sxD5JmHyCMP0VASdhfkFfJIBxRGIJCEReMPZibxTEzimX/EI/2IR/ogj7RCfG5EJaYS8swk5JkwyDNfkGdaII+sQB4pfjzT93gmBfLICSRrsTnT/Hhm+fHM8uOR5ccjtUiIcgITlNs8aE5s8hFSI0A5sE3BT8hOWIAZdWKu3Yp9sIglTsyDW7MNi1jixAy5DduwiCVOYK4DvQoOiK9vWEDsEHTjQQNe4jPmWGK6E7MvotLgMR/Ia3lFXWJn4MbAAlCME7TkPPtmEUvGPYa5dsSPhvU8E+p45toRPxpRbwnEXxLv6S3q4S3KBg1bLNkgprMaz5lSQI1wKVYN7wmq74PcPNYZX9MhdQmY/nqDEV8X9iT6hC4BSTaJsFinQXdD4xh6MZ6p+u740fhQdn3VArFtwaloSVCXMQmSAm9qWBDXbtxW+x4QT9kuMCbEVvE5DGmJEQ2QEOkyPLNBs7z5htjduA33kFaAhDjNFijL5wbdjdt2D2kNSGtAWgISY1YFU3HEAlHkxHrHIY6iQd/7Br2TSDCU4NQ0tAC5tVu2iIjXChQOLMlF9jS0wIoTko9EMrJQuqZ6uKayQcMWSzRYkuXSBdXDBZUNGrZYogGf+0oEBB4nNjgx5T5iJwWZhi1W7Bn1BTZ70IUHXXhgMJ8bVPICmz3owoMuPDDYC2YcK3mBzR504UEXHtjMZyEziQ0+4p+X0wd6ofgkBCvQkcdcejGv6EFguAdNYNcZHZ7Yoj/nxHnFY8Pty2GtnJgxilFSGo7vGyELR0iNAMXI9objwHwLCQ4br9iR8TlcKhEnKNbErTgmFjnOOALaGdvOOoTkxKq4NftgkRNrEVeVLZzgSA6rytayDzZx5I1o7oArTuz0DtuckMBBX4QqhFM2EEu85QDJM13kpax0xT/v0TdaszHYp2N1slUZkc9IefJ6JziuE3jLIoqyLjJsPDZC2hVCMWVMHr8545BQnJAsnOeYWOQoT7jI+/HYsA4hOcGlXcs+WOQiY3dk03jfsICQnODf5C6NKBIidCQN8EegP2P3G0aQxUCxO8jPXYmQ7MJ2Ft7FepRWRfiYEGN5yMCECtoFwQlJWQwxSM1d18SdSLlgAaBCCYUfIEfNyEssi+AApFUWyBBOBGmMImZfgggPCoNNJFacdkDNEv4KUFaiBGkbKIQ6wTIcCLoRRZIJtECXVs4i0EWIeZERgiXiQ0WYiQeT4fMo+7EktAEWjOJfX4KVpQQndjUxWx4r7knSbBI3NW572OrwWkIHFniBBR5Y4OWMYGUpdoldU5I0VpxiVMMmwzOcBug/EN0H4pNn5JxnUJ1nvJtnKJxHlFoo8ShpRckw3wgv84g743ODSrD+w6xPC3+s4Rlx5hmL5hlB5hlb5hGWHEoIbS1K1nGsa34D3jcsWEdITozLYVxOjCuk3UdMWIsYLT43qOQRluURr8XnhpXW8f16fOsZoeUZlIXqzXV9MUeO37wRJRuUbEXJNo51yW9Y4htYgLVzAmfHX4z28Yj2uaomIDDexzPexzOuxyOuxyOeJozAsR8WOaxUy68EZTQsaMeZj0+hQnzrGU3jRTQNGsgCtvGMfPQiKNIzCsUj9MTHiJShCd43LFgLSFiPURxh1IhH7MkolQA5PKfNE0CLxQnPolZs7hHJQUbp4yRj/jBJDdF5eBaTID6pBSJsRtBy0ByQLGlRghUUZCOwM8ggXQtQZ8MmssUSLZaiZIWSlSgBLvDZCciBnhEh4REhwecGlTyCFwJeYFnHPYiBB57O/55xAR6u+aEEMymYHDh+wwLMw7iv0Gm/LxFz5/ktYu48oDkBzQGaE9AcOGD4fLir87lBpXWsvo418NighofTuo9O63zd8D2dzj390fsSQfGOOCLIY/xFb2xPb2xPb2wPb2xPL2tPB2zxo5H16I3t6Y3t6Y3t6Y3t6V3t4V3t6V3t6VAtfjSs5+EV7eEVzecGlTy9oD0dpMWPhvX6Z4HzrmUbFo0/6Ofs4eccSrAC3AvEQuN9w4K1gITZ92L2PWafz61cvXHb5jRS5MT78BqTjEkSuCgRAX53LReVTWQLjxZelLQowUIIbimQLbBuhD3IWmzOcAiPcAgPX+PgTIipd6K9w9YreA8YWcMC9OHF8ngQysis6Qzs4dcbSjB3XiIk5ktwGzCbhgVE4IWAhDkdmTXd/vtZEb07rFwjiljiRD9uwTYsuqrHXinKEquFGIkCYKTYQ4grLMCYnCBrh/lygkzDrxvkFnjT/xA4T+uZh/WMDRpAYgcNIZF4QDuhB/gttfBmDrXYgkQFmgqQ4HXc0tMY3t18btDdKDLR1OZha+tnVlBI+MU9D1uerCTb0zznaZ/jLolNMrSAz3jY1rgTio2waxG2uMuPhRgvVhws2glKd45fItyW6ak4AL7eUsXOxY2LBaQ/wUucZ98sEr7gPmKDF9ggvDaBVx4YwOcGlbzABg+88sCrUGslewj77c1G3JAu14CDBqwvyBgY6QVOeNK3j2CvagHX/AZ9o7WEBC9xgVEeOOhB+R4YzOd4GgyrHjFBSvqxQ2xiwi8dKO+5hUqWBZSXEgd2TfFJQTDoWhCx24jYLbZDIWJgMune2wpiiy6+o6vGkvx4GdklGzRKC3hyg6cilmW03nGXEJsEDGvBR5RL7yIS4VHUcUBHJ+bSxflwxAKKLKBGvm64m4O2HHB3lHaExUw0pxwEAYmvG7z3dFEYUJxr5yMOeGCWF6vi4cPN1hJSrOSBcV5grye+Awv4PLo7rGLzfgooE5BTAc282H09+K8QKGJrL9htRDkG/1yx3gW6xtbNAC0yccHQXZwAh2E7MWyHvhtR5CgqOBAI+0YdQnLiK9yCfbDIcdtw8WPx2LAOITmxtTiI5fIACg4ojp8cE0FRDG3E+EhVHCApDI2FcItvo3u5iPUSLCZSP/gi+IAIjgvcb3EHsXNBLreIXM7TkEYD29ACkRAUWhs2kS3gd9uSd0R+Ac4BxiGhIFJl1HX0JYhIoUAphUAHntKIIhl1FITFDpqcRQRXtOR1DDYhH3KRo8k+GHFEwdEJXucEDoqIAsS0iEgWRriggOKlOK/xuMYC0qrgmuQUjSgCO2mAqJG9EXvF+nlg1FV8A8MrRTwL45YoNorNVgQ0MW7JA0saNom7MPZjbMfcvSV0YI0XWOOBNZ7baNhOsASj8B3fkXIlnkolQvwgISVIBIajO0Wxhk36Z+p0o0oXGmBUaBko0DKEoGWgQMsQgpbxOy1DdlqEEIQ27GctSvpfLeLPWgSmtYz4aRnkQ4tLNLjA9IIKLQMOWoYitAg4CCVb9LwUPQ9fji2oxbbD5waVWoQFDX0MvwIXHP62EV2aFkjB5waV2u6oOrzuz7DxfcMCLOZ4oTEjiNoY7DpM/waTsBKTQPS5wB2+edxwMQlezoETOOEiRoaxRmU71O5xsgG6ZVBFyziKFvFILQKVWoZUtIyiaBk40TJwokUUXovIOz43qNQy4KgVsUgw/UTDD+1B8W3L8IuW4Rctwy9ahl+0DDRqGYPUMtCoZQhShxmBgJdxA+Fzg0otApMCpDbOx4rztMI8sWCF0XoxWh9npI0z0o5v8bLBeJz4suFXy+COlvEcLWKSWgQr8blBpZahHC2jPFqGJ7WMMOooNCzFCjiL5waVgkQ1/O1m3GP2GyxXwwIfJ3nByV9g8lmwiJ+64RTEDWNYhPiBDQlmgyXAcvn4OjxGAKE940FaxoPIbhjH0SKOI5S0KAEWCOLdihYLtFiIkiVKlqJkhRJgrNgMZIs1WhCj2ATU7QR1j78Y1dAyqqFl9ELL6IWWUQotohRaBlq1jMFqEd3bIqKXzw0qtYgvbBF4yOcGlVqEEwzj81grsQlALmhYQEhi1TzW04s18FjPUfqgX38Lr/tQAioXmwneNyzAOnuxNh6r5sXaBHliCa6wBFfAc4NK/SpLzBhWdqTpuGyBShBUzOcGlVrEPLaIc+Rzg0rR+EKbDOw2eN3CHb+FOz6fG1Rq6Wbf0gO/pXN8S7/5li7tLb3dWzqyt3Qzb+GL3sJJnc8NKrV0P2/pft4ifCeUYMG8YFceMy4kZRBWwwKQidi98L5hAdihEz07sFAnSNGxjSAtxzURpOUg9oRPR6wtnxtUasdPi58rNn1MT8OC8Ewn6xae2OOmgO1eSjiYLxZIwPAs5M4kUAuYJTapjYDkAUn20aIEMy+QdCtaLNACKyK2NdkCnpPjRkb/6Zb+0y39p1v4T7f0i26Fy3RLL+mWXtItvaRbekm3DK9oEV7RMmyiZURFC4/mob3HzI5bCn2aW3g+t/Bp5nODSi29lFv6L7f0Um7pv9zCSzmUENpalGA2BfvC+4YFWAkvZtVjvr2YVXFEJUHhMNCwAPPrxBc6CiWkIPDzhgWgE8E8iKkswNw6MYMOM+jEDDrMiBMz4jAjTsyIg2gkWBf4uRDZuLICyz0wduTz9Mjve5cuyvQ5G9Ac3rL9Vs5RAXcbFoBbOEEHDnTgBB04thF4HX7RBVV4oG6BS72f6HasNBop0QJOqg29V4M7L9xPA6MeyTx+sNwhMREsoE8qesQAg2hEL9juuwXGiE8NGrNtZPhs3QCsaE2wdHGFP23owaMHfEMLBLlqASfoFo7PWG+B6Jz+0RCwxcbRQ1qgbzj1EqzYdgRYDEP6a8Mps0V4RajFFvTNhWtugITgh7Ax0TdXuOb2LRBqwM1LblFOIEX04B/NDT2sDWCBpcj9TsJaR1giAqIF+bRiFiPNtAILFyCThegDyC2oLDIUPI7GU7zviVjglydr8hFv8SjqeNCIF/jlPSFF5PakVeIX2T3W2INGvMAvucFjfyCG+IidDK3xAr888N8DI/nMSh604wXeeeC5B0P1grnGSh404gXWeQSUhD7QYoAUK3nQiBc454H/YudcowfOOKayYQMRBRAbM9znarPYoAe05nPYdzoFONaB25HDfDsx3w4btpQRsVOwgC7emEk+hwK87wVSzh0ElYYFHKlYT0esRLQQA4dYx2E9nVhPJ2YvrgMeRR2H9XFifRx3KRcXC4+ijgMndGIzdxDphcSI+WtYIOY7cjI8ji4leN/j2D17Jo8jD3bxvWDNMhCKAUrktE5wRYYkNaJIiHIOUQXEM8YS8BDJeYJY1rAAPMsJ/urARxnIJIKaUMmBjzrBRx25nIv8Eo+ijuOYBB8F/RJHgZd4LUMG4X9+5baOIBkPLJPnvuE9G7ZY2lExRnGNEDA5gkLEUBiqROFQiI2RdEBEoCGSnIQOB/1RVOtLEAFBAVBQoAh5YmQTBb2GTWQLOFi3JM5IkCBNUKaEggihUYjqSxD5RuHMCWKWxMlYRAphjWh01Qbocn7+9u7D7uk3P+5Pf/zb4/79H0+HHw6Pu4fPd58Oz7uHt9/vHp725/rvDj/+x+7j/u1v96ePu8ef7p737z68/fny79Of9k/73endh/37t3/57IfT4d3Lw/PLaf/tP+4+HR8O7w77p7c//+Pu/7zsn56/3D3uftifLr9P+4dzT8dHvPrh+PB+//jZD32DH0773fNX++Onh/3bn4cfp6fj41fHw+PzpcY/7n48vHs+nn4CiP3fPz0cT/v3fz48nKH85fLRjtoRR/Wd46mQRO9o+3M0ijkeCh0NDyR1xwOtownTUSXk/M3IRDdt4dr8++n4f16Oh6d/ocURnkdMtClSOuOZ/lBMzywcgphNU5gh2ZtI1otnkVpZODMtr8ehXXERkjKULd1Xx4efHvdPh92/ztrxZllmKnA4hvBCJYdDBe+MZS4D3vQqbk3CMYIp/Zl/gXe78gokh4NXSNVftjjnaTg8/AutzNVBVeh9ZbCUjGaV2RpkhgYZRSs1xlfHWRFVe3UQFbkdpLZYhn7JcC95CJXRuTErRNmq/v5l97B784eXj59eTv9CayvvRhR3usjr3+XFhPJmF3kZ/fk0J36JeAK3VdptWTbWXIqyoPM0rMrdu8PzT18/7573/ZzsHs6/z9vZafd8uPziqu2eP5wFkPcv/0JL5iWa98a5sPPQm0/m35Pp7KX7p0xwLNPbS3dQmcBYJh2UyWxkQmOZVVA6jMak+a+wuLH8vIzHl9O7y254/vdhd3jEwv/Pl/13+3dvPj9X/pdbepEASSy8SM60IlWJH2v+2HB9BF2u+UMsvxjBlgAEtHXxaeDx+C+0Ma6A0QwWIZ0J9+ub+kvUWaLOEnD4vEL9FeqvUAfBIeL+xxb9mjY3hZL+x/5v+4fTTxRm/vuvdo//tWt+f3z84fivs3TC5iZSQIs7l0VKZ2lSa2+qaQavhuvWbG/7obOuFv4ork9uBK/f3oxNBPzJfjYEsAGAMFCxg4vNnT72IkFrQ6Nds7mtxngEMTvis8UIWmEOEfHePBB5E2uZFAS+vXt/+P77Djd/evvV6fD4bn/3fEaSL3ef3v78cffpq93pjOTP58bdz68P/3XGutPu/eHl6e3i/u5vh/fPH95u1ncf9ocfPjy/Xa7vHi9E8buXH85s7Wl/xn238hu/3i7Xrl2vzvTx8dP+3PuZEH7z9+fT/uP+fEp7env/b8tt9995Wi7d/+Hw9HxG0+92T/s/78+jPTy+/e1p9/T0cJZUzpPw6fh0uHzA2447X6bjPDVq5XOH3Zsv9l2fZ9z/3eHh4e6LMzE8PX97BWpQ1k/3etvhl8eXx+d+g2U1E7S/J6vpo//2zCQGdvT1h/3+082EpKCNzf79dHy8bhU8keqncXBjmvdFvz0zuzd/PO3VVfaGSR+vPjUt41W9ry5C0tPtILUPNXYS70Y0Y3MhOlxPv2mSkkutLKbTJknFH+tXBrdCy9wT0y4c71fH5+fjxz8dzozv7fPpZR/f/WH//XN8f9Xn4Lxo7fF6VhtfOGTi9P7jU8XI/e3I88yw1TGAQzgz62R/ztrfbVdzGEa6s2LmXci/btZY4RwJ8tGwPUlp1m3l74UzcTN+I5a0twNKjb3Nbq4jhv/ueHraX7OE9nY2TTR++PjpdPzxIho8v/3s8SwoPz6/Ob0oLKfNLfl15RBrogzHSBdDgMo0K2yVrpRJ+3z3/PygsSlTJz7bSYIlGb/U3w7COv7GzRiXQsopCNcMyN7Tl7vT04dr1jP9lf952j0eXj5q3KaEKb8Kj5sho6n7mI3HZWlfw/k6ucWE9WWIlZjGhVWmWRTMwMLO7fRRNYsCdrYolGYiPn/28PLx8HiD0M0iLd/ctK0QZsbc5JOzP+QoN67S0j5vJqBtAdA2BfR2Mf7Hy+MPD3tduLSMy1d35Qo+zN32Nk/CS3ZoPWpdtf/D7q834kbhxhOkjXiWPjz8VZss00408OZK+S0n6VsXOCsUmbFEkd2MKx8n9Nf7/Ukhv2uGOoNL2jca/fNMHGAe4uPzf7pB0WVq44FQdezMc7css7zdsnpHWiq4VAZimdqn1K4mtp9BFKvYfZZW6XqpMBO9Zsg1M1lzyE9TfByKDOrT4d0NSo13YNStUcHAdLnFMgOLyo5aa0dtqiN137XU9PMWT918Lf25V+gviRd5WfCm4+RmWy+I2HnsACSO/Ve7x/P/2jolTvn2LXj6UPjN4VE7uNfu/4qOMifI6qxZI0/jqSK90Whcx74Ll2p2TLRbT44r6zlwld6ATQu7si9BsyrYc3XKWt1ikUbCzSq95dp201VqNwWhfDgPVu3YsrmurKe1VZIdXdcMIQHlFrIhgKCGvldK58kPV+sZO1pmv7JALqgZxMI21V+//LDTzgmplqpUYJnUtgCoTwLFwJ+PN7uAL5yzvODvrJ/mbru9JXkTLAOcYfc3MWlFjskeoI0iRU7GUlQkOcVNUmWg4ZmxrqZLyxomjHUz57E8x1WOgqk+tL3O6EKg7KfFR3MLticI09pD8hBuY2vrAmEgPQKrOLC2ynnrAivxOrnzK0AX0/xgvLJuquL6ljbT8IxEvE4elSZsOOO1haVMvglXik3O33DDmH1RjJXXBXBXObglMqX6wRMztbTO1DLVgSpVWGouCuaotQJtC4D6JFCw0R+PnTfp9UZoXy/FMyZn2m1cAZq53EhyduAijJtWHN+MIimUTIhsqp9Co0hP1nWynkJv1Bd/PNxIe4qOKSu4VCuob/XzjWLKygo5VuFJ8Z0o19qnz6tmlxFFH12idLpdNe24XnzSanIKAovpStMMa3JKdvOxqEJ0djZ1tlHdVHVQjxcQu4dvjo/vzwzsNw9vfn087d4flX21RobbKHNTpjTfpIwralcFblDTvrAbq01loxBMCgM29tPNmFi7YPaMGqWNUT7cZPmfcSvc3PLbdGcpxlyziKazzia5rV3XDNkWLGs4JGPIynOKXqbZKH1YBMHNbX/lRul1wQeuMx2qErKx8io1carkm/zkKbvtxBQPp++Ph4fD8+70038+Hp7f/nz82+MZ0cekBV0gxje70+lwPN29ezmdzpvil2GT9HfnDfPj8dJlHzP07vDjGdjuMQ3q6/1FzDOAuhXX9a8xctpFDnWsUm9bMIy0X4Udg+v91RufHLIih5bNcHLarGNzBRTjTOuX6c/a1Qw00dZHO1bYDzNJv/KJg6B6MklroTVkMeq2NSt69mCc3PpyJ8DhfPAK3mMDEyk2FWunh1dxH22SXiRWlqZZ3sq3Q8XOV66HrHUnVnSZ5YJ0kW116jSfPBtci0AmmcoCKHkYyTtaBJGt6hyytc+/un5bq355W4ttQ7DsPGayLTiebMsoPT2vRkVI32G5K4ttr92m1NvqKJK82igobXNG7vwSNdvkbmXDxe0cvac6iNrteky1OzEPKgNyITWvccn0qtM6lcPDjzf6u625603+E0v2w43Sad7KYRriWgH76/3T/vRc4m1h6mqV7oqqvzI1Y2phszrlZXIBzUedhaVv3SK2SPc+rRsdHPKsR4jWNEW3Vua2Zoy9otQ8ld6MQd6wboYjVREvUA4qhQRttBqVc4prR9SZjMY4d9nTqCkQcJh/4ylajbpX9p1cQPDEcTAhMGq+TrnQ3Tp/Nc2xO2vhma8k3X/UDMKvdHy0RpJpfolV39AkPSS1k1il87DiADLjJGa2acxwQyo57SRCIJQYLeX4db13J6hppuSV8CYx7RO9cGiZ40EItcKsOQO6++TKW3HH3WcMq3p/FhOWu8/ZjSOy3brjD50UhAKk8krcF5wE3X0Z19JPyu7e7gkwdKm7IRi3z/vcTmGWed29sjmpbKFKHXuf3DytR0R3r+zVk/KCOXvKvV2QSEXGhKyCNgQYLyirOjm7kNa7AOsKOlUl1vtcl7Mj2bfa0PK83a6KMc/QJj9B8w1DG2UU1xue6ou3zszL/OGsleGkRNKVNoLUmf6Lh+Px/ZtP3fhqDGmr9HxN9ClN4eZT41L7Ss2zYKmMzIin5Sa7hXVUizKiLPU/bPN0kdcxtmVjK9O0Nn4eI82Kp34Oiyvy5SzCIE1nML0WF/nKaqqdsTw2EWPOymuKgipVxjDpr6M41Sz8WW/iAv2E6eykuT1nTcF1inUtICy1VeQiwGy9aYHxqd6UEPhsfEyZXkLVTFsUElpYRVazbtE1ZL0C6wSkJumaOI95po2TBdbNeb6Xil+W/UTepI/5Rr5c49yaaJxTqjsl7Wjiy7RspvrZXcmmWPgdpcs/ZZkrT8SWGJTBin2hFnWarfTstIRGZUiU0VwUfe4VkF561nqrykMydGZKj5EO2Sj5LlNobTYIZgoPtTBJl3cpMyptkvYKvbtaD0qniT1ZFjFh2lPjVF0vgr9KGurxnrF6/J85oJKlrB7ovTbQAj/QwvPkeNdbzaC3lWOe8mRJj08e7XXdTUVAjpL7a5Mbj66qmR69ekheKz3lNTIFoeEpwEXpH/Ul17Qjk71NKTyuACQVHmUZV8qcHKosK205nWnZ0g1+DnXEXMht1WjEMl8Je2eqxV/jusX2ocrlLRuBrs54lasvGk0TVKZfUMJJM/4zEJEe3+0fn1ScnO3ncxunWRIAkpgiJQKkzLCjha6rEWcFoevzMv2UcGtjWIGWB/H1BqIkTyy2cGWTSlQqPpTEFmnly2J6Uys1izZK/GYZcmre2SXbbbV/eJEXQloGruGnZt1GY1aYmESdShHBJS9psU6cdp1F4eopeeVT36qsczJ4LJsSOS8HDz0ZvVKckvkx9wFGNY4rSEc1QFa1LfmDs1NyR6hamqELS1WnxJRdjyWRT0OLW8tOUK3DvuZ9WaE1qHTfyNp16jYaN0MsSlB70oRl1QhlTZuJTlU7/E3d/tg015CQuLGjO0jpMKMsqrjkh6EbhzOpkTKlbhi2IsN+PK20K3PLM42v1/5YAW9nLKemzSlT3adOOhvzV26UTlOKlLUG1SD/Wt3r1uUTkAiIMa7aqmSFlyWQlwXTuiicVpuL2KJgBCovysVWz2EUZR4qFtzVWE2FasA8A1mOYwsWsXygHTdLdUU5/ch8U7KZztVtskiYL/Q4SmsdbR7tzYyALE0vciUvJfUiVbJZOh3h9A0cr5FCsUZTM6HDVVJGz9OQzA7i+XJ3+u5hbx6wkrezeMBaHqhSIalRkk6VCydmNx0lkn1KsrXyjkxcxXT0UureXSWw45piNG/jjPOGKuvOY609ymlitv3C3ULlSUq2r07nYRO8c/fsJc5Rxn0yfV3niX6geieWhXYFV/CmduHsLRtaf8VJJ7MpOl3+ak+rvi6XZXOep9wwMuu9bkpan9xRXK16O9A/7p4OT+rH6mokG4BhDCZfHcVH1aI+G7qo3eFdWY6wJB8oMFWpauy0RJbgEJZEBTW+IprbvjXNhXrD/UQQgfVYaNajaEb4Mg276gmQ5tz9uXdhI5v+68xSQnf6LQI9oVoLX1eb4Lef5hkhm/mcxoM8UHknsVfGNtObLGH/U5V3tT3eaz1mdHqvkyFtm+61SONXc5PXpmQMOkJuZqxA/iC5fhVCWefGpWv9ZgVRr0r6WWb70XSAr4NrKqtM9avxvhKZUHHsa1TmVxP2kGaDuj7QUlVjXwmRL/M5eSOkbdi2ESeJf3IIZlVlo+kqrcfl22Qfs5zoJgQdzalOXV5VIMro6yoUjGp+qaS6riajkZZCWe0onTHZ1I92Q4o+d8o1KIU7cvb+OW23qAuCq8tdnoqwVzKnF46rMGVi0nu84L4w3d/IHI2jZCJJx4tM3WSsn2qU8KSET5Fdt5Z0yyk4S9Z5BjWazup6QhI2+xL5ryBTiWkdcxeNJ85rdSeM3EWtk65O2n2wpe7X2oDqUr66kpvwXO6SGB1ytSZOySyt7jAun8266OxtzuxTkn/NKQHTCflOC8O+1pLp4YuKX7Ix1dbQ6/RlUlpwau4GAL0fS2Cc08STKQovyUeaDybW0mwkeLiauqMw8MaVRLnoqgQ1oKYkI6vT/C6y39zO76xx/YHUFLvaHUd1v8uCXSXdX8n8VAAIirg5HqSt0veUN99EP3pkR69Je53MjoNCrWbOXdlosjnFruEYD5Maz7svWY5tunNNq2YFu9HAFiurNtkJztoW14UDSHs1mNjAoCqbwGrV53lVjtOTFxmo/CurUKs8UKkMLKtJM82qypPKBEmNOVkljwyr0nRkpk9S2U5hwITSWQmELGVkz1VFiJJLpGSW1QtU+ZlMSWa9ntnNOm+UM1JNPkB34oSrinbmHHDFUWJpoTPvzZPLZ2+bpUxi+9w+qF3NllbNzciPpannSm5stt4Cbdb5KRcD2nbL7P0fmsRguPtQzWdb6rOjJNDNaM5sIVhKIh11/FoEWEZTZnbBssYp3hiQtCzhGdcr+7nB7vCmKLb0D50tz6hZb3QsimxHScTRn8tMq7csmIKustkVY2lVtrrc5cI6WBO+Ja8b02G+ilXVKTnzJ76lTvh0uRR8dn2jlvTPvBm7XLj7pAY2G4mv9WTdZpzmtZ7WY9Q7oGWvLlVJdPqqJDXPjlPlCksyY6flzp2YQVPwodPSzkwBtiXbcVrg0wwZJfRaoRxzmv9F4qij+nUk6vYHaN1ddFzPW7/art1Us0Ss8TLdpfrRNrfXReZDCnR5BT62VZ21hvlL5FkZVHnmiPCacQZ9nTFNYFpfZ0zrOmjlSrrL22h7tVzJDEzYfLfaAFPsZqt0Xnpa3ZhXe5PrTdfUTWCgpndel32TyeFT5UKz4rVqZ1tlTlkVXmWHKt+ynPA1dmU4nzcZ3qXp8Ew3WaocKe3VVi81lqySxn/szn7d/XM3ejz7Fwx3kST3UuMUq/pLRWpL7LkFRoS877WqubOcdfJR2WbdRDpeW9XTTYRH3cRJTOrnSi5vqI5hVoVgs+JiuN5R1etNaBSTFhNjhLF2Pedc3V5dapd1Ssmoafys57uN/SyoXbGb1fFd1U3r+IwcLXdjkUWfqKWTNqOgFpCn5LhOKwLt6Z2qrBVqlOIcp7kqEKpLWMbbos4MoirgknK5otdL7rf123sVbvdn09qNZjgZl8vHXcOJfSfpc7VSMCA9zxntpfV4tzIrNZWbMdNalsKLOTMLafL1m3HFh3Ldyq2oN4zB7P9XmFJTJUslLUSp/aYwcYWebLfccz6p/dLc9bNYXa8R1cyQ2S7tfoWqHDRreq2XnCWirHOXs025dGmZwbMqwhovQi0zlekCPKcmwNJVXVrom1WjpkbcGbVEiTwcTnMwys7whLeMPkG9GsfiRtxV1WvOzzWysne/Snaf0BCboC4VqFkH1ZIJUDXEts7aks7SaRiMvXmttyIlrVc6K87LMyiLJ26U1VI29kpi43Tl7nxMKJRNuHT/GnOwNfe3nf3JFXqJTQYvo71UiyXYKMO1yli/hIbFzvk0xvd/c+Qq00zJGxrbNMQ//xLjVtlyVjdePm6qDsw0l+HsmtL8l0vppnJ9s675i5eTpjVNj/eXWGR1Kyk+PmvbiWrUqBlqbrexKn6Ucd4eMWfNSMbilZwb68G40FyWy5BpPNuqPtnl5zLNYTtjLrDqG0rT0OgR8mWZzn45s4FFHZO5lcm8/prjTHEUfqF5QrUUVOQ2WKeNEkYV2LrQVqEG7CcVFlFVqETLbIpUHQbvhG1O0ZLedM0Rc9tindB0boJeQq/UeN3fKs2S2p70nZUzQtmmPRdV50P13ojM4W7CFVe/PFVLfVidxK0sPVPWjVqNNS+PcJ2da1z1F0o7D1fFcZR4MKumh6Rl5jWsHUWqgyksKRb6VUVVtQZ4nbTfaP1VJGJQxPahd6POVFf/rO3mRJ021gp1JVFOuYu82JZUcvm5U+7f0pinkpHNzboWbHIbymW31odg8sAsywiU2mq0JETl6DTPnDNhIRsGNyOJq1OcM+aamDRXkSzu2e09qoiZhz1hk9HcItaaMJ3vpcIkE/rTQUzIFdrNJnM6n2ERcloixfk5PcJISgCqI7LZedTo+Iyx5hXdlp3J31cNA+tVxhN3MKiyVKcyNqVpG4ZnCplZK1CzhrUJ1pSzkOpfbWbby0z/s6XTa3hTGXAsC9CbtqaT/SQiqdoMitioqC2fbbtZylcPzydx7he01QzmNNP6OWWAE0EWJmK7L/jwfLS7biizDGI7e/KlbbDebmYZrcb0Zlib5pnDLAPU+OftCXeeUWseq0u4F2Q4cLUVyzJRGrOd0ndU6n7NXCp9L1MB7v2SxkJ1S7DuKNpuoJi9LJYsC/fUuHs2N0rmw6qVrBon101SFcJJMYvSTVDz1EaqlDnLMKsaqSpiFZt8eNI00s7IfZW/JUbLo5SJd5nIwJ3yO9aSrGfMTmVe7hb1aGmg9YScrLoszrFMWZzxi07ujaYfSEekFLiZJoNHTSE7W5sVK3GdyPa1FDm9aGo7Mt4XabQMsSm9vD3Xe0O9yMS9gvZPvQA8YysyhRNql0+Vnm6VS7FSiRS03L+zbG5KxuEZcNRcLr+ES5iqEbDq5LPBICUBHla7k2Yy0Rwgiw+yZRYdY2SG9bRbfUnY5nb0CfLbKBM4rz/7sqfsX5sc9mhd1oYSbcppSv10W8zfpsTYlLwwVAdrvZRPuVUhB3aeOldLRZ1LOaf3bXKALohrHcCadEiKm4vtjj/NtSbdxVRWooxye6Klnlt9Y7D0qMnjNprAaDKYbZJmn0Qnlro91Cp7ziZtz1E7q7C3hM4s6Y2clsk4O181eam19CtlFns11ctMQVpz158zGjOb6fW5pjz+nUJ3+rCRMDZstI4y61+fYzSYp3QmZsOO9WsNZZWe5zIMWRWOKGXesh/89EjIZek4rHdXFIzM6COySA41YRLTPyu7t7dKH8WmpvKDibeTr1dGWHi5RbBtmajYJWckYdkyQb3PfIVuq7KA1VibSdixczWNqZWfD3IcLeuCkWFkZj9ilYeVsNMS3pXxfrdNuMagXjFoSOVVw8c8XoDuHr45Pr4/t/5iQM83x+/f/K/jy/MHzfxTjBnX5+x6q4/RD6uE093YlufFNU0LHVoUqcbw8jtUUQRT4Tal2YtqQNj4fp2skPFksAob5WZ13TxUIxNrYW22WA81615qu9ES7xWrjdW7QUq3ae3OEKNRKX+7cJWwouXCLQ9cqkv3pOW0KNuBVA/Mct9gzRW0OH4pab4qsTMVXYqRU5Fs86aviQPiVtEF1VijbPL+fcYEptqZbEYud6uSM4fcKFdf92K+PalEIhuCak2yaULblM7UuJHkr3W0yjjqgdF05UVFxv56y5HpGlQtpVc2emie3V07u2pRLyVRHSXmitLLW02TrJh6koOoUp28jrV8W2RXm2a8QYv3aoOzJTPcKmhTGBG/fQUD1vYVDFjbWyqdN446IE65atuaDKvwpu/M6tt2BO0aJKNtTLuHUUmiqmae0MdRFWOVC4/Wu5sITfj68PDj7S3PirdNQh2mefXo2jBNaMoBLbpXV+3MEpoZOiuOp+q7KOA+iUgos9PmNm1DmzBybtO2s2nftyR+GK//2GqHtDnGBO2a0iKGkzqpqh1VWdnyNzhYYyG169e1jF4zPDfUFGLzOLDdq1kNxzDKbr47J3ljEo2E7+4FxjWIGZGy28xQIiZqKei2ZQPI+91YfC57Rx/jrGXD3Ke+Nx3HaRpoyEts+qiVHeqyBG2MaTeXSvcm85luQ0wihHYundVvJkip/JDYZsdcEIs371Osam9fvPCaHkMfo25pNNXtql7XzEfRJeYpK2o6jdXNwlGV2SW2XbMso/FBfWpVVpe0WU6NU/WyalT+loxrs41b5WZFor7G5OqM9Kp50vQ5szleUWCaiaWXMMHk1cy2ry5hUoZEACpHSpC+xnsSO1wJn0vn+rNtQubdyjj61zBONpp10nIcV4P3ktJrSQCfmqPTKOhm03Gq9rfXu8muSV/4pVreShPklDAm611Sal715CpqGdzt6kxlvdQ0I3Oc7rSMJ5mgrcqYDc3LNx20ZY4807QupaLhfdYyp4pI5sw5Lmlsm/DhdhnT2+QNwt5ui/N2W1zumqHKVIet3Sy3sJvlFpVmOe1C6ddKm2cMU+v5gVljl72iRj0AV3gc5JOx5bOEapng8paxJP/5JQL9tXCla7JVgxmypiZVr2OsnD7/TngOFB6cJ+26morLFEjWK9SM/hQ5fVrdRjTo9YrE16n7BzuYE4pyJT9aP5SZEeKalrwDWGmp6wdVB6SDMaE41y/17Hu33uqp3PenH459ye2CBrnVK7l5x57fHX48PBx2j//5eHh++/Pxb49nyvmfL/vv9u/efH54/unucffxDHV/IdbT3buX0+nMzr8M7N3fnVn9x+Olo6e3P//jH3fKd1ji3rwSSV5o/xl6s4TDecVTKLcStZ7eXhPCch3WmPb6zkymvaEz4xVY6c4mtp5ExoKh9zoG2Q/AEvYW+jNu4z1gkwlvAHxVNxe1rfZlCpIb+iphOcb7o9Vr34s/whqr5tVLgWZS1rTJTBPqvJqDLT+VlYFWoc9XCELzvWKrKvV/B0MHkZBDKq4J6KWhImEz1d+0UFs3L8GCaD+p62F1m/RIsnbQYFK0rExvQqxg4cGyqI+z6CxXNAypNrJnklzWImJvnzQOdX54n/nwtrCv9SKNUNbeWq033RTXlhPS5NXng91xHqJk9EczIV6UWYV369XQmtMY7qukd1HZczrqsophqKw5GYppqtioDDdtx3xlrFTZ7fURMBFko/HfcUll8ODn5+Ljm/f7N18dn88QLNo3lTdbLNzl/Lgkeec1ZO1O6AybzfvjqQwxoWDVOKKOYRnGN+tQrXHHhMxe8D0aL0u6PxQKKTnnwZxsNjk9Z+nnuytVXtnI9PyYpQPSjKdW56FGM/ImM5VW22S1cNa8tdSYaiubtlU1j07etmoIT7REMy2182VxRtmlcqDNmz6NR+VGuyy6cFnVmwwsZ5ZGu1NhHiWreYD0M52WdKj4BK66bisncF2BqvmI1wQKmi2xTtOS5e2idpury9lcTdeS2QIefc7qaly//kAwmew4HB1qMvgvFG2w3tPiVl89O8WkUY1efKPBMmmuzWmd+sN2WdbPSU1qB3QiRDx5lcu18US3fNjV8No9Vmnf62t70jw/YSV34vVnJM6OJXFv1QkwtHi8tIHCbJjVjJqvEuVv1tbNPo9d4qONs9cpK+0DKrDe1lx83atQX02dW6Fedbc0MDE980y56kbeAZztN6b62vVjNHqHdJWtkl4P2WpCUa4YTRzztFtNS81ZSrbqIt2M1xJoF2f00UZluu7Ja3kVtD3eKx5jN5k79fiSoZN/dn42r0l1uVmwGnEToSjdOaF+wHMUMMP4//+iIu8/xJiYIAx+7p7+uoMuY8jX1TXN8DwsMCV0HgZhsGO/7iSZ0kIPgyvh2kbDtys1fBd9nN3Cbd8UZ176csk2USTX2J3/7dek+XyytKybsVfjIdLdmJV/vihKJCvH9cpeI7Pqalsrh1FaYTsFdta4b2SZOWfHkmQjdY4//VmqasjBzF+c6D+f32lTMDD7vaEFo0xdMK6M63XuERw8CMoWIx/HvyoYbKkAMnFIX2ofU2TlXeaoutAvoC4nzyI7ErtOp03Pieo18CrSV8J3oGZlNH5b6EChMuGas7PTGHVecZ3oX7X0WwGrTNlyXChhxAl/K5UPp63/1TezqBw1HdFsuu5B5YG2/CtpZqcb3y1VNR6kw1T5TM7cXrSHCOlTt8nbutb4Sr5ru+d4MV+ZimxQxpq34lvT7lkBm2EmJzXvZFnoemC7T6rJuiFodni7hK8cBzS9VFH27EZLn523ts+7lVg1uhsPZ0vtxPi6ociGSG7N1LkyegTMuwnZcIeobhNaF7kNrMvcBgx3IKqX62Qs+Ha1e86Cb/cDuKHlL15OumHfGjE5EQiSx6LBlF94mswnMFT1nxP2fqsvgc/6Ethd1H3WycAmDreKIj1t+zfdTLIwuxMsKt0JlmZ3gmXKnUA1zhfE3Zly0vXHYyPUxDlurVisypz817cGsvSFTSX3hOpalQmnAv06Ny37a4WHZqOlpM3Y20tZiMF9Nx8CXKvWf50swY1mWdeVqmZNZb1FvFONms39vsDcr8eN51X5PreMVnXjoBv+BWw8PmP7t3IuXSLvx2yNmfS3lJ/QOHuFyxQG/HYw6hw2h3FY+KJX7nUus8xrd0gXxdoqtwHYzLnajQPFytRS65eSqiVhLdfyv8zxA/OKP6QxiGMYxByfApVv2dwEVFFwfqe2QE4/27avdjrX83cYxywVf+RZ2k1RXjl6ZOfCUreHWsDbii5YzabQ6ru2Gcm9dnZNhZr4pI08r7UberHdpOS1C5vmW1bLTN8FrOqVNDNezZr3KvYPnw0aKdB2Zu6ZLNt87dq3vLJuXlITLVQqRxZ2b9ZeLV0bGdGBSUJJjNHMi+yAXeHXJP0Sr2H8+eXx/WmXP/sOJyu9pa3r+9zX2vUl2/T8mk3o25KJH7wLUiv68fBweN6dfmLena+ODz897p8Ouz7rzpe74+nw5pvd6XQ4TuXewfNffrf76+7S7M2vd4/vzlPxjzstyc9VZ7NS/PTODvqkms2665KVSaZ2mx5FsSfAShtYkb15lcXdMo+EiQAH/SKKZXJmVH1c3dcubF87hQ8q+zVZpTSO+xoSQnA9sEyk07iz0T8geZm2ysPNDjbq0d5pLL30/OxU9l5n/3Aaw7dlKld5fIpBa8y86ESv8nfNbHEr02ts0xax1KjcMvWNGmO0TWWO9+VsJ1mOp1kPJztRz48aX7Oe9asZncbnckkHLFWzwqJdxVj8aZPTpbGzMtND9b5SOoI8DZnJZxrDdHce1aMjcTPGnd2pRb0FofBkoxyZkl4Qs260abRLAfIuEVZni9qr1RVf3WX6sK6xKlPNVVpNofFYa8a8taZzSWS6+0XyVK0VbVFqsBtNDVXmZ7lRlF65nTxzz7X1iKhd2lZqUc/nmLSfVrW0lhPpCez2qTFbnXYG/e3+9HH3OOR9tZ09EwdMAWleBllXEvrlVNX25Dzk1cmDo4UpPVur6fPtfiytYjnIOFnUXguyuLWW6L0tFftM2tGiSPWZ1fD152+Th8fq1jSWzpZYlFlZ1VZMKM01l6KNYmicE65SkolfU18V5Mq+PUceHv6q6tUmvD20s7qaTVxdXC1duWHfr3auqM3cnswMoKlz7ckeCvwibIqfWtVwax/QoFq3c+icZn1CHaZdMDxo9l/D0tOBMuvgWwXZK/qtTZrfKozAeHru2tqMka3C8qzBAnrofwfSloyhVRh9kbeFcslLTUjAMKJ/theGkrPJqGfyWmKoWX4Ciu9obtFM4b2arJQDWpRR34aHxhz7rSaU6i5GrSLsFgknQ2emFEOtcsLIEbIpyX4P1eYm0WqnNpPo0Cpnw8KIs6H3iVs/VNVo370tt0CrndqL07GUEHsqn2NiaIVxIWqPBRJ/0m1CTXJZpDHwWjDOHOopPFeZ3Tc0zVgObQx3KCkJ5nw6a3eim7osq16Ly1ONIJqVwasRgGk5qlfd12p6OjDXUEzeDG22f3VqJrrJOySau/LprqzHy+HUU5Jxq7bHe63HnHPIrduyLr30TiPVGsHBacSUzXCb7dGmn1VP/In+jWyx99CYgDDDN2KtjSx1C+I6NzeqMucGtB6ssspOeuGdEsagl0yyUcP639wwP/O+CONgc3kh6vL1Fd44YaIhjWFmct8aoWq8MQG1iAU6jQVWxSup/LBwaTXOpx9NVOY2K3y0aBI0S495zjVupn+dyqCyfhJl9J+XFFQeVhIYXbAuid1VZWrGHIsaM8tlj7BU1XiOydejUTlI7dUNEyPRTfuNynb0o7B5CvNMp8BHYuKTrl2tZvQ6gTjlm4ryGfWe180ruLbl87gVOeSUZjrLeo5NnNmmtHra6TDrnmFNipdYiYVy6C2exWXhudzgZNj7cxhdT1aacqIcK1eKsiTv7mHXzujXDa4VhVDeZ8OevljdBs0i9yapQ7MixVZT4E2l+DaEbG8LlIs2bbFT7wct5yVOu5K0lMGqiWZncNhsett55n41IjB9TMyHH06NIKF3caq63ubUO3hwmG/yK7hRZKGYOzLOGrWuIctbi00mYYbJNWR1a4gqDvGw+YKsbw13RT1tFMth4ri4uTVHltLjVjGSpvFge2t8TSrosjejq6q44qOg2Zei3rE5d72BZXO6df5U0zHk/S5qEw9OuD9MOIhpnhb60cNmgDOdYha3fU6o5ycyzus2tcXt7FpPZAtlGdPfYvQjV52th74qXNk7ADXKkn4E5pWb532h7W19xxP2UtVau7hlkjZnnYXCiIsnW3W40Lv6Z/tmKAmwcsNL3ABotj8q/p6GeJ6h863eucotdFcLGx1fN852ZHPAWGgSXYX2qO/bFN4x9G3yAlwoAvUsU/pCk/DnZGBaKMeN1FainXAy33nFR3S/z4V2wjOgbN/Fyt6Fkcf0e0ItxRdlsEgM2Hik99k8oVYLq2oIV7OZZonVGubj1aigwmtJfV7vZNjpipNVlLDhaw1cb/JODEStO8m59Gu6tPzNOZK+rnvtvXCrWPNacKTFpJ8YwETOiYSvZW/7WBpmuatqqhlGpNad9ptdJPsxumJeN7aeG3o3lImehxyuWhjP73fPHz6eu3mpCeQZDlvWs6tPD7noxJharSnqUW60Di4vlaO6Lx2ViSH3/i4zoKoahpvxZTxeLDv54MaSSEtVE6nRe7dMXX0q3RVs6UhMM7BO916fd2TuJbHJ61SS/KMsD4k95WLOU6YycaNTeXGhy47GksuCwVTGnPFtsWSaDL4tRl7pNF45ZfqNvi4zNxWn8ULjoUo38juVM5Zjl8YJK/QeGX44T+2occ10dndz17rCUWOPSclbZXyTcq81Y5zGK3M3qRhHrXE2U2qkRuVm6btUTENXuVLOvj41dDWhq8p1THpWOxMqk9fsvC0z9DnKGI0NFe0lBSQ2xS3spKZ6/CRsTHfVTjVqUphyk28266BtJHlvf4Mjx692j+f/9aQjM++PUA/ZtliLRjvLaxLwslCjkPHou4aiktlKU6EUeu6sFKWNhTutNc2QjttrRT2l1tyUaL163xK760zOvUT3UPkl0qtsFZ1l+lY3s+NLOmtbDQSn3hQ8w6NFu5y4XORT0zjb825oCaMLXFnUvItqIGaCw2thn1U+gk41eWTSPhbkTElfxVJ5GU1/vNSdXKZuUFwpJqrE565urWBlN7woSTB6lYGJ5XVVLTV7nYluK4jGjx+Pp59UbYspGcpWMbDmfU+mEp8o4+k1XraMAfe3Juts/JndveVS+6qytlGr112UX/NQK2upeSoy8eUzbvBTfTXiQO3ZxBUHEd0fwYYCprs4lrd9psApX2kxIS5vZzWNXEvranU152UyVE3zyzS25hd/eUsOZVi+VKgv/ck1N1f1XVm5wvKWSU2sW5n/XspWrlwxNsPJTbvSrNTyWZCDK3XQ0xJ+pWy7iqtoglFpnqlmZJ2Zv0MNs/OquFIi//ZDKnEpSYyh4MoqfQy2PWKpSaM12tq+83qvzqUmuc/xVVkqB4m6/NhhcEagk4MrjFTIqe6HkZXwRGusRZYlTB2HpxnT9bFc98pRr6wtCO3I+l9oiVyrwwbCmK/glhmHvRaT1M3QTJOKVwOnjCZw1fVN00BNyUXJY2GFI9VSUbwlnDaWmn7PdOQrwagpRxnViUq9zT3jpVLgVZOgYB2E2lm1cserAcgTJDExY71paFVFZZ3F6ArE58fdU2Lb1HtTp0wfV9lRKvV1eX1T711kGWlwJqqbwzb9uTP0VcE7qG5MPj2mPFI5y7Rrh0RXOguqwuOm65SofV/Y3YSPT6JXi9fNVhmJlgTXEm85OAfNuXW52nFo+u55UxYc44GzdxeyRZapjC4JWGNpaUWeytbmZLuxfYrK1dJRkSWYkHLIMXWm8bCsQ44JqsaFbDeuOJUP6b1onCcxdpXF6NmUNAajL6rKQSrO5BpDydr3yjpXzInm3vIkbuvQTvh5uree1zR+oKOHygvSTjAmmCrBZ51gau5VVik+fcXOBGmqalZzDxbiTyQJaFTqL74mZ1KunbvX2qRYm2StOgEVaiQ0x5+urzjTX+13p4cbzZV2KClMxK+l9knht3oDVGF/hXdDpa6seoV0Nlr8yKt5CKon9SRf1lQAFnvkSlNK3LiMawGpK0X5YUpgtdbUMENL8+lwrSiHVCa00TRRaQ9TU81tWiOniQammoMjiyVOr3dYMUtGadXobP1e76lS57Tu1IvB7WNTg1IG95UyoImToVMTfc8JQnVadvFUdtBMkOxkaJTTgnHnua/Y3GU0y09pf6uM/WnCt2Ol2MIyN93YfGLWtza80k/aKCbDTNKUQv27pn/QfWNUXYc1XPY+aw/Oy4iXthYG1WubpiKW1HwIl5YWJ4pem1bnM9yr5EoSXet+CKr2sdo9xpzyo0knFtE0uIbULBlLi8kLxnZvgPHw1OmybY4wq9znqSpy0/SurCvR1Zzn+qIb8VdWnOtqzksemrT2rcooLIHGq1uCtibLWCW5iNZJjUqt72rOkTFq3ZXkS8qNbWlDonYRXJGvhJJ9rJgharnO5geW+UJH1MR49EOFfVJqvGACU7GII31ntRd/hR5nWHPV8dgyIaw0+TTNamY7og8dzWOSqZuKVq92OgjjK3CI0We98uaelXbCu5agUlkYVsmD5Ky5qFML++wFwPPDobx6B3GpdcuX5KsNfRbd/ml1sNBCkRLGbTXyyWiZ/u3+o8q2rnU+idwZmmCktyxmVCU5YPIYO6Uxu+xUJfiR8HuZMzJdAVCCI3UOMitNUzvHt6T25KXeHaC7nWjRz6UZSdRw61IgvZVsnScULXFJZxq7aqd746zSXajTclXz68fj3yzu9ImPmCPiLZVhmDxSFqUDyaVwK/og9bw+d0501+G2ekzejgle6SwfJWQE7IoA32uAiySn+4JZy/v96KP4BWJaezehCfzXMpNsSmar0Fuzd/yZGJSeMMKpTC7v7WNTUqqsrSggV+N4pRZVlf2VnfQVUchpXHCWTUHlijmjgpk+ncrlihZA42plrksqV5tjYjIincrsihwONB6Y6ExlgBkvpELn/0i5aiiHyvjU3jWWNeGIZJkAjelMeBzVIYLGfEy5ZVRWNE9hoPGknBdSBSpqPKZOcdKo3KbuhguNJ83wdbJMqcaOcol+Zs6dcmKei3gqO9JNm6Yjw/yvul262/7++G6/u9lz7qx+Yo3mq6WBVLMwJdSUylHwyiHqi8PTBwVPjJmItFvTtJOamrd1pspRSyZb7cyhht2UntK1oJ9ZfpoJlYzGl62+UWtN95ROwWPIk6wclzeaps3m6bxR9HkZtyOjTtEUQbRVdJo57yS7dGPzeXJZtbEqo13XVj0qvaYU132pvKKDLxUzW80SMJPGe18hA2Nxmcz26mHB6oCkhkfn/H8sVV3GVKUeAIuCwSey4q3ThrkJL5OuaWUqn/4ArwWyqkd9Y2b4Xn1RacXtgBQZKbIT3St2itRAFjbRK6KqrPYXCAbG0evSyriBycDfa+mK5ZFe31gfe3oBo7GUKe/wzAU/014hyv1C6pyb88U02Tw0RVYJg2tTKvu84mSk5k4qNmTeWhEMc9JZDIysMmutMLlrrW/nP7FS6+Si5jlu19C0p/VdTCCnfr3W+pYcqhJQrBUqTYWtrm/5QFmqlLXConS2ub5lermpnIjUUZPRVN4uOPRcoQTwSga5GQxSS1mXJoHKCyW95oycoe45rtFelXmKZ9YqheVZi5m3FLquJ03oa02EzXRbF00U+pvgRfqG0g+gfotfa2eQzCcX5DudmOaKzKn9UOrchsIwKuRDr90MPYOPmW+i0lL9puVkNYew/QamvNuKFkiV8CZSA7cKHVM0Dcs874pXcCZaK1qkeYOxnGv77oweQvnubNFBNSmF1oqqcd5Yy4I9yxBJz6aTs7+GUZn8ibRLGnK0MXWtlJY1RQuGz/ZRlRam8b2Vri4zV2e/uwJxdZ785sPuQTkFrzO9j23166bWqU7VE9pNJ53Dk203WE1/XjINXeXMLpWus9evGbtTv3OR7GzyRrm2uPMJzVGrjGVWkFbpCkwYy3uXKfNW7dIj0JRaBV+cv0FtnqNxfgu4T6OHdXSDj1WhyaImkdHWgNOp4NkMa9RUuq+I/sGZ6vUgOo1dlq6eykjLHbEqR6Hy1aRaXOOgM69Ts+X8dRobLe5RZaipHjVmmTClqCxx3p0S9czKqezRIjm41+GWTuWWGccrK+NX+VzapcoKVuVIFv2Pxp/SJu/JLlI32yS/WLs59cv//qvd43/tmt8fH3841tyeWs2WNK6Uc8WaF+aoirEae6q4j09lVIYsThrPUoVplS+Z0rxoTMpsO6qY9oSazfrBKovSOYQC8tZrqfRDrhpPdxA8rWo86TQfsrQDlvlGAeVoq825eoGfxT7ZaBf4jWxO40G/3T8edxW8Z6EpD4xJMRaKxsLylWqq4lkOWgZrrBp8llxhLeYtM7IzR3z6oPnm2vNcaSq7aTv6RtMYppNAWXN6b9MKUU1AsF5Bl7nK1ZjJqnfBMjl2OU1xrXNGl9SSa+JiSTiwyVmtd9WyuH+1ml3CnL2k98CaexPwQrPDzLhJqHfZyrMLXVTO3CKhnq2uq6pTqkb9l4bUpLMMmIlANShmEjklDJjWZeh1AqacDr3+IOkrpikqrm3As9y3CmFMJwXo+EzZeTZpIbzAMkhdvd6s/sagCxgDK+sVhbVmxwsQi09Zx42st053ta1XmXS8pjbvTq9JnhZp0jffTDnh6Pm7lMu/DA5x5gxLjZa2qcLLx+4l1Wg+WUZnANOh1HKO6Ww0ttFurB/W232siLxRVkq3i25uMWEC7HROGR1bN7eYnvCI2uRISwNrJvCNwg7S86J7Ndgv0dgonC69uCb/fq/dxZmGaRJYvZYxMQ3T6CM9gJ2IylDdELN7+WTqoozUME9t1I/Hekga+q+5Tm1TIKql9pVNicyYMTUnUrDGBXz5YXdrotyYxeC+E4tHQIBqcrPaKMeIWdb6gvAUY06kfmxVd7VsCo94OT+c7BXliZ7Lkj/ks+9piZ/nzEadEchrgWBzhlGSR6/GR0hTlVjcsCbSvWSUNWUeKrYb0Taa/kk32W8UdddYUzV5nIW8hxp9YxjeRDYowzrpvlyWlSh04KLryF+Lhlh2N1pitBbxru/O5ti10ZTTGfSYdw1YIo+uerfLHGetOWmX1HwOpYvSG0Yt/qVdVb1mKQ6Yutso3en+ZGsNqEyglfHtrv2kVbL3BFJZDwf9AblydMvC0Wn6A9N6BYc309ouCr4sl+irAERKtmlLhzLJFPxrDc2nh5Y/jQQ/N4vlo/dzK8OyCcZ0n+78l0jc1TvC1dGJU/lgme+80xjk3CjzDKOcWHynMU4j+mky0u9fdg+7N394+fjp5VQjKTmVTU8nWHMlTDo7pyqnzt9SOIv6nMp0i/zy7GzXqWy3NAReY8gJK4rKeS3B+k5jtVm3OMPu7zQmWRgF5zLc0qpNcRobzWYXs9R1Gmu7mWvNYTXDz66qalwrbXq3wUzKblMOIyqPULvQuEI6F80NzBL3G40TqJKoSvfp6wktIFXqVkFqJJxxGauYD42Odcm8tieNuDW/p0al4LRX2CTIgnH/cfd0eLpxCzMMOuPJVuIWZnBAU5OmJVdMrThBuOq1ltPmwka75FKl4oV2zE/qIBeK/iBVWb33XU3/kr1oXuEZZtWMNVO+ljVcW8ZMEKLGcK9raiBVLZxmcFGcYDVlX7EZfKtpHVUc3ipqT9tIBxcuC2vrPbhMe7jTdM8ZDy6j47Qtmejg6jWDpAd/LgPXGPy5zGnCWsW4kcmgNS/djyonX8NSe11qJqT01ywV45TK7tX7UnIZtix+X2omhfRgtSQOhR5equ0y3WPWMGrQMGg5mnu/TqMnV3+2L8gRlrj+quMNtZlFLkDMWhn9hkIDJ1ATXF0glgX6afoo671WKZvzBcYMZtTr+8yO7ZfaFtevjsHY+YvqH90rPg2MpdfFWvlKV9uQZtB+s1yjXWqngrQkh9JzZWoZqEzrqzk5GeTHtBvVRGIk0/HFUKmzimjj1i0t+S/Up2Z7O6VprNkqS5cc97SbVsJ/ZqvgnM7HtrdYnPAw2irUod33o/VgSzm8Vai98F7rDoaZDW0VpmV0NFQugs19lTG4SDmrDn1NBILpLqJaikvd10ZxhLbeHak5Yl+3VdxBtU0/N4O2ewG3OWkmAbjGzWuryGtT/U0kn1Hd6baKvJmdLePJVncruXgeqCMo4BSmuj3UMh+vCePWVjuTWPmU7tKV6KPOrUC72H7+5VBhTFXeBl5LZ21ydVAza9eso9fivbKrYcgP7DXNgzVHhJ7HRdV6pFHd6FK11ZQ5luvPtoq2KNuHt86a6v6UANpagVY6LG2tmsG+t0pX0q2m4ZReLEnWbUxQtdW0tBlnH5PGWL2tpsrdM5MjpnA264C03ZG/Negcu5rXFXOLYAHai+gWjecQdGGBuTHDXGswL/ionRZtIFcayGu+k7rX1Di9y3Qf2nl8ajTpCw9tfSzsI2/tUFs7VG+H6u1QnQY1rcky1Rwch/S65ryDaUosdAaawoxEeKbTqNYe9JnwKFEJvOyznEb6U3zaHg6tsovCEWqcZL6nT+EiJIA5O+9xKu8p9vuZw5KcypKKutY41Zysw07lY4YTktO4WlGWX6cyu6TbkI0rOZXXWUManZ39ObO44TQmd5N2SklxYpY9zKKHWfLQuI9Z4agyl9x9UgW0n7BUqCwklZHFtsAqe0i6B6l957XhKhNIOgtdV1Qda1RitqS50IhZ7SFNs/lIcyt8lXxVqjJBtM2wbWwZr6VJvajNjyn4/pjy8irHLg2ieq1j0tNswptIWdmFdkrNu/roUdgTOvalduBOO/4YLHwrTWEwj/VMJKJSpk3N5l3euZZYXMMCNe6tvDstZM9iFVNVWAYWqWnJki7g95r2Le0OZKk5eAOZXIycoqMsdNbwmuI07SnhFQVtoR90q+mJ9e9rFRV1xg/oisgTyVcHRx/DbaWDo88rXLTR+wAtDV2uNNOFftfcSjGIZFyAbH5F2m0quteamhxAX0ctF8E0KTrVOjYjZ2zWJjcvl0zvB2iXIXPplaxpJhI2k45f1MU3dDAsvgwdt6hPeX4Bk88hnLxKrz7F1AWMJcVUx1Nst29dqk5IGJrBr2MvRu5iusbsAlB3X7jyyikLMb12ukjrbo13smVuc7l2Gunx4gbCZ8/H1CU+FQDUlEdphbrVi+baqUc/5Rj9hGyHMkOlziQxw91osHoYvqmrWHvb49CdN3ZnF291X73BpFPKnLpmZdif9XYYxqGmqZnQBXcty7iK3rnKSbTOitOE6v1N+EEl1OmtcgmtOVNoq913a0xTrUXVtUq6RFV4a7UcjUUhVlZH4aGrmmiutJCSYA2Wuj1UUx7QAWqFm1TfmdVNaujvqnriONGDtma/G0C3BaBNLk8DXLtmIXNa6butc1YYxqMDsQof/UBMngtDf2UeUVkng77zibQrulPOMJgqV6hWSwBdlAGjVdNNzxnFRIx74jaeVo2V0rhhq+lGcut8XTcN1Hg3YGYCr0Gk+zK5PQ1Ayy4RnAjh6rs3OUgN3Vvq9lCvOIp0N1LOIEMHBgVGD19xZ0qAtGRw6mEaAjsCUAtz6YGa1Nn3muY7A9R0UVyr3nkzg5Bt+SJaNfuAxcbc9pYUp6CMbZfuDCxK84SQbjotKSDtHqXXLVX7yVbpIueFZajae2GZYK6Tc573Clybe1hpPegOQivDbCccWZf2XpaGXpIX0yzs/SyS/ahKJSPU1g7Vp6FOxof49CTZtj+vUrNBT6dRcdldzGnytipy0mSvaodtS+c0Si9O+a8ygetFVXwznMYTqhKROZV3GLij05iH4ROC39VESy2iN81ZVFvLTR+6DSPDSeapbZzKXvTONfYy79rBNJQJLuE0ZmQwkjqVM1m0h07jS+bxBl8rw77lNDaUNmyaJQqnsZbSrO4qz5med7OkYRY0NJ4yzyXA1J3GN7J3U01NkupZpPGKnMOVYeAao5i+UdrODDRekHG3ski+VogWUlYsoFbwKsEmEy9Ng5xBOLaRmt3AGpsfWPCssubBsvhqqZc5JvHEUnGhnViTicZ0Xy2bTLbUDtxJ4l+mDvI5pFxpioJ0zrfrmtr8rDV1Rv5yO0OqFzUvd5KTW7yt1Gi6dPYjQ0Wnqr8ynsm6s5UNOYYMi3knz0QWIqdoD3O32plcq7yi+NSBtpqatcwrvVV0vQb/mIWmZs57PRmuCB28npJGvZxLw+DoZPGtWmkGAuNFnL3rk8Wdap01i6gHollX9ql3lUzkPLJkb1ID9i0jGryeLC4KqnXNklpFs+ClL4erc3Pq1RHXMNJOSsk8TPably5wLP7THQOod4q6gLGkauyo3pb541LV4urUUXy5A1OvtLOkUeqIPX8/sI7FXct8Q00F1ZG9yWvpUtOSREm7tSxzHZthxzZn4mm0BD9JBxiTs5Hm+6NCNAEzAbJ1ONgQrBCLfUoH+JbJdLfLqBt9nIIaSYgWpOwhGmp2FQvck29NnC5FmFpPRv/qHqjlyrpWue6zXPvQaneP6j4nSoq7tKtGOsOeBtbmi6M56xr9jZSw91bbE8Oy3D1eAO0evjk+vr/cZHR5/eaLl/99SJBcYUSyOhSbO4/TBI7r/UZLytZ3YvcozOB8JZR+JHZnw9xIjFJj36VVlB1gL0wk24OuZySFmVj1SS24fykVbjGMRoeUO1m02g3p0piqnUda9Q521elBS+Bb5pWiZgvWfQy0+KDMjmO9ui7hYqCdwzO9mRx+eqBFRi+zgD8Mw+Lf4xSdiTVvk3b5wtB1mReQOiib14/T9E2ZCdfzIuUMdKEPi+OPU3RvViKzhGP2HczINe80FWVmmvKRq/qJZuikzjlQy+tv9YBo1WsF5gzA4NoXerN4AWpqdcslbUECr7vIUsmI3PamkeJDRtdOb2bThoYvMhwO+1mznCIHpylzIEVBFjdL/72b1Gy/R8XWPpzJ/S3GaIf38mUMvlWGDtb2CVuZJ2xlB7qch6i9J5Wti4WhC8VMuEivet7/rjXPU2voQtuxvErehT7qXqP1OX5WcylDy4+n8YQaccWrrCOpTJ7ZtWpPSPMXq2VJ4zvpMOXEQmj6/ioO71TekgzfnsJvxfnAmTmNS3OaaXHCpXnPdTcat0nbSNIM5xquxmPSCQVsMDWmkrYU2mBqrGJGOLvKL2ZcRmdfCpX8CxNNaIwhaZ+e2mhU0Voj9FKVzP9X2v2t2LJbVxx+lTyAC1qqWn/63IUQEhMMBgdyEXLR3t6xTexzzPZxwAS/e86SVIT0Hqr1VW8wxgbtoWqtGiVp6qc54ydgdoKvIxJ7iv6fEQjf1FP8DqSe0mcgnMj+6i+/fftqvv7gCiR9Eqb0CbksfQwOSCpZDquibBdyBQftgbcFyd+ZpYJG8mgR85r+DXSvIm3qpuNON97TVnROT0HDLW2lo+IWduyp4SVFB4iDuYSIxMzluRJf+nC8bzhnpE6f0nZaCiiOe4osnVpt3UNQa05RwVneknKSR1/E+34HKaLEazFwOU8RdT4L1iivS9nz6izs+4yZWVPMWeDzNYS1T65GthREPwdtbSGSP132YsKrSzh+OKCnxMSdlRIi65aOcJ5Dzh2aEhirQ1Kn89YNXArsW2LpkTwsqaBJnIZiMoA8D6UsA1EznoBm9iOdq0bNDjd+hKBs//T9v5yjTgQ0P1oKPNWMSMknHy2Fj2p2O51TssfQwHo9gCfOay3BeD3MCAbqAUlo2COjxD89WoKzYkEvGdVQRWyOLtGyPSQVmtI2BkMhm2S7Cnm0ah2OAwh6NBuUoajPKAuhcUiCivCqDUVo2RqeX3Z2fbBRa0jJBOrsm/D8nOibE9qtqeqmfPfXkIbvo927TAQ/Amp7Eg9eE/V7KkVQmgTPHdrFGTgTYzXM6nOWp6blwvk/jk4Ja1rufOT3fL+4+oZTgPFQCkrVsFyEgPno5VwOpWeXrPvDYDIlurU9HvOd5IzsqmH1/0317Ub3T9iqr4d3TcXCPwR3xYLlcKa4puTF59irmC05AyLpAhFPTs9SLoXjzHW6D5+sAc4XEeldyK5ldCH39bvoB45vRx9yXNf7gKpwu+jHPl3zD0AGqiadS9uuCuD2Lnq6bFzvwVc/hk3VEKQ8HAxhKlNdgqMnhQSNa7qRG1MRxUu+U8ljvqn9DicAxhgiP5FvKV3iPhi4j2d2WtZ+2nK8gcxlQtrxy/md53hk3Zi8b/hNZNLAt/ROSO47bnxN9GU2ZHF7/uxnmRcdtz7uqY+nvGeHtqiD26yDFGixwR6YFnTfMa389jwDFwe3JVHIC/TyGMUT9xu3j1qyQ102jtH352DTmr4Ahxmz5Gebmz6GYE107uYnKBp7uyZvH2a2+oC5C5u7RHPHYxD2c4l+nh5ZmCb7uSQ/z09rzr7b/x/cY7eW5P/8VGLrWTaBj3wNdqoKPk7vu5wb22moueOPdqMl2X9+gmpvTnK/8jMlfgGmeTno0aP/Z8fe79udOgyNX4EpNnWip1kQgD8R6Qvx0Vp/0N3043G8WOV1QPoMTHkTUky2P+ClZPmpirxCT2Y94KNk5iBFErNHi+TWnI+SQ+S0JZvzUXKKlLaT03dBGm5pczzno6DhJe3go+IlRAXmPBSc/HYeChreUjwkKt5CjGVOQMkR8T3EheakkxzHvYb41QHpRDZNCcsPSCeyTbqjGTVjbPKAbZLccWsKqc4ZdCoEuKVI8AcYJeA1BqP0TTzUJUTXpwvszEM9XWlewxnCAcskFuz4kvBRHV8SE3ZgSZCoDiyJDTuwJKhGLDFyACzJBBxzJmTNlKPhAFiiCSwdl84BJUGZemSCoKfmQ5nDWkuBnprbZA5rLQV6ap6SOay1FMypOUgM1FoK5tT8Q5jTo6VgTs09Yp7WUoiSVP1rjiFpgNfAppDQaBquNrAJOSNb/ssfu1qH4ziAHs0GZSjK8K32w+1HFqhIYNOK72trKE7pioIyrWbSoQgt11kdzaflA1Mdz2kPdKyXMvDFy/KBSj1QPH16v6Y5Rc6q4rQ1/Que5Gqc5J1Y03Q774NgoTUtC6ZczhpWGz46Sv+sYZ00OVFb0+pLWIs1rO8QEpjlsFjT6vJ9UqxZDcQ1rGGxVtmaVsrHg0ulkGKZ7285VV2nWXInfROmk+6SHIlKCaU1bfEIaYnbSDtM7J1+sCrO6Jh4nTXssw9GzACdNQQEjkx7itCJnZ34QkzSIT1zeiAZe9eE7awp5IO/Z+/GCieuKVil30BEedYUYjt4EdzkxPKk25xHms+xnzUFQA8kAfuJPRyW9UoIq5eH4AQHa7woHVmofuggC9x26uBrZtJcg+YRzaQ3DEyzsGaZaT5ZBr1wDy86uoP/Of0wnf6hHu7THlJ84MmjTO6v3eCvyBTT7WO/xcCDJBp31TdowECieQmah2mbzv/AyaDzm372AyeDHnI8Mhbs0MoOrVOHxgCqaSZPzm+mkmZJLjzCdEQzufD5dLVDO9JD8txZ6iP6b47z0BhF/+GKqyRL5jj+3JHvNacehPvxzzw/v5JvgxUNegBW/OLty59/99U1/Kl5j2+cRyfPkZx3Dd9vqifFEdnaha3NzmZjs6+nk+t7RfbxdOp8r8hzZbLq9GifFNmVvHL1hSuv1ngpxXMNf4v4FSdFErNHY5BnMZJnx2U0jZPmhTIAR2vxbWmvOH1fpeElbWjnuAw0vKZt9xyXgYa3FB2Y4zLQ8J5iGnNcBhq+pmjMHJeRo/+XFFo6wGXENTHP9wEuIwhOvGZ3gMsIghPDjVkzhTXPXMvu662PJCjqS7VcWe7J6mHwNFRp7hIi0M8JVSfHrykYLsvIBtsc/7u8iuzwjRi6wzcC9HT4hoCeBt8I0NPhGwJ6GnwjSEKHb2g6b/CNbkcR6EllSQ7gG5oOU+6AA/iGgJ50jDmHbwzoabCbAD3NnAT0PFoK0NM8RkDPo6UAPc1DBPQ8WgrQ0xxEQM+jpQA9zT8E9DxaCqXQ3EOr60dLDbYa0BPqfc3xG861o0SKAT3I19gGReP09GQb/g2tIY3ehuPczxJYUX7izV6uoajjSEDPhp5qDQno2dD3a6gWeaAoAA+mbBuK0HJFwnIoSkVtnTX2V1zyzG44u+2a6huar4em1A7ZcLWwa55md3oPdH62pYUTog9bWJ0x+rClVeB8uPJJueds2NJCdt4dsTaxEPRc0y0puM2aLhkcacKuaE07r4O/XZp2Tcp2saXt6VyTTtG3tI2ea0ar2Y537+vJhdxfvH359R++wg62EGqQei2jz4+RMqnoSH8SQmW2FJw5WdBqC4EgzOIw+j+XZCv2bzTNluJlEXxJSceJQ4t5zT/yFxF1E28JJupGo577Uu+QugkpyrYQpzWmeUuxYEpvw8VL1lgCIRZI4+lo9du/B2kF9LPUj21kcdvObXy9TJoba66subJmZc3KmoU1C2u+sOaLag7ISC/0mOadNe+seWPNG2teWfMaNI9AIdFMPqJ1wA4OSSfJWEeokGgmYwGFUqPN5vl/6Kmjzebpf+i1iDaLmmyzwjYryWZ2IsK2K8l2R+l+RDPZ7ijdDzQtyXZ5fKPtprepTZNdVnj6KtFl8Tl5+ipzXz2vI2K/GE9mJblMzrN4aivJc2fZpoXtOHXje0U2H095bD2e8Hi+Y9/xbMeuY9P5kpFXTTxD8FTJHubXnxRJzB6NMaTFOKQd9tEcRJrUyPAhLRcXt4zT91UaXtKmd+opaXhNO/Op76XhLUUWpt8maXhP4ZCoeA8xltkH2fCh1xA1ms4oxg912EfnQQSISojqRc2Y/nq+JCCAKF4DnC9dCCCKEdr5EutJBbScBPOSIsvzpWFGjCw2MiAdMVrHco6vpod8h53JEd91JgdaDiaHOJ/G5Ajn05kc4nwakyOcQmdyeF9GnE9ncojzaUyOXmVBzicV2JhupJHzSdf+pxt+5Hz0JLTHNIzzacCccD7NVMT5PFoK59NcRJzPo6VwPs1DxPk8Wgrn0xxEnM+jpYABzT8cPdR4pHE+j5YCWGgVqkULW3FCmUVz1DAjsyh2Y3sTDbjTk13wb2gNafQuOM79UIAV5Se+2Ms1FOU1vJgBhqL+MsT5XND3KxY6HIrC+WCWsqEonA+Cl0NROB+dNfZXXDifC85uu6b6xjifi07tXdOtI027JpE9l7RUiuTDJay+7LhidCIUzyUsG7+tItYlrVnnfdspf6wavFf5+tn3jyd8+8O//fD9bz5/+e5fvrz919uPP3yVTENTcu69Ce2TriscvUvqTaN94p4MOLTL801gzLlwSfvMnLnkgnvXXVRQoAvusXdNyArfNeOdW9ur7n0d3hEPcMUlxDXem/ufPv/xa7bikmInCQ+5hGjMkbukulUXvT3tfJcMLZ8kekl5qo9e/jsOBKE38X7gdByMvYlhyLmmz5+U1+aC4dddU21olExM5I/fJ6P2+e7zsvazGFkStsMYX2WS5oU1N9bcWHNlzZU1K2tW1iysWVjzhTVfVHMwPHoryDTvrHlnzRtr3liTfVSTjySdELuqJldlbIVdVZOrDst5Hf+FuWZYslmaR2t0GSDINZnuiOg5XcK2sgVrtCCNE1uysCULW7KwJQtbsrAlC1uysCULT22FTVh4aitswsJTW+GprfDUVnhqKzy1FZ7aSvLVqS1J4SmvJH8R4812Y7ex2dhrbDV2GhuNfcY2Y5exyXz5yCsonhF4NmZ/8StPiiRmj8ak0aLALKc+WjT3EVczW7ScWbyeMX1fpWHc9E49JQ2vaWs+9b00vKUAwvTbJA3vKcox/X5Kw9cUmYmKryHYM51FDBHqPI/OgsgIlRBLm87WyAilOvXTVQUyQimt93T1g4xQunI5XaUhI5TCw9PVJDJBjYiDlgPNIfanoTnQcqA5hPs0NEdwn47mEO7T0ByBFTqaw1sqwn06mkO4T0NzZP7paA5NQA3NEdwnlrXImqlyxnQrj7iPJhSofHY50BzBfTrvRrhP490E92k+Itzn0VJwn+Yiwn0eLQX3aR4i3OfRUs7em4M4LKiBRsN9Hi31SqPhPo+WsnrT2kyLlnvidDOLZrBhVGZR+sa2Lhrvpye74t/QGtLoXXGc+5kEK8pPfLWXayjKa3g1AwxFscrVTDoU9bcm3EdrCK6Yw2woCu6D/OVQFKRAZ439FRfc54qz266pvjHc56pTe9d06xDuc8VVza6p7hFkZ9dU/0QUh+mGqy5J11SN9mQi+1WK4cZ45DpNzznp43QG0DXdNDj6zdWXhvrErRaPzLNKWKl4zjVtGDPscw2b0KM/QyiDK26Wd813TQE1ueIWf+9BmL1rCEUcjYQgetcQMpmAPNcUiJmLGnsXS8J/Y6aVlA37aJwA80l37iBJwhpv9f3/f/jzLz/kBZlbNzZ9/sExHuiqodGu6RMsJX5vmifWpjrBnsF6dIK1OwJ8bXtZ+xmTrBPbIVNq+PX0+PNPnydzI/V0/caeLtzTZdZT3Caa5saaK2uurFlZs7JmYc3Cmi+s+aKag2rSW1WmeWfNO2uy5+rUczGuZppTd8X4n2kmHx1xTKKZfHRq7V+jvyYS4UNSk+sosU6NLjzz8JXdWaM75wmNSJPdWdmdhd1Z2J2F3VnYnYXdWdidhd1Z2J2F3Vl4livszsKzXOFZrvAsV3iWK+yjwrNcYR8V9lFhH7GN2EVsIvYQW4gdxAZi/7B92D1sHl8h8iKJv+z8Yed3nF9xUiQxezRGqhYlgTmN06J5nLiu3KKF5WJm1+n7Kg3jzZqpp6Qh7/cXjSHcUoxi+m2ShvcUVpl+P6Xha4oETb/x0nCASzwVEQxVUgxuPmUSDFVTsHA+tRMMtaag5nwJQjBUTLU+XyoRDBXvh86XdARDxdj2fOlJMFRn/wiGavCfwFAdXCIYqoFLAkN1cIlgqAYuCcjRwSXeGhEM1cElgqEauCTzTweXaAJq4JIm50UYqoFLAkPFAiNZU6uWVE6QMMAlgaH4ZHeASwJDdQCQYKgGAAoM1XxEMNSjpcBQzUUEQz1ayql/8xDH/jSaaDDUo6Xe5DQY6tFSc8YbDPVoqcWlDIbCUlmck2fRND8MEi3KJtl2SI8p6Mlu+De0hjR6NxznfpTCivIT3+zlGoryGt7MAENRrHIzkw5FsTMWSxyK+vYQDKW541akU4eiQBc6a+yvuMBQN5zddk31jcFQN53au6Zbh2CoG65qdk11D63Thqb6h9aTQ1MdZFXJuAzwmjKO0rHJymlNV706sWuqr2j/s/JWqWt+Q73rvS/JlXILu8cT405U0w13vbvmce6UXEPphrv1vQ/hmm4YVdg11Y/CKu2a6sf3URrJbHVLgSAf7WO3TqpkxeTf89GnDEbxAuJU0/ilGBvksTGC6aYRza7psyIRTE3zxIJSZ0ULTHdNnRXPYEnqQrtKwdfpl7UficlE1M7EfMVImjfWvLLmlTUvrHlhzY01N9ZcWXNlzcqalTULaxbWfGHNF9Uc9JReezNN9lFlH1X2UWUfVfZRZR9V9lFlH1X2UWUfVfZRZR9V9lFlH1X2UWUfVfZRZR8V9lFhHxX2UWEfFfZRYR8V9lFhHxX2UWEfFfZRYR8V9lFhHxX2UWEfFfZRYR8V9lFhH7GN2EVsIvYQW4gdxAZi/7B92D1sHl/L8XKGv+z8Yed3nF9xUiQxezQmsBYFFzm91aL5rbik3qI19TbddXbOCRrGbL9TT0lDvoO06L0mjjMsGru4p+jI9PspDV9TDGf6jZeGg3PiqYjYqZJCZvMpk9ipqoG+wTlp2kdkp1aMcg7OidipxjkJOxVz1s+XdMROxeu286UnsVMxoD5fIhM71WFBYqcaLSjsVOeciJ1qnJNQH51z4q0RsVOdc+KrKsROdc6JJqDGOQk71TknYqca56TF0pGdapyTsFNctGVwTsJOcbaJwTkJO8UHwYNzEnaq84LETjVeUNip5iNipx4t5aCwuYjjdBr5M3bq0VJvdxo79WipmfWNnXq0lNB9cw8dMTxaasEuY6ew/BgnOFo0ZxJzR4uiTLbF0sMMerI7/g2tIY3eHce5H7iwovzEd3u5hqK8hnczwFAUq9zNpENR7IwFKIeifHIwa95Q1PeRIA/lY1edNfZXXBiPO85uu6b6xtipu07tXdOtQ+zUHVc1u6a6x9ipuy7puqYbiNgprYK8a6qHaH2+ck7YVW9W7JrqI2OleGvUNd1H0rRrnpiA1EfGQN11S9w13UfStGu6j4h5umPUYtdUH1EcZmiqjyhetHKC8lXv+e2a6iOrw8Zxuq7pPiJq6Y7xyV2TV3InlnLqI6OWuqb6yELXXVN9dAZFUh/ZPQq+8b+s/RhOXuV2Duf2IM07a95Y88aaV9a8suaFNS+subHmxpora66sWVmzsmZhzcKaL6z5opqVfVTZR5V9VNlHlX1U2UeVfVTZR5V9VNlHlX1U2UeVfVTZR5V9VNlHlX1U2UeVfVTZR4V9VNhHhX1U2EeFfVTYR4V9VNhHhX1U2EeFfVTYR4V9VNhHhX1U2EeFfVTYR4V9VNhHbCN2EZuIPcQWYgexgdg/bB92D5vH13K8nOEvO3/Y+R3nV5wUScwejbmvRXFJzsG1aBIuLnC4aIXDTXeyna6Chl7pXKunczbmRTM8842rRW9xcYRl0ajNq8aB2jdeGg66iqciIraKhtUGXaWMMxJbFWOKg67iSr1EbHW6ioitRlcJsdXpKiK2Gl0lxFYsPDBfehKxFa8Sz5fIRGxxuH/QVUJsdUiRiK1GKQpp0ukq3hoRsdXpKr4gQ8RWp6toAmp0lRBbna4iYqvRVVrJHomtRlcJsdXpKiK2Gl0lxBbX3Rl0lRBbnBJj0FVCbPHx86CrhNjqlCIRW41SlAOM5iOO1Gnsz4itR0u9/2nE1qOl5vg3YuvRUg4Emn/o4OLRUo4tmnvoeOXRUotaGLGFFeQ4C9OiiZ2YdloUoLJtmx660JO94t/QGtLoveI494MhVpSf+NVerqEor+GrGWAoilVezaRDUeyMNUSHonxyMLXfUJTPIiK0Q5HfcDoh56moa56wjfrGiK1Xndq7pluHiK1XXNXsmuoeI7ZedUnXNd1ARGxpIetdUz1kxBYnrl31PseuqT4yYou3Rl3TfUTE1ivuCndN9ZERW6+6Je6a7iMitl4xGrBrqo+M2HrVUEjXdB8RsaU5z3dN9ZERW3xncdWo2r6cUR8ZsfWq8cSu6T4iYqtpnljKqY9itBeLvfWe1F0xUn2qJ/WcheO7pnruDLKlnrPbI5yNYdna7n2D1761lIb7Ol6tZJp31ryz5o01b6x5Zc0ra15Y8zLTRNNs3NP2jT2t3NPK41RZs7JmYc3Cmuy5lT1X2XOVPVfZc5U9V9lzlT1X2XOVPVfZc3Xqua802V116q6vNNlHlX1U2UeVfVTZR5V9VNlHlX1U2EeFfVTYR4V9VNhHhX1U2EeFfVTYR4V9VNhHhX1U2EeFfVTYR4V9VNhHhX1U2EeFfcQ2YhexidhDbCF2EBuI/cP2Yfewedg7vpTjLzt/2Pkd51ecFEnMHo1ZukURVM6mtmg6Na5suWhpy0130p1Yg4YX3e93Yg0aXjVW0Yk1aMj5vBfNEc739xa9E8gxq0XjYIOI5qmIKLiiIcBBrCk3jhRcxfjnINa49DJRcJ1YIwquEWtCwXVijSi4RqwJBdeJNaLgGrEmFFwsVDFfIhMFx5fJB7EmFBwfoQxiTeidTn7y1ogouE6s8aUjouA6scapp4mC68QaUXCNWBMKrhNrRME1Yk0ouE6sEQXXiDWh4DqxRhRcI9aEguOCS4NYEwqOk5sMYk0oOD7SH8SaHLZ08pNDdQQpNB/xHVi9VWsU3KOlVlYwCu7RUo4kmoPo6OTRUg5Omn/oUPXRUo53+qZMFNuuDBS1zt+ipQM5n9aiKbqYIFsUSrPNpR4kyZP1syl6NBuUoQgtW0Oqyv6C70I/PmNFKR3/YgYYipKk+cVMOhTlYhIWjx2KsnHEJI1DUfKeI5Y8FOWun84a+yvOrjlhG/UNzddDU51D64qhqd6h9c/QVPfQOm1oqn9oPTk01UG07t24LPqm2YJ3TXUR7SM2vniz6S5m/7Crj2hfNjR5/jkxAamPaJ87NNVHtB8fmuojihsMTfURxTeGpvqI4jBDU31E8aKNU+Jvemdz11QfxaiawRobB/B6T+4uado13V3StGueWOCpu6zERddUd30DBTd6Us9ZQL5rqufo2GBoqudOoG1U+YYTcWwHyT1+Gvzfvv3x8y/fvvz03z/9On/+7n/+9Ie3vz7+x7+P//Wvf/3T5+/++S9//Onn+/S7H/78+ft/+P1/f/erP33+9OPbjz98+amz8Z//+Nmff3z78uPvv//tP355++7vv//0+8/f//h3n7+8/e1nn/7y5ctP/+eXTe///m3r+ue/+e61vFx+/fayLp9eP31etnvZll/X17flft/u66f/3D69/vrlb/8LEtKSPOQ3BQA=`

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Resolves #4786 - some Info over there, but then I started optimizing and added instrumentation to prove those optimizations.
The actual issue resolution is only not using terrains.first() upon a certain failure...

<details><summary>Measurements before optimization</summary>

MapGenerator run with parameters (Huge Hexagonal Pangaea, Seed 1628279571376, 6/2/0.7/0.59999996/0.4/0.05/0.1/0.0)
MapGenerator.MapLandmassGenerator took 20.67ms
Mountain-like generation for Mountain
Hill-like generation for Hill
MapGenerator.raiseMountainsAndHills took 90.75ms
Temperature: -0.3531763882369978, humidity: 0.18667701350657573
MapGenerator.applyHumidityAndTemperature took 81.57ms
MapGenerator.spawnLakesAndCoasts took 45.77ms
MapGenerator.spawnVegetation took 2.62ms
MapGenerator.spawnRareFeatures took 2.0ms
MapGenerator.spawnIce took 13.75ms
Natural Wonders for this game: [Krakatoa, El Dorado, Cerro de Potosi, Fountain of Youth, Mount Fuji]
MapGenerator.NaturalWonderGenerator took 22.29ms
MapGenerator.RiverGenerator took 49.55ms
MapGenerator.spreadResources took 516.11ms
MapGenerator.spreadAncientRuins took 29.38ms

MapGenerator run with parameters (Huge Hexagonal Pangaea, Seed 1628383638257, 3/1/0.62/0.44/0.15/0.05/0.1/-0.08)
MapGenerator.MapLandmassGenerator took 15.61ms
Mountain-like generation for Mountain
Hill-like generation for Hill
MapGenerator.raiseMountainsAndHills took 78.54ms
Temperature: -0.33561568074118525, humidity: 0.18225636915378696
MapGenerator.applyHumidityAndTemperature took 21.88ms
MapGenerator.spawnLakesAndCoasts took 40.89ms
MapGenerator.spawnVegetation took 2.93ms
MapGenerator.spawnRareFeatures took 3.19ms
MapGenerator.spawnIce took 11.74ms
Natural Wonders for this game: [Grand Mesa, Krakatoa, Great Barrier Reef, Barringer Crater, El Dorado]
MapGenerator.NaturalWonderGenerator took 24.95ms
MapGenerator.RiverGenerator took 24.63ms
MapGenerator.spreadResources took 586.80ms
MapGenerator.spreadAncientRuins took 35.81ms

MapGenerator run with parameters (Huge Hexagonal Pangaea, Seed 1628383671238, 6/2/0.78999996/0.65999997/0.4/0.05/0.1/-0.049999997)
MapGenerator.MapLandmassGenerator took 10.31ms
Mountain-like generation for Mountain
Hill-like generation for Hill
MapGenerator.raiseMountainsAndHills took 62.47ms
MapGenerator.applyHumidityAndTemperature took 17.12ms
MapGenerator.spawnLakesAndCoasts took 38.94ms
MapGenerator.spawnVegetation took 4.37ms
MapGenerator.spawnRareFeatures took 3.62ms
MapGenerator.spawnIce took 17.19ms
Natural Wonders for this game: [Barringer Crater, Old Faithful, Great Barrier Reef, Grand Mesa, El Dorado]
MapGenerator.NaturalWonderGenerator took 37.20ms
MapGenerator.RiverGenerator took 42.98ms
MapGenerator.spreadResources took 356.13ms
MapGenerator.spreadAncientRuins took 11.74ms
</details>
<details><summary>Measurements after optimization</summary>

MapGenerator run with parameters (Huge Hexagonal Pangaea, Seed 1628279571376, 6/2/0.7/0.59999996/0.4/0.05/0.1/0.0)
MapGenerator.MapLandmassGenerator took 16.62ms
Mountain-like generation for Mountain
Hill-like generation for Hill
MapGenerator.raiseMountainsAndHills took 52.56ms
applyHumidityAndTemperature: No terrain found for temperature: -0.3531763882369978, humidity: 0.18667701350657573
MapGenerator.applyHumidityAndTemperature took 10.84ms
MapGenerator.spawnLakesAndCoasts took 65.24ms
MapGenerator.spawnVegetation took 3.95ms
MapGenerator.spawnRareFeatures took 2.70ms
MapGenerator.spawnIce took 7.92ms
Natural Wonders for this game: [Cerro de Potosi, Old Faithful, El Dorado, Krakatoa, Barringer Crater]
MapGenerator.NaturalWonderGenerator took 31.69ms
MapGenerator.RiverGenerator took 15.90ms
MapGenerator.spreadResources took 229.71ms
MapGenerator.spreadAncientRuins took 15.63ms

MapGenerator run with parameters (Huge Hexagonal Pangaea, Seed 1628383638257, 3/1/0.62/0.44/0.15/0.05/0.1/-0.08)
MapGenerator.MapLandmassGenerator took 13.49ms
Mountain-like generation for Mountain
Hill-like generation for Hill
MapGenerator.raiseMountainsAndHills took 31.73ms
applyHumidityAndTemperature: No terrain found for temperature: -0.33561568074118525, humidity: 0.18225636915378696
MapGenerator.applyHumidityAndTemperature took 6.32ms
MapGenerator.spawnLakesAndCoasts took 25.57ms
MapGenerator.spawnVegetation took 2.63ms
MapGenerator.spawnRareFeatures took 2.31ms
MapGenerator.spawnIce took 5.79ms
Natural Wonders for this game: [Mount Fuji, Grand Mesa, Barringer Crater, Cerro de Potosi, Fountain of Youth]
MapGenerator.NaturalWonderGenerator took 33.25ms
MapGenerator.RiverGenerator took 48.11ms
MapGenerator.spreadResources took 232.72ms
MapGenerator.spreadAncientRuins took 19.12ms

MapGenerator run with parameters (Huge Hexagonal Pangaea, Seed 1628383671238, 6/2/0.79999995/0.65999997/0.4/0.05/0.1/-0.049999997)
MapGenerator.MapLandmassGenerator took 17.97ms
Mountain-like generation for Mountain
Hill-like generation for Hill
MapGenerator.raiseMountainsAndHills took 40.50ms
MapGenerator.applyHumidityAndTemperature took 4.25ms
MapGenerator.spawnLakesAndCoasts took 27.35ms
MapGenerator.spawnVegetation took 2.92ms
MapGenerator.spawnRareFeatures took 2.5ms
MapGenerator.spawnIce took 6.39ms
Natural Wonders for this game: [Rock of Gibraltar, Grand Mesa, Cerro de Potosi, Krakatoa, Mount Fuji]
MapGenerator.NaturalWonderGenerator took 20.89ms
MapGenerator.RiverGenerator took 34.95ms
MapGenerator.spreadResources took 192.74ms
MapGenerator.spreadAncientRuins took 8.42ms
</details>

Notes:
- The first test in the comparisons is ravignir's seed showing that one hill on a lake.
- Reproducibility of the timings is reduced a little by some generators not being deterministic by the given seed - vegetation and resources, for instance, will change when repeating a seed, coastlines lakes and mountains will not.
- applyHumidityAndTemperature is _way_ down, pity it's a small proportion anyway - those were the obvious optimizations.
- biggest gain is bringing the repetitions of the for loop in `chooseSpreadOutLocations` down, it often did start out with distance 40 and was finally succesful at distance 6... My formula succeeds but is a horrible monster. Better guesses welcome.
- I tried hard not to change resulting output at all. I passed up a few opportunities because proving nobody would notice any difference wouldn't have been trivial.

Draft only because I _expect_ someone to point out the BS.

### CODE REVIEW

File: core/src/com/unciv/logic/map/mapgenerator/MapGenerator.kt [hunk 1]
```diff
@@ -429,34 +482,45 @@ class MapGenerationRandomness{
     }
 
 
-    fun chooseSpreadOutLocations(number: Int, suitableTiles: List<TileInfo>, initialDistance: Int): ArrayList<TileInfo> {
+    fun chooseSpreadOutLocations(number: Int, suitableTiles: List<TileInfo>, mapRadius: Int): ArrayList<TileInfo> {
+        // Determine sensible initial distance from number of desired placements and mapRadius
+        // empiric formula comes very close to eliminating retries for distance
+        val sparsityFactor = (suitableTiles.size.toDouble() / HexMath.getNumberOfTilesInHexagon(mapRadius)).pow(0.4)
+        val initialDistance = max(1, (mapRadius * 1.2 / number.toDouble().pow(0.4) * sparsityFactor + 0.5).toInt())
```
Comment (xlenstra) [inline core/src/com/unciv/logic/map/mapgenerator/MapGenerator.kt:489]: Shouldn't this be `min(1, [complicated formula])`? As we later loop `for (distance in initialDistance downTo 1` which is difficult if `initialDistance <= 1`.

**Review by xlenstra — COMMENTED** [review]
Haven't tested this, but based on the diff this looks good. I'll believe you if you say the results are the same, and the reduction in generation time is very nice.

**Comment by SomeTroglodyte** [comment]
Thanks Xander... There's minor things like
- ArrayList.any() is less efficient than ArrayList.isNotEmpty() because the former instantiates an iterator while the latter accesses materialized size, so it's about memory allocation count not nanoseconds
- arrayOf(const, const) inside loop - will the compiler be clever enough to compile this to static data or one allocation outside the loop or will it allocate each iteration? I don't trust it in this case to be clever enough - too many layers.
- Looking where 'materialization' of iterative code is necessary, where is a copy necessary, is shallow/deep needed (that one toList was a shallow copy and unnecessary 'cause input always already freshly copied, and restarting that loop didn't count)

and bigger ones like
- moving the parsing of the temp/humid ranges out of a loop if it's not dependent on a loop val
- reading that distance downto 1 loop as - each iteration starts from scratch and does not reuse results from the previous loop -> starting as low as possible is desirable
- doing some stats in Libre Calc with inputs + distance where the loop succeeded and then just _guessing_ a formula that matches (e.g. using pow(0.4) because I couldn't think quickly of an easy inversion to `n*(n+1)`)

So these changes _could_ change results _if_ my formula guesses the doable minimum distance lower than necessary. Since river head / resource / ruins placements are not controlled by the UI seed one cannot really test, or am I blind?

Also - where are better comments needed?

**Comment by SomeTroglodyte** [comment]
Strange. Mail says you commented on min/max, and can't find the comment or follow the mail's link... Maybe because max is right. But I stumble at exactly the same thing every time. Thing is, you _can_ get there with small maps, such as the map generation for main menu decoration. So that part is tested, too.

**Comment by SomeTroglodyte** [comment]
But part of that complicated formula should use HexMath. `getNumberOfTilesInHexagon` and `getEquivalentHexagonalRadius` are already there, and by splitting a `getHexagonalRadiusForArea` out of the latter the set is complete, and that should work to replace the `pow()`...

File: core/src/com/unciv/logic/map/mapgenerator/MapGenerator.kt [hunk 2]
```diff
@@ -389,8 +442,8 @@ class MapGenerator(val ruleset: Ruleset) {
     private fun spawnIce(tileMap: TileMap) {
         tileMap.setTransients(ruleset)
         val temperatureSeed = randomness.RNG.nextInt().toDouble()
-        for (tile in tileMap.values) {
-            if (tile.baseTerrain !in Constants.sea || tile.terrainFeatures.any())
+        for (tile in tileMap.values.asSequence()) {
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/mapgenerator/MapGenerator.kt:445]: Wouldn't adding a .asSequence() here actually add an extra layer of abstraction without any gain? So this would be a net loss, no?

**Comment by yairm210** [comment]
Looks fine and mergable to me :)

File: core/src/com/unciv/logic/map/mapgenerator/MapGenerator.kt (hunk 2 above)
Comment (SomeTroglodyte) [reply core/src/com/unciv/logic/map/mapgenerator/MapGenerator.kt:445]: I vaguely remember evaluating what kind of iterator will result and whether it's the best possible one - for most loops in that file - but here sleep deprivation must have bitten. `values` is not the View of a HashMap but our own, effectively just erasing type information on `private var tileList`, so whatever iterator `Collection` chooses can't be improved on.

So - net loss - maybe, without any gain - yup!

**Comment by SomeTroglodyte** [comment]
> Looks fine and mergable

->
> complicated formula should use HexMath

need to try, but was distracted (by there being too many and not enough const's in Constants). Plus, spurious leftovers.

**Comment by SomeTroglodyte** [comment]
Like it better now.

@ravignir : "No terrain found for temperature: -0.3856287273971997, humidity: 0.18030086524055133" still could be checked against the jsons
Last statistics:

|Size|Settings|Radius|suitable|number|Old guess|New guess|Actual|
|------|-----------|---------|-----------|--------|----------------|-----------|-----|
|Huge|Default|40|275|27|4|7|5|
|||40|1861|44|7|8|6|
|||40|2004|44|7|8|7|
|||40|1542|44|7|7|6|
|||40|1063|44|6|7|7|
|||40|1392|44|6|7|6|
|||40|2235|44|8|8|7|
|||40|2791|267|4|3|2|
|||40|2526|267|4|3|2|
|||40|2671|53|8|7|6|
||||||||
|Huge|Max|40|29|19|2|1|1|
|||40|76|123|1|1|1|
|||40|129|123|2|1|1|
|||40|6|123|1|1|1|
|||40|933|123|4|4|3|
|||40|2|123|1|1|1|
|||40|928|123|4|4|2|
|||40|1564|743|2|2|1|
|||40|966|743|2|1|1|
|||40|1486|29|8|9|8|
||||||||
|Huge|Min|40|329|31|4|7|5|
|||40|2750|13|14|16|15|
|||40|3001|13|14|16|16|
|||40|2307|13|13|16|14|
|||40|1118|13|10|14|15|
|||40|2087|13|12|15|15|
|||40|2952|13|14|16|15|
|||40|3491|78|7|6|5|
|||40|3426|78|7|6|5|
|||40|3148|62|8|7|6|

**Comment by SomeTroglodyte** [comment]
To all subscribers here - that routine I spent so much time on maximizes even spacing of resources / river sources / ruins, and I think the result can look quite unnatural. Try a huge map with all sliders to the left and look at the ruins.

Let's think about maybe a 'distribution uniformness' slider which has its 100% where the routine is working at now, and 0% switches it to run with no distance checks right away... And maybe an explicit resource cluster group size slider? Not hard to implement either. All the coal in the world clustered in groups of 1-8 (gauss-curved around the 4) could get interesting, no?
