### PR TITLE
Fix "Translating" wiki link

### LINKED ISSUE #11543: Translating site bug
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.9

### Describe the bug

site https://yairm210.github.io/Unciv/Translating/ return 404

### Steps to Reproduce

open https://yairm210.github.io/Unciv/Translating/

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Windows

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Fixes #11543

I had some completely unrelated lints in the changelist, so I've included them here - better than in a more functionally important PR. Separate commits. Actually not tested in a targeted manner - but obvious, no?

That Quest code I came across because I had a "Great Lighthouse" quest in an information era start, really, but couldn't figure out how it could sneak in...

### CODE REVIEW

File: core/src/com/unciv/ui/screens/worldscreen/WorldMapHolder.kt [hunk 1]
```diff
@@ -917,9 +917,9 @@ class WorldMapHolder(
                     tileGroup.layerMisc.overlayTerrain(color, 0.7f)
                 }
             }
-        else
-            for (tileGroup in tileGroups.values)
-                tileGroup.layerMisc.hideTerrainOverlay()
+//         else
```
Comment (yairm210) [inline core/src/com/unciv/ui/screens/worldscreen/WorldMapHolder.kt:920]: No my good man, delete the entire if else

**Review by yairm210 — APPROVED** [review]
