### PR TITLE
Display URL parse erros on multiplayer server url & optimize redirects

### LINKED ISSUE #14432: Test Connection Different from Regular Connection Logic; not a good test.
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Game Version

4.19.2+

### Describe the bug

When using the connection test in the client for setting up multiplayer, http:// is prepended to the connection string. However, when actually connecting to a multiplayer game, the client does not attempt any connection at all unless the "http://" string is part of the server connection string specified in the multiplayer section. This variance in behavior can lead to users believing, based on the in-game test function, that they have correctly configured the connection string, when in fact it is not a valid connection string.

### Steps to Reproduce

1. Go to Options > Multiplayer  
2. Configure the "Server Address" field with the string "localhost:8080" (if your server is on the same machine as your client).
3. Click "Check Connection" to see that the connection is considered valid.
4. Attempt to join a multiplayer game using that server while wireshark is running and see that no connection is made from the client unless you go back and prepend "http://" to the front of the connection string.

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

Android and Linux, probably also Windows

### Additional Information

Suggested fixes in order of my preference:

1. automatically prepend missing "http://" to the connection string.
2. fail test connections that do not include "http://" in their string.

### PR DESCRIPTION
**Pull request by touhidurrr**
resolves #14432

>[!NOTE]
> How to check if redirection optimization is working?
> 1. set multiplayer server URL to `http://uncivserver.xyz`
> 2. check connection
> 3. close popup and settings / options menu
> 4. come back to settings to observer multiplayer server URL
>
> If it is working then your multiplayer server URL should be changed to `https://uncivserver.xyz` because [UncivServer.xyz](https://uncivserver.xyz) has automatic https redirection turned on.

### CODE REVIEW

File: core/src/com/unciv/ui/popups/options/MultiplayerTab.kt [hunk 1]
```diff
@@ -117,10 +119,33 @@ private fun addMultiplayerServerOptions(
...
+
     multiplayerServerTextField.onChange {
         fixTextFieldUrlOnType(multiplayerServerTextField)
-        // we can't trim on 'fixTextFieldUrlOnType' for reasons
-        settings.multiplayer.setServer(multiplayerServerTextField.text.trimEnd('/'))
+
+        try {
+            // we can't trim on 'fixTextFieldUrlOnType' for reasons
+            val uri = URI(multiplayerServerTextField.text.trimEnd('/'))
+            if (listOf("http", "https").indexOf(uri.scheme) < 0) {
```
Comment (SomeTroglodyte) [inline core/src/com/unciv/ui/popups/options/MultiplayerTab.kt:136]: Simpler: `uri.scheme in listOf("http", "https")` - or - actually more efficient: `uri.scheme == "http" || uri.scheme == "https"`

File: core/src/com/unciv/ui/popups/options/MultiplayerTab.kt [hunk 2]
```diff
@@ -117,10 +119,33 @@ private fun addMultiplayerServerOptions(
...
+                throw Error("URL must start with http:// or https://")
+            }
+
+            // URL has stricter validation than URI
+            settings.multiplayer.setServer(uri.toURL().toString())
+            errorTextField.isVisible = false
+            multiplayerServerTextField.color = Color.GREEN
+        } catch (ex: Throwable) {
+            errorTextField.setText(ex.message)
```
Comment (SomeTroglodyte) [inline core/src/com/unciv/ui/popups/options/MultiplayerTab.kt:145]: I assume you're fine with this not being translatable, not even your own throw

File: core/src/com/unciv/ui/popups/options/MultiplayerTab.kt [hunk 3]
```diff
@@ -117,10 +119,33 @@ private fun addMultiplayerServerOptions(
     serverIpTable.add("Server address".toLabel().onClick {
         multiplayerServerTextField.text = Gdx.app.clipboard.contents
         }).colspan(2).padBottom(Constants.defaultFontSize / 2.0f).row()
+
+    val errorTextField = "".toLabel().also {
+        it.color = Color.RED
```
Comment (SomeTroglodyte) [inline core/src/com/unciv/ui/popups/options/MultiplayerTab.kt:124]: Setting Actor.color on a Label is different from using Label.style.fontColor - which you can simply pass as first parameter to toLabel(). Is this tested?

Comment (touhidurrr) [reply core/src/com/unciv/ui/popups/options/MultiplayerTab.kt:124]: can you show an example

File: core/src/com/unciv/ui/popups/options/MultiplayerTab.kt (hunk 2 above)
Comment (touhidurrr) [reply core/src/com/unciv/ui/popups/options/MultiplayerTab.kt:145]: Did not think of it that way. This was originally meant to display whatever error the java URL parser give us, to show players that the url they inputted is not correct.
But then I added this Error to be more helpful to players.

File: core/src/com/unciv/ui/popups/options/MultiplayerTab.kt (hunk 1 above)
Comment (touhidurrr) [reply core/src/com/unciv/ui/popups/options/MultiplayerTab.kt:136]: was trying to write the js version `['http', 'https'].includes(uri.scheme)`, then I realized there were no `includes()`

File: core/src/com/unciv/ui/popups/options/MultiplayerTab.kt (hunk 3 above)
Comment (touhidurrr) [reply core/src/com/unciv/ui/popups/options/MultiplayerTab.kt:124]: ok i guess I like the current style better
