### PR TITLE
Fix for the wrong placement of purchased and upgraded units

### LINKED ISSUE #1371: Any units purchased or produced will disappear if there are no free tiles within a 2 tile radius
The player will not lose the strategic resources that would have been consumed by the unit. Gold is lost if they are purchased (obviously). 

<details>
<Summary> example of naval units disappearing </summary>
H4sIAAAAAAAAAO1d62/bupL/V4z7aReQC+vl17c0fST3Nq1vk7vdxUGxoG3a1qksefVo61Pkf98hRYkjipJpx2nTzeIAPYrN58xwOPObGfnHIvgahMFfJAviKJ3+8QP+fk+2dPqSJHOSBCRKrXUcLml0sabp9EeUb+c0+bB6Kz/zrDSLE7q8IrtdENE0ndr2YHxvrRNKshmNdyGd/hB/JGkczeIgymCo+3trF4fBImDj3lspPEQL+h/BAkbbs08yuthMf7B/0480pSRZbOhy+sfFOgkWeZjlCf3M26R3cfn99I+bIAqi9ed762sx0A2JyJomfDrYXMZmY7vM9pew4SzJF8XOf8zzIMxewj9L6A9tbmLYK40y6zYjyyDfWi9J9MW6ArLEiXVFk22QwcDWmzhh/xI+mXW3ob0PCVmE1HoXrDfZJs5Tal3GYZymFMb4ME9p8pXwthf/k9MlTG/d0GWwIGHvHZlbs3wOJOndLjZxHFofvq/iZNn7VxR8BdLBmq1PcfIl3cQ7axYnCxqSIOrdxd8orChOd7Ci0HqbwI7Z8MmWzXKbxYsvvdffFxsSwUJvd2RB002w65VLfpnEZLkgaSYGmpEQmlhAx8y6DJJFnvZuyPdgm6fW+xw2RpLeLCQFXeYhaxjCvMm+d7EgS7rdW++5LMF+YNshXZfbh/43JPlCMyBkAiT6klofdjQhvStOI7THt0xWep9IGFp3dAviw8hKsoRaJZs5qS5hzWz+nFP2lpJdnGRA9nnCts+6p5+tRZ4kwETM6ymIxIZkGYl6syT+kwIHggieQETTVBGKRtOp7U6sy00Aohj1rrO/yNSxbesdJUzqCgr24lVvFqTwzXhsXQVb+mfQK9Y6HTmMHxGFzmsKx8ThAjPbJ2QbLNm5GQGNFpsc+i/gf1Nn5IPYMmEFYvMzY9HvOziTbBs/xCG45advajuDe2sV5xGT38vg63QWh3s4jgGxgHphtmGjWWG84OyZ/vg+HVr7KZzTiB33qziKwzzM4Uju8lA0WcXxUow+hF2ir1zfSnd0EZAwSNm6xFKmLlcWU2ibxEtBbqc82lMPNpMFIT+B30Fv7KdDOJTfpyN4sgfVo8+fxOrEZyP+NK66jKtvJ/A04U/2QI7Dn4tObB6PP7lVJ7f22bCasHjy5Th+bZhx9Zlc46Raz6Raj+g8qXWeVJuR842qJzkgosS4GhtvS346qtYjVya34FVTy0X41ablk/wWTT2phpHbGss1yA+H95+tb6CV6PKuYm2dlCOFi4jdXq2h38paxBG3RoGJwgfP0vBBkkUSVZIF0VzHknFt3UOFfpKmBYE+F7fMaZdLoW7FlXKdxBGja1pdLlx19PgNgK4Ug2vkUxAttwGo0+r2aNwWyjVRXh4HbwuzK8FQ8ZtrewMtfwHGRRj3uGIn23YVX2839Uae1dT6Q9eBq38dkN5tvNsEZGr7Q2PN7J2imG2hmG/JNiatWnk0rGnlYV0rGyhhJslOJdN2JfuOPBqVnLvVZ151MsRnxQjV933ZvW9Xo+NHR6iS6mAVnf3q775bHV3Rz68W41cL5LrIQ9pfdnKqUymf7Oqp6CM1RV9us2guVQz6SgzqKZspluqwR6Fzq+27UrdW7V25XqliJEnt6kkuXNKl+EwqJNkP0c6Rj7acTCpaV+rhagpXo8d1MuHVnmzEf0+VAltLLVshTn3PrrJ7KW6S6766PUVKXEQjKTWj2pOnSN6oRm+vU3iAVECswpm4ZMYqHEXHKj0nebyXwS6Mt2QB3sw/4LyS6Q/xSRYsbuJlsApA8U1//BdoufTDakZB2U5dOBKyFVMueTrlX4EKW4U5P8O2FWcbmlyKGfngVpaAsmV8i3Nw0FZsaHB0QgIO2SLevsgjWOCLMF4Hixe86Ys79i9vaYGSySMwbq1lnhS6xBkJ/ZOvSWJl+x2dvsu/58n+v0EtwwwLCiSARQTnnGsXwHXTMhn8x3VsyDSfFNH+EB07jZKqKzh8gKWkDeUZKYSmz5/74g+uBKT9UEhfn4ufr4q8FBzReSIHkjaFtM76vuyFHotdSTkfojmlATyS6x7jdY/RukfIOJELalhyoqc0ohihxKHCx9NDQyO9K61XRAup+wTZ+7ac26lOlIPUlPzeQz2kmvbRHnzZRdrgkr4uWilmmTz4iOoumg2b2kNMnGG1jCFahrQIVU1ZDDeslilb9lV9h1ri+7NV76FeSAgwzUZVC6kH8b3gKrrOsbBZrSr4voM4U9+AGBQ1KBbgVQuQT/zDqt0YDT0pvpA+kiM7+WhUH6l2dNXZUjaciocKL+WO5X0tWTKuiI93LBjt1uUWc0oKLuKJW8yOe0+qmSbVOOoNxZfpoOkR69BZGRWjj9DoyDeqtlxsV7nIiuZDNIdqeBQaCXlO4rHv1UVAOtLDammC01I20KqlOkZHAnG5UDhCQDw0perYOYLX2OLBPPPRRkfVpCM0InI+S0Hx5UIb1gUaqeiP+YrVuGSXdKmlhMlzhuzFQlJcpJ+QTVxSfigpX6IidfWKNAu+P1TnuFi9pAmmlHRnVVCh2NsYjYtPlVR6SAZLHvhyFXUkQdpSyGzDWpotAs0oJUZacPh2xndb7UKrLVWiMvLCkGQdojVLakixRVxDBoX8VNyYyMJAF0whsEjcxclAe1CBpGI3aNE1cVAhnYK38h6WKhJbA2IIhCgV5MaclrfOUG4F80Yq6QnYgBzwcx3nUJhg2AwTOCP7cJighBY9zxbg4mA4xPjixHcr59bxhiyqwHq+iZP39Hv2Vo4IqxzApqM4A8t7UUU8SDFMi/mK4yMv3gkn/YJ3qXx2CXpxAGgRg406/UGA0fPp4MVg5PmDyRhWD384o4E/Hju+lcAfPv9iMGKhju/Z9G9/3ObzLUmAOp97G5L25pRGPQ4d9YKo90eJ0X7+GzDgiFVfBtlerJgBFhL6fcBSGZLE15hmJAH/pxfDAhu4ybEr7aRvYd036evButwJE0D8R4L+qOjLVk2TgrhR3GPubi+Le8v4xTkXWjgfv8FCC9/nN1hoYfo/2kI/W7uQ7GlyxxzPq3xLIhSZJMt4BwI+Kz/gxzCxbmiyIFEGG0i31ieSJEGc9C7jJbWYqxvwTcApyCjfD2s0Y0Ade7iMt1voTasH6MeAzwz1lR9VYCpDQCkbcwXKs4iwXSTbvTUjWRKzIKd1kQSgYxcJWeytd3RN+GwfwmDNUFT4iERLOKmvYTxqvY6yhO4SGtE8YQivdZGXXW9gNN6BO+0s+gh8sF4FoGR3IVNOVqneLxTa2GOh5C+F0vYn4wOR3esKl53+mIEqCRYh7c02+zRYpFPPGXpF61oE+E3IYqvW6xCIC1uHltaHXcb+d5tRsu3NODR9sYjzlH8KtJyzR2DJTTwPYII7Jpnwzcd4HvOHImxs3RKgNvz/NVwuXP6AaClcHkBamDrZW5ccaQYivSQhQ1lZ37d5tIu/LWHKNzRhEvEXZfKRsRAo8IyPtwCh2RZrkegzHzVgIgK0si4y1qJ3t6EcaCfRF9aTyQEcHusj3bG4LMPXe4xOqXUVJymdk8WX3sdgKZrOgT1LJhYw0YZuYYEw1HW0hN0nDBYuDhtD8aO/ilAC3zVjEL8Uy9lnmyCM03gHQsAWkGeMBpUk3hYMBVmEi5bFPWeMf9YNyWBOImgShMvUehnAgV3vgc6LL5SthYU3YY3w9DpawwNN2AIYHQgtmhZcDdhNZb3aR2TLpPUjWZIETlCWsa4oA4CHSaqNfAxWnH1sF3yw9+QrSD/f80dgLQteVCGLNwE/RtYlCWnEhodJgpixine9IWAy8MgIpaElJJIdCWa+rFkM+CsJRcj/04a1uYiCLfD8Kk/ncNJYdCIJOPcvmaLr3dLka8Ai60wywjxhZKGrJFjTAgazZiEpBOoiZWIds7O9IckW2J5nLLSTavId1DMDW46Y1tlExTZuSUZDduJT603OKNa7gy8fLT+iSoSgLNQD/CKFkmJUKuL6ZegGR7NwFPz0bAmDMJc+KeIiWn8B7f2JZOb5EZ2pEa+D1YqGosPLYN17SaNmVKyWG1DGyGR+gD5cJmJkKGr2PgZN3ntFti2RMxEyE9MYRM7K490aMhPZDN4YM2Nqgx1eI8N07B6RvTCuB8kKTLslQNYXSG+BGtM4D9siZPbQx1+xC0qft4AcCrclViaxrL5EmvsyHtJHeJl0+PvSd+xLjKTv1EdA4w6llyeRMwkuDSucRGBiBWSCvFdfDmDLR0c+urKtIx/RGpFLiTx5tDX0qSc9Q7lIBNmVUE0zuoRXqCedMqvbWICyWOdh8XeR3FWefJTBhdXXKWldzZSjFtXVkfFlqMxUfQV+8DxYghfeE5qrrqqOitW/p3m62HyDI5zRINLoIgMFpCZq/SOhW7i0z6GQXF9RQLZtHqW3B4NjNFAJ/nAV9DJPuc+gVUGu7daC9G5n6pRnookwctuv0NNyVfh5jMAhpKX6SPXUwNYmCIbQKjSTLQdBaD8K5dSAZoSU1VBT3B4Ba/0KGkV/DtFu8TOmQi2Mc18hyRKRR1EtBMDWUD0MpGFotAYuIyAVA804RtHHWL1W/WEmNmB5TC28sANM9NVFDpuUtlUO4HCVo5BQIW0DYa+jj+dQvxfhhmxBN+izKnXa+ahkqBnMS9Zgbp9sLh62EXny7HGpUQlzzqM5uAW9t2CyPyhXqlvhPkTRYntv4pV0Aj1bLmTqjhUd7JmnsI78YzRwGQznGvjvNI7+bM1edSbjmgoenEEF42ANTgaQ8Yt65AYHMnBKgVkAA6c54GATjsrhXAMcUqgFEnBkqBbNwckFOFJei6CjlAJNroEupDBUqYFDQ/i2wXvA8fVaZsMETTBBnSc6/YrJNFKf/W6mYHIP1X22kbuZZtC65dp2NHs+Rx6pLFK4ZUgVeNuXG7KjoSa19IowNIapngS0UNqSaqo1c3mKEmXqGRQMTUA1dXjoDU17R/4EH3pzUOfitHhujb+L86+JiS6+yucMM+MNe3cUpGMR72gth//Uwgahu3FiqKnT/pM8dd53arOSBZIEcdYrcExwt83tYtc7Si2X+StcLb8idN2qlV3Xq2ll21wrt6WzFufQRWcPub21z0vPGB1fbAfb+Jj6+A+c14UPvIOekYPdx1kVyNuu2qCPPDxPTVG4+A8PrcBFz16bj12uAe8Sb9xtbnxoug2vSQK/uTC84LO46LWqq1NNwWPT4Ztm3oPy3C95uKb3kYLKhX38dFtOEBgOk7qRqeOIPbMn1aceGOuO8egYzVHWIs32cbTeA+FbQb1BrRjJ9joVh2umOLAdI5/xyUHJGuiwixbItsCaoKZHSt9qUDPwsI0mntFHjny2decbLVK0fyQIDF/+8pTd7pcR3fewoD8mUt9dfvL4dSePcv5sdVvTsepE2cNx85BCq5J+U2+oVoROfdc2PqiTo9B3kbvID+s/CE3jjqPqjs3wd3PPS2aq9mX2IQcpUEIpgj1QUmqBnYvk5+orp/pmIptOqkYy67A9h5Nnpg2qx1H1dXnWZdO+bNAvExPLD6r8Tf4/zWmX68G7lMnFgiLnv2KVaqqDeuEpVaW1qQWsDSoV8eshlna14I0KrsCpKhkznbhNxeAPEYOmji82PHUdsaepM7DKIN5IKhEXITp+sQnWUlgC/jE+w/BYfVLVu+Xf4lYo3R4MatpkaF6F3A6lC+P3XiZolgsqzxaClRE8WgDMJU57L+skMKKNsHiEiwsMXaqO6kkm00uMWn6GQWH5vcDeq7+1YLOcBkPOzeUVEzbrm0ZVfVPBS1TbVBU8PVZ9k6yoeqQap666o7MXOXUUVLXUOCmcaosBuNUdgkNAIldZunWelFgFDMMAWM3ZxWgYRr2wB4hiwRj0wqhiK3rYCvRVIY99vRSp7pg3g0/KAUZRsGYYvOYVS5I69TOBQmDSfsCGOgp5T9DA2L9H/jSmvozy1z2DZpURuuhRHExRLjUXHieYI/lAzTUpAg2roub1N6wYDHnUEAptIRJOO5BJAzWgANcSIVCiNOZkSns1NJ4RwTiIf9i/wzEutUwJuXelyYfNvYpDioirZUhq4VLZFFHMwRRzS6NPEgMre1wqpdYsSfMVg9do68WXGNhG4Vx0t+HoqQzt4mW0G8A4VQPjRagFqmhCdm5NHSgOssYPbilfktcgcglwaAQXNZXVS/vy1kcFakg08CWN3ex6yROW2VIIkajhEKqUEazA1fKmWjwZhVtl2ROWu0IpdrzLA6fIoDooDE64dTriSK9UGZokARwXqUXDqsBLTZniEDISKiXzaY+vKiRwmphzW11SHVhBoXpZ3aQmMdUjZfIZs489o0XUC3/KidRyIWko4lsbXZmCuYI099oqIWS8qVkSjUoknCiFkwFwoAsHw8yij3ja1sgijm/hJAqURoajgThK2AwfVqVFk9FoND5UXGQ7zeoi17fAG4jSd3SVgdtUZG5nVSdGOtPaI3s89IYvPNsTjsVo7I1fuHatDGk8mLgvHG8sa5EG0OzFyPY7KpIcf8jSjjqqDW5jcEdpsI7AIX2TUBbIonSxKZ7vwMNjmfCy5EDE4GT5gFqDAOPCGBlLMajqENhYy3jbWnNQBvZEO4uXSLDhUOL4R/o1DvMij7kqSPhId9zlLzOgY2iftdYVgBsNBCdJUSMRsjxw8MV7H3OGlTMnOciKCTQVGPBHUNUvFKvnwwBV/qIRL3CY8bk/sqKHlOWAiKzwIqYHjeX2m3UZqJn1IVnD7v+iS9hzGKzZKLLGoqOs4hXdiieBMRCgSL5aJUCp9pIKli5WL6nwmcS01VSsgEUswZu9lq9RX4ESwKeuPf4NSivQin/DMguUe39MxUUjpf9nl2BUZRe4FuO5lmAo9RSHKzIOlVlUuOCMF53V3hezWnGq7qevKKP5mmzp9XI6pvZkMiG0P/eH8743nw/6czJY9Qer8Yq4y+FqNfd5W5Ac+DfjqIt2MHZ5LKf/zIPFF2tLdm/gwHKE5e717d3Nxcx+MWAfMy7kKSuahj94URxraEWxfCnoFA4XFWVzHBbZxKBU62+3Uovq4HaXzTiKBLQQ9GGtYJz3QNeEhNYrOKOROETVUflc4HY3ZDf9wR7ewbmDqeegRni5SRBNbxjqAg8wFf74Mga2wi2bBhXmKMwrpeEHOPpRrWFheinNymlQS91o2mYmc6pNdOvXtylqKkkEV0zG7BcuaDdgQ3BI2SsgKF68+zImoN3ib6AJBKQHxsw2Fij0f86KxL1gC5+K3nBaN0zVFD1rqyntw0RAWbztYWqU9rN2K4ZT2+rUnzagTVIjxjZm1jPWrFmjlX7ONs7h7X4AXfUNro7mTm20UWhlRGJ1visWdMHT3TDjayuuFr3k+IXk3LEAUYfM+JUdM5Nf2LjVH68SmL53/Zm//heLENoZu1FMpadBzrcJXOQhqH/lMIhioSwLwW5o24Mi8mXEqE4cPlI9o6prwOZJ6VhzNxvcgg03lEXEuA16Ha3ACIabznQBpa9YEfsWbs6dxe5lgcaX1/QZxMZhNwj76qKzEhwavShqxV/cZswcEVXgon4cHCe4APa9MqvsAu6D/kWQgDW9ynpgF4rNo6unLpa2Vi6dmlzeblis8fraEg+qgBZ+9WHFLKAOU/E1GdLWDqlXLyYzGy5QM1iLSmvR4I1NmCjSCsiHpiRImPBwA0ORLLsQhfJd0QlcDYzBHcfgs3XKiXPEiSuMZiRsZkdd0dcGx0wurHYBgtVZF0cjUjb5/P+nuOvGwIR5x+fq8RSFpgZljEW8ZF5NVgz3BiSSOeqwX5pmRlNdku3uefGgdtt/BQfA/BSc7bya2Ss8M2RNNRZLGWk99Uzzk1cbsYSQK9KAHlVtPP0BxsMUCLOZeigmNFouT6YpfDKVm3jJr/YN47u4Dbr55v08vjnaTbdeRY2WZ96Oujxbuzz9zWuyC8PNagZrue1NTRZzI6hpQBwlgmUkpCaDD7tqn5Uy7vJHOo2Q/hmuU45Cn3px8sBHtO7BgIoAelq9rE719zxah/S0zXu6vZ9mXhWu6SLOM2MtUeZF1K4K1SQ5fWOGB5IbLs111c4iBavcgBUHuN4NbJ3nQLJYzZZk9F7CZJVH0XEIFcxAex9jh/tfCfju+fbEI1dmfZ3qsNcGKyPEB9bWGAkf5kOIxWOoynYARM8nrBGvyBfCPcZXJFpQVR+KmLyJcDao0nY9eSqVL+MsayBcZoadbwp3tWiZwmF+S4FWoC8MYbDz2t1aO7pjX1pk9Fld0H4n6nsILjeyVIvwYO+CRVZD2oEntlrfWjPbPzEm0BCHNlis0VBvtDaa6Q1ls2aGczbN7pZNGBjeelSxBX40M7zdIwxvcyvmVAXgNC+hky14bfikYTA1D1KLjZOnYBakvaLcpaHYm0DQaRe7ieh9N9aTbda2SNM83eJuGiRluudhbs1YdVpaG+6fObjp+8YSsTTwdxGcGR46ztYu05/PYXL5ijGoCXWZ2m1nMgJ9BcDRrOgoUdB7Xg+zWmqm+BnNlYfferW7/GIB85DFXgM6ifzLwycCGZGHQrLnsHFuQ0p3pVUdL2kS9Xi9188wbcRb9+VJ56Uxj4rbnBlk7GC4r2W4IRLsK5RhWau/gAha0MFwTwYrefoSLJIVrq2WrIUia/2wVeZqCddqlpkM6WiH1FuOZjOXNUUmbW3dqMXkP5vn1Y8mnIPhn+JwtWPJnteWfFTYriOSyiBTmut9mBY/wcxE1Ic3jsqpchSTYEZJEh5OqXK1TsoxWLKRSaPdtXeGMIKnWp5FXeh5zPsjcHa9vYd9l4sw3waRIYbYGG7YHWFsIRrID8v2ffQEJbw6nnx9XChHNTDssxkYZTJY064z8n4MBUUUYurHO2NCjKFCvCPJmvIM8+vev8H0/26xcUmyZJPyC7GeV3N1GBJ+gAFS1rSeJaemlGiV+tg9uyQsX9BginfkC001i9Un4DzNaIbiRrVhCKKI/PFjOse7fqjapeN6K8vZlfutKBe7i68RDfquPznaox4qkC3zqJ+ET9ykgm+iuY6yHcriwu587IMX86/A95saqfWc4C2LH6OrNvySRPCfPgmmyYHR08nQw1Z1CzLyIONaesvXVrvnLH697sxi6atiqYlG/OJ8kKdB/uLnKw8Lr6cS1BRPf175NZ6iHD6xt0kZAgYNNrQCBmYty1cwGGEGhkPa5gu1DUfVDdj0r1u28X8efah+LPpEV9JWoMUWV/LZUNPRIjBmoary5Rqdsar24Kth4m17kptrbIlrE92aB987gOA8KrJ8Ovjja8GfB2UtHQ1jGArlJXufQ68VUC7fjvTAWgLVnqoFvnX59k2jk0T5SrxesWG0GuJYOgd71HCuj49+jh7iW5mF9kfmyZ1N7wcT+5hkvzaHe2QuEz9X5lXhLd9rdcb0gpFxPkv5HrLT7sWRAnkfjYs2l+IdEvUjSNC4oExl0T9lT9oEmpFiOBT2/mFE8jw45G1AWTGHdcHeN7LRAI9nR09+cihZXAyNC6F8gaKpP1zrLN7udJrcsc6NvppJRtpJnjuMMeLUO2hnt8FCenr+RqjYUNl/oz7BWIh9LT1aDUETkfXMh/R0Q3ZU07VMbwZTuQrROt5l8Qxcs/JFoKZR70bL50Mpu0P0VOzAhKDmGh33eb4M0MNgpqkPpsiYQCuOycBqnKfhATDy2bDsmLITfbaKUfCsPVvFsEZbW87dhG789mjz4dwS9/iLWrvYoRkQo4PSyryHchk3JJkbRd6P8KKaCTiGbpRRgoeWIqfZcT+tFn58euZKKyw51tYYHFFq2/rmjfKVyqemHnSiI+oWHoRjdG/hQUN30t19CN11x7J8c/zxEPdYp7dM1Wv5Uv7Oq+qo7L6xAtV/CgyrSt7BB3A3fdEs8AHFmE8iw6dTlIbHitIvreT4KcryCONLBwuOlViwFhRsQ3EM47HiHd6nHTvWudFXP89YO89prxb83asAxpxshzD/DtDajOYjc+4MtaM+rFDYP9JS5+8PVY1DTCZtVnlL1aM5lXxzKnknUUm14ye/M15zLvzBNWeQa84gp4NBqleM2aDJ7XoOTLCP0MkqeGHCkVNG14z8DFihh+MMnE1TfE4gQdwoOByCe8Ne6t9hdR3c9XWUsR9E2LE/YefdJQCmFuHxb6N+IiE5xzRDtaVE6mT8Tvz00ENAp5ZaM8MsWk91oszete1r4S5DbMoMJusotjDyy4da5/kIt1yb7KKWq5yc8WJpXsl1uF+FlxgFIQ1lYKwUVWku28Mrw7f1W7o1SJZ/iE9j8kL9yYn44ETBLY8qzWurRJyoglOUIp60uMOvHjuK/eVv051S36FlzmkoT/OMlL8gaM6Jp4nR6N4p1yInE0Ud6ytPOoCCB75NZqKFiR70NpmJ9oI0S8edKPiKDqr8Je+ibTMkJkdEDRt5nRMlV+BNnqRGrDCxvx/w/tqJ1vY9YtITf1mh+sW64/0f1rPZUQjdTynGq35Ir1MVmin85k6aFpn8xT1VYkgYxrk6cSvAbzTX6Ki5fjFKNSp2dfTLD6qfoHxa2xkesZ2n6ZKfN1HGP41LqjejHNXfDPU7L0k9PUlbfVDDpuJ3FlpYpTrVbYroaTLgrAlyJiRyfjsSPUJ+nAmh7N+OUOd6p9Fh6jxLyggw1yBM1P6rbRjtMP3VNsOEzn5H4msDeDSMIWsriluKBU1eVaZ9S1oLSmjyLixfVxDTjgqavIZ3qAMaD5vbIxUM6QTYftGPM44UEKgNsGsgh5p38polKxi+h0sLB9XwSsNqeS3G1+Ce9nzWDLm2d2srfqZp1s8vy/FpOrcGR0D4z4fIiF6xo3ekWXJb80U69uPiMHowQA+ZN1Zs9IM2A/WoN4XFVOIU0LNN6n7Se9sNk58KAhgm9LVv3ORV9k8EnSt2bAiRNuA53hsn2+vKrp/gfofdN8Uxu8dYLP8ZGBN08peQpOM9vgVVTi3t4L0Ny8eKmU6t1uS9z5KQd1wc3cRJq7RKR72k2D42lW+DECT1/rO4UKbeYHz/v1JcGxex0AAA
</Details>

<Details>
<summary>example of land units disappearing</summary>
H4sIAAAAAAAAAO1d63PbOJL/V1T76a6Kcokvvb45Tpx4N060sfdyV1OpK1iCJU4oUseHE0/K//s1HiSaIChBspzxrLNblaEpPLsbjcavu8Ef8+guiqM/SBGlST797Qf8/YGs6fQVyW5IFpEkd5ZpvKDJ6ZLm0x9Jub6h2cfbt+pd6ORFmtHFO7LZRAnN86k/Hj84y4ySYkbTTUynP+QfWZ4mszRKCmjp4cHZpHE0j1izD04OD8mc/lc0h8bu2ZuCzlfTH+zf/BPNKcnmK7qY/na6zKJ5GRdlRr/wMvl1Wv0+/e0ySqJk+eXBuRMNXZKELGnGu4O5Faw3Nsni/gzmW2TlXEz8x00ZxcUr+GcB9aHMZQpTpUnhXBVkEZVr5xVJvjrvgCpp5ryj2ToqoGHnPM3Yv4R35lyvaO9jRuYxdd5Hy1WxSsucOmdpnOY5hTY+3uQ0uyO87On/lXQB3TuXdBHNSdx7T24cGO6KFAVJerMs/Z3Cr7PyBojUu5qv0jR2Pn6/TbNF719JdAfEhFk4n9Psa75KN84szeY0JlHSu06/URhjmm9gjLHzNgMasA6zNev3qkjnX3tvvs9XJIGhX23InOaraNOrJvEqS8liTvJCNjQjMRRxgLKFcxZl8zLvXZLv0brMnQ8lTJVkvVlMBKVuYlYwhn6z+97pnCzo+t75wIULZgiEiOmyIgjUvyTZV1oAaTMg2tfc+bihGem941RDc3zLpKf3mcSxc03XIFCM0KTIqFMxnhPvDMbM+i85ra8o2aRZAYy4ydj0WfX8izMvswzYirkPsl5ARUYEJ0qA8CCtea7Jx9kqAvlLehfFH2Tqua7znhImaoJIvfS2N4ty+GU8dt5Fa/p71BPDmY48RvKEQuUlnbqux6Vkdp+RdbTI4cUIyDBflVB/Dv+ZeqMQZJVJKNCTLxSHft/AOmQj/SEl/4qvuKkX+g/ObVomTGjPorvpLI3vYQlGxAECxcWKtebE6ZxzYPrj+3To3E9hcSZsib9LkzQu4xLW4aaMZZHbNF3I1sfeAP/kD518Q+cRiaOcjUsOZepzBTH1nE2WLiRFvWo9TwOYTBHFfNl9n46ge3cAS/H7NIDHIX9iL0P+JEcnn8SvoarCHkd15XH9LqybEb+O68rjutwEnib8yR2oFvmzajLgT35dyW+8G9Yjm9SNT+rGZYuTRoOTemSq8qh+UpOWlUd1z2NtjOrtqJ62IoCiVFB3rQaBCB7Wk1FPo7rrSd2MmtZYjUG9HD58cb6B4qGL65q1TY6pRtVTi/GKdyY+Icb7DQpMND4EjoEPiiyKqIosiOYmlowb4x5qRFOEFAT6IraWw3YUoVHlPnKRpQmja17vKKewR8ZpjyslshaapMd1PtpWjFtJc+P4HCWLdQQKtN4vWvuDtjFU28XO/cFuE7BU9fb63UKvMyPF9MNF/i/Yh69oMYU3tFvnt3bj6dD3wAZYRqR3lW5WEZm64dBaWwfe+ABt7UptfUXWKelS1cOB21DVE7Oqbuhov0NHM0H3apF366XhqZVTLwO/fhfUC0e+Ey3Uv/dV9b5bt44fPalp6nXnI3Ut1nT9U9+vF7lsIlRNhKpCPWzeSqAevXr9qie3fhIFlU6RfSgV1FckUPPyleaun1DvSrUoJa2mLyqrX+RcAo1IopjHHoN6eIouopJSXYoriHaeenTV8IbqURHXV8q77s03KH+TpASNJxdJRaDLhmucq2pQp6xJ4BS1FddDfaaawPiIXEpqRo2nQJNHRWYkKR1yBKQCYoljxxkzYpnN5lRHLLX8F9EmTtdkDueef8B6JtMf8k0RzS/TRXQbgXqc/vgf0IX5x9sZBZU89WGhqFJM+5T5lP/kpMWKZmeyF96gU2Sghhmv0hJOb7esOTgGxQROa/N0fVImMKiTOF1G8xNe9OSa/ctLOqB4yqSYus6izIR+mUiVVC5J5hT3Gzp9X34vs/v/BX0NHcwpzBrGEB2xq00E21BHX0DvX9Pq7gsOK7yzizu2fT/tvKq+ttHwaPPyfuK8PIt5fXngu3/MtuSmYaz0ulAi/aHS4M39Fut9pdiE3uzzrQcpaqG5+vy5r7S+UHt9rvdCXdcqjSVrT1RlZQGrs0Q/VLXQozKMRT/qvDVCYx2psY7xWMeICtiUVgNqnTtkTWXyM0JJbY533AB1jzZ8ddZCtPD17bbvqr69WpV7aKtUvweohjIVQjSHUFWZoFEpCisGY5YpAiOq+6g3fDAcYuIM62EM0TDU+UXfokVzw3qYqmRfEdRXs1CH2Mqc69xwUS0kBJhmo7qE2oCxbeJrm6zn4HOcbmL1PcSZ5gRko6iAGEBQD0A98Zd1uTFqeiJ+UCd6T1UKUauK6SGyLpDhJZrjPNR4qWaszDxFchfVVoySQ/Sbcos5pQQX8cQXvQ9R7Und5qRuRzeNkO0sBoJYh9bKSLQ+Qq2jk3w9ZTHdetJKCQ5RD8rOkwQImoweIy2Fzv7yUXQ+rIcmOa1kA41aqWO0JBCXhcKRAhKgwegwRIWqYKsbcy9EQxuhdhBAIh89KUZ1pZE2ZgXj9BXgM0RtYg6rCWLVrlg4qttFxwwhKT7ST+iIVlF5qHhSYXhN9Yo0S4Cq6FCOGDOWGx2xUhiOgsDEPPCegleVUnpIBisehGoUTdxLGfGS3KIo1tMj1KGSMCUwrJ4oMlbjU0iXUM6Nza0xbIUnKp2jtmkdQWvCl4h/yLRA/EA7i5QvId1I3KWUoRnosKeYARpoQxyUPIaIt2ofVopxjPqQTSD8UxAbc1rNfahmhDmjCDYBE5DD05MgHO/yZI1anizXdYPdrqwKXnHdiSt6c4eud+KFDUh8EE5qxMVzhz7zf7H652n2gX4v3qp2p743gLknaQEnv3ntmiOioQ4jFjvyTs6i4v6UF+fYlEL+H5x5Cvbp9AcBJt9MByeDURAOJmMYN/zhjQbheAzjzuCPkP8wGDFP3Pdi+jeGHPZWJO/lBcngJNtLk95vV2JCX/4GFP81vl/j+zW+X+N7meP74mxick+za4YNvCvXJEHxDWSRbqDKrHrx22eSZVGa9c7SBXUY8hDxwc6ytKB83FG+dmYM0WcPZ+l6TbM5KgkVmaOkQJ4W5h6hrIVb2LmEw/00W987M1JkKYuC4LUpCx6A/UTVU72/jmB/2sSw9TnMN5w5l9ApSYqID0JWYI/nZI6HpQZzCj8X6Twj83vnPV0SXvFjHC2ZEwdekWQBhHsDDVHnTVJkdJPRhJYZ972fllXVSxgvr8CHUTf/xak27VONnp4rt+6zytPhujtiSi5qr8/0x3nJKvWu2a/eKBiLgo2wk/OYBXQ4b2JgD5AzmjMXVsH+c1VQsu7NuC/sdJ6WOX8LY75hj0DWy/QmiqF1Jr/wy6f0JuUPIlbFuSJAWPjvG7AUuPQCmXKwA4CY0HV275xxDxaQ5RWJmUOH1UUjdt6WySb9toDuz2nGmPUHZawrWMQFyARvew6EXItxKRcX7yFiAgdtOacFK9G7XlHu5SPJV1aT0R6Wm/OJblgYCHPu9WYg/znwJsvpDZl/7X2KFrLoDcjOgokddLSiaxgsNHWRLIASGfNGieUJUy5ozIQgZ97E5A/h0uTEYCzjZk81kNkqitM83ayYJMP05mwAq/tcEnlTFoxWtTTLBQnrAGwrFp8xYyx2LkkB4yGcdm+ZTxZ6jkATLO+BH/OvlI2ThWHA+OHpTbKEB5qxETEaESqKCu5HTKU4r+8TsmZy/IksSAZrtShYVRSexN259cw+RbeczWxavLEP5A7WBafHJxAB5lWtfannEV/CzhmJacKah06ilLGRV70kYCVyly2lsVNRAxYys1uBEavojsQyHunzipU5TaI1yMO7Mr+BNcjcplnEJeOMqc3eFc3uIhbkw6QmLjNGFnqbRUsq8E9nFhMheKc5E/+Uh/UkTFmtEjGm2Ypka5CQsmAu6NwQm4Vk9skCtOpILMr8zMATIpQgo4QII6r8xtiVjiNy9gnX2tvHbo7BOk2WX0HNfSaFfTjW1kisN9HtLY1lhVfRsveKJm2XfCNOqXLQq1gls69eOuiRy/5DCnq895qsO9z20l8vu7Fw21dLuDsWS0RWBWPMjKkb+k0yTMe+vW9eC6QSXrMOt3xfAvnCI0DTMu7yy7vhEP/EtilzCJWFX76vYM8mZjmscSmJQQqICqFAvnr0FLYSqEdfoVOBekTVENw1VGd8BOV46tFXR/VQvdVhyL5CjfthcwgIL0AwjauGi94G6tiv4E2Ex4YSh2v7rNGoEGkxOfzmxL3WbH3jCNG4R/rEHhUrJKNPK82AQkyxenuKuNNatW0JQD1awOl5mt1EiwWFwQhd11Rue4UWfaBlPl99g0Vf0CgxaC8LlaVHkv4jo2vYyo+hwvxQU1muax9P5LqTfZRWBQFyrfWqzPkBxai1gkHQiCYKtwZ+BlbKCzkoMK7fr5H12rn1UOPryk+BfH0Ilm4gnH1XvcZ+Lezr6SNPXr+ui/5EC7/hrcEoehtR7yN0tY+9iYH+HnsNhi1YGcGuiCxoXmgqeCYY/8TgNnY2tID1EaIOLi99N0aN6el0cbfTDtPL0+e/g0ahPngDO1ss1wXJ5HFpotHHUMin8YqsQTeYY8JN+nqv2M0Z9EuWYIQfbGDu1rk8un+/SM6MHeaTGzgs9N7Cee5RoZ3bFe5jFC22ECdBRScWpyIHMvXHmg4O7APwXd/bRwVXkRJcBf+dpsnvncH33mTU0MHBEXQw9lphTx6OFMGuPOzawrEn2J/V7cXCMS7Y04gduDj4BPuYGp4l7CrEERINVx+OQsFhFjgOpRl8Mm7VxrPGzj3sK8RaG88BB1w0Ql3wuCeo8sSkYDGZWtwKtzNlqFMGz7OL3O24k84pj/XxGMjVmLKBLscIlVfJV1cMDIND/NmKbGhsiJ5/RxiQw/RTBqoq7wifN1rHPKCSMh0OWohmoL+2HPxb6via/A5H89VOxYwzf7gR/z4t7zIbhf2uvGFQHC/Yu6YgQfN0Qx2cpnRoepZU8DjO3RYL+EkAAK87dScwXZJFadETUOnU9ewP/IE/3Ed1V0FPXHW/JnTZqbn9QePM73v2mrsrbUqsPRw6iM6ijffS6MFLFttcLl6mIf4DBwNipeChZ3RwbwRFoFN8XQa9CnA/jXg1H/8RoBH46DnoOrtXY8CzxBP32xMf2k4jaJMgbA8MD/goJ/tGNumh9uLxU3wemc1zxr1CvU8UlDC0f2QTsKnlug1BSXhYZPp0pp7XJsI0DCSB2M/aKX3kWisafxDso2eq5MzZfZos74FNXWoGKqJf3D3O6N1aBhtG6hkvMxQOhDSDLIGMA6w2GkqnOqENGhYjNvrkM3rlqWfXpAzQIGX5J4LZsKWgluTV/SKh9z28Bp7SW7BvRt7Tp+Id9bxWLVPXsCRd2Fq1yU7H+vHNHY7bKxxKVXSeBkM9WX4a+vYL2tXT+LYvaBlGyxf1PwjN0+4l7fqNNe0NHn/mU0HTfRRY66q3Ksa4j8oqt4KMw69/8upfJqropC6kQodN4cRVfKPTCHDVA8H76mW/etsM6BVvRnUP8JtBLajx4FmqOHedIiNMnONv51oq70618pyyert0CFYdtT758zEfpUN0bRGMBFdgrVWMmU78tr4Ih4hBUy+UE2bWvJgTW52VH3KkdIuPIKZQTIKVlIZEaH8+CfdWMnWicPkt7YT23bCRKOyODnZI1luuq3bfCtJ9UKHE1dCqkgitFaB+BRvL97VWUAA/BtnV7+qpGXH9Hf2NYGj5Uo0J/aaaMqLeaII+mqtqI2h142B/p2fIAh3VWaCCsSgDtE4LPWYWqMo1fZpM0G15jMfOmfwJqYX/ptOyyc48dibotuzMo83LIjvz2JmgW+dlzgT1a4Ol39JMOE4DhVY0EBJl8GD/msGPhqFgDB1juBhDwRjyQEEVGAluwesmSL0L/a70tdoJMABVexLV6a/t49S2EYQ9t4NbWrBXGy1TbSArEYNf6DUGyhsYl9PMi1IROc3TbTsXE9mgyFONNji80WjRNfgIXvNbN21RddxqA+ZqGb4Y42tAcsZ0TRy/g8JcMDKGEQNXe682ygCdM/qKJ7hzxEskDmPEYezsVQcV9SSyN7EvBo8rVFKqTihI8M2pnlWBB3w8aQCbCMtEuZqaQx/FB4mDFXboiGWhpAZ7u7HDvXk4qyiBPUNYHLpTPXEcU6gRFp3O+o2zlzqMmUEeA5ZjjAyo/4PycRGbGiacwnxwYIGWPFqJEBJHVUe/2MsisRQHGSD70pgEigLZ6hCEpjoVvG0ng6L8T79JdlS24cZF3SizWYbOaKmc3xuhfVqEm5A/vImMcTcDRBElAIaYlo48T3NGZ2f2ZhMcDJoEQqEs7VTOJpLotA8LevCPFnkjNyME/EsN8WDMkcRCikaL8okRuduBS2hYOOgF+3mxL9jO+d4KSdKTQ7vd7djpi0OLUFwj9vliX3Dbp14nYMLJczge7krBdIN2Dqbn26dgekM/9E4Gk0BeSjjyA//EG+HjrBuOhuEJG0t1rA09d3QyGXjbUjJDl+dkbknpuUrvaEajZVLcO+cZZb5ZytIzGqk+/IfrVVqyZBKVeSN9zCqRRk8Egk6gwYLF2bSzgliji3TdmRNUebBlOYdnJ7EWULbFJ3qXxqWI9a8Thj7RDcebqiyBFMozVAfnEbF8Bpm1szWj6IoCj0T6EHc0w+TuaO9TyfxDDL6JCtG7KfOIZlHR7ARnIUFXf9CEpxDN+Pg+sbSinEVNyewK4eCGwopE7dwlVMz5mC2BQn/QBdAljpasFZXFtCVx6TVdyycJghGgWnl7mwE1u7OX/LGevTQYcVnblJvTGFjHjg/8pMFyJ1RWknNH4pJOUV4FLLaupKdbYD4rkoP6/JXd9Cu7qZ3dVGc04TSnX9lNR8puqrHsGU8Tbdz+dnvLqXo/fU0ZzZdkTS8W0zF1J5MJof2bcHjTD25uBv0bMrjtD27Ht8RfDG9vb0JeFiQH/i04OmhsjO1Ei+k/y2j+1VmTzTksWI4KXr+5ur48nbknA/aacaHM2e0T8AdPY2UFnSRVd4GLCzNFoitHUVYp6NnmXZZ6GiwYA6oYRzuBFpI+rBS08wHompHYeQ1rNJGLqF4qXwTmfEk20x/s4T2sO+j6BtQIz/KKkuklA2ngAbrCr89SYCuo0TyqgXJptWkFP8LSTxoFhSmnFau6QSVNrRmL2fSpFzGN31xGJD+TBHadghlDXNAuwSDhbpBAIFY8gflVSkC7pd9AE0joGUyjdSo9J/89E9Gv0RreytqwWldM1YiajdFUVmwmkS9edjc1KkvcOBXLrl29688r0Ca5FWNbPZsZa1esVcrcZxfn8HQ/gq76BltHe6YumiiUsiKx3t875ijE3V0ys2wttxaz5IRCci7BdM2SHvdibZOdsDZxZuoHF5f67XUGw+hdfOHX/2NRQjNkO4utFLXI+jaDDT2GbaAx18pv2RbfLQ1sp40vaUOZa5XbihfJLdissP10kUifdHVIq2d+BdvZxmGbpXTlVHvnEXjpMbXOfjrdeo8CFDoRNy2cXBXMRpD3KMjbF+BoBFr5vleFQp6Cku6fRhlYvbdFD4w1OXm0HzRlxDUKidcQkqsVc1pfXDjyQZcWcYrdrS0l6mErSzZNusYmzWvepmfLARoa69AzHWq1NQkb7VZD8FCURBkTHr7ra5IlPT3VZxoy0NeMwVuWwRfnkBU3OBn57H9etfSESYukbveS89ra1GK9mZXKOdiETbm0ommb4b+Ws60ef8/76vGgl7YqZYxFvGRnjkI0dw6iyU7WMF+aF1ZdnZH15mXxoLEHM/fmYaugdkseuq649DdarBDMenig1HQryLyIcDMClLVboqJDq+HyEClxatEpiof8+r5lnnZtWXaD9EzT6dqyWgXN24dNz5YDNDTWsWXZ7rv2O3l7F9yLdRUk3+Dd47aJF6VIthnVu1XHI7eC4OERSp9D13DihAY1AQyM+kzv6u9lsozpYZMPTHM/zDQQ0TDztCysDaPKjd5Qsfp2evjELBck33Tb42qsRQqmpQUr9uC6cafA57J/ZXDEK9eHLndra9XuDH3GPE2GM3QVAnTo+bHRWOWK3EGDVkt4We46QD+F0us+j5vVHibsO/KV8APMa8Iu9dPoK/3ANmLWokrXRhPoVD5Li6KFftiZNuFjlG7fsnaNUb2oDS3cir/tBVx6Osf3wUxbTOoy91oFzaZXq5jZ3LMrZtln23jsmISF+WgGeDrMajvz0d/DfGxrTf0YJZXmwbajERJubdVtkezYXcu8SNd5T6SdtBRR+/h8mEKxEZfv1hqny86TkWqH7/ptRVhFvO3m1owlj+WN5v5Zkiy7bw0RSwO/f+B4Z4YDrLwqAvQYJkKoGUkG2N7WzjiS0RJqR27DiPYSBbPN39nidi+cp7xwW7HRA+Xg6c1LGZC2eyUgY2eXe+kYVsJVTOnmodNT9aTGgfwUg1rhPAPhSZECPk8R1gHzLGBR0C0up06WGzVDi7tb9r2fYQBi1nZM+VHsPZ3DuMn8nnFYPZsMf8xkFq94ZH4eb/XyNMwl7ToeWnLYYuTPf/FKX/OF0+F0FiHPRuNx+9SDYy3CDmFssc43sq7Tfu2YVPsc0ipoNrHteq5yWWzKuqZWRec/W+quyps1yZhGO4LIfU7j2w2LGrxw1KPGTxORdAbZ0tx82Os4UNnZ5WYPxN5nXGyHzSjJ4t2xOb7xNLcPimFlRxpnHRzBaxDo5r5IHz3OmWoPWN1sZOMD42lcrqPEEtBsNTfc7ojrIBrIDwsbffKgGjw6HsXb5bnZGtFwbC1Txb5estjXeKeu4VF4z3NYXbEbulnsHs0sNgZvDa3P6pYrTOZZHiAr+0W/WO4k1yRbUh7jfdH7D+j+Px3WLskWrFNuIjQZ8W434L6HrWk8+3kPx4mbqVSBTn0MJpyRgl0LsruL9+QrzQ2DNQfZ7DqiH3t9NU775mWlnfi74C6ZFP54x9fxUQr0KZ0tRkGVlK5ZBQ6MOcmv0wtEg37A7rXYE/wZajg9A3/+veAb46IMbVTgXtZblWy4PbR6p2n0ZziI2lTsXHN4yvLTmvWEX5EE/m8RrSPzIJ9NON/zwEvk1z2PLJahLpYGx9mfHIDzPMgvPuW7W3gDnaC2bqSXFdAUaMrhM7vMbDd1faNq6IRs7EpWly9YoTaWTbr2A3UtWzU12EY4Oqbxb4//SNRmH6y9xbDh7sP8i6GmZ8TA7Dy01bUaW1203XEClhHC3VGFvrVVb4wsbC/8YAeG9pO9EVsw7SrG7jC8LjTidY+KRtsbebKUYulP7fJCVBcpPTJTQTfAGgEipmj+tpVKkvJWXgfasnItoUfT0X7UOtbvHyUweszBzi4EZmQffts+LmFi7xMs2nXaH9nLxM+VeV14q7u0jhiGM7KO1aquLDtsIx1pXoqtULYVOCAwwLcUSEdiW4zADhh/BExQXU63fRHuwZzWXmu7SsJDHAfGELiRZgOJo8tulPY42OxVRJmH3Tllt6CsDGDs0UGlpxWOof1hvVFZXkX1vA6Nz+MQzkjTooyBhCMjCV86gjTi1Nt5xOlC5MY7E5afgR/tL+Hes/IqPSMkd6gJTiuJyVq3hcaF2XkWsVnrgX2TganJLamqHd13Q6svABfwNVnYckPMC6BGdTeubQhQq+TLoZS7ZUXpMJ4NQe13eFzn5TLAjEjbxoHZgtQSONwnILa1noY7/AIvhmX7pBCaQ/es/NjdoXuW9zoYr4Boo6hhdwTJ7kA7f3/7wzjYoR3EaUK1q1imahiXJLuxiqbZAwVoRyNawgBWQVtGipi16DEhbZsVUUfYbznAsAuRD6V2p7dgbMx42+PKAXtk8CemJVTXsh8a2bQV/9TJ9yiksvPyoepDB4c3vZXn/mN4blIP1bcj9vd6jU3601bNV9/l2Lpl7hVyPda8d58jy/zK9/AC9sivhgFu2cWef/TgVjka7itHTxUR1ya6pRVmci+NtfgMI7q9R1bP0ydSju0jLqob/g9bcaxyq665n7Gxn8PuDP2r54WNOdl2OfS2eKTsaD6y587Q2OovjIfbyJhVxkyjjusH7DkV2nMq+MUpM6cCjVN/OTTuWOiSby93vr3ceVvkTsc8MBsMQbQvgQnu0ba7w32vriV37UeK67SqvAC2moHbJ+bqowPhbGFkCViOdjo3+dDP2RddttjlO0l+kRTsAzkb9ieQfXv2me2ZYf9PETyTy08825yGjrTmg2Fm+YG6x2CjHfnhlnkXgX7GtvvQQmhEZS0hVDs0d0uenxVsMzRiK3ugNsZoRz1TsjvksblUhLqkrLD1adqgyR4VCWT50Qj9sNS3yC3fS+bGWv6wwUrZPTJs5ryla4t0rsecs22+3jI5EDafaHD+Xun7e6Tk/SRdOtGXiLgo4SCy7L6ldS/Bq77Yekjuo1EsDoM7n9TurL/Ray9PzxD45IdTPZTWjBJPtB3MnN65BX975E2FEyP2um+I9E+6F8zSazMxGjV2STcTDbE1eR/+FMB2x3QtQxJa6RgTLRDpvMxyK2mwObJJIpyt4JSVMs6zzyrupwo6Ik2ah5Tq67J7a2les11RispPcTHUn7fdqortNpz2TAzUqr+Dq3OZxHFa6h13etqs+hrt1dcvJFIk+gx2gcYGSg/NS+AXScV9P5YkfQHkqD8a/0tSTJcTaJr4L+YHOK6kBGZJ6QRzLIvK72F1SKCOTnXtM8+TAUcNiLYhkfeXI9ETxEPbEMr9yxHqWBd67qbOi6SMdMlY+MO7v32LYTzbb99aBvD3tyQ6tBB8y4Ad42UuHfc0POby4QMPfMY7jzvQe5t7ZUNTPnA3Wm/z7Y+hyQGw+3A20qG7rUD0n/TF7JEGWXYB2y2E3fBRkd2UHJsg/T3Aywaub3nvkRELb3HPuNwbdmHXZ3Y0VOKvHKzZormASiyWiERjdpEZXcxohmVYzHL7+kXXdgBmd1GrF6vvOw705dsWAFsp0mB3S0kyqqc9riTgLdh8KMrQryXA3EIWeW2chGS66KWz1+F2RbTPGDCcyz/QZwNvHhnjbZmtgz1AW/NatEzBFT3tcxFCq6efHYv0WEBcTBnbZldRfEezhy9SpUyD0eTh/wGtdS8lX+AAAA==
</details>

### PR DESCRIPTION
**Pull request by JackRainy**
When you buy unit in the empty city, it is expected it appears in the city; or when upgrade unit - it should be at the same place.
Currently it is broken (most probably by PR #1993 ) and unit is placed at 2 tiles far away.
Even worse, if you buy the air unit it sinks in the nearest ocean immediately with no refund :)

So here is the fix + performance optimization.

**NOTE:** Further investigations of the changes in the PR #1993 are needed since there can be other similar bugs in other places.

Upd: Also it resolves #1371

### CODE REVIEW

**Comment by Kentalot** [comment]
Oops sorry for the bad code!  I'll look at it to see where i screwed up!

**Comment by Kentalot** [comment]
Looks like I accidentally changed a call to getTilesInDistance to getTilesAtDistance

https://github.com/yairm210/Unciv/pull/1993/files#diff-acd571b4a622cbdbdd07304dae452559R142

This would get rid of the current position i guess?  That might explain the bug.

**Comment by Kentalot** [comment]
oh and the search for firstOrNull has the order reversed whereas the old code put distance 0 and 1 first, my changes put it as distance 2 first, then 1.  So even with the update to In, it would still fail.

**Comment by Kentalot** [comment]
I opened PR #2009 to fix this (without fixing #1371) since that is supposed to disable purchase so shouldn't be in this function anyway I guess?

**Comment by JackRainy** [comment]
I will finish this fix tonight.
@Kentalot, never mind, it happens. Please, take a look at other places, maybe there are issues as well.

**Comment by Kentalot** [comment]
Yeah, I looked at any other more major changes.  The main part that might have weird changes are bombarding targets code: https://github.com/yairm210/Unciv/pull/1993/files?utf8=%E2%9C%93&diff=split&w=1#diff-2f98ae60072d32be260c40fe317cea64R280  I looked it over a bit and it looks like it's equivalent.  But I'd appreciate more eyes on it.  

Also, my fix was merged, but it is still slightly less performant than yours since it saves tiles at distance 1 in a set when it could be the original tile that is already valid.  I didn't add that fix to mine since i just wanted to make sure the code was at least equivalent to before (and I don't _fully_ understand what the code is trying to do so I don't want to break it haha).

**Comment by JackRainy** [comment]
Taking into account that current implementation (even after PR #2009 ), implementation before the bug appeared, and this change have the same flaws:

> This change ignores part of the code that doesn't allow units to 'teleport' to further tiles, you'll be getting units in positions where they can't get to the city :/ (eg lonely lakes, or beyond mountain ranges)

However, this code is simpler and it always produces a unit in any nearest range, not only within range of 2 - which was a bug #1371 . That's why, I suggest still to merge it.

**Comment by JackRainy** [comment]
The issue with the placement of the units into the traps is fixed.
Also, additional notification is added for rare cases when there is no space near the city at all.
Screenshot 2020-02-25 08 52 31

**Comment by yairm210** [comment]
The wording is important - "No space available to place [unit] near [city]"

**Comment by JackRainy** [comment]
Screenshot 2020-02-26 08 55 36

File: core/src/com/unciv/logic/city/CityConstructions.kt [hunk 1]
```diff
@@ -293,9 +295,17 @@ class CityConstructions {
         builtBuildings.remove(buildingName)
     }
 
-    fun purchaseConstruction(constructionName: String) {
+    fun purchaseConstruction(constructionName: String, cityScreen: CityScreen?) {
+        if (!getConstruction(constructionName).postBuildEvent(this)) {
+            if (cityScreen != null) // it can be null, because AI does not care about popups
```
Comment (yairm210) [inline core/src/com/unciv/logic/city/CityConstructions.kt]: There's a mixup here between UI and models
Purchase Construction is a pure model function, and should not know UI
If you want to conditionally popup, this function should return a boolean

Comment (JackRainy) [reply core/src/com/unciv/logic/city/CityConstructions.kt]: That's a good point. Thank you for valuable review.
