### PR TITLE
Fix problems with stats from tiles and improvements

### LINKED ISSUE #10868: Stat on tile unique doubling on improvement tiles (again)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.15

### Describe the bug

This bug was supposedly fixed in the update 4.9.13 or around that, but it is still here with us.

### Steps to Reproduce

1. To reproduce, you can use [this version of the Latam mod](https://github.com/Caballero-Arepa/Latin-American_Civs/releases/tag/Honduras), because I'll add a restriction to only improved tile to the unique, which will fic the issue for me.
2. Start a new game with Honduras civ, and settle next to a Bananas tile.

### Screenshots

image
image
image
(Unique)
image

<details><summary>### Link to save file</summary>

```
H4sIAAAAAAAAAO19a5Pbxo72X5nSp32rzJR4J/3NcS72qeTEm3E2H1KpLY7EGXOjEWd1cTInlf/+NiU2SUlEs3EhZZ/Nnq0kkobdANgNoIEH6D9nH/PNtijXs5d/ztb7x7t8M3vpv5gtNnm2y5c/F7sP1S+7/I/d7OUs+CL9wg1nL5q/TEP3r7/UXxcfi1Xxr2ynBtrOXv7yZ/XNP7PHXD3zZba5yzZFpn54ocZZ1OMtPmx/zLd5tll8yJfqkdmrh02x2K92+00++1WN+VSuikWRq+H+PM7wWo292+wX9STVt/+7z7e777N19lARU32zyVfFg/qDky8fytUyX796OAw22+7KTb58kz09Fet8q77ygupvKobf5eXTKj8+lG+f1DhqkJOhPhYL9fjz6Zz7Yr09+WaXKSoX2erV23qsP55W1aQ/5g9HUSuh/Tl7WmXP+eb981Mlpjf7x2w9e9ER3JtyvdxvMrrYZtsP5X61/OEpX7+rvn1+Vyx+q0hUUsxHlqmbSMv0aVP+UTwWu+dqvvfPm0pEr1flNlfy+TJfPWyyZfXVN9lGffHtXi24rPn4rlrj7cfbcv3wISuaz//IN/tttsofm2++Xj+ssvWyHS9fl53nn5fr/Ln+2PO6F8Xu8AbUPliVi8OuqIj+Qy21FzP1nOupPyqq0TM39d3Ez50oyFwniO5SJ4vvl04UR/MwiYNFFiyr7XZcEe/zh/22eMhWT5n68r7cr5fF+uF18fFstew361eL/90Xm2qJeNWaeNqvNBlH+p7P3/zsbl+sdl+qf1RjVsTP3mWrbHFcVWoBqw3cDKBXxNlbrRd/saqZP2H48NE9fnTrj/7xo19/9E5/9U5/9XuH8v769cXs93LzW7583524+3Ox/WGj6F1nq9fZU7HLVsctoARRrtf5Qum592X9y+0u2+3VILPqD2bVw8eX+fqoDw/jXuzm2a58+i6/39Uv2QkPc3uhEsZduduVjz8WDx+aX90jX3GlOFfZdneb5+u3j2p5f8wf8/Xhzxbq+4qIRfn4xX6t9ukX/7Mt11+8ybYfvs+e/iuv9oun3rT6881xpXWZTisJ6SH+J/uYfaHW8sMXt+pv1w/qqY/Zal8tp1dqZDXCzWGvVbyqQRCPN4r9Jl8vssenA/HHUc5evMVgr9WSvFmoEdR2/+vXasl9yLZfK9v0w+/rfAm8vq16Wds3RaV8DlrBrf5xO3sZvJj9c/Zy/mL2+vDPd4d/fnv45/vDP79R9CUvZm8Usy9mPx/k9kr9oGb1uEMcNHulHGcvk6421xqlVebbSvqL/If779QiSN6rTVu9yOBF8GLe/u/XF31K//tifRTf+w/5zc8f8nxVKTm11HIlCEXIunjMVjdv9ts7NeXxq66ZqMd8X+pRD4akGl39rf717frdplQafHvQDvrXl8lf50bmoPpf12NX772e54wx94V7xtgVzZPnTWGejtaiY5y0veKap0bZS9sn96i6fG2fvDAN7tI8d+ZZvnSCZJk4abDwHe8+9+J5nN8vXb+1T98pssr1hWlql/6JIVJ/VS5vD29G7Te8WVIkNkv04rGfs82mKNW7catdvej8/J/7vNI4vzR/cm7f9PrVpHkog9dK8PgxONoC/TE6fAz0x/D01/D016hvKB8yePphk8G7X2UPSlj79W5Z/n5gVqmAcr9Z5F/ljweHxw/+ErOLdlp8V6oPtf74ptyoV7lTW3x7UCXnGn5eq2dvbqGfXc87KOj5QUGHjY7XZsL3D4O4h0G8wyDhYZDgMEhcDxIcBnHdk1E6aj5Iva6irzezrJ7/clOu/6VUvXrtfyt+luL3RRX/wYF7/UFp9fWP+e/ZZnnQUNmNWrfbDzfl/c1hibyYLYvtQvl3m5vsRpmA3U0l6HW5Kh+ej4c2G+PRe7LBH2WQtqNS2U+vVvlmd9Q0u+Nx9b1ioLNWO17h6UqtNMVaqY5NtvpZTaz2RiWgr1c3X5WKrfKw6Kytk5McVJzjavOU5vdxEiw9J10kvhOk6b2TZaHr3Afzez++C3MvWrTmqdqZebWCtxcmqtm0pxaq+8kTtlDfbtR7rDaWUim3i3KvHP8QMlX6b5GmSq0rNbP6/TBhpTL0j9XSVJ+/yx/y9dKLu2eO1kl/qxRxtcybl+vND4rPaP867+j4OT1+1jbOifV/JGc/JM1f9I/gAoavM2L1F/unpbJI6jxR/CuvJH00MhyLOP+sLWI4P7GJQWq2iUHHJvodmxjOva5VrIepzrL9VjFMu0ZRq6m/Tz+fhBF0JzCCSuzndpBq6vSx6eycJG7rEJbIq3VSpE1Rfj8Ps8XyzpmH84UTZG7g3MVB7NyncbqIXC9fZklrir7Nygsb1O6R6YzQeMekq9iezlupY231F6H+wjv/wj1/xIe+iM/HiCGDdDGr331C3EB5yWdtoFBHNsg84Y5sUdc2HXXC35bpU7BM/nXicuMkjS6sT2Nv/pkXDx/uSnUYwlkdV7vGgTY7QRAHbhzGzvzuPlEnoDx07hb5neMvYvduESR3YTjvmJ16qZ8aHv3thNG5Smmarc7xL2Rjc46bXKj/qP7Gv/gmaL5JLr6JwW/Ci2+ggF13Jl7Mzos+JQNQLZRq6lyTWZ2vS/XvVVasZ0B6pNmMf+vhT0EPT5MfadUgR/nq00GrfvU346VJ5oedm2gtfHc3Txfu/cKJs0Rp4bl35yRh6Dn5PMmTxXy5yKOO899Z66eKuPMDrIsjYV1cx54SSBMffxdOkjTyO3xM64R4nefoZLHbv41PP6anf3w6UgKlSNz2538/dVttGSXw1WGPqbW/rUQ+6/zBT+tCaQf1zwrK9Y9sXWy3VVCx1ciVbDt+8XFH/q2QPwWFfFXHGFTGWtHKRWKOI+K84mPi00m1NvaD8H5xly+cLJ+nTnB3nzlZ7OZOvPSiKMm9u/u0kxV4nT3naitfesV6+U+nirVbDOricbziVn7Hz9otnesvjonnNkAfnv9BePYHQf+IKeQJB53fOYo5/iQVc8cP/kf+e7460bknoYjDNvxb4f4fULgdHSvjBQ+q3QZ7JOQDH/ds2CjdhXefB/M7Zxnmd06QJpGTLgPPcdP8br5wM6WS3Q6S9bjQTzVu/eW/u75tBNdBteo4wlGR6tBzcPJbcPJb2DNKCOhXPSpPu/ruZ65d67X+t379FPTrlRCYdplFQVQNOdTbyUPVGUZv4UdZkDv5fbBwgjD2neTOvXeSLL13oyBLfb+jYZvFfpZk1F9PF+ytAwxwrHeMCMOJ/E5w990QrX/xzWUGMQC/iS/GgTOCQfcv/v1c3NPYwzcbpVeXq2co2Ntup7918Sehi8UL4EZEwzMxHpdgxJ9W+80eB0Sssdatbk7TPFvO7zwnzu+U95sloZMEueuEiRfeZ252F2ZRq5u76/9UPXd/uUI6zpvUEe5IsQtwb7Sx/r35HPX/fXT2e3z2PKSV2/mYOjn9rHSyIuSurclV/LTlW0fRPJXbogfrdCwMaOSgqN8+ZRWRVUR5e8BpXD4bNjV86GejBh/afdSzedQ95gG8OeHZxlYnhIfrFZgSHk3oszaYW5KsmkpJ/CvSfk9CeLbOqqNFdfmM3UqsXTt/cL5KyS2L+/uDh1Btna/yagsdldf32VM14GP29C7bKG2+OxiRwxe3xb8qLTdT1q2o9r2n1v7vxbIqoA/Vf37Ij0WgftSGnvfKFD9WVumxPIImv1P6fn3z6jFX/km2/m9lFLaV7u5U4/+XLtevi/Fv/uOg72/S0P1/isZtftAs8TzwvTAI5mGUVh7M41O+qQxf/vUfu01VZnqw+/MvwvTwf1Gtmr8rtruDCrjLtvn7fLOpMvYvK/j5dttULx6+/SY/DHcgWmkgpX0qOj80sK+jRlTMHCpa+19IC+Y/ne5dBRTY9s/1plitqpm04vzyufq202MASUW9+C9oGGD5H3vlheSoyfp57c6DGWoKiv8Ymgb3urEU61eNmsVrjQawqDDDebo872yw7ysFUv3n+UI8uLq/Hmz4l23l94/FR+3Jn/zU/balyrBXDGzJbojLiaRfVj873VlMHG3aoN/rSphr5PYZn79GlAMLv8PJ282BD/3Nq8dqlR0WIUGvyu1ctKxoqkZ2zxKsyguqIfM4hgw1U+1v+TKS8huHyJ7sVkT9iq+znH/aZOti/9izogOagHGUSnsKHiAtjC1AK3wDy7IK37Sk0LZMf1v1RIGYHrYOlyTZWgfMNMYXan5JoFEG9PutslM52m2ysMf4ZYz3xli6Uc4YCam+gcUlZtR8gjEiStqf9MX6wLLEa+RGTRKYFXIZNP4oEFumTebeTns31rPMllXcb9OiIdpZq0qqX/TX/zzEYi3FZKBjAsPpD8kCvVQ6OvXb/LEagiu4x2JV7LLN8xEc++esrMc6aV5Y1sHYH/p+1NjuzX53AN3uNxs1/PdNUy+lCLPFUSrVltsV94cs7KZ8LDv5nKp12/b4c1GHiB/rIb7PH8uNzkeAIVqD+6R+PDYIBKO7BE+j6DYu628JRrFPl9QMu1lWDpX8Vugsxler/WOx7nV5E4pTRiN20N8cdr3MilDo+E+b5OSUNpb72Tp3Zj+B4MmZB+x6i/uHQwKT4NxZe6RCEQcoTEZ28igHapbbhJvq+2yz/YCdybCZcb7KBFIJhL127WBN5JwGFutxXP80sNmIwvxizsscpnBhmPbcNEpoqK48CMWWaoOrva7nHkjzFdD4OvXvul1ajzw3IIcf1QeUI/4ac4Ixy2GyQ4xBfJxDjMFv9OWXlveJiNSjrUhKjpn23vDu4uU8rEwhfKKZgKkhdqxio3IRFQc6EnVJop8HYGda8AQApRAsN173cPAhz59oXrWcm+5AQUCejUL6/a2DYXlK/zJbq/8RY4RTnEkMGxvnGxHliHeXJkh9htOdCUPe8YHCltweCnk6RsDmhtJ6MwQ0v/DxJhyMEKKGq+GrETxcNxCzVl71FpscjHRF4CSCMXCCf5sUorugn2y3OzS3GOncZSYPb9MMsps0E3RJB+igNv0PQA8f9DFGX5HeNNx4Q+9uXEXqiu47l8FMn+fJzzIYX5/58CPxTkAHsYfFyYAv7dGJdrzrsPGm3Gzzrp3hAQoN9NhMigzsgVlJSWwNlGs80fXXWQQg0o95WJMb0CrETThh4TAlEB6xLiIkef6mQ4ZU8MuhHJygoy6NWWufhMElTk8L88ct7Rg3nhBRDrQXKXA5QRmrHGQja04E6Y7ptnrEOydTXjUmQdcyxTRykY2NIzAjdEyOAN+CuElJfnZkkxDh+hp1N+AYyykthHWcDT2Z4OElgviVjgxGFqzKBUEI/MDqevhQaumxXFL1Vb7NNzubUMoPxarHXY9p2ADaisNLSMTHDmiyowCVDZNYb8NaFmeBsDLre32+bWLR8iBiWPaUwI2sOPDnSil2XA47XYtSrD7mWLCfO7R8UcEYpmLDzGWYynjw4EWc2sgKNe7UvnGhkByIxEBGekRhnKbsI6Oq2TbiQcQ843UyGn7MweZJBnJs0H5TRUoYAEfhSMr1z5KThI2IQY1+E9p7yASUSYQ8gIi8DoSgFsXHYqX+8ryCp7nZ87x6p/mhrtypW1z1l+6c1+lYFeXEvRYk7i/DwRxget/b6+zpWQmr4qgD2uz2rZu9y7aHtnSn6cX2wuKq+Oh9+bYL+TwJ2x/zjs3fW2UeY8kFy9g4MXKPtjI+6RinHmgvrwXkKCGwKaNxMSUaN6RR8NEKQnk/uWVDzInI4VkTKHUicIdzpZqiFjm25dDrmiV0oFDW0MeS3r/myYyWML2pfu2PoqHTdQ44RTIDn8cJLsen6X/dPJS4I9Bk0ECRMcCzGQz+AmLPEF69nIOSX6OFUiKAS3wohxOQNb9SMILWsdtNjNHGgB4tevOIlUUPAUGxehXg5P7NqiyXN0/HCU2RRaNcTJFEimCCIcGMu4J8iiR/yLaFUYT4mAdaK0FGrWmFfGobvsrRsUUdqBVatJ4FnzArlJAsQ6b4iCKJMXLWp589a+jctMS2UVdaJpBZ8+JAQXJsxHlK7BeIbuXkXEyjTRDWlappgeowmSi28RtetKabEXgWjNwyGmAJR25pGBw2COozb/nTQKjgeLTXG2kcxl5N2u/HgdBnchFtiuEYDheSw9hMzwwKqA7GMVGndiF1jXE2gKh2T6GPUKQ1Gat2EVIt1rmI441IZ7ri5NMvs7cPayW7m5rGm0W5Pd6hZJWa0BcG9MYW2h/7EhUJZWcM7VZOm4nh1WDVaiKZPO6ejBF37+ydb8vV8uYHON8jsXus21lJFYZoqV0FTJtYOHDdVOrHamAaf1f2EpNBLAiBJ7PbPuo7w5QkdsOwJ1C7pye8uU6gwxyAMhTmWwJpR466J4PwOC6q+njPz+Hq7+EZZJANxykNM8oKzzARfjVcDgamJBq6cSWzOtNyORPFcaZFVeOhNyR1no8ovA4nYQbB2f7ECYwIEOg0fWs699MTMj0cz5KVAbFyOkOeZCmJI9y+GEx39MtLIC1EFopQIsEfFJdcBsigQYS48Wz2ED5IjSeck0nQyR3a0qDCaVyL5WjJbF9g41RBvVpX9+Dubg5XqmJeCd4QsUIZn0OU9PDWeuSUXgY2RJayeGzUKpdJ2EASGXd4Q7NTRmCR0HihGKgsCHaPmYlCIzk2zXoGGIIa8fT17Pj5g3rbtLwZoXQFTtwwDAPU3VYazgn2COOlrNg5NDRBomhPq/p2eyIQ0mBH2n/ONpui3PRYHKs4uk5ewadDvz+Kzmw/IAdmneJOSQfCtMvmrFhVOEJuWBu5MZc8SDBMc/fEXirfCxcRAiDs0Sw31cVIyXkzG5GNkOBJeYl5vh+oRYa5Jra/pK3Ow4wmJAaYpkMmsZFQClnfqcp3UgsXhMIRGZQ1EiYklS5qSSEneuzcUAqcDqRzGOlg8muSpSmdBOtZR13V0kmdnCuXzk92fVvTwRSanJgMQHiDLMZl3EATLvAxr83vnLQWUFGb41SmmfCpNmuBTcBgiuWPzlQyzBT+iEAU0USnhxhkeZxWSugTYw9l9nGpaFruugH3Qnmg53eFWmX4BhxZekYVL4W+0k/xy7QGyJowExhCYmLEq2mhRapQ8DFVE7dW5V4k1JlvxSU+s0njhpLaZGwmUoixkwA5DzJ2froIM0p1F/G0eMEESvVbT+jRs1E9IyZvB2YeATLqXoNjISuHmU+Gw9FegCD4wIFy8oJ5TGawACygtfeVoKrZTy20Cfa4tLyaacRSSke0fSV4OYx4izro1hjeFUr49im0/hcOdInqFZKSuCY4IxQ52jTgnj6WCTZAskqWjVHXMdgESjBHSCi5GSV5D9UcifI8RuLpa7VNjkv3M0rW6yw0HD0DSt6gHCOxYpr2GvHO5NDLQzvwhHO4Ve5ysJ01shu5jsCOseKlHZZrbwodGO/fFk3Y/Lgx2E02b/MK9ToNsfDPEh4BdRMDGh8fgKbv4hFsIEsalza/H+iJuB+7y6hxeAs2YMItbw7jnWA0G9KYQ9YrE0yCa/4IWXAC4fI572sr8AYsYRJuZFaJ10vQ1xRY57enSD1rqUjABlhSISXkOQVvdlK0qmxrpGjNBEtUpHrcwULLePxFJlTf67g6vG5wb1ByraPml8PJZ/kbz0yiqQijUd0cYlkeEZ3SOR4jEpEOvmyi/Lm1vwkoJy5lMu5ZwhGc0BVNDWQER4VVT1jL6i4RWcaQLPuOA8QrJ3tGH0zjG2TAeW2R3J4j585DulSQU4VI3crGa5hZIuAyxifdFyfdh0gfofOuRzJptJpsj8HXRaK34+F1/qjj4Xlnz1t6eCzTRQA44BfoFKKQXNFi75yAXsDH34nJUyu4Ch/fQAAzCAI4oPYRVy24JtTFk+9ogVq/W13R0vWq9w/ZZiBOOqLPBt772ldo3r2k5DrkOtCdr9IIjhAKrAFYt9cVb9YOrq1jJwcgsbojm4CLGL9kn3QZkh0OhF+7B10PJdQBVOZiULDj5jVBEyMDRcDSU0obO2qqDqrAnTxf2ZMzhbcpMzF51fSstQvdYZLZSUU4BkhlfEj206AhwKg2yRkeSUrWeC3RRQIpJH4y26XVsAvDElxOtl4Uz1yTgk64d857U+yJTwQQ4NKwvtTDsTsNWgC6552XnJu+C7QLXYAkXervgtc8jfFiRO5smwRLAPbww7x5islwoRqZayIrwEqgvn7dDK6nLr534SAhUWPoaLq5+Q1XO9RxdJkjhoT8rNlt+qeSwFmfQ/vSzmruxbt2fuzBdrW/ksAM8vc8NUdJTDsnuJq/vL/P0ct9zpIJCeCBg/qac/JjABhSSCRi+Apklvwz37INYqUfo9751XS50nirxm5jyyAcEsraOmemzyGQOUjF429RPPrFQAwhvG5kTorySE6FsIEsZuNCAKxY2wo2YEWO9GDwhVg1EiEFqnzSpqKk2HyIS1qV8YkQRoKEwE69tHCGHXuY+yEEOU4ylmhxUDJg+O+2XD98yAqLACdxoUDnHJuWEW0+cDRMDcaP7pfVMNgGMwdVAQoD1x0QDcW76mQ6ABDYoafvxm7etdwj3BjSbxCIE7H5DKDwG/7uqler/WOx7m20lpBMPi6IyUChXMZke+sUmSj0EIg0MyEnAxiWMTMtkTCIJoZyFzRFFwOZF9Jo4LWj8uBdB7pGdfK093DrbELM53qNuC1Ku0WhGoZ5CDF7KsikF0VHCD5TgSekaFbbQOU8lNX+IlIf7Pr1q+oN/5vbOiCI5DV2cOsTq4nIy68lchb968jcUvVK0FUkx3YKkwWM94B9g962TS6Hf2dEkzgzHSQHzoseGeZDItV857wNqZjL0PuhWyzPTzNySQayClJ809SUCXVfmwz15kHOGKcBwTAuGHkTdk0mGvqD6LREkdrY0CDP4lQg7zDYt1halPvduR0++fTL7O3DWonhpqbyZlFW78HSVnca0pjeAtRxxINOdeSlLWDCpC8IIa1b88nZivXuFid0AXfxHWf7mTaxiUVCCbxeEgaK9A6Jl2tTvC48wonKlGkqLlwLLOSVR2Q07IgFmnWuy9zAzOzA1VksBOz5H/lmv81W+ePl1qD3SvNAVqjBLv1qJcIh0/WgaJFogpJwByVxPXbnILtWlajjA5Q0aAuxQ8TkZwJ2jbquOcexlLPvhJZVAgrpyg2FEkg4vDMLdBWLyDmrASoZpGkpMhmCYsoKG8ymY+15NCwVAopJYsUCq+Hb/BHtY4SyTIYUJoHyCTbgiVxxRsBCWW8ddvMeoTcF+oU2GK6R4UsIU2wN0gG9RS5IZ0R52LmKfCROi2FCi8fGYGEQQeMzO2BZKMgi60h+h152wS6lsqYHdcK4e2gAAoUupgFwSrSmnUwW5e+rc8AL6/q7kQucJYLJQFgBEAezbLQuynVoA8kiOElkjBcBlGSO1ZoOzEA7JLzjKwe0ihlAK/wxxr4lEkUpJbIQq0QSYgVea89BG42BomKF3MFbF7g3BFDDZwQkkji2hBKCpNdJjo1IGjvFaIYDaXxHPyrIBkqG8JOZyWhqL1SxBX1tZIiUJ+9LQY2E++w1OSB2QJEgjqteI+RDqlK8u60PqH96lablSh818eJ/spgpn+pYWMqZKzIcLIqWZPeHHD82xpQSDdYSIECcuIl6H3DeWRrnRDFL3PzXSOhTwRdB9w9LK8mGcVpr27EYN4B9SNzh+iWPecyBytpEoFJgdZ547b4LRr0I2Wwy0AiO5pGWi2aK5pTBfPFaRMG3O8iXWLnU4niW7iHXZOBm0/lDMqobJcn6LEotjIOwW6KHLFAg+E18+7xc58/U9SYajbIAusng7PErCSKZKD0Pkh4BBLiuqMxWP5fr5SF689Nqv9mj7a1LWlKQB1yLxQBXfl2o90e9o05i3UtcX2eK7DIurLCGyCHWD8iuCfJGkzMBuzaJZm9AaobzJAFaZqbdCih0S2jl2IDEhLiJIW4m6CEUDa835hTRIHcksBcJ2mXH5dv1Il9vsasipPA5Ft5LaGWCDhluZd5mK3JzK5w8z2ORBBgYoxe58O1uQqWUXWTQmKYR9Kymlh/sUIk1uBq9d4fFApDBf42n+O0gexjXlobnc6wAfVw0BNxvbhgAR4GCybUwlL8K0wGDQqSMpDZqggC0AArFfZf9lp/RB+OqJkCThUDsU3qiSBwpFk2HFIuJSDGby6HHTEzGwuiyxAZd1iOHBjFHONOhJ2uNYUflfpUfGtoQIF5S8LOUkIUc7eK1tu5fqHx2DuSZ2Z3HCYivSzv8usy2l4eJfriEIYQ2QpkgPrLYg9Jgswc1yaGlWCRr/GBMDptpPAwJ5OxNudnmXY+222IKlaCQZxN3kiBp6gbjJ7J+hIEmAbSApD2ceibrTt1d7ESnqKlFaHZqmubdB6xLmgJIYeAbppL2bkAAe2FwJpooQHw2KTmeZM3NImQvsgsAC4vDgDKTbAEFtcWJmdUzEtwmo16hMG0AamHRODQhXHrCYLgJYx8+LZAVdKm3dReWhiPs7XUCZBu7LZ2R/bnfjeM27bhNLyEBWodxe3lbvUHxi69cqPZOPCzjDtcTip0rwFgVfs/JYM9EDxABEz9G8zZF74H+Nl+XIvqJc29G9z08FYvzICZCNrQ6agq7Mp24LJc+YrLjC7UYW+eVzX05UaKp08gSHtUJAq7rhHeFSXeDj755dyycdz4gNRG0VzAoTZPILvNfg1IcQ14+KK/3+/XyUNSMV1qtQIcrA/xTxhuI2TlvzQ9WjOkIj/hSpwETDdK1kNwPxYSC8wYFR0MgSryJzkaVKZFyyavEOjIvBQ6eWyk2YiKKAFK8pKMv/kHtymc4cBNwiLS1RwIhil7jIrJpINwUwaFuwIlCXMYQl1PC2iKrjTVCxD+icD8SeFFov4EO5oQswR4gB6Z4VZZgJ028QRnoN9EK/mAHyAYud+Lf1F+zgIa1R9QMVblEMNpQSggWLhCmfxkgFSOTloA6EcXOc1NsJCF0hV8/w/gEmUzNM4ws5fW0ZSIbJ6nhgDtSjgNwJHZrIAAfx77dtYOIHD+2ZhHhpCAlL4dDISWJgWeuLxySK66p7WIiKC/AxFHichp9LfD6IxRIBRhz8kJjIOXq484kMNOEAzMlBCPkAaeJBeDUmGUgADTNAFHL1BKta2pKQ6j2aB+hW7zmEFRBw8iGEg7zIbiFNFjT7FoMS8ijxSIxOBo4H0mo7YTv1xtE+nVm/qZQ6vc6kALKnaBOc7ehIULuG28Zk8feyqMDwDZqPyzyjAXSgXrETYo/BpGUfIwqE4qLS4DK00/VtzoZax8YwRA19LoIaWPhLoX2WE4uYDMcws4ThCEMbD3VR6+L3fPNQv33oW6lksrtTg2mhpr9qD4QJPUaJSlei8bui90/ZBsWDqCH6utfxR3ABq0WYSB2IffP5ea3wzKQsscthUPUQz9yFofNDni7frcpH9QA1YL/Jts8ggv+gF98X77t7h6fDzuhahhaCdRnsdhDw3IJTctFNLXebz6EosHdN2lObtvYdQJgGws+C6EzMDjTMNoZZsjQkJIkYkKDy3Eb3kO3T1ylSLMRkxBKmi0Xc9CxT/OTQpwN3+j5RuKbGFwm8TzQhMAYPJNme/yauZbtSTpphoNJkhEgHi2P1q07+vDB1txNchVfy9TldACskcUUqZ3iabQbe40y3NOLF44nycFxNUTp0tQ38paPJ9fwpMs5b9fl72bJY7GrJ2hnPqY5HBYXBXJKWLoSFJxIlhMosJWyZbAgAKXcH1PrhTbXwWw8kNkAyDcI3W7N1g1DRlyhPig7GkqmES1nfQwL3mplaOi9+NqnQe8vyeDgzkdE3NPkRQPji687KXC5C8mCdcOhVeKzTyq0tvVziInRkCENbt4wJwE3LzRaA44fuJoQj4/HiVi8GWRM3U6kVivxIM/CiHih1w86kuM3eoU9QQ68ndYvgYs3g/0tfOqJiDQEHSzxa3BgB4nF7ACgfDAzgARVg56Q3eqD0kctFefB//aX8/QRDbrRANdN2P6oH7wh6oC1r5Dl4VrVEIDv3Mr9Bb05Xu2AtdbvR8y3bcfHrB4w28HTN/dqvSjUf91s9pTyAoo4UHUBZA+ZAvmXL5agIP3lGg3ATcbHgfMLdaTXRodShdC71ygofglkiWgXFVrrjsbDtZGYCHzcAfucTHtXLy2rIbuj6UmcMZKZ+jwxYalEfYbhTiklgZiT1LQlaBxIRGyR/kWD6T/zBmiJzs3DhRz9zc+aH8dcB+Lg5jp+I9e/PbUpdrlaIUtKK2TRGlzIze2UdMAZlh4yXu1KFBDCEBGdxgd2IciVPAhAB8CnqHHxIEygbTmOZ1GswvcICddXw1ee27IG3QRv9RZ6KuIppQxwpYZdxYJtK3YC1K4Ht29LG1RUMEoRXs8h2ZZOWKUNSCgCGGTXcUSQ6ElVAhGwRthd0Sm4kUsyOtm083tGfywXv92U9zffFnfq612GvTqjnpRS40Yo/zCxbdehG9uLOyKg4DHFMLVCHuxrLolfjyBbZY96jgDDepUFL9S4pR6O5gYNo9h515BHkG9IytHVw5GdXjncczQCPJzhxkE3TfGNfcMq+jQ4AuoXagQhyObl4CK3GrtgpMfWGxUKT1n6rLLoTFpra3JUrZEVel4iajuCYrr65Q4WxoMsXI4pCl6OoHA+sWxGk23AXFvr54ajgSJc3Xz83MHQ39vlBsFLmrEb9HIERo/iPhn0AD9FRSDfjVjgkiS4/6XkfnBcDZa6tOyWR78a/wQ/b4cdNQqBTFwEEWdXq0DFGhvx77aS6sW4G1Dtl+My9qGIGBBwdbxQRoarE6Q5oBRQ29Kny0VECj5FClT3xRtrZ3gQF3ZB7B6Yo1TfcBdkmXyNhMtZuKOmbhoo90RtyDTU2yCKS/dCLkHUwL6FirNTyiqWwrcm4gs1gdjhxW/YcHFM3pOIAAF9pTHqQWHniYcQIoDMpboUwC6ULIIN9KjEE5IO7AAxwhz9eK5v9husxEFnaOoAJOwP0fvckPp5y3Y5t8WqX0f3w34ZCzM3CtYZdPWmKAKBvTlZvQS6eKJdIIY2mgyUW8gmSNdO8sDa42BzIFwepuKkv93UyadfZq8enz4Ud0W53x62nFUnqiYKaECc9/eigm+hmPTVyV4r4TfyuFo9mMasS5BAN9nwJYzTAa7BSycBXcaHlxtg7hSouHx/WaapgzNN12nIBSbcxD11fUzE5SPlk8L1eXWCDlgJBx4vyXFiAXYX4jm1Sf5bd7B/ela/ZNi9nwrjunX4zTa8SgElkzM07hCYemh+1wINRIEI0zv2ezTQ1Qj4EZ+LdvYBWN01upxfWnEcNFi+Xz2KC7DfNQ5EbNUvG06FMkDMQxjfoTwxeWJuapq8+mNIZFSYSz2iLUgdgZOOodWFEhUBHmxJGLUqoX7ecJSxQe+C7e5IWAmqOq2fl4CbmDv2k7gynH/lcXIxr5JJCJccy4J1Ywuwrh3mGF25CbE2SabJZV7IJYdSBu8qkz4auVD9rYRHzSpLpjFiwOkKcILvoMxhRc5ctwyYgbUUKqmWuqXJgJS13mw0EG0MhdWwLOBQsxjMKHD5qz8GjDTmImm1OAxIWoBjTtulIebt2oqCl8VjmTcAXfERxf4l8fQ0EpAY7AFogYHtUPguzzar4QtWW5nZTti3zXsH1mifSwtqd1irB+h5XtKckKmLIeos4MDYe0AikFgcdvnyeQ4QlVfdFg6+AB6EWZZXNHvB4Csjshdw2KMBh8VfkQ/xYOVbS+FmPe6u8shsnJRnCQFjXS47LmdljdOaqEH7GmTcmVnqUg8N+p1gk6Ugg7zWO9TNRcHzYjJc/UA5UmQC9A9YjasgSC9NnpJQ33F7SokH5hzYa5lMcqDfcx2EAezzTCYR0DuaOsAGO0gWOEcRkwl6UvLIbNiT4qFfB4MUMQtmPMwZ6MmJ9wuHvTViLpy4gUCnry/FIdP2FPbspmUddBDRJXB1nRQORkxbZDIIYxzPrdy7GbWnYpFTIcno5Its7Y0DosWtV2BHEl9ma/U/rCjgbvPXgPhO0jlRmw0z/kcU6EsDUI/hLWkH4Zro5wAKx08J94HvYgRDjf38mvD/n0lfXqe5BtOAdPb7r6sAb9DkvkzxdrxwAxvrdm0O2FdnjJZHhHJAOB06RTkamN8dCfhMT1sLI5/JXbRSCEkgkI1JBxAQA4HLOQTVkMMkM4OqBrx0z6tvGjzb4ZWnAeZ4EMDJFnrpATit63T987nIbB8A4FmuiwDC/+GAyGT8YMgFQocDKM/BU3AwSCPY3BYHM6Y+D2N2rdHGA6BhNOaXmq3mZ+HpEw8Bn63mp0OcEt4iqp8fAc2cMNHMyYAC4BIGj4xftkNgZSEQboJU6tBhqMXSnp+E2l/MxdB/WVY8a8nAUuu/e6/5URT/TZI2udF7AngvdBZ4iJTEBueMcjKgW1WuzCHszCKc0c88kODqQlD4vaWmnSd90RP0guWv+nHBWlwkzoNy8HbBUyihkRRcjU4JtbeuyiVx0rAPLQbbWy5wR1bNB611NJEVupeuySXfpUEhl37w0eSKtmmmsEA/O2oWRmq3LI6JTrjAcM0wPIIQLwbq6ZETTb0wRFsTRq2JbQmj1+Nq+NulMbI8ntVoN4Mxs7QZ2JT0iQDI5Ccs8nHExlxiY4jY77LfcgRexohxJ1MXDYpSHpgRcokOB4keC1JxglIn0x9A9E+K5PZBNiyPoj6ZjTGQ3B6XHY+yqi7Y4S4uF2Sjb0feFquPws2TNaKdurtoUHVmGstELQlZbpuxgzED/QDzSWqKHdjCUu78JuJAQCs9dg5XoFvj7aLc787jJnCvxheztw9rRetNzc7NoqwEaRnPdFqDaMLS90dWHNhBkelfTMDcG0gZ8QZTB3aGKA3ibEXwmYf0GgcQLgToX3ig5yiWmpaP4sGepxSinBLeA93ZaZL8n3Jz207Bg6kcol6hi+Kj4iVbcxR/XpU7UTNTOHLhn2ULXWQODMOHls93lfnG1+abXxt8jrqmUqEfzvhzO/BZbHqfBDzWydx880mva9e4rl3zuoZPopNBycGjKGoZcUtobEN3dmfBfoYmuCQBLoiiv09eZn2wKEzoPAxfo8EqgjE0jWNoTXJmQdshCXiLyPv1oRROXxcCyolPO0xXvr8ggBJt16h3IVTdiJtcXTRyScvE8H34cmDxtg7gvcZ8bALcb86+sGWw6R2dvEmBEw6IAWHc7NcHXrHM5qYQMkeynYaOksNBaSy4VAfe0V5xAyoipBR6IHS2GW+XV0/iQSBFXBkGuQ+2zy0D8QHgKq5u4tJC4eomyHUbIbduIwRg26gsN6NuIxrAs9vVRNDRXlDbchRgglGTwatnIGfK+RAX+sQ8kdXP0994yqzASIEVi5yfOkD9/AiFFilPl9TP22La+vu8W9rYlKd26+dtAWx4GZLtSTpgDrmEkQ0tdHMP4wxk0yIebiOEioeAdx+huB+nJ/pgJXOPZC1Lcl3QiRYk3IRP59Xka/LHgaVr8tGnK+LN7SkXmK4Jho+a6Eq4lIs+1zQR0OcW0G2KfOmusOblcgSwsYkttDmFAllY2tCIcTvC6OcnTRg8Aosw2F6RnQYyPFzTRGvswC9AbzkgH/e9Ot7hXepsuxHqAXqeF1TJ9tR95hAhfZaZmw468/66vxR6Ebfr8veB9zBeFR95YenCeoMzYVttl63w5Mdc8uOB1zFBTL4pWqBzEQ2+hBGxDc09gmTyQ4h8+3C+jujRiQggImjg/THapDYlCnQufRkuKYUIBuNjFa02LW9SSQGdIHeQoO6m2pVr/HVpXIvvghZ/jCQU7AGIVAlMxAVsDJlcgEZyyoS4AxvLiXvQmzU9wxOFDen0OX/QJsuwChtd5loFjTEVYvbTJlsXvfd4eCRcSR/PXHgL0wei+w4C/hfsE0za3Bn0LMbQ1LBLMZkqA50SbAcXAkSwj3EWBrWvghIPpaQ5VEP82BDNL8Qmk98BkhpQrOOhReUwMPDdCAKV+eCFBzgsJ+YuYz5Sk5p20zhMoSbz7PtRDD0/bJwBKqB02KdibYAQis7zY5oaJ0kDbJK1e2QDE5VaG/CVt+PFAsB7erH1sFJ3tMFdoyzxjmDfKlQ/bEOu1A5vSW6MqvsNUOMMOlJBRozqaAwdEuUOZPntsJB0LKYHYCxQITkGFtMfAJ+g08sBF50ZADgdVDyYgc4MAUgTDh1JT0lHPHRmzEVnxiysG7fZsc4qMaF6DHQmD+tIjrmy87NkjnWCmM4yD53ZJKh585NXvJ6fOkD9PHnH6/mpA9TPE0CYloRRdWH9vC1MBE8Y1UjUz8tDLjVhVHvsDV31wSUMHhl94IdqXgRAId5giY6dRoQ1qgBxZKdVUzcKxLGhjurUa+rY6px8rNEUsBW6oX7QjgK2Su8ZAUcB2Y1tKKCWGWkKyI58QwFTS9NbuzYUMNUxOfDYUkA94GkKRlWz9IoiT6cUyL5jHfyHnxfgj07dHKJOEvnIrYqiUYfH0iZcepMxpRlzqYsh6mRy7g1Qj0xgZEGgXXsqIxKPTF8I0UcFwfXh35h9bQMukwGZyV/luPBBLshhOx/ia4w+tR73LXiD1NJAfYICBQ0bkUTYlqGC9cg3LIUzGbZ1PIwfjSsSwM/WfGEBfma9blbesPG7Ztc80KJaJrK5iw62uMw3BlpiJGTr2/wRfUUQbKZlsHvj30fswEZ4yk5ToCUfA3MGW2wgec0D0k1U3+rAhnxwMdIARj0zSfe3c4adAeIOA10CW6Ab9Um604AECuNORAzcXwdxZg2cY6CFwLan/541isYOvp0fe2oU219Jb0W+StGHQnh2Rw2NxrPNFaF2QMALcGqAHRopaNfn3AqGj4RMadwdFVOosXXke9iiIdyf+XmNe6PG9TWITe5mY/guQBwIjfo83KHCMobM7JHhchNeDQiNHI3QEG46DM4dylfawdDoMDiPB4PzuTA4nweDC7gwuAAABOBAZ3TQW8gDvUVc0FvEA73FXNBbzAO9gRfZ40BnzP5sDNAbr8EdF8GlM2X0LB55YmbikDExE/TmMkFvLm/J1M/TMRIuE/TmMkFvLhP05rI0VjM/GdvmsjR2Mz8ZHOGyLFYzPxkawWsi3MxPBkZAwH0k/9QBPNBlQwqADiNzeW5rSwEZKuZyoWKaAqv2dsQWWppKtqqkw8lcLpxMU0CGk7lcOJmmgAwnc7lwMk0BNXSgKWCrTDqcDLyjBUsBU2uSL4htKWDqTUOxAwfwBcerbSWsMxpkv6zOU/AdQ6Zn2PO8IGSQTt18ROqacxizesjwPIe6hEtdMiQ7W5AcmYKYS0HEpSDiUhByKQi5FARcCgKIAjuwFuMKtxP4GZl+nytBrpZ2QS1tSwFXS7uglu5tA0fpb8lV1S6oqpGIMaCju0/EkPHK5SnskFsWwBrfjmSuwof1vaFd+2kO9tV6Uaj/utns8RdCca0FbCz6yCfoMtCYiPVihK0NpokKXYSwrcF0o+l5HI/he7sp1z1qICJCqdAk0TBOoK2a8Opf8ttjmznm/KCRs7BAdNvFOX8Ng7/sUE3kvMKYiCuw7ZwdbfDd3AK0gVds43A6tEb9djgdatRF43RoGCJ0oVbIi3NpiA01zqYhNtRIn4bYkGOVMQ/iowE15GhtMgTx6TEYlpf7wFev4MA25EQ3XNttm+lmlpe7cNICCbZhFh9x4D4eE+7jc+E+Pit5pgMYdLhPwIP7hFy4T8iD+0RcuE/Eg/vEXLhPzIP7JFy4T8KD+zCvU9RxYmbDHzrch9kxiYtd0TkGso9KZ5yZVqFz7PFEptM67LwSb356Dttjwn08JtzHY8J9PCbcx2PCfTwm3Mdjwn2gO7OR85NT17w+lc385MQ1BFBGzk9OWzNdtlYBkbv8eVy4j6aAqQMZcB9NAdcKsNUgeQRNAVsRkkfQFLBVIXkETQFbGdI7Q3lcKI+mgKkPGVAeuGE+jgK2SqRDeZjhxNYpYupEBvyc24nE8XQ6gqxR6gQD/HxPuOjt4jyPYeSOqe1Goc3l0uYO0WZ3CGNQMGdS0MCVmHUnPc/bJisSLgUJVwYxl4KYS0HEpSDivoWQS0EIUTBG96aAS23AlRdX57qgzsUCkMgUgJoVC0AiUwDqT1zZLIMCUH+irq+gEzCoPdGpN1id8sq76doNVq+Ygnf6O4KVK6bgnz4/rFpR+Bvy/LCypK4IrvaElSfmNq2exxtADMqcsH1UrhrjajHGBqVPzNEJXOiqw0H1NG+Mc+binfrgOy/FYCzkE62GscBncj6MhXre1zAWOGLBvpKWHA3RoBVyRCjiRZQ0aIUcE4t5MTUNWiFHBRNeVFEDU8hx0ZQXV22AKfRjIPPWgQaYQlerzHJalxvgb4ApZGiMRgjSoTE+L8+iD6d0aEzASjTpozwdGhOyEm06mEGHxkSsRKMO59ChMTEr0aoDWnRoTMJKNOuQHh0ak7IS7dy7rHRUlBmVZUBjeH1VuDgPHTMn50jpgmcmENgZDDrLrDfWZlB48zMEz9sy9fP0jLDPUxn18/R8sM9TmfXz9GywzzMZHnSFKXJ+ciqY17uumZ+cCOaBeZv5yWlgpsvWKiByGtjnua0tBUwdyIDGaAqYWpABjdEUcO0QWxHSoTE+7xDbUsDUhQxojKaAqQ0Z0BhNAVMfMqAxcA9pHAVslUiHxjDDgK1TxNSJAsAWrl/IdwzpI+jsC1mj1MkW+PmevLolAMbn0uaPR5vHpc0bjzaXS5s7RJvdEZlBwZxJQQMcYlbQMChIuBQkXApiLgUxRAG2lxGZgohLQcilIIQouF2Xv88s2i/Gkv1CWmwRmSFQYWOxRWQKQLVMRpW4XHXsDqpju9QEgwJQ6fKLolskEjN7RJcPVx+D6liuDaoDa2xULyKyjGB9LcckqNJRWWC6jECFbjk/rM9RaCWy9oPVL6pbEHl+WPlSleegNh5y9ri+nrw14Co7xhqlT8zZFlyIlsMsFeB2G9SAJerz3JO4w4wFaK1AjmYEvGiIBh6R4zkhLx6kwUXkiFbEi4hpcBE5phfzYoIaXESOaia8qKgGF5HjuikvLtyAi+j+85wXG2/ARXQVyOyC34CL6PAmZvmwy03SNOAi5uXvHHhTwMuV6QM/Hd4UspKFOuRBhzdFrGSpDvrQ4U0xK1msw150eFPCSpbrwB8d3pSywAI69MmNnTJjtwx4E+/aJG4bFx1ZZ2Z5GfAmHliIETRnpmDoHAc8kekUEDsHxZufvuID3papn2e8eJ7KqJ+n5/QDnsqsn6dn9AOeyfB4V1M285PT+bxefc385GQ+D5DdzE9O5TNdtlYBkVP5Ac9tbSlg6kAGvElTwNSCDHiTpoCpBxnwJk0B1xKyVSEd3hTwDvItBUxtyIA3wRe64yhgK0Q6vIlZx9dSwNSJDHgTN6SoKYA1Wk8+0RJgomnjeoywruPTxtSjo3T04fYFcTyd/iLrpzr/BT/P546pO0ehzefS5o9Hm8elzRuPNpdLmztEm104hEHBnElBAyVjVrwxKEi4FCRcCmIuBTFEARZKRqYg4lLA1b0uqHux1+KRKRjUsHb5AQYFg3rULkfCoGBQW9rliRgUcHWiy9WJLlcnclUiVyNyFSJXH3LVIagNUely+vygLkTBBejzczUhVxFy9SBXDYJaEIm5IjtFXA3EVUCM+ekTc1jmYsocZk0FtwmYM9io1mbFMhBezFonbsjBGQyH2GgsBsIr5AWENMKKHNKKeCExjbAiB/ViXlBQI6zIYc2EFxbVCCtyYDflBYYbhBXXa6RjvDTCilsjQcd4ce8maBBWzLa4HIwXsw6+QVjRMV7MZJk+BzMwXiEvYahjAXSMV8TKmOpoCB3jFbMyxjoeRMd4JayMuY6I0TFeKQsxoGOC3KAiM6jJwHgdB2DWDjMwXry7srj9iHQ4npmiYWC8eIgpRjSbmbehcxzyRKbzRuzEFW9+duKMvORD1o5t5idv+ZClsZr5meuPDmsIeSbD491H2sxPxjTwmk4285MRDTxUejM/Gc/AdNlaBUTGM4Q8t7WlgKkDGRgvTQFTCzIwXpoCph5kYLw0BUxNyMB4aQq4tpitDOkYL+YF9i0FTH3IwHgN90q3o4CtEukYL2ZIr3WKmDpxFIyXpo3rMY6B8dK0MfXoKBgv7k1VmrYxGkPhmuGoAbe7bLMr1g/flYusGqma7Ff18EP2mL/LNuqfiphtNf6yuL8vFvvVTj07+yov1L9fzJ5W2fPh91/+nC0+lNt8/br4qH5/U66X+022bf7k/fNTVd7/Zv+oqFCk1/+vKNhkD2r+zkUJL3ebff5itt4vVnm2+TnPnhRZX6+zu1W+nL28z1Zb9evHYlGxUQ17kM/toeNOoShUU75WVKrZq/YZX5WPxfrAWfWheFqVj+rTopLlY7k8PPqd+mJ98+ox3xSLbP3fioGK7NtFvlYEldub8l7/OKsko0auiFQH7MV+s1GTvjsweMp0/dN79be3lYTfF495pc7nge+FQeSm8/lRxm8VS7P87i71XDdzvPR+6QTJXeKkXp46Yewni/sgXqp/ta/uOKAauWog9P8BBq1txpA+AwA=
```
</details> 

### Operating System

Windows

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SeventhM**
Should close #10868

There's several problems this PR aims to fix

1. If an improvement and a terrain type share a filter on a unique that gives stats to tiles/objects, the effects of the unique will apply both to the improvement and the tile as a whole. This is most notable with the "All" filter
2. Despite claiming to use tileFilter, these uniques instead use an amalgamation of terrainFilter and improvementFilter 
   1. Even if you fixed this, it also comes with a weird side effect. Unlike other filters, tileFilter does not use the newer multifilter system. This means even if things functioned correctly, a filter of `{unimproved} {whatever}` would still not work as players expected

This PR aims to fix these problems in the following manner:
- Do all uniques all at the same time instead of splitting the improvement stats into its own category. If a unique works for the terrain, don't do anything with it for the improvement. Nicely, this should have no serious implications outside of this context thanks to `getStatDiffForImprovement`
- Add multifilter support to tileFilter
- Do all terrain checks as tileFilter checks. These check are given a boolean to ignore improvements. Sure, this basically is the same as terrainFilter, but it avoids the awkward conversation of putting  "unimproved"/"improved" in terrainFilter. It also is sorta a way to not worry about if tileFilter/terrainFilter changes in the future
- While we're at it, add support for roads here. It puts us one step closer to generalized roads

Main notes
1. I have no clue how to add percent stuff to the breakdown. Maybe that should also return as an `ArrayList<Pair<String, Stats>>`
2. The cached Percent uniques section kinda bothers me with the blatant code duplication

### CODE REVIEW

**Comment by SeventhM** [comment]
Weird, I swear did unit tests before I tested in game. Ugh, time to see what I messed up between then and now

**Comment by SeventhM** [comment]
Ah, I see, when I moved stuff, I had to do some function null stuff

**Comment by SeventhM** [comment]
Actually re-reading it, I already return a hashmap. You could just iterate through it and print it out that way. Even better if you do something similar to `StatMap`

File: core/src/com/unciv/logic/map/tile/TileStatFunctions.kt [hunk 1]
```diff
@@ -27,16 +27,28 @@ class TileStatFunctions(val tile: Tile) {
...
+        else null
+
+        val percentageStats = getTilePercentageStats(observingCiv, city, localUniqueCache)
+        for (stats in statsBreakdown.filter { it.first != improvement?.name && it.first != road?.name })
+            for ((stat, value) in percentageStats["Terrain"]!!)
+                stats.second[stat] *= value.toPercent()
+        for ((stat, value) in percentageStats["Improvement"]!!)
+            statsBreakdown.firstOrNull { it.first == improvement?.name }?.second?.let { it[stat] *= value.toPercent() }
+        for ((stat, value) in percentageStats["Road"]!!)
+            statsBreakdown.firstOrNull { it.first == road?.name }?.second?.let { it[stat] *= value.toPercent() }
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/tile/TileStatFunctions.kt:49]: Sounds to me like

for stats in statsBreakdown
     val percentageStats = if (stats.first == improvement?.name) percentageStats["Improvement"}
        else if (stats.first == road?.name) percentageStats["Road"] else percentageStats["Terrain"}
   for (stat, value) in percentageStats: stats.second[stat] *= value.toPercent()

File: core/src/com/unciv/logic/map/tile/TileStatFunctions.kt [hunk 2]
```diff
@@ -27,16 +27,28 @@ class TileStatFunctions(val tile: Tile) {
...
+        val statsBreakdown = getTileStatsBreakdown(city, observingCiv, localUniqueCache)
 
-        for ((stat, value) in getTilePercentageStats(observingCiv, city, localUniqueCache)) {
-            stats[stat] *= value.toPercent()
-        }
+        val improvement = tile.getUnpillagedTileImprovement()
 
-        return stats
+        val road = if (!tile.roadIsPillaged && tile.roadStatus != RoadStatus.None)
+            tile.roadStatus.improvement(tile.ruleset)
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/tile/TileStatFunctions.kt:39]: Isn't this already a function in Tile? If not then shame on us 😓

File: core/src/com/unciv/logic/map/tile/TileStatFunctions.kt [hunk 3]
```diff
@@ -150,51 +173,82 @@ class TileStatFunctions(val tile: Tile) {
...
-                    stats[stat] += statPercentage
+                if (tile.matchesFilter(tileFilter, observingCiv, true))
+                    for (stat in Stat.values())
+                        terrainStats[stat] += statPercentage
+                if (improvement != null && improvement.matchesFilter(tileFilter))
+                    for (stat in Stat.values())
+                        improvementStats[stat] += statPercentage
+                if (road != null && road.matchesFilter(tileFilter))
+                    for (stat in Stat.values())
+                        roadStats[stat] += statPercentage
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/tile/TileStatFunctions.kt:215]: This is just Stats.add

File: core/src/com/unciv/logic/map/tile/TileStatFunctions.kt [hunk 4]
```diff
@@ -150,51 +173,82 @@ class TileStatFunctions(val tile: Tile) {
...
             for (unique in cachedStatPercentFromObjectCityUniques) {
                 val tileFilter = unique.params[2]
-                if (tile.matchesTerrainFilter(tileFilter, observingCiv))
-                    stats[Stat.valueOf(unique.params[1])] += unique.params[0].toFloat()
+                if (tile.matchesFilter(tileFilter, observingCiv, true))
+                    terrainStats[Stat.valueOf(unique.params[1])] += unique.params[0].toFloat()
+                if (improvement != null && improvement.matchesFilter(tileFilter))
+                    improvementStats[Stat.valueOf(unique.params[1])] += unique.params[0].toFloat()
+                if (road != null && road.matchesFilter(tileFilter))
+                    roadStats[Stat.valueOf(unique.params[1])] += unique.params[0].toFloat()
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/tile/TileStatFunctions.kt:199]: Let's use names. 
val amount = unique.params[0].toFloat()
val stat = Stat.valueOf(unique.params[1])

And then these if/elses

File: core/src/com/unciv/logic/map/tile/TileStatFunctions.kt [hunk 5]
```diff
@@ -150,51 +173,82 @@ class TileStatFunctions(val tile: Tile) {
...
-        val stats = Stats()
+    fun getTilePercentageStats(observingCiv: Civilization?, city: City?, uniqueCache: LocalUniqueCache): HashMap<String, Stats> {
+        val terrainStats = Stats()
         val stateForConditionals = StateForConditionals(civInfo = observingCiv, city = city, tile = tile)
 
+        val improvement = tile.getUnpillagedTileImprovement()
+        val improvementStats = Stats()
+
+        val road = if (!tile.roadIsPillaged && tile.roadStatus != RoadStatus.None)
+            tile.roadStatus.improvement(tile.ruleset)
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/tile/TileStatFunctions.kt:184]: A second use. This should 100% be a tile function, getUnpillagedRoadImprovement() or something

**Comment by yairm210** [comment]
There's a lot of simplification to be done regarding all the stat additions, we have builtin functions which would cut the loc by half

File: core/src/com/unciv/logic/map/tile/TileStatFunctions.kt (hunk 2 above)
Comment (SeventhM) [reply core/src/com/unciv/logic/map/tile/TileStatFunctions.kt:39]: I believe the assumption was RoadStatus was supposed to cover these areas and roads were hardcoded, so it wasn't thought that we'd need the improvement. I'm half surprised you have even just this function

File: core/src/com/unciv/logic/map/tile/TileStatFunctions.kt [hunk 6]
```diff
@@ -150,51 +171,88 @@ class TileStatFunctions(val tile: Tile) {
...
+
+                if (tile.matchesFilter(tileFilter, observingCiv, true))
+                    for (stat in Stat.values())
+                        terrainStats.add(stat, statPercentage)
+                if (improvement != null && improvement.matchesFilter(tileFilter))
+                    for (stat in Stat.values())
+                        improvementStats.add(stat, statPercentage)
+                if (road != null && road.matchesFilter(tileFilter))
+                    for (stat in Stat.values())
+                        roadStats.add(stat, statPercentage)
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/tile/TileStatFunctions.kt:215]: There's a lot of repetition here as well, for the 'if tile, if improvement, if road'

How about:
fun addStatPercent(filter, stat, percent):
   if (tile.matches....) terrainStats.add(stat,percent)
   if (improvement...) improvementStats.add(...)
   if (road...) roadStats.add(...) 


At like line 183

Then the 6-line repititions become 1 line, and the 9-line ones become 2
for stat in Stat.values() addStatPercent(filter, stat, statPercentage)

File: core/src/com/unciv/logic/map/tile/TileStatFunctions.kt [hunk 7]
```diff
@@ -101,9 +115,16 @@ class TileStatFunctions(val tile: Tile) {
...
         }
 
+        if (road != null) listOfStats.add(road.name to roadStats)
+        if (improvement != null) listOfStats.add(improvement.name to improvementStats)
+
         val statsFromMinimum = missingFromMinimum(listOfStats.toStats(), minimumStats)
         listOfStats.add("Minimum" to statsFromMinimum)
 
+        if (observingCiv != null)
+            if (listOfStats.toStats().gold != 0f && observingCiv.goldenAges.isGoldenAge())
```
Comment (yairm210) [inline core/src/com/unciv/logic/map/tile/TileStatFunctions.kt:125]: Merge the ifs?

**Comment by yairm210** [comment]
All in all looks close to mergable :)
