### PR TITLE
Fixed a bug where production would not be retained when changing from an obsolete unit to its upgraded version when that upgraded version was unique to the nation

### LINKED ISSUE #6519: Excess production incorrectly changes from Composite Bowman to Crossbowman for England
**Platform**
Operating system type, major version, architecture (64/32 bit).

Android

**Version**
Where you got the game and the exact version number.

4.0.3 

**Describe the bug**

Excess production incorrectly changes from Composite Bowman to Crossbowman when playing as England, wasting all the hammers. England has Longbowman UU.

**To Reproduce**
1. Play as England and build Composite Bowman
2. Get Machinery while Composite Bowman is being produced
3. See error

If game data is required, please add it here. From the menu, choose save game (or map), copy to clipboard, and paste here between the backtick blocks (or, if no such save is required, you may delete this):
<details><summary>Saved game</summary>

```
H4sIAAAAAAAAAO29a5PbRrI2+Fe48+U9bwThJe5Af5Pkm85YY43leb0nHIoNNIlWc80me0i27B6H/vsWLoV6si5AAgTlmXNmpsMiwUJW1iWrsjKfzPr9tjiKv22xP938vi4eHsU//+FFX6yW8Rer/y0eHZ72583h1/2N7y835el8PDyXm5vz8alcPh5O2/P2sL/5/bcbL1o+38SflqfH4td9ufnbfns+3firT8v/8HxBzMs0agF92xdve5n2eiDejm2cRH2cxDZGaj5CQcsf4CMUb/va24l4268Y8YP6bXzDr6rzA+2Nut151e72FVVh3tuLedUPdnJJRU6n5q/o+0n1vu31ahD0MRCNJU0R7+pDsPr06dNyvf243W3/UVQFTzc//y6+vxKfBPfr5tHvdZm/FA/lzctuOi0328fd4aFYP9/8/qbYb3fFze/to/N2/eaw2d5ty6N4+ctyvSuO5ean4vj9/m8n0f70iyyNl+/uq6df7cuH53ombfd3u6dyvy5FM1fLw/m+PL5qa23oC1bL30QF4q0ft7uyYlV0Sdh2ifgc1v/1MvEkaT6K/nu+SZsfVblqLntt4epz87Hu26h5Wn1uP6bNfJNVBe3H+h8/aWdHXVciB7f6paJbtar+pa6w+xa0wlAVU/w1vHppx6HiCphqGVRMQWOrj16iuPZi1UTJcFV3jnzkwK5P2PWhiSFpYvMtpn3U1pxAxSnlLVXNiDsKsseBGjxOSDtTaGeq+i9TTaN93H5rGheQxgXQuIg0Tn5bqVGCdkDz6hI5ls6BEZ8w4gMjIWGE9mxLOVWdUX/GadmOZNYWqZczxUKM1Saq1hQrTVXjmwY2hDxftasjtCIjIBnJFIPNP00zmyfBsmMqUhKTUEEDWYWxDjtiQKulC7QiJct1K/KOQZh5Ldm4IxtDveppwwIMKS4dUpya/kxVf2Ywf4iUqxmDsxmqwo5NusIeSFKkqsmRdA51ykFPgXqieqX+HKhhA+mXNdVfYDixNyRBrD1WtSeKGhLzgPFYrbm+Wjz97ik89MgEVutbO2iqFwPVW6HqrRAmLcouciaJqCbAUJJWkvGOVTtxXqnZFMAQ49T0Vc+rHcdXHRxAXwdYI1kN5OAorqOOmAcC5sPghkAtxH6FHpNVwjIQY72x6udAvRVAPyPlUPVkhD2JS5avPnfromKa9AA8J10D0k46SQ2GD4NBphSMUvccOYUW4GQKgAaIEgwjfOxqTLRu86Hfu/1VVUh2JfxCOqV9sdEeGx6rzz6KNW448nOtdstNpfriy4FuBC9DupGiG5H3E3g/Ib+k8AtsyKT7yVD4qo5YfUzUx5TQ94E+9kHevZCT9siZEUO75daKTV2pClekwgAqDAjpiJBOyLcUaUMT6TDQfZ8Qj+Enn5AmIxQQehEhkZBvshuxUfg51Luu3VtiZDvGMciWoLrI41zbUGw/TIkMmQhVmVTx0HV/COOCL3TnL+AIBilHhnKgS/vXR04iqCSCSujkCWEmqOmCw5GR0VhB5XTmBFh5DBXSKYVsxeozdCL2Z9aVQJZiKJF3JbCTlKhBHbl6jXQomVOp4jxDxtU0kNVr1LsxxvHGPouh3hhYzwwZSru6Emh1gjR9qNhXY5JhU6DLEhiPFVSLg1aV0eQIqmw/BjDW+Ln9gUiOVLdDxR9Zl2OgAvPQw2UZZm6i+AK5xyUg7UqkyJTkA1X4CDqWbANqvfagTKSaQGYL6ZW4rQc2om6q+mqyxMB1rNgO2uHrBk6JVaeHI7cdV3DO9iSR36TOKQc4xfUS32h/gffbeSmP0OSBlCE8X9dc4fiFwD5OCFjqyJoASwJKNnzGmbJSHODn5getgEe207AtoLYuD5brEOoAiSLbD8zGGFsQQ5VJR6cVqOYBnsdROpXUwtueeh1EEEw53cACKUWpHlPZ9bDv4XZIdj8itsBjrkjkMMC4QQeqS0KonBzr5begm/n0Uy0BVGhTnMTtyIKBq1tgU9hImlFumcuRAIx4oIqCkiA7INTnL8wEDwuFpP52aQL+2zWn+QcmOCy4sIhC/0Sqcpg4mRp6mDdybjT/oF0OxqBe59uSMfQd7AUe1KFV0TKBtalmqFZ4cHKHAz2qVlDCU0VqRjtZUnOJqEIBTKxVxw9OkWYCtXJIzJBwwoX93ZMEOkEmL6ECBhZOoOWp03LDl49kOrVMzR6iLIF9lswwLISNxj0WLDtgRfVghMEACfNGDaScbnJ5U7M5gNkMvd0e/eBoTM2H8luiphFUnmqTDsQcl6gIOlDNfMU1McHInSyFLlQWMqmswpIFMoJlyNFWWRy7bWsFy0vTcGJ59FFSwIQDKzJOLxiuVBWGMYIVDmzxyoqcoaSvsAvQ1IKCT8cpgYYoO3ZLSTHQFAAWW7kFDTZXnQof68dkOSJ2AZi6ypQpezRV3ZK2nMCC4zcCDs1sN81uIZKrb/tShBOzPRsTqxeaZjo1aQU92/QCSkDWMd0oanjiVLz6aq0AOYfprQy2cpSVtdFLu1HwQM2ALQdMSVAHPMW9CquGCoFyouRNcaG4xL0uAclrOgfFR40ocRZoHgJqHSBKFGokxMzkg1Yj30DHT6yaoM4JXqT1L6wYmRoAWDZhuwWhVVsKdljadRguRBkK4Yr0Aq6d1OZFrIntFM3UzFP8yiI4AGFXJgc+cuSDGqaIooNbD1oS6JDFpHYYi+TT++WHw25TEQ/rT+X+xYfydPP7/unhtjx+f/eNeuYvT+fKpflt8fi43Zen001YNfbDsSzOb8vD466s/K/3xemrj+LNynX7/XH7Ybsvdq+Kx+252N3cFbtT5WfebdfbsvbWPh4enx5f7MrjuXKSnp8fy5uuxuXHYvdU3vzpT4Lf+pevt8fT+dVhfy7W5/bH1t/aFvipODY+3NpDTIu8X/79qTydxbfiQ3ms6j6WO8HeYd89apr3dbE931eSeHza7k9Q/lyu729+r/57+qE8lcVxfV9ubn5GD/Tyy2PxUCyK/Wbx9lCej8/LV8Wu3G+K4/L7x/N2fVq+Kc73Ze14Pi2/edruNtWj02Evin57OJ7K22L9y+KH7Wa7/7B8s91X/3y1F51Ylsfq84/HuvM/LF8eD/t/lIufDsdfqq/viu2u/v1ePLsvy93yRcVexcDT8Vju18/Lt4fzuXrwYr99KHaLb59Ot4JP8eCn4/Zcvfviw3G7ftqdn47l8rUg3xF/e7/dHU6Hx/vn96IXDmIk6z76+nCsBkN06kksXh+3a9F9z6q/xKCsBeGycdSfnzVP/a1o/Pll1QOiClHmzUFMuXJ/Xr4Q47QRxZYvHh7vRTVidpXH5bt70f5y+bbYFeuybub3x2K9K5ffbW+PhWjFX+oxFw17ddjtSjF7vjkKVo7P75drqPivT6WYEj//eNwey4dS/Fb3zhl5e33626k8vivPDSpiu397PIg5fjppDXh1PJxOt4dfH4r9TZCI5m7EuO435UZMjsPTcV3evNvuhCRUUIBif6qxDW33vqsnmlgAxEJwd3jaV13wavvxRoz0TpBYbjc3cZreJpsy9NJ1mXtRlkZecXcnPt2uN0l062/SdbLcnnQJq1neHdaFApJIlW5f4RO+O+w3YppWYrdry9wdDpuWoSTBX6rlS8rIze+PVRcI3kXLq96XPywOdwvx/TvR4/tNkIom7gqxMvx/xcfiC9GWD1+8FjNETIhWGMOVIPrNYVO9dq4G8bHcL9798jz0nl+9qNg5vTi/OzyUbw/b/fnF5vB4rgTRQraarwqA4YN2235J8QvxrxH7DvFuJviOzafa7m3EUkgqIr8QGyUx19O9dUWqlQs83alSg4lULHy/CjkmSBTaXLOFqa25A8w6+CPtlRw1S8M8K4KU/z5xF0uCkNXy6WE2gQ99m8C/2oripx6Bj5zynt9GZbGK114ZbxIvuktuvTwrfG+V+OUqvSuSdVlogi3RD7Vg/5cYY5dYBzH+kswv1cFEqc7mEGoDBNJNXzTHIVqAeLPRSp4bpAjEgpxfSSXkHbBI2gzTHpotpbfg/VJMk/2L9d+fttWIRabM6vZsa2OczZcMvBc1Nbvyq0ptqybH0kTR3R3LUgni75y9qNrktbF+d65VlmaopQxXot9bDkRc8MoRi+tULSRV9MK7x3K9vduuu94Qa8PHrZD5m98l2aHqOb03xBqnGzqWz8XZwm6lVt/8/H6ptHfxRfy8aUa9+vZOaOUVqlF8bJRg8eFVs4D98zRy+bVY2ARnnxTUUy6jgPN8VRzP90IRZSM9sy/SuBfZKSl+Wr4sdx+OxcZF+7/EyeD0/d3bUiiqQt/5tFSlqqF5Ot3UP1Hqkuan5dcVbLTiYEbqkuan5Vcfnh/Pc5KuCX5ajsTVDva2PNf9n3K/nbcvGopWhC7aMsGFAkYZwKxJCyzReuQ6jNZI26pMnLxE9erUKDS8I2BWgX8QLgvM5Vgb8cyj+4/gGCiQlqIXKJSW4lXtUFhEyBIQK0Us6DBWCoBYIePUO0/cghp0gUJVY1IBAlcpWhVhSYBvArCpwonW/4wBkarf1c8ADkOwqhMZq+nl5BwDpjuqwLiQEZoqTzR0cpwAvCmCQwGRCh+JvoSwYKItkVMSOXjQ0xQxfBHsBEEPoBsWoaecMxPxqyu8rwFLdWJOYW0gZmky9Qm0Cxw4bKwpQQygX4GewQBqTlCeiANtf7UprubBNu3GGlCJQJQM+wAWg0It6IEYzPIISUWAGTrNyKylLmrwzZgIVqQHrxLtmeAoEAhBUA6ynDTXQj8bIFR6IgAUKoWeIprVs6MaCHxBsw9gOAXiVE0UK4GiEhwrlEUUIukE4gKieCcTT6DhEgiKAJwFBOtKJ1sPBJbiZTUIAXSjARXwKA4Aff+IjrU7+k1ArQ1LS9YA9Rx7hpiHEOhJvOWSvRUpaIHpAnqX+iIoHerS9qi/mvggQeCkj1ebNTbcrmfCe3W0JzpblXfK6hcmTl/09EorkpoHFuCu53BpKgsZDBDxTDrdkdQBSYG7FClFHZc+6XziuNQEzXA7TvYUDnv/dN8egm51Tx/FFQ/4/VQXoedPAyAT519bkPocKYKYKp+UE8Ik9XTRwbL54ORvVCsmdePea3erUVxzRCoLzWbTgrl0wUWrgHjgDGdbqPna6i/flPvyWOxqo9npJgpkkePpsG8evqrCLCuPzDfVL4v6kH/ens6DJve4Crnsc+c1zobidH5XlvvXD4/Hw8eyMti+Kz5WFof/8OpY1Sr89H+L4/PDYxX6GtSxqGH9aHt+XqzLirnul6T64a0gWTmhxMOkC9klpX0ZQKvRiLviQGNVPYxdpaufSfEuOLeLIF2IM6pgv7ZFiwJVTLKXViXeiJH5tNwfzpWJqItKLRqDStu968PDF0/79fbjF7vDh+36C4xh/eLHcn3/ovEcVn7F9ui7vhd0j8/igLyuKVaH2dfVx/+7tdAsuzLvxXu/nW/+JB2Sla30Z/XrQgzfQnAg5su53PxflSd1BHfftebmlkNpfbZ6U9qTy/uO6Vei1iqmt1y8rE3mS9UKZXVagk1dNuXn4P2iMVEu1vdiWpabxWP3wuLueHhYGMTfL84H8RSIjWxqNTPaZlaeCeI5s4yDaoHkuvKV1r19OhdH0dcLwWvnZpyDmbaDpzOjnCBXmAZivVZD/31lb2l52+52xYdy+eLuKCRkv/harGmn8+KrXfkoxvYsGX5RyVj58Lz42VVw8WvVnMfKh71Z7MVcXxyejgshyMdt5Xaet0lS7+pt0l+ftvu/P5WNH1lvBv74WVlv56ziHNblhn9cBKFZtfDcF9vjS9ma/6rYrCbg4ufGbSzkUozM7eFBLIub2iVTt1YsK++Xj7viuTz+WKEwvn2qxF2hPIrGl/NWPvj5u/JDsdueHpYvjmIfOqyPxfp5+f1u+6FawZ6X39VONTH0Qr4rwMOmTgywfHPYN78L4X8oj2v4bfGqXeLeLyVu5YVWadKCV6Q9uzIXio75bftQS1hnL/5Luf1wf3s4nmqMwV/KqoMq4/Lp5uviqEy/9Zfjk5CnXfPLm//1stj/o/D+fNh/ONRP/rMUvxe78qH+1hheq0+dgfeVkMdSWk6rX/78VOyKxXdPD49Px/pBa/2sC34axq/IB9XSUIotbS+YFx2HsBY/THVgS7WBv7oXNex/KH8VAysGaLM9rcWcEaNf91axW4ju2d6JWXpaPlezorGdbvcfFk/77XlxLNfl9qNYsM/HosasvJdomYrK3e7wq3QtCM3p1Hz8/u47UXH249OxmqVBvIxW1V8Qwl/8fnk9uE23S/4rAW/a6YvQGz8Q3WZH5fjJjLgcisD5VihHh2O1qd/WIJwP9+f7w9PJ8McvhRYl5PuXk9Ux/6Y4/lKKXYA4HKXP6mux1f94vz29qiU0XGfhpihKb30bRl4U3ubebbxJvSQq8iKLgyQIgiEvVcN0vTi6nPwNRy5Az6MQxx7/fqD59+WqUjn4OfyzAD2dsWOPbimX798niJ7gSr7/Lwsh0dJP/+LpeDgWg8eLVfXi69OueBgqGq8ixAlUc+L1SbD47WH3XE2O7+9uajr9SAILj031FE+Q4WGOeCiIsYjYsxCz7RGnAzEaZHgWTM0vCE+VXzLzC9qfxRcLvic2mRtk293UxCSQWhqUDbQhHI37aVecdqnpWWPEXN83S/JptvXmrkiK1A99L7stCy/aFJmXJcXa29wld3me3vrBehB5wF9v4mjKelPJs2u94fCvAYp8abmoV5a/nbd/f3KuK2GAv2T/kuuKH2RD8CMLAxr8qOs0MF4Rd1BAYeTUvEmNXsRRSx0RPkKUqFU1oI5RGkBDIv45OCONFVI5bV7e01bKmJ2Va60GjUiNWBS2e96SsA6yu3V4W3hxeFt6kb8qK5FaeUEgHiS5v1rf3c6xJAh+boKQtyC4FwAOt9oC0Bkr6wXg2+3j42HxQ/lh+3RyLgP4Qzr/KuBPXAWyz7sI9Pg6NOMzdZj0Ga2pNySyfKM2ZvoerYEau41lILMsA7GlCro+9Rm8+5t0megPnznaFeCnYrezi7zE7rHEPojCbHObJV4pNk0vSvPUK0Khw99mQbze3GXFKspnEPsOTxispmCLxYnFvhTcl8WuCmiJV9WqwGmMtipIxbBeFL4pNqV7NQivDDSeuhykn3c56FRpUKnRdaWcbeDqIl42mo5Cur+IaOFZAIVO/qDJuDhdGkJu50mj5wVmtXHH+kRR/qkC2S7ebHc7Jc42GbZKbyvXTkmqf7/xsykqdZS5d9QySpO4WN155SbceFGUbrys3Nx6aVCUt9FaqNgrTaWWQKtadN4VH57256cHJ0yfSE++PFXY48pQen6xU2be39+Ux8ovMuy/+/Tpn0cAP7NWjggjhJyhy4ogxBCfhIA4RMohBA/hdKlONNdlT6yL9jN62l97by0k00FO2jdRKB2SyDpRDx1wE+sB95vyoUcWKxv93a740Liw60zBv/9Ufnf4WIoZ+2fRhjoE3iWtQZKvV2FReIGfZV6URLnY6TbiFBzf5f4mWSd+qu10HQIVLWuHxV8OHwuXzEb/1n+lZNA0UihXdFfBhCW0GGZfsWfjwC+InZawX13uclPuLLzaqFtaseqpd5rAcWLXlKo6rDmm1kPjq2Nx2yNkPSJ0W0QrPy9KLyxXsReFYendJnHqpZtisy7ypIg2MRUhmfSwlqC3xf5wfHAfHoMUf4n/eaQn+azSA4kiafoKTFlBMgdSeDwBEGLCv8x4Q0uorYlL7FvOgc5qrRRpI8xos9QSbXZ7eBInuddnsRf8tD3fv96vReGTmI5vj3XsR4NbEnP/8b7kaT1rLWYHI4N0ty4jtCRIv4h5wSUa8eW5chZXPSkk8fu7u4r0zw4nf130i8qlXdYll5unJo1BpT004iR42gmalY/9u6ffno7P/6+U8Wok78vt5XW0Iev2OqplbkzwU3UkHRf8pHzmDPLVUs0h3xEdF1wV9wx6T+QSxFo1YWk3v/eUbssMBFCRCwjipTE5l1Vo7MvDcVOVDpxc67pUBex7WZb7r4/bshKFCvjIvs0AEJw9FxbIzwHJMqVFSzkvHSAXBZAwKoT/Y7xW/V8SG0AWJqpNkMCmABNFYeZ+zKRPwpxSgzlqH6OxVRRGHJFKVeYbTyV+ktUH1G9AVZaV2Tpbnv4O9f98A/EVmIuJhiLgcQlHE7OGYnk8LZnJ6kkgAAmrpkE/GCmE4Vk0sgdjeRCuixh8VwSMeozxGj6mlZbfYvItId+IJ4PswnZQP0Hu+zRFMqbKJnmz7bZiamYlqbxsubAZnhgSLqbZqQl9EoEVoL7RTc4MaFA2YktdFLqNXQB5fhUJS03U14UBkFq+ZntS7Iz0DWk/hatTFDo1cVvSX1M8POlETmbsmLCFFnyK0qdRprHZp6QbSc10GuFYkoTcIdRK66E8kKlHsfSY5jgiL9EOJDZOOpUtqq07Y7U7S7Wsl4w+SUDeJu+lJSBfbpd+DzhRbhqdmsprTWmQwE1rnmnyA80BhtYeEhdJQiHJK1piZX160nrM1NGB0dM0zTT5nUxk4ntSISVqtEmYCa5veopojxDpyQZtS+NM7Nc4b0DTwJjAQO/Jtj49p7PcFLvpQrAx1GFnT9HcDSUqKbgakpWR+tlIEGLzjaxkxHgP80pPxAxTAJdKizeiDZPyIUyJ2GKIvwCnAHSckScZAwzdyCmqQslXOiLk58TS8fZEyroVB5jANLQEb0W7n/CKQt6uB1qCZC31scUeRjBk2DjyA20cmdmoFxETGiqwWitQ0DGHaysaigvIutiynRgDY+RENozbPippFgM8Cb5c4cS2oNfatYg8I92DY2zJaezhIQALYd+auRi0HiRJdnEe2FITo1WfbKYOCF5HBqngi44EyanZGVarKtl/8dRASuEKRndsEjpKliXDDYOrAswOWMiRDQqqolGiBHxA54cl47GKaO2qgBrwNWCThKk7cxYTh40l7weewIixzMfKaWChxfmEkf+85MG9YDTwZUEtSBgqJLknyGmU5FVA1QSX3djoIOgSLbkpESs6/irbONEGzEBYiIOFp13h7h2wrkI4PQnKpTG/xDZLInm1mF9kEm24esJgD7e3VghIzUhjfE5e3LEICbJfETUUclYYDkfaDcMpcGVYPE5UNCxAvgYjWy9USPI0Uq2KJMR1581FBZCE3lONSovHjaNoQkbcdDUcpeunw2G6XC9/eHGQbnfFri3etfLk1BFAPx32tXXx58obvN0LBhavjnUexlfl8XhYbMrF28P5cNrWIVhvtvtDZUU8vTifi/UvdZq5noAw0ditjAN7tT1v/1HuT/fbx+UPZeUHEmw0+Xy/24oBOD9Xj59uxbvuaK9Yi/ZKspyEe109tkuFkUkrsHrCiPgSH0fHe/3QfiPxXlG0YsR7/elPgvjHstjV4Ym3zws1FeqbmLtwLmvsVuYvm78kr/7SVf0nY7ded17LutsPu8OH55swjj79jwvtelWFcS7elcePYoidgV5Nt/x4kB1z87Pstb4YsCiOHDFgabKaMTczJmB9tT2un04yIMxEZRoZmVtYZheI3CFLVIZXEx728knMw93ix8PDrYFMcQM8qzFrFlLFUI8H3VZcLBqOpM6/uL3peTwEWcm1FLDV2qFhNMMgK7LV7Z2X3d5tvCjP77wiSgovWfv+XXKXbsr4jhMqVuc8ksBNUf+tG7mZE+yZ2Lgd4LMXR1bqiGtAzzDJ7E/FcZCHqCr/Y3HYnga9+EkWDAWYNYT6Pf1tGcUj8fPHy+4yjzrZkjrdwzEOrpfCj0qRhqMZHFrBaOOruyl8SO2kjlhYAHhQehfYnsCCBkq7+GgGndnbFGt19zUvsrY01soa3OvNMxrSNm/WrNPt2teLXSURKPVS1Q+lgyzV7hzUssxNGkyBt1ZJZIaWnzv/rrzNy413F1cQ8U288bLID704WEWrwi9WaYHrTHOJSL3GvCmrrnLDw/1rp5f3R64RPn+NyCJmqmpd7n05gelljSj0cC+MccOlLwuQ31rTLRh25RPlb0FcG8LawIArPuowcQsESHGLbVkZFZnEXc2SD9rWf37RdGsOSkSH8XZh3kn0TZLa5PHL5z5pTLJhaVz5t2uxPyXe7VpoBFG6Drx8nfreKgqKOCry6DagGLx4CRL5rZiwh+rk5RTKiIc6/wM3/rFCvfoMQp1oW5y66Qfv5lOmc7gqT1no1WV7YHMDwzp+hKyYvqKldku4jcuQaRMFqzO60tmDOjNrnZHG3/hIkIFbHQaCuy4IDIms8VWDgSGJTVaFgG6KTRiGWeht1n7uResg9/JVnHh5ka3T4DZLU39FBLS7m62WUJnhqGq161oWqpyv/hvI6GfZeOu9qXViwYV5uXoM97vDJZt4eV6uP27pBeozXIGHFwziNfR48TzcHt9QMXC4QWoILNZn599srdnyTOsEjQsDrRt9BrTuUrtsgqN9Dt74QC+R4Ejole6v4OzeV6qaY0UY15GzXYnBGZCh1nJ69g+9EoMzkYca+dk6aoAGZy7Zr+aod8kL4fdhDxJbN7ZVd02Isdx89/TbV781+SOr7CR9KP1r3+jR+RLmpN7S/KQ5J2asghAGNPuMd4dI8Dtxg3Aq4NFHsp/5KhF10am6K0Td0aHu8DCw69UWDeoG7NDtdg4njwDucfZBIffViduHE0PzagivgtKiAADKfhaBerACcgGQi7qDgVIxUK3wVRXIUQgk4A5uZR613Z0B13I0Falk13A5a6xqT1SNqaoQMGg+dMZKlcjhsa/IqauNI2AfekaBCdRgQh8DOzkQQCb0eyhU0mnj7gh1LUXNHEyDWBFXSJb2sKpKJaoUDBiwq4YW5ow6s3rQMzCcanTUXFenx0DVD30IpmVFE2ZZSz6H6Q6ar/U2AT/S3rPr/jmUWHWPW8hC81jSU2QD+BU/h4ouXBsv9XAf5nqo1Q0ng8g8PITAkn6QsCj/vkYcmgunkUA1V54D8iUxOqoey4GwDy1oWwnWeg/5BtJgQ4S+9sGi78e0TlmRDxWpueSDdwLHwQeCodaFgKG3GGL9TG8R1AQdkAFB1YVAGoDshBxWA4MMHY58o+02gjdjoBhCmxUryCBYbfFFuJ1CPoejYUCHsAHFywd4OzhZS1sIPHRy3rEEcwN6EoYmVcxlwI9m3UbbtyziqzdVfUBZwbtxQgG0HCkQyoAcRP8T9JHqXQhRaRCb+AaIALipGpM+LhQAn8aJAx0PuDccw7bnVcSDgh23D3O13oYdyc5bRmcHVgKTA3CIphfPAwUlVW2OaIepsWgQ9YCxVzu5r5hHTwF4EeqeBB8l9JXhBvW7fgUtxsPPsgSRIdA+2tu/TBeHH9IKoQuh26xeXrUrI8IewLFKG/PVvq+6D5aYZhqBJzSFUVCdBD0HgEkwQBt+V1+pMTVdHF01jWGyNLNQwdwR7gzgWtOBG+tsKygzdjVg+NEaDtojLFpK90AQu6ceeEpn8pRI2M36VGRA8BpPmNKTfKX8oM2w3WozrZ2q93NVI5jfIewD3AcwOgrGSkYHalNeNtWnkHMGoNkoGo04gFIGLYQhA/0O/Ac4kIbTArctWPkAp6BQmqRNqi4IVoAZAWELisNUdYQK+gSnhYpLURO6kSfQNwI4UxFDMJ6O0o6m4ehBtQIPXYHWRGqLlU2AhUDNRQj4AOCsOp34MDEiqDlRVQRKIFMooRDhuarY8P0YBm9oBhqdQbXpSKj1Qa040AiIBIB1Cvzj+g1IamKos6M6iSI3OI5wDJE9BIutjwspHAKV7uPjJo3LEBxAqAkA5qLyu6nNwQBAN/UGUBue85OuPzN4ihyHXQniGexEDg5akvdIG0o4ripUtB9n41HRtZXSREX3wJ+ZrqyoStP+WBP4+nD8S/nb+RtFuEGMDWKjdYDzm4qTxZ+Lraj6/v0V77G45PqKJPM/1U7Bxxe78niujE51zo7qQiEFqW276U15rlCYxamCpFZ3dVjuvajAx3xUNICZiflRPacI6Q4XXcOlW0tiDa12YKEVoYvuwLBiov0w5mGii/2i2NfXZVU3ED3el+vnASR0sqz+smW2qiHRYfNnucXCQDf3gJpNxLJEJrvxyK4bJSSWeEnmxJIgrzugtYRTGyBqF2L61f1WzDjxBkCmXchoioZm3XQRrFLfgXKOorhJtvNDWU+RSiCOzcfWX29NzXNzUWIeUWeTKa5KsHWVtDyyhv60PKKaz4HwrvJSV0Ms5tx+8fr8j0JirC4Aev9YVivfCGB3jaa8Pzz2oTzaIje5FcA9lEg3W1Gghz5xNKz2+i7bFMHGW+V+6UVJsPKK8m7lhX7hJ3kRhIFfcrDa7RWl9Wi/eDiJ3t8UzkyhcUIAIf61su+LBet4Xnx92P1Srd88UMer+2oz3Ip1vU6Z3n+xhz+Iu0ZyA3nWKLeEEYILUfe3Kiu1MqYDvgPsa2Cwg6fgdQANH56qg1N7AAENTWnV9Sd1R21OnrVGZQviGtph8LyytUyxYeMSW2Q0eTS4y7KM1OtHu2TwVwi5NEip5gR/1ItKX7hHXaBBFo3MSZpHY1aHdBWG8aZMvDit/Pd+mnm3SbD2gmCTRlmYh3maUWxYa0Ks14Ef6t28Zx2I6DoQXAoM65SMPy7AY+yaE41dc4bhZBoLFFOmeRjh1A62AThoK3CZ+gTmadMcriyWYKkGI3lORVM5d8C1lBmJUK2Lh9kOYGllY1m1SGPDzvH4TMS2dcOMLLvq6tGk6u9ZPZoCN6E/RbvwwzHrR5YVQVDGsRfFQVDhfwrv9jbKvVWyvs3iaH2Xi+M5WT+C7vaeozhznJ0rR05Q39dKvTpSmFefWZjBvILebIlZUILgQUlpO4JfwbPkmTYWqTBAoUAVQseleuoZIO7ExIQiZxZ2QrNCB4daxWNlth/IzUdvj1DtI2u0RZsh1X1HxsjgTF0461t1klxs4amXZYkQy1t/4+XBOvfy6K4Mi/QuztdUsZcIn+b2DHFeroLn97xrta6h2U8SzODzCqaeUBQyTgFsClNkqQLKkyizfWj5P37DZF8o+opm69Vr7LQGOjvWJNHGChDTq4h47dLzbUqQ2D8HSpuj2I5EaXP2upEkOcJ6LfQ1wy7wB6GvOb3yhyKnOZNraDg4s2mIBqujhpDTjHlgRU7rew9gqDuj/ay5y7tk6fMkLQ8YlstLk5YHjMToo5OWZ9wOUwjvz4XBHpUenVsHpEdvEtlcCsmnGO+K5EB685+Ko1AmxX5THsWe+EW8xHznWrpzds+5U5cDIrvbaQ009nT0tTouUw+wp4yBnjpYYwZLxQQcN/g4buWztcG4IVu5gpJBynHIcg6AcA74ezrQuzmuqIwWoPIpSIinrJeQHR0IqC42FC6C7LbCwMF0A+A8VcqEgmekc8HeiuABAxRuBZBDYvSUNg9HwgNH/ABuXFdDR2DEFeYcEqlnikFfS+mp7NcKyEEw5itVHq3MADK3otD1HO0G9twHfTnTdelMO6zrlm9AEKtloGG1HQdVcx9WHWz+YEw3IesB6VUF7kJzg6yoB96u0FOe2zgBvgc7+D2j/aR8DBL1gdBsE/uufBWAgk+BJwcgHm0qADnWSyCVfjw8GjlWtCGxomHA3h1Q95iyNIB1Hwdk9zFQgolkh9YMgNqXKg8jA71O0sAPQtmdCeBdYHaSuR2R7YjjxCIOODtA2H29gwMojVQMbDrYw5ddvkc76DyH1daNP/f6Qedg+Ab8+VIloQQsOmRtt4PO1ShhitHOJwdDoRCAmAbUBzODDUGuxsBqxM/hbYV8BWi4D3nEARpO8e2WbOnIFkBFPd0cY6C8fbCmdDBvNSYBjo9iTTpP1SDkikygjw10l4He1iDXaKuB7PGAlTbw3Q5kNtqEFaYeO8ADMLKBy0YwNuYSxwUIMMNKNNT6hZZoNGKhRRgrG0JYO9KE29OBp1oHqS4wEoF3Yk6mCsCtDVw1KMmQ1ptAqFV/9iKpFSQaMuOayce0RGWQ+t1IzY2JvB2gaS5SGnN0+3B+cSCoXbBnMDpCqgiEn5rQZy2JTLu0GNm1IY02JPuGPNtKT9MS0OBWDCLRi6uGPNsAq45JsyHhB7QEulYHR9uzZdOYI1hijBQ6Wq4eDyC5cCaCUKXuLagU2gd6vmHclhon1aLx+o/mI+KdtbgMVRMXSQ3Q7Y41PPkp9DN4lzG0lo2lpimijQzRkGQaEktDNmkXrhr2ezUWEBs7BlSNfgAEWDcH9A5IPSG9tD279MU46lw0pynPBYAEESvvdC+22swc3YO1Roh1h7v+TFjrVfLJiZnuTIsKsczOHQ1Jos0M0g6ktHrn6rmjwyhl4KSLxeksBrPyQlbTebnZntYHMSkWjeu12C1Ed23vivV5II10mi7TvP6L67+0+bOkke7SO98EiW/JI/0vBa6u5qOQND7I+hJstZlcuuvLvuzSeZ44cNdJEsyHPW4hAy3cmHM5cgMN6gEMNAXE8m3Nltp/M7KvQf0a+apAAGWWr8ONH3vlKsm86DYNvCyIM++uvM3yZLMKs/yWA/qVwU17lU3ECQyIrnxXcrxaVUs63EsMkVfK3qPHTUKUFoSywmsYtqmetmXVWcZTu30bkmsCXvUKTXoRpWfzlvsWb7nyurWDAM42tk+EnfWm8YhcMZ+O9b5WZd/FXoLgdRgoef+JfYCVJdNLlkboJQmGD40poQU6SzpqzCJjOsTqiWQspeMM2RwguhXi6eG6GsmHegVmHcb8q6fQQugYuLsF+hXYhzBNkAfZBGWT9qQxloiQKW7tP00+hlh1RKA+EgFqnioy0I/AD3CZCmHR8VE/lGuxNO+eXz7tdlshPqtlvV2LiSWWtd1O7AXVXRHflrvHm0o3rTTbII7Ha7a+odoy1EulL1KNLY7yqdFxy76Scq+cGkNn0RHruDbmDSNNWauG2JJxRNNZg+fEZrD9IHr2rzJeSj74fl8N8U2ULtsn3coiHxy7dbI4F36b5K2m3lyBva1Ur13xXCNhPuwOt8WurkXNqygQe/ZGqCmbJ+M31aEroztXXYvFaarpFYwg6RqHemwW6mpsrx4qjnq2P4se2qpu9bnxIiW0u67kj1dH/yA1tO3KvuC/KHfooFloVUHF6vRsYFumxcRpoHL9xhMHxBxTjQ9k/q+B7hzcqx+sWlj8TR7Imiq7WJPaOMlUQvIgtKq8YtaIcWcrvc2SosHS/fL2NtykqRdF2dqL4s3KK1Z3Ky9Js01S+oXYMwqO/ivhB3uF2HAC1n1WmvI/NIAln4KS1bOK41XlBngkWtoMqGBSD9THWCsLpjCoAmyEgUXltlcI9KBCnftAb0jLp10nPz/XpojGliUGVvTe6+OxjSzt1dnbiXNZktEeHXu7vxODVe24QTCQSHQAmff9Y7l/eTjWtrDgCz/QsE2JHVR1PIjlUkiBoZtVytHLstx/fRTbmGhmpVoqZhPfju/7pDQIRr/EPUAvVZeXrGhlsgo450DpOHckAu3uHTv1llfFnAAvr1GoTbEA1xJID/imwHoMvgwDD2OHdEWa/BkwKy1lITVcA+VYlyNfkQu1+oxbhpVXwgO3hB1Qb3fZahh06uls057ra48O1gK0C+BPoCONNS3WGoY3pOqrF3h6ATsFwB0w+oMXzrh0snXLMU4+7fHGD7IJlvvKAjX6fGO9SdGf6dgz4TAD5xd5pGkOHtcxeY+wcA8eZmJ1mOmUwe40I3eQ+jQjVBx1lHm9/yg+uk4xsc85xfhJzzFmda1TTLK0/fWcYvLkn/IUQw8v3Znmf8op5goHFlHrB+sNK70nGPvBRUiMUMrPfTeWtUWEdjw+2t44jeDSoh1KirRMori884JotfKi9cb3itvqeHKbRdntXbnarALOoaTzQe8NBD4vau+f+HDCv3GFxMlinjTIP4bQSYQxmvnKsIwFJamnPCXAcsxOFlqOKISjSH/bQtWoOXa2ZtpRpf39b/utkEPx3/ONWBGfztXU7z/IkLl22XnGd6vtw8eIpdR9qtjBzbH8tT2D1DGpKTlkDByIruQ9sWn9JLOfC74b6fMA82cDJp7MD4TSQQABuT4HEVyZOdsR74JJp3uxL4E5XxEGDQg3H1O0GvlUETqMsGnsK4Rqo+QGRB4UfeQZ+cG+teQmRPxdqPcD8oZwa+QH+TRTWpMchqHOG9aL/CQjtP8gDscr/0E2Qfn/w7T8/svQbY4JpdWPTvR3mVofglqvB0wq7Z4uq7WST9FOoPC3Yd7tbdDNEu9S/0Xtk5wYwfW1/3hp++vT/v85fRj/1v4v1/4d97S770W1JNa5KM9WnF+u+csFyUi/typK/zb0os1t4kWr0PeybJ14xd1tdcnVKr9LWFeltziAPcb18qA4yfyqenKpHwHS1DTt+r0zg7X7Z/ejAg23ie7r7x4ghcPuNw/yeVsUcQjzWprxdgaZhhu2ht1op7tnu379dBKzt1rJ+/TrbmAvvI8s56mqY70DtJJkXNT+1VTtzw1UCsncbQN42tCUTyo3u5lyBWNzPIhpULMeAEcQKYGIJ4VyUhgpW055GsypIgeUERoSekuewJiv4Em2GE9lvwY0EYRp03BvQ2Db6CjMj+5T4eu6obHtg4MBuhJC9jAaTfWvgZuCECBwMACQSYKuYIzo+kOjwbyAkgJKRhCQp7ktbNEMyr2i3Jj6MuVB9DnitQDFhQm1CAXlEdXjwz3N7aocJmM8D2GcTHA8VBDp/4bAqgl4e3Vg4SDtG8+G67DSVT/aE+H3wKrUDuV0RSz7CJqujUspNtiu2cg5D2kMwo5TWJCxnDDhH+GECZa2vz4oWfBPeQz7Hw4luwpqbOCCexZuTJ7Tes5gLXVxCFPHuhvfTxVQzE9mOJ61a7B2PFuvgnK9usu9MAtvvShKfC+/u1t7yfo23NxuNvk6ztiBEl1u064yV3r0EH/J5j+gZdN9KXiBGt4t54G1Fa/M8iBFgHFRk0y9AMmB8Po4vCvLAyu4vJvQEmGBbwcOjnq5CNy1cU963x5OVX/1H+XkFJgSqRE4QE1OoJVUyN7uys2HcoPekGU/CCuOvoitp6qxVx4H6YQ7j83zlbK4w2BBIDfeiEkmgAocx3HWspHgvFNXj9GrDvFiTDLdVMS3B5Z+D1KShPaJhz4LmI4q3YV8kujthPdjeAwhEVJ6INWHLKEKIgGI+vZUKhNwI3k0Y0ab1ED+iKtDrLML1zbCfaPk3k24Lc6DNDBEHuEKTxXqjHciguOKCDs+7xxUqg7wueE9ibg6gRvJa8KoZTR0FE7wq/hh+t/ybGN4YHinmgvcMLz7lgbPNpn74NAt2LV+36giTyfQ8ru1ftGEi7v0/SS5NHREqvvBH+51qWTh3+r+v9X92UBWoTXo49129wtfl++Wlk6Zj2plPi6jTejf3Xp5tt54URmXXlYUkXdX5nmY+LfR6jbiKPMy7eWeZB91eltSkhF9dZWM6Bf6WyCRJ2RbqZ+qRCIepP+C/J9QFtDMQAwyr3gqbZenctqJp/bLgRA/bRDUa0x1RoE74NlS95x6vZoOVwvn0JX7vxzOFYnNi7tjUcU2LaXZtVJvIAjB92d071T60Cj3js1VAnEHsTaEALiP9IGF4W6g9SpvLYYukBSTMPiQwcec6JhNT8uKRtKawUQGGipzFwZOQHQBNNaY24neFsxDGupTOjOaiLlAMdEkVARtVMkKMXYBAi9A4LDh0JEZw/RfzcHG9h/6E/TjPPtvqR9b4hAMnJKpMl85yc6Qcpz02ulh4asV5NenXdF8DtrPSlN+J/a9YrOQSXucMdbRRMO4H/0Thif4/5zhCf9WlS/N89MPSOq1f0udu0cz7i7FsF/2Ny4DkFw3auRReRunt/HKi6NSaMP+WujF/q3v5bd+sYn8xPdLnmnb73K37jFy0qUPiyPldW/uqgMF6iVn+FqgTDNut22RGYExf63nYxZhr02SF5LfpCEpslCh70XkPVnDilAJyW9RS8Vi9Nbqo7zQNtD22drA4UW2YWx2om5u8C8D+bIUYyjmzU/F8fv93yrzdPxFluqBx5wQ3yhzIo/4CKGg3/CuqvNXjhDhcTdJ0GYuzd5Iq96YEuHcc8GEHPxIGTq9zpDbzJJYmWK7aZGT2dTMtITMphgJ0qm1ItPcR4pytsYWaZT0E1I36L1twZxwtSJVU6kNSG0hoR8h/Rx4JHV15IMeEYoI+ZiQT7Cz/JQ01Df6J4ehyEh3Uz6o8IaED9rFMeEjIXyk5LeU/EZ7gcyKFTCZEybpOmVfJSPCVmwZ+Yz8lpIaIEtVxwgch1oOfcI85SMmfCSkrozwTzlOoTIcJjq/6Ywmc0yTpphwlZBvo4BYQTrhMBb86wOx1MFoXNAIH5XFS2g1XzC4AcFSe+wIhFNvdPkUinHEZ7EJVanvW6uS/Q4Fsxh1pb0HU62yNlSeuG3El+Oiuq99Udv8nNHyIec8GsR9Sb+iq59HO7/Nv8+j/zPPo3Pkmw2t6War7WHxvRgx9oETF70GT1WIo2W69rK7YuVFm2jlZWGUe2mZlXm42dyFGcsF47W55fc6ZMR56gw/w6mTniVV+ntPXcWBOBSA2StMt6eufvHUhWgIdEgoXfgICTJz2zkR6tY4So1agLlsiM+2wpnTYpFhhQNjtzHPiDqSNMdEoYy7QdCZ01ZLP9vCVGCYQmPE4FYuD+5F81R8h2OaIVAKL1aC1LGJ9jhSo50aszKhpAEIhVg71MbRuqDhnH4zcYOgoEOUhIlp8uD6H0AtoQhCQtuM1o0KPB4gIQImUzQkeyAJ6pZDRC+BfMBVQDp4CUYO8vFiJZAAtzvQrTRWAZkFwwG9h3A1E9XkqTufKKopyFYTzglx+C9/ThgXVq5OFdfAOV0CaEoTJ6CJLq+1blwdJRuPjY8K8k703aJLWSf69+HRooSPqqnq/6fF2+1a/DMBQpWu5oJQhdcLmfDx798hE/9SirjQZOqOOjdZoLsjbPu0Gmux4R/PP24fqvxoUR5noR/EsRhroS3c1T36fPNlKVaV5Qcxs19vbpI4KeIo9L3bTRXufZfdCSU4y70iWhVltoqiJM7qsm8LMfbludY4rMTePZZiinz1uF13V8C8knqWaM/ysea5PkTUV51UirhsQPPbj9XC+O2TUO8/1fGX1d/7Tgy+2ldngE2zMJ+qZorh+OpYiPV1sy3FArooj4XstIqUqOpVe1nK8svDg1jc69nRnuhFA5ZfdnrSeyVulXW/EAJUadpiVi9ePB0Pohahtu92h18rVPpuW94J4pZS7/GYQVMk12cCyysq4mGzPVX90KBg6mdLo87WOf10qi7ceXiqUFXLbw6biuRPxbGtHsq/uhdHpPuFEO9HsU89m/w1i+Je1dk5qZCdxlXO6YGl4vDF8WxhqDyWD4f9VgzXyyexcO+Guqyu+tPySyFVx/Pi68Pul2pzsg0HLWHS1YPkmhGhb32SvVm1qMoru3j3y7OlMkspS9+2s7uuyPKGjo7DHsdfLB1PuRYL3O65mgDHrVjpzE5/uxX6gVjPPnB7BWv/BBPM3RNq9tknlyrWHkffFI83vz8Uj7iurJsTWpUe6/+IB9U5OPpi9UW4FOXkcf9005x9i2NtFzueqx/fbf8hpsR9pcCcb4K8zTEn1oWnh2V1RZU4AgWr5a/bjdg5I6HcnqqlqlkggzgSqmEmVu8HISLVxVrlV7+dxSQta7Vx9UWc1/8TiqhcdL7rcs/9/L5uy3fVZWA//35bnMofS3GM3O5vvjmKlb9ZnMWSLja+fWVdWw6XEWrlaau82LURvVqcdGPHuSHydVmzLFj5drvbvWfVsH0QyuXHqoXnm9q+WJnjy+PyQWzKoonPde6H39tN5Y0sGSwf2o9vhAQfG3sQMttGt9fqbUWienMjGBou876ddS3cdnlodfFKMYcY1gP9KhrxcJDn809LSzXHQ7FpT8A/iI/uzqn2dDHbJzW8GaCeVlsLtE2uFA/R85Ma7BhSUObeVPY3nZFuKlV6VfftxUOlqoq2nut7SA6vYY4EI+dt1fejp/qEVzzjHaEXCZXY/YLMjcASngFijbVjokhzeRgW4LdCA660ZH36BzDS74RK+3hJhWQO2XgXqqtQW8cTm4+WyrQxSzvbgZowK6fMietOhzYNSDcdxDp73pVTRGe0wMn0IV3dL3ZPQhOvtmW68IRmB/znk9CfyvED1+QU0V6rr8gUHyyNMsoyxthWxVBfSOA2a6Q7fu+L08vqcpGHHyrl5oftR7EjtLYpOvVHN0MbmZfinLkvTtxx6G1tbdqztnN5kXS75GQyVZlmZyLVS/QGlfmnV2NyFOrTH3SV/mB9OlqbcC0tRKmoTS0nllqRTFgntZXMtZpkc20CE9YGtohbJAhXck156/Js9etvU9bnCZtcaFN+WJWNfqu9yGI0i026qgnD19Q3eWEct3KHNi57NiujrKX7uoq/K++wXmDIykvrs+udYMms6lXVz0z9b0Q79W3DVskFu8albCMlPiHmDhkOr8UT1BbbkjZVPQusq4B7yjP16SElONR3KqsWPI22py/NIw5cA90/ZQW7aHYOtTXSmsqbZPbhjSbuPtGU3UdmILzGqbhLbNkR/367Yxxx3hTH0/2EtTNyHSXYujpjj6Cb1tDm4clbpi7oUGqALOqrmU7vtvt12bm2aoRKg5p4v2xL/Hi/PdXeXl+G1ie+0L1P5wZoXCnMP0rtWd73NKSbt8kue1XzFrxx1mlL5fzt9pf6corx1r3/562YLdKL9lb9EGCpn788ip5dvH69bD+816ygkr+Jy9BUNcJrrwEbUUOfhtSkAGWtJ6G1Yvtc4ygPoa1q5jHFKQoOrWOc2hhM5Mx3cTZ1N/d75th0/Wp00+xMXKRJoSZcZ/qYQ+Nrh2DCrm43VXGsdtzz6Gd1FslM0b0LrKNQv7tokvXDVivbezRWU7yqEjLeRhvZ7NwDL01Zezg7gr59jW6MvAJ0Dt07tqmZ9p0nth5qhjsl1tTGGWwNPdrZBGtWrNkEuL6DC/VIrLJOmXqBhMyv6spcMHMw1bfLt2jerie+rK5iuEypmFfdT/QJ1QBTZlEjW/CxuevuDofN4rGeclfXYrmDPNE61cDr55rF3TPWLuQlQ2I93pJptIW/QAXW+TSxXwPH3LncV0R67d35sOdZkHTt0jqxp2rLzBmE72Ar/nYs9lvThxLNpPA6jxzT1eexmoS82mImFnQ7+atDYRp7JrlUuDs0TykvmmTK78rz4ulxOVpF99rLOXpVdEehfhW9iR1oNfP2i2b+iDSlXNYzRSk3VORgYPDS0fqXsXOMNU869dapB3Nvivo8eiX5jbdm60oNv6FDsphMNCEn0zwLKt6k3K+Lh8c60NUqdWJpOW/vnhfBBMFLOIdjV6lW9N79ejhuThbzo2yBPBnDg55DsaptxJ7KmAnGgvdd8Ut5slQ91vSRaIu0XXe28z1Ni51yiLBuSj0KLm9ix+PXtxlOLrwWG3u3pbPJWzKv5qh+6hvBPiW2Dc2cYUw4aqqXuNpmG44Zz1bJhGZeesjHZfTr4vhgOU6mMG9/uhdczTSqbQQyyIR4Yz+u+T0ezHT+E5yusjCr6MUPNae+dB6Ax8SDWaiNhG2UuQ4Wo08YpwDrpL/oPMgcGf1ENB8jU3iggzBma+Qc9qZokb7NesA51k31z014z0CGOU7OwUWO/nFnuNbhnYas09yQR9tR6OLTnJ/YvNm+7Yw3p+XXOPhNcIVdBvH1Is4Z2l6oD+I71OeTAb2eDmTpc1DZUL3ZhHMvnse/fC7Huz8MVWLs8XvqMbLJKjKyMq7CN3T2TQdhWNHoBqVTnG7piN5DFeWvT8Xx+GzUHwyYWC1HxHSi/y1lHkHTie6z1ObsZ514Il1LmvugmDqQG+wjscmzldy4U5rOIcfDZDKSXNZ5Q3W0SU0Hp02Tx2dKAzJLT35fnLYGq2alqa3Sieq6l1hbOvNJNLtstK6FbnQZ2c1zazZklx7RYfrmaJsJE8+pxjjytCbjtR7wHWfi6Sr12Hea09/YtwJXX/Yecy7U/nwpy73qn6NUn/7X5cgYsuH+sYbsOdovjk7F08YMkp9ox/Zdy+sYR8vInpyUSmGo2+xlrtJpvkN2JkWGWjv/IrjoSIIcE8YEq47n2+x0EyIsAl2DmUu39/pgEdPirEc49pmhd5dFEHCiV7xBPBszAmMKLs44+46G9OqQwRFG3OluOm7AltWtOnQcHgPZ5NjMOO7VQZtMuhyfqYZjCYusljAS1/FKVHU0wzkkS1Pm7pBcZIPLzdgkML81avGFvFZZHY0jlX8d23V7CcIk70Sv4yXTbBpzBG5nut1sRl6J+W+7E5Nxyvk4HO/M0xlxBe4OH4K99o7GsR2C1lFR7tykDBy1vLQZkXtXlzYl7mdBbmQaIKCDmA8nemKNM9K2RD2mwzTt/W/4iDMNDd2aCmZqhmFosptzDAWPRZzz1pUCbbrbePq3O0ep/v1OO4V2X/vOX7KifoPJwPJXEcknjUQ+sCrZR310Xe3dOuPtnZx3+pEU8lLYOS2eyZQ+iGdiZG6rRJugfTC01ykN9rjeJtnlAT5rql/O8YG2Fff6P4Y6Ppoy+SKtYo6SIkn2Wsl8lo+0vgJr2DftXqI4ZjLXAtV7IB1cMgY6NmSMKMviaYzo+JBhNwnTRsYr6/dSHTZy2yoatviMfqU160w8kRidM96Q3AdhmWJsCpjGJsNgMwWcYw3tucAAE89kgJnPVuTy73TBiBeGHXix4zhz5RRziUS99K2sjkJ9C2t7X9kBv1yanlYx0r8J2VT+8eE2nhV9bpGg0Ye/QeR+ai/Ur2sP9bhQMOJh01J97/OH0jQudTzNYxv20gmGwMwKI+FYQsa+ZNNKJzZ0aGsfJpEv7QExTAy4ebri9MaVTpt5Y+rqnf72MldO6pBrNrjGeDDaa2929gTQUW5beThTTV8e+fNtaFvONXfGrGkpGsYHvSUD3Z2P2PBZIzc2EiWfAkfKmbalfIptKbdqj3biHBBPv/DT7FoMo1PKMjo5fdgXGJ3EZphZDU+jsSbqzup5AhZrev5qLBvyuuppm8tqwETLxKsPzpihWdHdy94/Lborsa8xLxhKksv/lk0dhMw65iwb4uDYjdvqDXNhqs+PCRaONgh37KSWFzIyz0SdUQHp7Yv6fqfmXrbKIVJdL1Zdm3ws7FA9Fpe9HshY77ELI0vtpjAVA9Fe+DIJujdi3RriLHSug1ZcKsMoRprZZxW70LzYcD6UZ7294MC56sxlXxwRihEYk8GBBLKdiP0RKNmxkbyBa2pdkgp6ysLqz8mIa35PRB8p9zFWQYaziUNlkZ6Kr/ZdTpjJeSX81jUyF8FJaF5vGpy3zzA6a2ioHud6IVRnlJrVJRboW+667FZz2qA0hUnWMYutdz7cYmw9/DFtuPG1DsnOdBAT19TEYXC2avYchN5laUQNzTa8fF5kVvvLq4MQGlNxR+PP27I4Vreqj4UcTIoQzJeTc8OPgSsZxnSrFjkikNPXrysc0hBn1AiaU/LYA1N7Vr9SX9tvWltpU4sHnuS1JOg/+uk+D6u6PBRoIG936I00WFkLXfUKImv985yxms41DLADr9VvRXyRmsTU2FDR+i2bUZR7JmPFuDW8xYYXdJaW18Q5ZtVLcXBNK4aQmc5iUjM6PNTFy8XLw68WEFB75e+BfBvKbafqnKtD03FWI97sTKetrKY9uiY3OjC2YYIdGcsxxHL9gDzWbNSsrM2XXsL3ecYNZ7m+Rfzr6m7pfRfQ0H0dbd34oazasWhOiEsHY0ob3IpTrDsHxBw31LYbnz/lVszB5LqtGjL+khyuXjRTevPWqTBBp837uHAEGbHQuVxmBpJIZPrYTkFRplMZsk2KVOeIF9PHM7wPtXRSHyZz9GFs78PJeIR5wL+Dy6Wj0GXw32zY8fTi4fbpdG+/yMcfvM+c51sYC5WJ5pF1lqLZWeovamg4Zo0cYLXHLj/rOfMyUzznpDy8bc3fKs495RNWRQsQeeJSPRvyaXBR6VtQHNbW/hWFLBG2pXoSZpV92/R4d6/nW73gg3w4pz2F3llvaJrs5LCC5TlehNGODGsGFGY6u1ldFk2a0fkIxmPOtEzr+wTwept0eFa7+kz5lTlW9xk9AtZcZEwru2Etc1jZJ8Aa7ShKC/0GwskzLkyy1LdW51nG1sLXJJaMl+xROP4ke7k/oqcG93J/OflmMx6j8xHvjYCXJnHcWj667l2a1hKO7dng8dKUQvIm7F5Lv71Q78FnvKlfHIaC4dtN390f1r8snJebSlavOEycu9ZZYhGPNgXNlX+su3yHYR10JiSwGgeHLd092cfsBxDJxXUOIDNGOfjyCqdBWRqLsJgkTLo/QdY8yV3jiAidmtjbt2bF6qtkLAredwVkThf8maj5LqgUUxkc2ALmyM/XwcMY68PIeHgmHjswnGGyMuVpZacBH/L5zIoXVBqUcaj98Wm/ORY97zUmJJL3ujTS7AxQqYn43Ji9scBw2bZpOYbMXh8bDCjdKNz22fXi1aSq87bm8QghJ7vTUq+piInrgM4yF8sXJIFmjxgzGbkxDDynCPbZi93Tw3ZvXtSQjROdy0OxB2NfHIV6FbEhM+Gwf9YQ/o6NGWBh8ahJMcFyHbfMXnI4HIOZckYKWG51sEU7XS+gwH2jw+Q1hJE1xjq2VtxDT+Jolpiz76G9bNfwgvEcabB8ppz17+CcsI5BhdbelInxC63Lht6faYlhmCJWvkNcqBflMwiUWd0cu9mojdaZamcSXMOTfrbL0y7Pfg2iGeM002bd59lhHwE4Hp8LDnjGMjhfXgp7wv8hHiLHUfoiH5DrupvpF3Hr9/nx7+Ga6hBMJpo/amX0gkvkDX/QbCmP+rYlT94NY+4/+TT/kcuN5ZgDDu8SxyBruJY4rqsRGTnmtsF0UP9hCL47Z9CMlnlrfurAFh//eukIlDejF+ZNJyKDLj7vVW7SW8aw+lpKXTVYgh9T3LHHGpp5oLZe652c78qNOU35g5J3/VRFvKwUL9aiccX62SJvwXVCM65oeGpsl6Md1oEUrukWwcCGIuBM4sCKU5hgr6gpca9YnNRDo2ObAtvmyquL89rFMrq0pUvX5dRaaP4N0n6VKRFVl8tasjjHccG3337rnvQzJfBsK04+K0400BT+mfWJoO+YMtbH5MpMMH2QudSYy+6k5A0DupO8hjgedjlK6OaAy9FR7FJbT+txnKY9Ka4mq0/xxK1yZSBdps5ztvGD5X4caVViOkYNzWDwvcaIzM1RMNS02oZs7KKWt0aFrTgv8ebJjD94Z5GzXL/Gyonzc50MjTu8FQ+TVNKBPnbuDv5EhWpwYvldc4asTXygJmdm2Xzh3Ond4wsfXXU+qmaOi9xFi+8iH9RRMmPQRkwJRpbiufqj9Zhz0lA7fDMXqtapbMxQvmr3ojIxHI5xD5orHC415H27+2USSIA7jIzrUcxB5DnGx2KBDWNtrPeGDaXDMfxf1B2cvP9TBbLPbczpvsm3Pht9HVr7etardryA3S7DkzzTdPb8SSz4s7HAXROJd3XktjLFcDM/GKs306hnONvtqUYvcqZ1wayXk2XABzx5aFD4AUe2h96FYKRLuntG08W+EmQPi025eHs4Cx5N1+74GEczr+mclopozOlzwg4wn/s5HmO34Nx4OyFEMlna0OTDU9d+pdoEQq5EELPkREwvcywzZNW43fHd43ZdMtLmcb3M8hZMBsiQ4+i93Mec28zgzKws7PyIlnplgrOup7/enu7nsZwakXO8EPtBw6Tf44Jld7j050w0ZfFdik3VRMhFD2/3HxYvD8VZi9McGIjBrhmtN4XLyRkiBzW50NrDdgNBaHON8Wq4AN5rsEAyg1oicMM5u2bSYE28KWV45nAdagZHMQNAN+GOrIYjppNpxC1xlkqSgVF3xF071hrGZQF1kcWfi+2uON2bLZlyKZ/vTCTNnA6zg4vC1hnV6zm1F5rfc+oPQ4tcnlPJIm+55wlan0p5IVRIYjkHu32cg+tzAoX0a0sbPdWmrI3WHYxbVedbQ/32ADZVdmdzjo1KQsX0bo31ivnOUIiJzjkZqTE2anHcLUHgy+v3djVGy5HpCpjOLkaCghb96EpQAPxNt99McYfVptaJKsq7/eHXS4bONST60IX9Q3eZo/KCK56AsdlWgWi879AYBpuLdS4mg5bJOf2lc/Hm9/E2FWOwMuTSMSzRTCtn43qdMZVT3tvJk23BuYtN7qURHAtwZq6Kz4ZViRm6bON1KqjYHgVRcTqat3TCrJ0p40vCW4Bdxa4Ym2okWgImZjkuTYvIHuoqR6HLnN+5tu8kF0wY9nSODcFjeopZYbdx04RJfucLpsAY78+VQggizjRyFJotA6iqYRLsinmlFX+opsVKuzYNQ49qoo4vdrwzU/1OVKY5LvsL+pN3d0fXgEtSKveqYaNd+9idr49iGDW1KxlH0MrY0L0LPQ0dj3bjh7kLboezsfXCraxb88vj0+lU7qRFqPvKvGCnq3LYhjzbzOfl12EJ6PXClNTVoVNszyYywO2ImXq/o7wwVqNrph/1oomWsXg5Ish9vptNYoYJ1VGoT1L+/FTsisV3Tw+PT8dWWsijy3PndEyZltLxHphkyFA9RlaSxojOhh5cNoKp9IUMQUsthfpG8D9LsboVu/KhHT71/fKxk+wM+R8ZiIVLolgvjRdIl00q717ZsRfqV0jHSI/toqu2zn5dZMTtIAZcxcx6eQESoDZVJKPRAENymBu4Gv6W5QCtxBdBFuTdcxMPYYHFvDYFReNfiqJpEjczUSecjOP2YOHv12VhcX2bKIuBufGyON4WR7HALsr9unh4rB5eIcVniy5hGOSdWQve/Xo4bk6mnaNrQad4qgc9J1VVG2ekLd1tzC7b2DEKNa6S0YkpG51rLgGuyQ1c9am7WK3tZc7quuA4dHVHHo8IL4u9+L/7nraRJ8xo2qrRMsY3BHP4mHI5dMOH8eY8II/T+Ydy3T78UYroi/O5WP9SbgbRCPL6bP1FHZDgLDczFISb+t1Agcx7D3g7ZFyCdtBTZIMKcXI5WzhBxbPKeTx+C400Df/KudT8NsvYPL6+BoF+udV/RCy6BNRzgAbOc+YcV8IKpWnQZy0212PxoXQiDVxn9GluUr+1F1wnqlaaLebneDbMjbwub34WuWDZy5E0KriHg6QZm+mImW/BDsdwoGUMBYbVozPF/UsmZiPXuNy4KV8a1MeF0MPaDzeYLMdRqs/u8uZ/CY3vH4X358P+w6EdcvpstP3FvHun48vaX5x8ZAPQmagdkXE4K5fNoZl9U29Gn2O8JWJp2KvgKnc9l3/fSCM/k8e6f9R6J1o4eqLpd6azMFpc0R+Yfyb/gZx4fY60cf118+Ox2FSWMFGRzbRiEZueHBccEbPBsmw9dgHoyjUAE7Fjee+oDhC9TNJzzsLuKHTl+wNcVk6fa+XkOEuGlmgjejqTYzUdfjubMyTjDJ6jUDt43xwFx4sXx/P2NBon0guim2mNckIQ0m4cpmySgwdAToaTobu60t6e/0Oy6y4dRpBUl6t5LyBlORE9tmCPMygkY6YjJ2p89FJtmkudGumL82FalD3tPX7u8unXCEXWDXl6EofQnAOjM/D0K2DD9u7ArpFMAHkZqtTM2SXtjFoM89ZR0stxW61jjvrcC7pqa+eN5VLxfCsO1Cyo0sT1OC5HeWuNNHBOgibEZywWaUb4qNdFafWe3xyl+i00TFyYtaL5bo+UljQWTiqy4qTs67IF+GQnGluxTybRxGVHtS72ltmf2GzYwwutcb5LW8P6qOPd9AU91fwG1kwfZnOzpS3DSlNunKWyBTH0i0DWh1ixK2kjASuxLgyZzb1jdkTeOJIGPdd1O41yluV2ZXUmulKHcDYX+43GLhgFx3luTzVuaXSb8JwJo2ABM6ypKmxIASsww+U+9/s3Dwt9o+dtzWcUagyfHD5ja4scFFl9GXOBA7FtGDkaUKxjB2ZJQlOTnTGormFzbAhL/dZlt/JYuCBWi+fSgrLghuQZvCZUbWffmT7oDI6XWhqPidfF6rc7zel37L2QakK4gDU1GTNouxcH4i+ERGx3i8qZXW4soJDWyx0mwx6CLhlbv4PAUWxGLzfj6oQeJ7fk7woTw5eY7TnsYGYaRwmhn26I5PDPuoZ6+HoHqVhfrZ/nc9HHvS76keP2WeCYvrysluGedR72xNJfPG3MIKBpaExV2YxjcuHN5m1O42l1hwPHJj28bEqOjTba9YqbFDvczqbSNUbaAei67Zw2fkInHPu6q5TEFz+WxXFsGPXkW3haXsa5c2PZoyPGhJlvMG77Rln0j8XtFFTDVbiLdO4sM2mAu7DlbviEEVqHZqxzXDrfx/WH6V6fgRHfEMRvDrvN4nuxnlwAOvWncPddLS+Lh0rJsDneXb11Vad246QfXD4cpa7s1v7rk1BGny2gAnKEOh/21rRoRkTY6NmTj5rFA9tKbp0zo8Oh6GR+K9btHSMjsOFztjVqSgasXohR2t9/M+SyS11tscceDO38ydWW8YSxx1gUCfeu12MQv1CjiDkrgqPQjOk04h55sbh0GSWjHoqX+pBU1q1BJ5Ln7re/Pm33f38qj6KqaUBAa2UsFxyrqwMuxYChtDh8lzxFxcqxboRlERtm1GLb5bqUPbtP2aQo85wMW7MDq3/XLOi4nsXCo/2yNbv8WDy1DpHkFOzsBxOWRdNHafZBYvdROvyGnIJpY0kaJpguafpWdlAhbz/JdFscT8Aym7nU7Lfc6ld0uNMY5RoNl+Ofq0syCjaKPcv749scdBaK9tt0Xe40RkFHgnMbxZDpoLPHmNooRkwHHded5dk9ZBaKrGHmDHHCq1BaW5gUWb2XMPu5LshZYxuK4diVrn6N5TROmO7luiBr50qYLvC64KS884nusJoOsjAYSge9nTphZx9MyETvt6leZkw17M4wluh7gT1pylzXgRrt/Py5ifwOJ9TvUXMU6zVbcPxovBuM6wMxM1g2/1yNvtiNeIkHUbKmjHHlg+vqMU4IEGd2Xi2EViqX8wnSTJ40mIIWX2hi6NzDzlBOeIhjY2AFlI6MqlX+GYYkuN14L+6O23WxXzSNXHy1Kx/vi/2sQbZEMJoAkm9KQabYnRavezLXd5xfz2Pd3pl6IS5ZsmroQL0uCT+xHmKZIqcn9GdORL7Sw0OVNdZNzumntlIyUIyyeg7NxEqT5UTjkI+nkI9a8qPmlOOUY1Y++fZ3fdONOuxOxI3uHUzm5iw3i2WvSlDBuK/55aE41gGkbwWRZ/ftCqnhPunP2eY42vKmdGCfcy6fn6Mg00PS+vvSfsMI69IDRhbCab5N6e+73gRnev2GJrWr1IxG/q6KSYeToakxTq1QvpZeSc+vKei6wOZjpvMM4c1DU8JR6Mp+YEOLzXUBnabC2i0Ao5yx6ZAz1h60ceEyl3Kmhd14zVq02WqIXQuxaEtszcOueFgoRlyKdm3CQjHkUrRvfg5fDYuifeuzaZ1sDY5FkUWMx5rDd+doA6egI8LU5RNjFJRXKPDmAqegzFfEm6+cghK/yZMpTkF54h+mmDD9aqndr2ahmFr9ambBzOpXsxDMlpYAP4cHi+HpqndYRrlGZ2NJ6IrpE/PZPjGf6RML2D6xgOkTs1+I6/JgcXxiEdsnZk2T6vJgsbw61ogsx9ma5xNjuqh4SzvblMC3TjApsnov5frEUt7AtRQ5Q5zyJldLkTMNU54AtBQ5XrDUJqS2019qlXs70DS1rSVOogMKobsKYwF0VsEo6ae2JdpJkVHST3U7PhtN0X9Q9oftP2m7wQ/Zf+SWeC37DzOJo2NndvUpK+I1tesPLpqsmNfUMHCzTjBNDQ6He/9Yh8Nj3d2MyBpr5w1Bn3esR1reU6tiO2DYdVzEOE8AiyP305JV6pIAlsqqmnO6WlbOntcc1SplnoIkTVbRZgZz9NnaCsFRkNvqOTRTK03bLGkN8D7D691lL2M5+5zhs9cywDtcd5zuSnq6i2vvjmWrx+ZNYA8VM8fxcHhz1D9A18hxzLtyOmKPWNTTazZHiw0BZAXuuzwsrLoCO/+josyCprYxUWY+E57kG1PUor0Z8KRhVcCfQXxWBm9MI27juOAaGC4cnVwfHAt20GEqYc1r9l7A3grsO4HD4sSiaF8snZZmRkn7Eui0NDNK2pcHp6WZUdK+CDgtzYySAXvfZ6+KLIosYjzW2DZwj2cEl5ZmjoZlj0t1WZo5FoaQabuWNzUzLc2MgjJan2lpZhSUsCWmpZlR0HH2dFmaGQUztu06Y9quc67tOufZrptdiSWjK6b12mdbr32m9TpgW68DpvU6ZFuvQ6b1OmJbr62XX7lszSzbpjVXl8vWzI5J4JpfedZrpjGZt12wD538cyyTIqv3Mq71OuNarzOu9TrjWq8zrvU641qvM6ZM+RlPSFuKnAjNNlnkuHNpS5+DFmOGsrUUh3OEhSZ5PWMUtzKOSZu7uUhZYBRtaI6QL45JN2Nu1JKmUVQ7NUYW8nxx44SpNjRt2Xter42MAM3r/dApBkqUazl2lQMAVXv+uxw7piobaWOXlxJcPXeRglvz+s1p/r2SxV0zH4kWF7vFD8V2Y7cjmfddsM7pfsa2BMsEIEyaLIWvw7FxxMVGoDFw2ILAWATq932O+tyyytGgMzbNlE0zZdNM2DQTNs2YTTNm04zYNCM2zZBNM7TSdBs4OTQDNk2fTdNnt33Fprni0sy5JNlSxBYitgyxRYgtQWwBYssPW3zY0sMWHrbssEXHLjlOqyCjpF1unFZBzhRnUWQR47HGtld6PIOltApycb5c4DDPzmhPyeOyCnLOgvY7aFxWQc55NWbaGR0Rgi6rIKOgRI8wrYKMgo4DkcsqyCiYs+2MOfMo2Owv7J2Iu7fxLI0+09IYsC2NAdPSGLItjSHT0mi/Kd6lIXFvD+BZGmOmpTFhWxqtKUhcdkE20pNrKuNZGpmGP94WxJnYOdfSmHMtjTnX0phzLY0519KYcy2NOdfSmHMtjTnX0phzLY3WG1icFDnizExC1VLkLDnMoICWIgcTy3T9tBQ5BkTuriGnOGeDydkGxJy7XzY0+YLDgY82NG2XhI8yWXBsiXlrSxwJvWhr4EoYL+GAvPuWSZMvZCyLUs62KKkI2QsMQnzxs6KseBMhqDWqwJbDhUWgfj/gC+H0mprth+8v4BRtnGcsmimbZsqmmbBpJmyaMZtmzKYZsWlGbJohm2bIphmwaQZsmj6bps+muWLTbKVrqnTn3IrYssUWLbZksQWLLVdssWJLFVuo2DLFFim2RLEFii1PbHHiSxN74rMosojxWGNb9TyuMZyNR/S4gER2dL7HDc93JA532c4YBeWV10zbGaOgzHjFtJ0xCjqihly2M0ZBh+PfZTtjFGSfLjzuiaX1zbA3KNZxyWfb43ymPS5g2+MCpj0uZNvjQqY9LmLb4yKmPS5m2+Nipj3Ong3XpYVyA4Z59jhm+DMbkeZxQW5sW5bHNY/xNkrOHrli2uOaExmLNaY9rj3jMSlyRrihyChZF2Tl9F8x52tgvW3YSZFz8QAz4XpLkZO2hZkAo6XIgeczYc4tRY5rj+kgaSlyFB7uriGnOFtqRogNV25Ym3VLkys5LJWipcmVHd6FGCuujtTQ5IsP6+KOFdfWFshrvpg0+SLECnFhB6wFMiiOSZMvRlVRcW6vM7HdZOGn/x9zFoOoHL8CAA==
```
</details>

**Expected behavior**

Excess production changed to Longbowman

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by xlenstra**
Fixes #6519.

### CODE REVIEW

File: core/src/com/unciv/logic/city/CityConstructions.kt [hunk 1]
```diff
@@ -380,8 +380,8 @@ class CityConstructions {
                 } else if (construction is BaseUnit) {
                     // Production put into upgradable units gets put into upgraded version
                     if (rejectionReasons.all { it.rejectionReason == RejectionReason.Obsoleted } && construction.upgradesTo != null) {
-                        inProgressConstructions[construction.upgradesTo!!] =
-                            (inProgressConstructions[construction.upgradesTo!!] ?: 0) + workDone
+                        inProgressConstructions[cityInfo.civInfo.getEquivalentConstructionName(construction.upgradesTo!!)!!] =
```
Comment (ymorgenstern) [inline core/src/com/unciv/logic/city/CityConstructions.kt:383]: Maybe separate this into a val? This is a pretty long thing to put twice

File: core/src/com/unciv/logic/civilization/CivilizationInfo.kt [hunk 2]
```diff
@@ -476,6 +477,14 @@ class CivilizationInfo {
         if (tech.freeTechs != 0) return true
         return tech.currentTechnology() == null && cities.isNotEmpty()
     }
+    
+    fun getEquivalentConstructionName(constructionName: String): String? {
```
Comment (ymorgenstern) [inline core/src/com/unciv/logic/civilization/CivilizationInfo.kt:481]: I don't see a situation where this is genericized, you can just use getEquivalentUnit directly in the place you changed. From what I see this just changes a direct call to a more ambiguous call.

**Review by yairm210 — APPROVED** [review]
