### PR TITLE
Fix regression from CityButton reorg: Perpetual construction icons

### LINKED ISSUE #14385: Science and Gold icons not being shown on external display of city production
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Game Version

4.19.1

### Describe the bug

In the latest version of UnCiv, when you set a city's production to Gold or Science, the icon for the stat doesn't show up on the world display. Instead, there's a blank spot 

### Steps to Reproduce

1. Set city production to Gold or Science 
2. Exit city screen and look at city on world map 
3. Stat icon will fail to display 

### Screenshots

Image

### Link to save file

_No response_

### Operating System

Android

### Additional Information

This also applies to Culture in mods that enable conversion of city production to Culture.

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Another blunder in #14355, as you reported. `<shame/>`

Fixes #14385

### CODE REVIEW

File: core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt [hunk 1]
```diff
@@ -174,34 +174,31 @@ internal class CityTable(
...
-                percentage = getPercentage(workDone)
-                turns = if (turnsToConstruction < 100) turnsToConstruction.tr() else "-"
-                icon = ImageGetter.getConstructionPortrait(cityCurrentConstruction.name, 24f)
+        // There's two different "idle" states: No entry in the queue and PerpetualConstruction.idle queued.
+        // getCurrentConstruction does not distinuish these, only currentConstructionName does. And we want the icon to only show in the second case.
+        var nextTurnPercentage = 0f
+        var percentage = 0f
+        var turns = "-"
+        val icon = if (cityConstructions.currentConstructionName().isEmpty()) {
+            null
```
Comment (yairm210) [inline core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt]: Please turn this into a single if/else cascade, or a single when - the two layered approach is less readable

Comment (SomeTroglodyte) [reply core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt]: Single `when` would have meant repeating the `getConstructionPortrait` call three times, same for a single-level if/else cascade. Didn't have a better idea - maybe you have..

Comment (yairm210) [reply core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt]: I see.
Then this needs to be extracted to a different function getIcon()

Comment (SomeTroglodyte) [reply core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt]: No, had an easy way but I just didn't see it: see last commit. Alternatives: helper in/extending CityConstructions, or dispense with the visual difference between "just emptied the queue" and "idle is queued", and display the slashed circle icon for both... Now let me check: what does city overview use...?

Comment (SomeTroglodyte) [reply core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt]: ... city overview uses the same logic, so a common helper would be good: But where to put common UI code when the obvious receiver is com.unciv.**logic**.city.CityConstructions? Start some new extension collection in com.unciv.ui.components.extensions - "GameObjectUIExtensions"??? Or modify ImageGetter.getConstructionPortrait - problematic to change its return type to nullable when 20 out of 22 callers expect non-nullable. 

Or an overload like this:
<details>

```patch
---
Index: core/src/com/unciv/ui/images/ImageGetter.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/ui/images/ImageGetter.kt b/core/src/com/unciv/ui/images/ImageGetter.kt
--- a/core/src/com/unciv/ui/images/ImageGetter.kt	(revision d1c9b84b8ff86d47312e4b62ad302f72fa919e5e)
+++ b/core/src/com/unciv/ui/images/ImageGetter.kt	(date 1765958309156)
@@ -17,6 +17,7 @@
 import com.unciv.Constants
 import com.unciv.UncivGame
 import com.unciv.json.json
+import com.unciv.logic.city.CityConstructions
 import com.unciv.models.ruleset.PerpetualConstruction
 import com.unciv.models.ruleset.Ruleset
 import com.unciv.models.ruleset.nation.Nation
@@ -263,6 +264,9 @@
             return getImage("OtherIcons/Convert$construction").toGroup(size)
         return getStatIcon(construction).surroundWithCircle(size).surroundWithThinCircle()
     }
+    fun getConstructionPortrait(cityConstructions: CityConstructions, size: Float) =
+        if (cityConstructions.currentConstructionName().isEmpty()) null
+        else getConstructionPortrait(cityConstructions.currentConstructionName(), size)
 
     fun getUniquePortrait(uniqueName: String, size: Float): Group = PortraitUnique(uniqueName, size)
 
Index: core/src/com/unciv/ui/screens/overviewscreen/CityOverviewTabColumn.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/ui/screens/overviewscreen/CityOverviewTabColumn.kt b/core/src/com/unciv/ui/screens/overviewscreen/CityOverviewTabColumn.kt
--- a/core/src/com/unciv/ui/screens/overviewscreen/CityOverviewTabColumn.kt	(revision d1c9b84b8ff86d47312e4b62ad302f72fa919e5e)
+++ b/core/src/com/unciv/ui/screens/overviewscreen/CityOverviewTabColumn.kt	(date 1765958309127)
@@ -81,9 +81,7 @@
         override fun getEntryValue(item: City) =
                 item.cityConstructions.run { turnsToConstruction( currentConstructionName()) }
         override fun getEntryActor(item: City, iconSize: Float, actionContext: EmpireOverviewScreen): Actor? {
-            val construction = item.cityConstructions. currentConstructionName()
-            if (construction.isEmpty()) return null
-            return ImageGetter.getConstructionPortrait(construction, iconSize * 0.8f)
+            return ImageGetter.getConstructionPortrait(item.cityConstructions, iconSize * 0.8f)
         }
         override fun getTotalsActor(items: Iterable<City>) = null  // an intended empty space
     },
Index: core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt b/core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt
--- a/core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt	(revision d1c9b84b8ff86d47312e4b62ad302f72fa919e5e)
+++ b/core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt	(date 1765958309148)
@@ -179,8 +179,6 @@
         var nextTurnPercentage = 0f
         var percentage = 0f
         var turns = "-"
-        val icon = if (cityConstructions.currentConstructionName().isEmpty()) null
-            else ImageGetter.getConstructionPortrait(cityCurrentConstruction.name, 24f)
         when (cityCurrentConstruction) {
             PerpetualConstruction.idle -> {}
             is PerpetualConstruction -> {
@@ -197,6 +195,7 @@
                 turns = if (turnsToConstruction < 100) turnsToConstruction.tr() else "-"
             }
         }
+        val icon = ImageGetter.getConstructionPortrait(cityConstructions, 24f)
 
         val productionBar = ImageGetter.getProgressBarVertical(4f, 30f, percentage,
             CityButton.ColorConstruction, ImageGetter.CHARCOAL, 1f)
```
</details>

...Better, include in this PR?? 🤷

File: core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt [hunk 2]
```diff
@@ -179,26 +179,23 @@ internal class CityTable(
...
+                val turnsToConstruction = cityConstructions.turnsToConstruction(cityCurrentConstruction.name)
+                val workDone = cityConstructions.getWorkDone(cityCurrentConstruction.name).toFloat()
+                val cost = cityCurrentConstruction.getProductionCost(cityConstructions.city.civ, cityConstructions.city)
+                fun getPercentage(done: Float) = (done / cost).coerceIn(0f, 1f)
+                nextTurnPercentage = getPercentage(workDone + city.cityStats.currentCityStats.production)
+                percentage = getPercentage(workDone)
+                turns = if (turnsToConstruction < 100) turnsToConstruction.tr() else "-"
             }
-            ImageGetter.getConstructionPortrait(cityCurrentConstruction.name, 24f)
         }
```
Comment (yairm210) [inline core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt]: Maybe `turns = when ...`?

Comment (SomeTroglodyte) [reply core/src/com/unciv/ui/components/tilegroups/citybutton/CityTable.kt]: Alright, but wait - should that really be a minus when some construction will take 100 or more turns? Wouldn't a "+" or even infinity be more appropriate. I checked, it was "-" in 4.19.0 too
