### PR TITLE
Map editor2.2

### LINKED ISSUE #6635: Can't load saved map
**Platform**
All

**Version**
4.0.10

**Describe the bug**
I can't load saved map from map editor

image

### PR DESCRIPTION
**Pull request by SomeTroglodyte**
Smaller than the last one, the commit messages say it all.

Fixes #6635
Missing ruleset _objects_ no longer prevent map load, they get removed and toasted instead.
e.g. The 'Unciv Europe Map Example' I have on disk still has 'Gold' instead of 'Gold ore' resources. Now loads just fine without the resource and without the starting locations.

### CODE REVIEW

File: core/src/com/unciv/ui/mapeditor/MapEditorLoadTab.kt [hunk 1]
```diff
@@ -118,7 +118,17 @@ class MapEditorLoadTab(
                         map.mapParameters.mods -= modBaseRuleset
                     }
 
-                    editorScreen.loadMap(map)
+                    val ruleset = RulesetCache.getComplexRuleset(map.mapParameters)
+                    val rulesetIncompatibilities = map.getRulesetIncompatibility(ruleset)
+                    if (rulesetIncompatibilities.isNotEmpty()) {
+                        map.removeMissingTerrainModReferences(ruleset)
+                        val message = "{This map has errors:}\n\n".tr() +
+                                rulesetIncompatibilities.sorted().joinToString("\n") { it.tr() } +
```
Comment (xlenstra) [inline core/src/com/unciv/ui/mapeditor/MapEditorLoadTab.kt:126]: So you first sort and then translate? Would that still look good in non-English languages?

**Review by xlenstra — APPROVED** [review]

File: core/src/com/unciv/ui/mapeditor/MapEditorLoadTab.kt (hunk 1 above)
Comment (SomeTroglodyte) [reply core/src/com/unciv/ui/mapeditor/MapEditorLoadTab.kt:126]: No oversight, I was reluctant to pull the collator for something as rarely seen. I wanted it deterministic and a bit grouped, actual alphabetics - shrug.
