### PR TITLE
Cancel the chain reaction of defense pact

### LINKED ISSUE #12564: Defensive pact involve the 4th nations in the war
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.12-patch2 (Build 1079)

### Describe the bug

Byzantium has defense pacts with China and Siam. 
I expect that India will fight with Siam and Byzantium when attacking Siam. But for some reason, when an attack is launched, war is declared on the China too. 
Although the goal of the war is Siam, the China joined the chain to Byzantium. 
Such alliances work in a chain, and you can fight with the whole map, although it has nothing to do with it.

### Steps to Reproduce

Declare war on Siam.
file bellow

### Screenshots

image
image

### Link to save file

[test2.txt](https://github.com/user-attachments/files/17998696/test2.txt)

### Operating System

Android

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by czyh2022**
I noticed the discussion in Discord about whether to cancel the chain reaction of defense pact. Based on this, I made some corresponding changes. Before a civilization calls a defense pact ally, it will check the Type of the war it is participating in. If it is already a DefensivePactWar, it will not continue to call allies.
Resolves #12564

### CODE REVIEW

File: core/src/com/unciv/ui/screens/diplomacyscreen/DiplomacyScreen.kt [hunk 1]
```diff
@@ -282,20 +282,22 @@ class DiplomacyScreen(
...
-            // Add their defensive pact allies
-            otherCivDefensivePactList.addAll(otherCivDefensivePactList[listIndex].diplomacy.values
-                .filter { diploChain -> diploChain.diplomaticStatus == DiplomaticStatus.DefensivePact
-                    && !otherCivDefensivePactList.contains(diploChain.otherCiv())
-                    && diploChain.otherCiv() != viewingCiv && diploChain.otherCiv() != otherCiv
-                    && !diploChain.otherCiv().isAtWarWith(viewingCiv) }
-                .map { it.otherCiv() })
+            
+            // Defensive pact chains are not allowed now
+            var listIndex = 0
```
Comment (yairm210) [inline core/src/com/unciv/ui/screens/diplomacyscreen/DiplomacyScreen.kt:287]: Is there a reason to have this by index instead of 'for civ in othercovdefensivepactlist'?
I know this was here before you, but if we can improve readability, why not :)

Comment (SeventhM) [reply core/src/com/unciv/ui/screens/diplomacyscreen/DiplomacyScreen.kt:287]: Is there a reason we're doing indexing at all on a list and not using ``for ((index, civ) in otherCivDefensivePactList.withIndexed()``. Like, "withIndexed" is explicitly in the Kotlin library so we don't need to do while loops for this

Comment (yairm210) [reply core/src/com/unciv/ui/screens/diplomacyscreen/DiplomacyScreen.kt:287]: Correct, but now it is no longer modified, so we can move to the more readable format
We don't even use the index anymore, just the civ

File: core/src/com/unciv/ui/screens/diplomacyscreen/DiplomacyScreen.kt [hunk 2]
```diff
@@ -282,20 +282,22 @@ class DiplomacyScreen(
...
+                else "An unknown civilization will also join them in the war"
+                /*
+                // Add their defensive pact allies
+                otherCivDefensivePactList.addAll(otherCivDefensivePactList[listIndex].diplomacy.values
+                    .filter { diploChain -> diploChain.diplomaticStatus == DiplomaticStatus.DefensivePact
+                        && !otherCivDefensivePactList.contains(diploChain.otherCiv())
+                        && diploChain.otherCiv() != viewingCiv && diploChain.otherCiv() != otherCiv
+                        && !diploChain.otherCiv().isAtWarWith(viewingCiv) }
+                    .map { it.otherCiv() })
+                */
```
Comment (yairm210) [inline core/src/com/unciv/ui/screens/diplomacyscreen/DiplomacyScreen.kt:300]: Also delete this, there's no reason to have dead code in comments, if we want it we can get it back from git :)

**Comment by czyh2022** [comment]
Got it! I removed dead code and simplified the loop. Although I started playing this game several years ago, I am new here to contributing :)

**Review by yairm210 — APPROVED** [review]
