### PR TITLE
Fix of the click on unknown civilization

### LINKED ISSUE #1985: Interacting with unmet civs causes a crash
**Describe the bug**
In my game I have not met the Iroquois, but I can see them on the map. I believe this happened as my scout saw the area before they built cities.

With the feature to open diplomacy by double tapping a city, I can attempt to open diplomatic relations with a civ I haven't met. Doing so crashes my game consistently.

**To Reproduce**
You can do it yourself here:
https://pastebin.com/XvPdXYZf

Go to the Iroquois and double tap their city to start diplomatic relations.

**Screenshots**

Screenshot_20200222-180353
Screenshot_20200222-180359

### PR DESCRIPTION
**Pull request by JackRainy**
Resolves #1985

### CODE REVIEW

File: core/src/com/unciv/ui/tilegroups/CityButton.kt [hunk 1]
```diff
@@ -70,13 +70,14 @@ class CityButton(val city: CityInfo, internal val tileGroup: WorldTileGroup, ski
...
                 if (UncivGame.Current.viewEntireMapForDebug || belongsToViewingCiv()) {
                     UncivGame.Current.setScreen(CityScreen(city))
-                } else {
+                } else if (currentCiv.knows(city.civInfo)) {
                     // If city doesn't belong to you, go directly to its owner's diplomacy screen.
-                    val screen = DiplomacyScreen(UncivGame.Current.worldScreen.viewingCiv)
+                    val screen = DiplomacyScreen(currentCiv)
                     screen.updateRightSide(city.civInfo)
                     UncivGame.Current.setScreen(screen)
                 }
```
Comment (Kentalot) [inline core/src/com/unciv/ui/tilegroups/CityButton.kt]: I think we shouldn't let the button move either.  In fact, probably have this check as the first line of setButtonActions()

```kotlin
val currentCiv = UncivGame.Current.worldScreen.viewingCiv
if (!belongsToViewingCiv() && !currentCiv.knows(city.civInfo)) return
```

Comment (JackRainy) [reply core/src/com/unciv/ui/tilegroups/CityButton.kt]: Moving the button is useful in order to see the units which can be overlapped by the button.

Comment (yairm210) [reply core/src/com/unciv/ui/tilegroups/CityButton.kt]: Under what circumstance can you see the city button of a civ you don't know? If you can see the tile, you should 'meet' the civilization, no?

File: core/src/com/unciv/ui/tilegroups/CityButton.kt [hunk 2]
```diff
@@ -70,13 +70,14 @@ class CityButton(val city: CityInfo, internal val tileGroup: WorldTileGroup, ski
             // clicking swings the button a little down to allow selection of units there.
             // this also allows to target selected units to move to the city tile from elsewhere.
             if (isButtonMoved) {
+                val currentCiv = UncivGame.Current.worldScreen.viewingCiv
                 // second tap on the button will go to the city screen
                 // if this city belongs to you
                 if (UncivGame.Current.viewEntireMapForDebug || belongsToViewingCiv()) {
                     UncivGame.Current.setScreen(CityScreen(city))
-                } else {
+                } else if (currentCiv.knows(city.civInfo)) {
```
Comment (yairm210) [inline core/src/com/unciv/ui/tilegroups/CityButton.kt]: This should probably not reference the currentCiv. In Multiplayer, currentCiv is the civ who's turn it is, but if you're a different player then you should get to 'your own' diplomacy screen, and not that of the current player

Comment (JackRainy) [reply core/src/com/unciv/ui/tilegroups/CityButton.kt]: As you see a few lines higher, it uses the `viewingCiv`
> val currentCiv = UncivGame.Current.worldScreen.viewingCiv
Is it a right way to get 'your own' civilization?

Comment (yairm210) [reply core/src/com/unciv/ui/tilegroups/CityButton.kt]: I see, then it's functionally perfect =)
Even so, please change the parameter's name to viewingCiv, because currentCiv already has a different connotation

Comment (JackRainy) [reply core/src/com/unciv/ui/tilegroups/CityButton.kt]: I agree, the naming caused the confusion, will rephrase.
